### PR TITLE
#10099 Workflow action create record by Scheduler set incorrect date field values from related entity

### PR DESCRIPTION
**Pull request by re8260**
## Description

Workflow action Create Record works different from on screen save and CRON.
On cron run it set incorrect date values based on CRON user date time format
When save from screen - all works correct
https://github.com/salesagility/SuiteCRM/issues/10099
image

There is same workflow runs before and after fix with 3 different sets:
1. When workflow runs from trigger ON_SAVE system user date format not effect on the result 
2. When workflow runs from trigger In_Scheduler with system user date format DD/MM/YYYY+3
3. When workflow runs from trigger In_Scheduler with system user date format YYYY-MM-DD+3

## Motivation and Context

When action "Create record" runs on bean saved from screen, the date in bean are not converted to the user date format, all dates are always in DB GMT format
On cron this action receive bean with **already converted dates** to user format - the current user is cron user as usually ADMIN and the this date passed to PHP function `strtotime` that fail or works different with different date formats and time zone
## How To Test This

Steps in issue: https://github.com/salesagility/SuiteCRM/issues/10099
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by SinergiaCRM** [comment]
Hello @re8260,
we have also encountered this issue and had an alternative solution, which used the value stored in `$bean->fetched_row.` if is set.
Upon further analysis, we prefer your proposal.
Thank you.

**Comment by pgorod** [comment]
I don't think this can be evaluated without precise information about your _effective_ **`date.timezone`** parameter for both

- the CRON **`php.ini`**
- the web server **`php.ini`**

When you call **`fromUser`** function from CRON, which user is that? Why is that user's timezone appropriate to use here?

**Comment by SinergiaCRM** [comment]
Okay, true, in the case of different time formats, this solution may not necessarily work.

Our proposed solution captures the value obtained in `$bean->fetched_row`, which is empty if the action is executed upon saving the record. However, in that case, the date contains the correct value:
```php
// The following workaround uses the date of fetched_row if is set
// When a workflow is executed "after save", the date format is correct, and the fetched_row is empty
$date = (isset($bean->fetched_row) && isset($bean->fetched_row[$dateToUse])) ? $bean->fetched_row[$dateToUse] : $bean->$dateToUse;
```

**Comment by re8260** [comment]
Cron always has logged-in user, as usually its user Admin ID:1

image

and user has time zone settings in his profile.

_Current user_ is required when running scheduler from cron to set "created by" \ "modified by" and the change log

**Comment by serhiisamko091184** [comment]
Thanks for your PR, @re8260!

**Review by jack7anderson7 — APPROVED** [review]

**Pull request merged**
