### PR TITLE
Fixed #6285 - LBL_DBCONFIG_B_MSG1_LABEL empty string

### LINKED ISSUE #6285: LBL_DBCONFIG_B_MSG1_LABEL empty string
#### Issue

there is an empty string in /install/language/en_us.lang.php
` 'LBL_DBCONFIG_B_MSG1_LABEL' => ''`

Is this created dynamically and what value will it get? 

#### Actual Behavior

https://github.com/salesagility/SuiteCRM/blob/207f5f65d260b842b8883e591783608ec758b28d/install/language/en_us.lang.php#L571

#### Context
For translators it should no be empty so they can translate it

#### Your Environment

* SuiteCRM Version used: Hotfix

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Removes an unused string

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
1- Unused string? Here you said it was dynamically created. Please double check https://github.com/salesagility/SuiteCRM/issues/3926#issuecomment-316745139

2- The "install" en_us.lang.php language file you used from 7.8.x branch its too outdated in formatting. See the hotfix here:
https://github.com/salesagility/SuiteCRM/blob/hotfix/install/language/en_us.lang.php

**Comment by Dillon-Brown** [comment]
@horus68 

1. Yeah it's used dynamically [here](https://github.com/salesagility/SuiteCRM/blob/hotfix-7.8.x/install/installConfig.php#L273) which appears in the SuiteCRM Database Configuration page upon installing. From what I can see though, unlike those other labels it's not actually used for anything, it just puts the blank value on the page.

2. I believe when we originally fixed the language file formatting it was done to the hotfix branch only. I don't see too much benefit in going back and making a similar format PR for 7.8.x (It would likely end up adding a lot of unused strings into hotfix during the merge). Is there a particular reason you would want the hotfix-7.8.x language files formatted to be the same as hotfix? if it helps you out in any way I don't mind doing it.

**Comment by horus68** [comment]
@Dillon-Brown on item 2: no need to be the same file, just an alert if/when merging the change you done here to the hotfix-7.8.x branch into the hotfix.

**Comment by samus-aran** [comment]
Note to duplicate for hotfix? @salesagility/suitecrm-core

**Pull request merged**
