### PR TITLE
module="xxx" is not a valid attribute for an a tag

### PR DESCRIPTION
**Pull request by gunnicom**
## Description
Actual links in suite look like:
`<a href="?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DHome%26action%3Dindex" id="moduleTab_Home" module="Home">Home</a>`
"module=xxxx" is no valid html attribute, so it should be:
`<a href="?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DHome%26action%3Dindex" id="moduleTab_Home">Home</a>`

## Motivation and Context
Produce valid HTML.

## How To Test This
Look at the source code of the generated site.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [dontknow] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
@gunnicom sorry, this is completely off-topic, but I know you use theme SuiteR, I'd like to ask you:

In the ListViews (any module), is your "Selected" button showing correctly?

image

I mean that part that says `Selected: 2`. I had mine showing badly (overlapped with other elements), and I just fixed it; I just want to know if this is a bug everyone is experiencing. Thanks.

**Comment by gunnicom** [comment]
@pgorod I use Suit7 and SuiteR theme on two different instances, and for me it seems like they show correct:

grafik

grafik

**Comment by pgorod** [comment]
Strange, it looks like it's just me, but looking at the code, I can't understand how that is possible.

My SuiteR is on version 7.8.7, what about yours?

**Comment by gunnicom** [comment]
I am on 7.8.7 with some changes (Some of my PRs integrated, and maybe changes i forgot about ;) )

**Pull request merged**
