### PR TITLE
fixed - #3175 Dashlet activity feed can't play youtube video

### PR DESCRIPTION
**Pull request by shogunpol**
## Description
Dashlet activity feed can't play youtube video fixed
References issue #3175 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
@shogunpol - I'm unable to test is - I can post the youtube video to the stream but I get a 404 console error and no screenshot appears just a white box.  Can you show me how you were able to replicate this?

**Comment by shogunpol** [comment]
@samus-aran , did you tried replicate this issue in mentioned in issue environment? ex. version of suite crm 7.7.8?

**Comment by samus-aran** [comment]
@shogunpol  No, I tested this with 7.8.2 (hotfix branch).

**Comment by cameronblaikie** [comment]
Unable to get the YouTube video to play, I could post it, just couldn't play it. Could you try to test it again to see if it works for you? @shogunpol

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.

**Pull request closed without merging**
