### PR TITLE
Fixed problem with markers clusterer. 

### PR DESCRIPTION
**Pull request by daniprados**
The google code repository of marker clusterer library has been removed.  With this pull we change the link to a the github repo.
## Description

Changed   "//google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m" to  "//raw.githubusercontent.com/googlemaps/js-marker-clusterer/gh-pages/images/m"

You can reproduce the error using maps module and having a lot o georeferenced  points.

## Types of changes

- [\* ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [\* ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [\* ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

…een removed.  A better solution could be adding js-marker-clusterer to the SuiteRepository

### CODE REVIEW

**Comment by daniprados** [comment]
signed contributor license agreement

**Comment by horus68** [comment]
@daniprados  the user @comunicatek also needs to sign the clahub license as he is the committer to your hotfix branch

**Comment by daniprados** [comment]
Both users have signed now.

**Comment by horus68** [comment]
see your requests @shogunpol

**Comment by chris001** [comment]
Why is this not merged.  Image icons are broken in Maps module without it.

An even better fix would to include the icon images in the suitcrm repo, and let the user load the icons from the suitecrm server directly, since many high security crm instances and users (bank, etc) are blocked from direct internet access, and cannot load images from the internet, only from the crm server.

**Comment by daniprados** [comment]
In the last commit I added images in  SuiteCRM folder removing external dependencies.
It's a better solution and  removes one innecesary external dependency.

**Comment by daniprados** [comment]
This problem is still present in current version of suitecrm.

**Comment by horus68** [comment]
@Dillon-Brown maybe this is duplicated in https://github.com/salesagility/SuiteCRM/pull/3089

**Comment by gody01** [comment]
Yes, this is duoplicate of: #3089
But in #3089 images are included on local server, not served from github.
I believe that used resources should be always part of software package and not served from remote.
This can be problem even in case of strict security policy and firewall configuration.

**Comment by Dillon-Brown** [comment]
@gody01 It looks like initially this PR was using GitHub for the images but was then updated to be the same as #3089.

**Comment by Dillon-Brown** [comment]
Issue reference: #4134

**Comment by daniprados** [comment]
Now  images are added in the module.  Solving this problem is a must.  Every time I update SuiteCRM I have to apply the patch manualy when it is so easy to fix the problem.  Use the PR you prefer but use one of them.

**Comment by timo12357** [comment]
This fix does not seem to work in 7.8.5. Cluster icons are still míssing even if they are locally copied and referenced.

**Pull request closed without merging**
