### PR TITLE
Scrutinizer - Let's see what's under the hood

### PR DESCRIPTION
**Pull request by adamjakab**
Alright, so if we need to fix her up I think we need a hand.

For now you can see the results [here](https://scrutinizer-ci.com/g/adamjakab/SuiteCRM/?branch=scrutinizer-code-quality) until you set it up for your repo.

This is an excellent tool if we want to do some cleanup / harden code quality.
It dissects the code and give you a very good indication where you can have problems.
It runs for ~50 minutes per push so i'd advice to configure Single Inspection Mode (run one automatic inspection per day (instead of inspecting each push)).

I also hooked in Travis to report code test coverage to Scrutinizer so we can see how much of the code base is covered by our tests (we have some work to do there).

The actual state of the project is:
score: 4.93
code coverage: 7%!!!

[Issues by severity](https://scrutinizer-ci.com/g/adamjakab/SuiteCRM/issues/scrutinizer-code-quality):

Critical: 18
Major: 745
Minor: 2108
Info: 741
Unknown: 458

There is also an issue split by label/type - check it out!

I also enabled code quality where you get an A,B,C,D,F score per file.

### CODE REVIEW

**Comment by mattlorimer** [comment]
Using sonarcube https://sonarqube.com/overview?id=SuiteCRM

**Comment by chris001** [comment]
Sonarqube error: "The page you are looking for does not exist."

**Comment by Dillon-Brown** [comment]
@chris001 Working sonarqube link: https://sonarqube.com/dashboard?id=SuiteCRM

**Comment by chris001** [comment]
Thanks for the working sonarqube link @Dillon-Brown 
Some alarming facts on the dashboard:
* The Quality Gate on sonarqube is Failed!
* Test Coverage is 0.0% !  Minimum required is 80%!
These are serious problems!
What's being done to increase test coverage to greater than 80%??
Isn't anyone adding the existing free open source phpunit test cases from sugarcrm_dev Sugar 6.5 repo?!

**Comment by horus68** [comment]
@adamjakab scrutinizer is 12 months old, can you refresh data (and making it for Hotfix branch, not develop)
https://scrutinizer-ci.com/g/adamjakab/SuiteCRM/?branch=scrutinizer-code-quality

**Pull request closed without merging**
