### PR TITLE
Add Visual Studio exclusions to .gitignore

### PR DESCRIPTION
**Pull request by pgorod**
Microsoft Visual Studio is a free IDE that can be used for PHP projects, including SuiteCRM.

This makes the generated project files be excluded from Git, similarly to what is already there for other IDE's.

### CODE REVIEW

**Comment by pgorod** [comment]
I didn't create an issue for this, but I can create one if it's really necessary. Thanks.

**Comment by pgorod** [comment]
I tried to resolve conflicts but it's still complaining about some invisible difference. Anyone know how to solve this? Or just override it and merge anyway? I can also start a new clean PR if that seems more simple.

**Comment by pgorod** [comment]
@Dillon-Brown I'd like to get this one merged, do you know how to resolve this conflict? Or if it easier, just start a new PR adding those lines.

**Comment by Dillon-Brown** [comment]
@pgorod Conflicts resolved. Looks good!

**Comment by pgorod** [comment]
Here's a fresh start for this PR in #4292 !

**Pull request closed without merging**
