### PR TITLE
FIX #7616 - Add a way to handle creation of foreign keys in MySQL

### LINKED ISSUE #7616: SuiteCRM did not create foreign keys defined in vardefs.php
#### Issue

You have a module where in its `vardefs.php` there is a foreign key ike this:

```php
        array(
            'name' => 'campaign_id',
            'type' => 'foreign',
            'foreignTable' => 'campaigns',
            'foreignField' => 'id',
            'fields' => array(
                'campaign_id',
            ),
        ),
```

When you run a QuickRepair the table is not created well, because the method `keysSQL` in `MysqlManager.php` [executes the following](https://github.com/salesagility/SuiteCRM/blob/master/include/database/MysqlManager.php#L901):

```php
                case 'index':
                case 'foreign':
                case 'clustered':
                case 'alternate_key':
                    /**
                     * @todo here it is assumed that the primary key of the foreign
                     * table will always be named 'id'. It must be noted though
                     * that this can easily be fixed by referring to db dictionary
                     * to find the correct primary field name
                     */
                    if ($alter_table) {
                        $columns[] = " INDEX $name ($fields)";
                    } else {
                        $columns[] = " KEY $name ($fields)";
                    }
                    break;
```

So the FK is created like a simple INDEX: `KEY campaign_id (campaign_id)`

If you say: 

_"Ok, let's create the table like this, and after I'll drop that index because running a QuickRepair again will create it well because the [method add_drop_constraint() in MysqlManager.php knows how to handle FK](https://github.com/salesagility/SuiteCRM/blob/master/include/database/MysqlManager.php#L1040):"_

```php
            case 'foreign':
                if ($drop) {
                    $sql = "ALTER TABLE {$table} DROP FOREIGN KEY ({$fields})";
                } else {
                    $sql = "ALTER TABLE {$table} ADD CONSTRAINT FOREIGN KEY {$name} ({$fields}) REFERENCES {$definition['foreignTable']}({$definition['foreignField']})";
                }
```

When you run the QuickRepair will try to create it like this:

```sql
ALTER TABLE gcoop_salesopportunity   ADD INDEX campaign_id (campaign_id);
``` 

I think the problem is in [DBManager.php](https://github.com/salesagility/SuiteCRM/blob/master/include/database/DBManager.php#L964):

```php
if (in_array($value['type'], array('alternate_key', 'foreign'))) {
    $value['type'] = 'index';
}
```

This code overrides the definition in vardefs.php, if you replace these code with this one:

```php
if (in_array($value['type'], array('alternate_key'))) {
    $value['type'] = 'index';
}
```

The FK is created as defined when you run a QuickRepair:

```sql
ALTER TABLE gcoop_salesopportunity   ADD CONSTRAINT FOREIGN KEY campaign_id (campaign_id) REFERENCES campaigns(id);
``` 

So, as fair as I understand, we have 3 problems here:

1. When creating the table the method `keysSQL` treats indexes and foreign keys the same way.

2. Where adding a foreign key to a vardefs.php and run a QuickRepair the method `add_drop_constraint` treats indexes and foreign keys the same way too.

3. The method `add_drop_constraint` do not handle all `reference_option` you can define in a [MySQL table](https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html)

#### Expected Behavior

SuiteCRM handles foreign keys well ;-)

#### Actual Behavior

SuiteCRM handles foreign keys wrong ;-(

#### Possible Fix

In DBManager.php we should do the something like this:

```diff
-            if (in_array($value['type'], array('alternate_key', 'foreign'))) {
+            if (in_array($value['type'], array('alternate_key'))) {
                 $value['type'] = 'index';
             }
```

In method `keysSQL()` in `MysqlManager.php` something like this:

```diff
                     $columns[] = " PRIMARY KEY ($fields)";
                     break;
                 case 'index':
-               case 'foreign':
                 case 'clustered':
                case 'alternate_key':
                    /**
                     * @todo here it is assumed that the primary key of the foreign
                     * table will always be named 'id'. It must be noted though
                     * that this can easily be fixed by referring to db dictionary
                     * to find the correct primary field name
                     */
                    if ($alter_table) {
                        $columns[] = " INDEX $name ($fields)";
                    } else {
                        $columns[] = " KEY $name ($fields)";
                    }
                    break;
                case 'fulltext':
                    if ($this->full_text_indexing_installed()) {
                        $columns[] = " FULLTEXT ($fields)";
                    } else {
                        $GLOBALS['log']->debug(
                            'MYISAM engine is not available/enabled, full-text indexes will be skipped. Skipping:',
                            $name
                        );
                    }
                    break;
+                case 'foreign':
+                    $columns[] = " CONSTRAINT FOREIGN KEY {$name} ({$fields}) REFERENCES {$definition['foreignTable']}({$definition['foreignField']})";
             }
         }
```

I think these changes solves point 1 and 2. 

For point 3 we should [add more options ](https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html)to vardefs.php to handle: (ON DELETE | ON UPDATE) and (RESTRICT | CASCADE | SET NULL | NO ACTION | SET DEFAULT)

#### Steps to Reproduce

1. Add a FK as presented before
2. Run QuickRepair
3. Verify the FK is treated as an INDEX

#### Your Environment

* SuiteCRM Version used: 7.10

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

Refer to #7616

## How To Test This

1.- Create an index in vardefs.php like this one:

```php
        array(
            'name' => 'campaign_id',
            'type' => 'foreign',
            'foreignTable' => 'campaigns',
            'foreignField' => 'id',
            'reference_option' => array(
                'on' => 'DELETE',
                'option' => 'CASCADE',
            ),
            'fields' => array(
                'campaign_id',
            ),
        ),
```

2. Run QuickRepair and verify the the SQL is generated with this FK:
```sql
... CONSTRAINT campaign_id FOREIGN KEY campaign_id (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE) CHARACTER SET utf8 COLLATE utf8_general_ci;
```

3. Execute that query and verify in the database the FK is created:

```sql
  KEY `campaign_id` (`campaign_id`),
  CONSTRAINT `campaign_id` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

4. Remove that FK with:

```sql
alter table [table_name] drop foreign key campaign_id;
```

5. Run QuickRepair again and verify an ALTER TABLE like this is generated:

```sql
ALTER TABLE [table_name] DROP INDEX campaign_id,  ADD CONSTRAINT campaign_id FOREIGN KEY campaign_id (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
```

6. Execute the query
7. Verify the FK is created in the table again.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
Do we have existing tests for vardefs? If we do, we should probably have some tests for this as well. :)

**Comment by Abuelodelanada** [comment]
> Do we have existing tests for vardefs? If we do, we should probably have some tests for this as well. :)

This one?
tests/unit/phpunit/data/SugarBeanTest.php

**Comment by connorshea** [comment]
Yeah I think so

**Comment by Abuelodelanada** [comment]
Hi @miannilli @goldmanmichelle @TelevicDominiek @tmaine @WTNetAdmin @urdhvatech @bmwtourer @anhnhatuit @javieranton-zz @MattForrest @Spillo89

In order to give SuiteCRM Foreign Key management to SQL Server, Please can you take a look at the [method getForeignKeys()](https://github.com/salesagility/SuiteCRM/pull/7617/files#diff-ef3093ef19b1b0aa0f2dda158525b634R1637) for MySQL ans suggest the code for SQL Server?

**Comment by connorshea** [comment]
Hmm, I wonder why this causes the install suite to fail :/

**Comment by Abuelodelanada** [comment]
> Hmm, I wonder why this causes the install suite to fail :/

I have a fix for this:

```
PHP Fatal error:  Class MssqlManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (DBManager::getForeignKeys) in /tmp/gca/include/database/MssqlManager.php on line 0
PHP Stack trace:
PHP   1. {main}() /tmp/gca/install.php:0
PHP   2. runCheck() /tmp/gca/install.php:314
PHP   3. DBManagerFactory::getDbDrivers() /tmp/gca/install/installSystemCheck.php:151
PHP   4. DBManagerFactory::scanDriverDir() /tmp/gca/include/database/DBManagerFactory.php:245
PHP   5. require_once() /tmp/gca/include/database/DBManagerFactory.php:210
172.18.0.1:51382 [500]: /install.php - Class MssqlManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (DBManager::getForeignKeys) in /tmp/gca/include/database/MssqlManager.php on line 0
```
This would be:

```diff
modified   include/database/MssqlManager.php
@@ -2127,4 +2127,10 @@ EOQ;
     {
         return 'NEWID()';
     }
+
+    public function getForeignKeys($tablename)
+    {
+        return [];
+    }
+
 }
```

With this we will avoid errors while installing. [If in this method we execute](https://stackoverflow.com/a/12956348/2548711): 

```SQL
EXEC sp_fkeys 'TableName'
```
We can get foreign keys... but I have no way to test it.

Anyway @Mac-Rae @Dillon-Brown this feature is very useful, do you think can be merged? 
If you think so, I can re open another PR

**Comment by Abuelodelanada** [comment]
Hi @samus-aran, @mattlorimer  

I'm cleaning my "Open PR" list.
Is still possible to merge this one, or should I close it?

**Comment by Abuelodelanada** [comment]
> Hi @samus-aran, @mattlorimer
> 
> I'm cleaning my "Open PR" list. Is still possible to merge this one, or should I close it?

I'm closing it because it has been open for three years without approval.
cc/ @lukio

**Pull request closed without merging**
