### PR TITLE
Misc code formatting improvements

### PR DESCRIPTION
**Pull request by connorshea**
## Description

Improve formatting for some code. Replacing some tabs with spaces, adding spaces where there weren't any, etc.

We should really add a linter.

## Motivation and Context

Clean up some code.

## How To Test This
Make sure the tests pass.

## Types of changes
Technical debt.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/samus-aran/SuiteCRM/pullRequest?prid=4676008&bid=15645987)

**Comment by connorshea** [comment]
I think I need to re-run the CI job that failed, could someone with permissions do that?

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/samus-aran/SuiteCRM/pullRequest?prid=4676008&bid=15645987)

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Pull request merged**
