### PR TITLE
Update SugarRestJSON.php

### PR DESCRIPTION
**Pull request by chiragbiz309**
Solution for the issue [this community link](https://community.suitecrm.com/t/rest-api-v4-1-is-not-working-with-php-8-1-and-8-2/91286/3)

## Description

Resolved a bug related to the REST API v4.1 not working with PHP 8.1 and 8.2.

## Motivation and Context

This change is necessary to address the compatibility issues with PHP 8.1 and 8.2, ensuring the proper functionality of REST API v4.1.

## How To Test This

- Deploy the updated code with the fix.
- Use REST API v4.1 functionalities.
- Verify that the API works correctly with PHP 8.1 and 8.2.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hello @chiragbiz309,

thanks for your PR, 

allow me to clarify, regarding your last comment: 
https://community.suitecrm.com/t/rest-api-v4-1-is-not-working-with-php-8-1-and-8-2/91286/18

Do you suggest not using this PR as your issue was solved on the customization level?  

Thanks In advance! 

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hello @chiragbiz309,

This PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hello @chiragbiz309,

closing this PR due to inactivity.

Regards,
Serhii

**Comment by dkeso** [comment]
Hello @serhiisamko091184,

Alfter upgrading our instance from SuiteCRM 8.3 to .8 and our PHP version from 7.4 to 8.3 (since 7.x is not supported as of SuiteCRM 8.7), we are now facing this issue with the API REST v4.1 and "set_relationship" method.

I would like to request this PR be reopened and merged, as, as far as we know, the alternative solution provided in the [original community thread](https://community.suitecrm.com/t/rest-api-v4-1-is-not-working-with-php-8-1-and-8-2/91286/18) by @chiragbiz309 does not apply to default API methods. Therefore, the core file must be updated.

Thank you very much!

**Comment by dkeso** [comment]
For other users finding this PR through search engines:

As described by user [blqt](https://community.suitecrm.com/u/blqt), since PHP 8, parameter order no longer matters, so the exact parameter name must be used.

Here is the solving answer from the community forum with the set_relationship endpoint:

> The v4_1 API works fine with PHP 8 as long as you call the endpoints with exactly the same parameters names.
> With PHP 8, the parameters are named and no longer positional.
> For set_relationship, you need to make a call with exactly these parameters names (without $)
> Parameter #0 [ $session ]
> Parameter #1 [ $module_name ]
> Parameter #2 [ $module_id ]
> Parameter #3 [ $link_field_name ]
> Parameter #4 [ $related_ids ]
> Parameter #5 [ $name_value_list = Array ]
> Parameter #6 [ $delete = false ]

In our case, it was a "related_id" instead "realted_ids"...

Hope this help to others!

Regards

**Pull request closed without merging**
