### PR TITLE
Hotfix 7.10 issue 4497 - Quotations & email

### PR DESCRIPTION
**Pull request by gymad**
## Description

- fixing empty email contents from Email Quotation
- also fixing exists tests and code where the previous tests failed

## Motivation and Context

issue #4497

## How To Test This

- please follow instruction in related issue #4497

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
@Dillon-Brown Can you please assess this pull request?

**Comment by Abuelodelanada** [comment]
Hi @Dillon-Brown @daniel-samson  I'm testing 7.10 Beta and despite of the fact that the commit that solves this issue is merged:
https://github.com/salesagility/SuiteCRM/compare/v7.10-beta...develop

The issue is still present:

Quotation DetailView:

quote_01

Select "Email quotation":

quote_02


And the email body is empty:


quote_mail

Am I missing something??

**Comment by Dillon-Brown** [comment]
Hi @Abuelodelanada, I've so far been unable to replicate your issue. Are you sure that you are using beta-2 and not beta-1? this fix is only included in beta-2. Have you tried all the usual repair + rebuild, cache, javascript?

**Comment by Abuelodelanada** [comment]
Hi @Dillon-Brown I'm using beta-1 I will test on beta-2 .... anyway I thought this issue was fixed in beta-1:

https://github.com/salesagility/SuiteCRM/compare/v7.10-beta...develop

**Pull request merged**
