### PR TITLE
Fix #3081 - Export undefined labels

### LINKED ISSUE #3081: Export Customisation shows only "undefined" labels
Version 7.8 and up

#### Issue
When one goes to Studio and clicks on Export Customisation the page that appears shows a list of customisation but all the descriptions are "undefined".

This is a bug that was introduced in the file modules/ModuleBuilder/MB/MBPackage.php when it was rewritten.

There is also another bug at line: 838 where:
                               $return[$value . ' ' . $mod_strings['LBL_EC_EMPTYCUSTOM']] = '';
should be:
                               $return[$value][$va] = $mod_strings['LBL_EC_EMPTYCUSTOM']';

Additionally there are missing labels which default to undefined. To repair this second unwanted behaviour we have to:
. edit the file modules/ModuleBuilder/language/en_us.lang.php to add the missing labels in the section "//EXPORT CUSTOMS" found at line 619
. add a few more cases in the switch statement found at line 829 of the file modules/ModuleBuilder/MB/MBPackage.php

All the issues described have been discussed in the SuiteCRM Forum at:
https://suitecrm.com/forum/suitecrm-7-0-discussion/6952-export-customizations#25069
and https://suitecrm.com/forum/suitecrm-7-0-discussion/12950-exporto-studio-customization
#### Expected Behavior
The correct labels should be displayed informing the users what customisations are available for export.

#### Actual Behavior
The descriptions of the customisations are shown with an "undefined" label

#### Possible Fix (already tested)
1. Correct the bug introduced in the latest versions of SuiteCRM:
A bug was introduced when the file modules/ModuleBuilder/MB/MBPackage.php was rewritten.
To correct the bug it is sufficient to edit line 808

from:
(Current, but wrong code at line 808):
    if (!$module) {

to:
(Correct code to be inserted at line 808):
    if ($module != false) {

2. Add the missing labels
a. Edit the file:  modules/ModuleBuilder/language/en_us.lang.php
Go to line 619: (this is the current content found)
//EXPORT CUSTOMS
    'LBL_EC_TITLE' => 'Export Customizations',
    'LBL_EC_NAME' => 'Package Name:',
    'LBL_EC_AUTHOR' => 'Author:',
    'LBL_EC_DESCRIPTION' => 'Description:',
    'LBL_EC_KEY' => 'Key:',
    'LBL_EC_CHECKERROR' => 'Please select a module.',
    'LBL_EC_CUSTOMFIELD' => 'customized field(s)',
    'LBL_EC_CUSTOMLAYOUT' => 'customized layout(s)',
    'LBL_EC_NOCUSTOM' => 'No modules have been customized.',
    'LBL_EC_EMPTYCUSTOM' => 'has empty customizations.',
    'LBL_EC_EXPORTBTN' => 'Export',
    'LBL_MODULE_DEPLOYED' => 'Module has been deployed.',
    'LBL_UNDEFINED' => 'undefined',

Append the following lines:
   'LBL_EC_VIEWS'=>'customized view(s)',
   'LBL_EC_SUGARFEEDS'=>'customized SugarFeeds(s)',
   'LBL_EC_DASHLETS'=>'customized Dashlets(s)',
   'LBL_EC_CSS'=>'customized css(s)',
   'LBL_EC_TPLS'=>'customized tpls(s)',
   'LBL_EC_IMAGES'=>'customized image(s)',
   'LBL_EC_JS'=>'customized js(s)',
   'LBL_EC_QTIP'=>'customized qtip(s)',

b. Edit the file: modules/ModuleBuilder/MB/MBPackage.php
Go to line 829
Currently there is the following switch statement:
                        switch ($va) {
                            case 'language':
                            case 'Ext':
                                $return[$value][$va] = $mod_strings['LBL_EC_CUSTOMFIELD'];
                                break;
                            case 'metadata':
                                $return[$value][$va] = $mod_strings['LBL_EC_CUSTOMLAYOUT'];
                                break;
                            case '':
                               $return[$value . ' ' . $mod_strings['LBL_EC_EMPTYCUSTOM']] = '';
                                break;
                            default:
                                $return[$value][$va] = $mod_strings['LBL_UNDEFINED'];
                        }

Modify the switch statement to:
                        switch ($va) {
                            case 'language':
                                $return[$value][$va] = $mod_strings['LBL_EC_CUSTOMFIELD'];
                                break;
                            case 'metadata':
                                $return[$value][$va] = $mod_strings['LBL_EC_CUSTOMLAYOUT'];
                                break;
                            case 'Ext':
			        $return[$value][$va] = $mod_strings['LBL_EC_CUSTOMFIELD'];
                                break;
                            case '':
                               $return[$value][$va] = $mod_strings['LBL_EC_EMPTYCUSTOM'];
                               break;
                            case 'views':
                                $return[$value][$va] = $mod_strings['LBL_EC_VIEWS'];
                                break;
                             case 'SugarFeeds':
                                $return[$value][$va] = $mod_strings['LBL_EC_SUGARFEEDS'];
                                break;
                            case 'Dashlets':
                                $return[$value][$va] = $mod_strings['LBL_EC_DASHLETS'];
                                break;
                            case 'css':
                                $return[$value][$va] = $mod_strings['LBL_EC_CSS'];
                                break;
                            case 'tpls':
                                $return[$value][$va] = $mod_strings['LBL_EC_TPLS'];
                                break;
                            case 'images':
                               $return[$value][$va] = $mod_strings['LBL_EC_IMAGES'];
                               break;
                            case 'js':
                                $return[$value][$va] = $mod_strings['LBL_EC_JS'];
                                break;
                            case 'qtip':
                                $return[$value][$va] = $mod_strings['LBL_EC_QTIP'];
                                break;
                           default:
                                $return[$value][$va] = $mod_strings['LBL_UNDEFINED'];
                        }

#### Steps to Reproduce
1. Log in with an Admin user
2. Go to Admin -> Studio
3. Click on the button "Export Customisations"
4. A list of possible things to be exported appears, but the description is "undefined"

#### Context
Low priority. But, since there is a correction it should be addressed asap to remove it from the list of open issues.

#### Your Environment
SuiteCRM 7.8
SuiteCRM 7.8.1
Other variables are irrelevant since the bug has been clearly identified.

### PR DESCRIPTION
**Pull request by amariussi**
Fix for issue https://github.com/salesagility/SuiteCRM/issues/3081

File: modules/ModuleBuilder/language/en_us.lang.php
. Added missing labels

File: modules/ModuleBuilder/MB/MBPackage.php
. Fixed a bug
. Added missing switch options

## Description

See https://github.com/salesagility/SuiteCRM/issues/3081 for details

## Motivation and Context

See https://github.com/salesagility/SuiteCRM/issues/3081 for details

## How To Test This

. Log in as an Admin user
. Go to Admin -> Studio and press the button "Export Customisations"

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@amariussi  @mattlorimer Should language files show words like "tpls" or "qtip" or "SugarFeed"?
Why not use plain english... and also avoid the "Sugar" word?

**Comment by horus68** [comment]
And maybe avoid the "Sugar" word in "SugarFeed"?

**Comment by amariussi** [comment]
Please suggest both labels and text and I will correct them.

Only note that the values I used are those provided by the application itself. I just wanted to avoid undefined labels.

**Comment by gody01** [comment]
Tested pull request localy and can confirm, that it fixes the issue.

**Comment by chris001** [comment]
Hi @Dillon-Brown 
Why is this not yet merged.
Also - why are the codeception feature unit tests #3600 not merged in `hotfix` so that they will check test the new code.
Thank you.

**Comment by ajedvaj** [comment]
Wondering myself exact same thing  - why is this not yet merged?
The bug on export customizations seems critical to me.

**Comment by horus68** [comment]
@Dillon-Brown this issue is on fire!
https://suitecrm.com/forum/suitecrm-7-0-discussion/6952-export-customizations#25069
https://suitecrm.com/forum/suitecrm-7-0-discussion/12950-exporto-studio-customization
https://suitecrm.com/forum/announcements/15690-suitecrm-7-10-preview?start=15#53523

**Comment by horus68** [comment]
@amariussi I used your fixes and it works. 
Consider that the 7.9.5 version file modules/ModuleBuilder/MB/MBPackage.php has a difference not included in your file. The change was introduced to PHP 7.1 exports - see https://github.com/salesagility/SuiteCRM/pull/3678
`public function exportProject($package = '', $export = true, $clean = true)`

**Comment by horus68** [comment]
@Dillon-Brown tested in 7.9.5 and the PR works.
International users only need to change file modules/ModuleBuilder/MB/MBPackage.php : the language pack from Crowdin are already fixed.

without fix: (undefined labels)


tested with fix (OK):

**Pull request merged**
