### PR TITLE
Fix array accessor deprecations in tcpdf.php.

### PR DESCRIPTION
**Pull request by connorshea**
## Description

PHP 7.4 deprecates the ability to access array values with `$array{1}`, instead favoring `$array[1]`. This replaces instances of this syntax in the vendored `tcpdf.php` file.

These deprecation warnings will presumably become exceptions in a future version of PHP.

## How To Test This

Make sure CI passes and do a sanity check of the code.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Are you sure you want to replace this in 3rd party software?

Isn't it better (like you were already working hard to achieve) to move all these into `vendor` directory and get them updated through Composer?

**Comment by connorshea** [comment]
It's blocking us from running CI in 7.4 and tcpdf doesn't seem to even have it fully fixed in the upstream version anyway, so I consider this a necessary change even though it's not ideal.

**Comment by connorshea** [comment]
Without these changes, this failure occurs when running the unit tests on PHP 7.4:

```
1) ViewSugarpdfTest::testViewSugarpdf

Cannot modify header information? : Array and string offset access syntax with curly braces is deprecated

Trace

#0 /home/travis/build/salesagility/SuiteCRM/include/Sugarpdf/Sugarpdf.php(52): PHPUnit_Util_ErrorHandler::handleError(8192, 'Array and strin...', '/home/travis/bu...', 5898, Array)

#1 /home/travis/build/salesagility/SuiteCRM/include/Sugarpdf/Sugarpdf.php(52): require_once()

#2 /home/travis/build/salesagility/SuiteCRM/include/Sugarpdf/SugarpdfFactory.php(45): require_once('/home/travis/bu...')

#3 /home/travis/build/salesagility/SuiteCRM/include/MVC/View/views/view.sugarpdf.php(46): require_once('/home/travis/bu...')

#4 /home/travis/build/salesagility/SuiteCRM/include/utils/autoloader.php(87): require_once('/home/travis/bu...')

#5 [internal function]: SugarAutoLoader::autoload('ViewSugarpdf')

#6 /home/travis/build/salesagility/SuiteCRM/tests/unit/phpunit/include/MVC/View/views/view.sugarpdfTest.php(24): spl_autoload_call('ViewSugarpdf')

#7 [internal function]: ViewSugarpdfTest->testViewSugarpdf()

#8 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/Framework/TestCase.php(908): ReflectionMethod->invokeArgs(Object(ViewSugarpdfTest), Array)

#9 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/Framework/TestCase.php(768): PHPUnit_Framework_TestCase->runTest()

#10 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/Framework/TestResult.php(612): PHPUnit_Framework_TestCase->runBare()

#11 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/Framework/TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(ViewSugarpdfTest))

#12 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))

#13 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))

#14 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))

#15 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/TextUI/Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)

#16 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit_TextUI_Command->run(Array, true)

#17 /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()

#18 {main}

Failed asserting that 'Array and string offset access syntax with curly braces is deprecated' starts with "Cannot modify header information".

/home/travis/build/salesagility/SuiteCRM/tests/unit/phpunit/include/MVC/View/views/view.sugarpdfTest.php:28
```

With these changes, the failure no longer occurs.

**Comment by pgorod** [comment]
I think we have more than one PDF package, maybe just getting rid of tcpdf would be the way to go. We have mPdf and I'm not sure if we don't use even a third one

**Comment by samus-aran** [comment]
@connorshea 
Just a heads up you have less than 24 to submit your shipping details to collect your SuiteCRM goodies.
Check out the details below :point_down: 
https://github.com/salesagility/SuiteCRM/pull/7690#issuecomment-578213178

**Pull request closed without merging**
