### PR TITLE
Fix travis due date

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Adding a 5-second wait to the subpanel due date test to hopefully resolve failing Travis.

## How To Test This

See Travis.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
@Dillon-Brown does Codeception have anything like Capybara, where it can [automatically wait until an element appears on the page](https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends) instead of waiting a fixed amount of time? e.g. if the element appears after 3 seconds it only has to wait 3 seconds, but if it takes 5 seconds it'll wait 5 seconds, etc. (up to a configured max limit of X seconds).

**Comment by connorshea** [comment]
Oh actually it seems like `$I->waitForElementVisible()` is exactly what we'd want, is there a reason that isn't used instead of a wait?

**Comment by Dillon-Brown** [comment]
@connorshea I used wait here because it was slightly faster to type :). I agree we should be using waitForElementVisible instead of wait unless there is some edge case where wait is required (Wasn't planning on actually merging this PR, just wanted to kick off a Travis build).

**Comment by connorshea** [comment]
@Dillon-Brown is there an actual fix for this? I'm suffering from it now :P

**Comment by Dillon-Brown** [comment]
@connorshea This should work #7263 (Or at least it's passing on my Travis....). Will need to spend some time to look into the 7.8.x branch though, seems to be passing both locally and on my forked repo's Travis but then failing on SalesAgility/SuiteCRM.

**Pull request closed without merging**
