### PR TITLE
Image dashboard.png not found

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

When logging is set to warn, an Image dashboard.png not found warning occurs. I have removed the reference to this non-existing image to get rid of the warning.

## How To Test This

1. Activate log on Warn level
2. [WARN] Image dashboard.png not found

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Actually this is more widespread than just one gif. With my log level set to WARNING, I get all this spam on my suitecrm.log:

```
  17447 [WARN] Image List.gif not found
  17426 [WARN] Image Create.gif not found
   1218 [WARN] Image View_Email_Templates.gif not found
   1215 [WARN] Image Schedule_Meeting.gif not found
   1215 [WARN] Image Schedule_Call.gif not found
    810 [WARN] Image View_Project_Tasks.gif not found
    810 [WARN] Image Resource_Chart.gif not found
    809 [WARN] Image View_Diagnostics.gif not found
    809 [WARN] Image View_Create_Email_Templates.gif not found
    809 [WARN] Image Create_Person_Form.gif not found
    418 [WARN] Image dashboard.png not found
    418 [WARN] Image Create_Security_Group.gif not found
    408 [WARN] Image Create_Contact_Vcard.gif not found
    405 [WARN] Image View_Process_Audit.gif not found
    405 [WARN] Image View.gif not found
    405 [WARN] Image Today.gif not found
    405 [WARN] Image Role_Management.gif not found
    405 [WARN] Image Quick_Radius_Map.gif not found
    405 [WARN] Image List_Maps.gif not found
    405 [WARN] Image Create_Lead_Vcard.gif not found
    182 [WARN] Image icon_Administration_32.png not found
    100 [WARN] Image icon_EmailMan_32.png not found
     81 [WARN] Image EmailMarketing.gif not found
     68 [WARN] Image CREATEOutboundEmailAccounts.gif not found
     46 [WARN] Image icon_Home_32.png not found
     34 [WARN] Image icon_UpgradeWizard_32.png not found
     26 [WARN] Image icon_InboundEmail_32.png not found
     13 [WARN] Image _image_inline.gif not found
      5 [WARN] Image png_image_inline.gif not found
      3 [WARN] CSS File yui.css not found
```
This output is obtained with the command
`grep 'WARN' suitecrm.log | cut -d']' -f3- | sort | uniq -c | sort -nr | head -n30`

and the numbers on the left are the frequency of the errors. This is all just in half a day on my lightly used test system, not production...

I would love to see this solved, I don't think log spamming is such a harmless problem. I've spent the past day trying to debug a nasty `SMTP Can't connect` error and I can tell you all this extra crap on my logs is not helping at all.

And 17k warnings in half a day, for something that is absolutely not a relevant problem... that's waaaay too much.

**Comment by Dillon-Brown** [comment]
@pgorod Just encountered this myself. I'll be putting up another PR that hopefully addresses most of these warnings.

**Comment by pgorod** [comment]
That's really great news! Apart from removing the unnecessary references to the images, I'd say the log level of this `missing image` message, when it does really occur, can be lower (maybe `info`) because graphical problems are detected graphically. You look at the screen and see a missing icon. They don't have to be detected by sysadmins in logs.

Thanks a lot @Dillon-Brown.

**Comment by samus-aran** [comment]
@Dillon-Brown - So can you relate this additional PR here?  Does it supersede this one? Or can I review this as is?

**Comment by Dillon-Brown** [comment]
Superseded by #4320

**Pull request closed without merging**
