### PR TITLE
FIX #7780 - Bad css format in Date and Date Range Inputs in search forms

### LINKED ISSUE #7780: Bad css format in Date and Date Range Input in search forms
#### Issue

Date and DateRangeInput in search forms have bad look&feel

### Modal search

In this example we can see al lot of useless free space:

fechas1

dateTimeInputErrormodal

### Legacy search

In this example we can see al lot of useless free space too:

fechas2

dateTimeInputError

### SugarCRM 6.5.x theme

In this old theme, the date range inputs do not have too much free space and the look&feel is nice:

fechas3

### Modal search with fixed search

For example, if you select "Next 30 days" ("Próximos 30 días" in Spanish) everything look good!!

fechas5

### Legacy search with fixed search

For example, if you select "Next 7 days" ("Próximos 7 días" in Spanish) everything look bad

fechas4

### Search Form

Besides in Legacy Search, the fields do not fits the form:

imagen

#### Expected Behavior

A better look&feel for Date and Date Range Inputs ;-)

#### Possible Fix

We should fix styles in `themes/suiteP/css/suitep-base/listview.scss`

#### Context

This "look & feel" makes SuiteCRM not look as good as it could

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 68 / Chromium 76
* Environment name and version (e.g. MySQL, PHP 7): MySQL 8.0 / PHP 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.04

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

Read #7780

## Motivation and Context

Improve SuiteCRM Date and Date Range Inputs look&feel

### Modal Search

In this example we removed useless free space:

fecha_fix1

DateSearchModal_Fix

### Legacy Search

In this example we removed useless free space too and the option selecter fits in the combo.

fecha_fix2

DateSearchForm_Fix

## How To Test This

Open modal search in any module (for example Opportunities) and verify in date Range inputs.

To enable legacy search form include this in config_override.php

```php
$sugar_config['enable_legacy_search'] = array(
    'Opportunities',
);
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Hi @Abuelodelanada, could you look at resolving the conflicts on this PR to allow us to progress this further! Thanks :+1:

**Comment by Abuelodelanada** [comment]
Hi @Mac-Rae 

As far as I understand the conflicts are because the `style.css` are 'one-line' compiled files, and are generated by the Robo Task: `./vendor/bin/robo buil:suite-p`

As are one-line files every change will produce a conflict in git.

**Comment by Abuelodelanada** [comment]
Hi @Mac-Rae 

I merged hotfix-7.10.x into this branch and re-comlipe style.css

I was wondering if we should have style.css under VC...

**Comment by Dillon-Brown** [comment]
@Abuelodelanada Definitely shouldn't be under VC :), same with minified JS files. It's something we'll need to refactor at some point, potentially a Robo task with documentation, compiling on install, etc.

**Comment by Abuelodelanada** [comment]
@Dillon-Brown as far as I understand if those files are removed from VC, two others problems have to be solved:

* How those files will be compiled when building the .zip file for the SuiteCRM packages.
* How those files will be compiled in the install process after cloning this repo.

Am I ok with this?

**Comment by Dillon-Brown** [comment]
@Abuelodelanada Yeah, for the ```.zip``` stuff we can easily include it in our package building process so we only really need to handle the clone from repo which I've started here for JS #7340 but I'll need to look at making another PR for the style.css stuff.

Until we refactor this though, we'll just need to keep rebuilding these files in PRs manually like you've done here.

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Pull request merged**
