### PR TITLE
Only add Bean to array if it really exists

### PR DESCRIPTION
**Pull request by gunnicom**
Otherwise if the bean does not exist php will throw "Trying to get property of non-object"

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Please fix conflicts and update branch to hotfix-7.8.x.

**Comment by Dillon-Brown** [comment]
Looks like this has already been fixed here: #2629

**Comment by gunnicom** [comment]
@Dillon-Brown An this is another good example why these long standing PRs are a problem.
My fix was from July 2016, and the #2629 was from November 2016 ... two people doing the same work, because nobody at salesagility cared. Maybe mine is inferior, but that does not make it better.

**Comment by Dillon-Brown** [comment]
@gunnicom I think we can all agree that the longstanding PR's need addressed, just a matter of time/resources. As you can see I've started to focus on the PR's from the back of the list and getting them assessed / ready to merge. Thank you for all your contributions so far.

**Pull request closed without merging**
