### PR TITLE
Fix #9511: Case Updates Thread now displays updates from 'Unknown' sources.

### LINKED ISSUE #9511: Case Update Thread not showing updates from 'Unknown' sources
#### Issue

When a case update comes in via email, in some cases the email address cannot be matched to a Contact/User. This causes some issues where an update is not displayed in the Case Updates Thread, even if the update is in the CRM.

#### Expected Behavior

The update with no matching Contact/User should be displayed in the Case Updates Thread under 'Unknown'.

#### Actual Behavior

The update is missing from the Case Updates Thread, but can still be found in the AOP_Case_Updates module.

#### Your Environment

* SuiteCRM Version used: 7.11.22

### PR DESCRIPTION
**Pull request by MikeyJC**
## Description

Removes an if statement that checks for a contact_id on the AOP_Case_Updates record so that it will always display the update. When the case update does not have a contact_id to pull a name for the update from, it will instead display it as from 'Unknown'.

## Motivation and Context

This resolves an issue where Case Updates that come from 'Unknown' sources (the email doesn't match with a Contact/User in the CRM etc.) would not be displayed in the Case Updates Thread.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by jack7anderson7 — DISMISSED** [review]

**Comment by clemente-raposo** [comment]
@jack7anderson7 commit messages need a minor clean up

**Comment by clemente-raposo** [comment]
otherwise looks good

**Comment by jack7anderson7** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    
					    Status$acase_status
					    Reference$acase_case_number
					    Description$acase_description
					    
On 07/27/2022, 12:07, ***@***.*** ***@***.*** commit messages need a minor clean up

**Comment by jack7anderson7** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    
					    Status$acase_status
					    Reference$acase_case_number
					    Description$acase_description
					    
On 07/27/2022, 12:08, ***@***.*** wrote:otherwise looks good

**Review by jack7anderson7 — APPROVED** [review]

**Review by clemente-raposo — DISMISSED** [review]
LGTM

**Review by jack7anderson7 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]

**Pull request merged**
