### PR TITLE
CLI Repair commands

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Adds a command for repair and rebuild through robo.

## How To Test This

1. composer install.
2. composer dump-autoload
3. ```./vendor/bin/robo quick:repair```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Hi Dillon, thanks for this! 

I was trying to test it, I created the file in my system manually.

when I run `./vendor/bin/robo list`, I get 

`PHP Fatal error:  Uncaught Error: Class 'Robo\Runner' not found in /var/www/html/vendor/consolidation/robo/robo:41
Stack trace:
#0 {main}
  thrown in /var/www/html/vendor/consolidation/robo/robo on line 41`

This is some problem with Robo, but I believe it was working well before... have you seen this before? Do you know what is going on?

**Comment by Dillon-Brown** [comment]
@pgorod First thing i'd check is you are in the root directory and then run a composer install. I've encountered similar issues when trying to run Robo in docker, this normally fixes it:

```
wget http://robo.li/robo.phar
mv robo.phar /usr/bin/robo
```

**Comment by pgorod** [comment]
I tried that, now I get `Not A Valid Entry Point` on the command-line when I run 

`/var/www/html $ ./vendor/bin/robo list`

And if I `cd` into Robo first, I get this

`/var/www/html/vendor/bin $ ./robo list
PHP Warning:  require_once(modules/Administration/QuickRepairAndRebuild.php): failed to open stream: No such file or directory in /var/www/html/lib/Robo/Plugin/Commands/RepairCommands.php on line 47`

so it seems it starts running Robo correctly, but then it is tripped by the relative path in the `require`.

**Comment by pgorod** [comment]
Ok, so running it from the SuiteCRM root directory, I get the `Not a valid entry point` error which I traced back to these two requires in your file `lib/Robo/Plugin/Commands/RepairCommands.php`:

```php
require_once 'modules/Administration/QuickRepairAndRebuild.php';
require_once 'include/utils/layout_utils.php';
```

Makes sense, doesn't it? How do we manage authorization when running these Robo tasks? If the user isn't logged in as a SuiteCRM admin, he shouldn't be able to do these tasks, should he? Or if he should (because he's admin enough in Linux), how can we get that Entry point check to pass?

**Comment by Abuelodelanada** [comment]
> Makes sense, doesn't it? How do we manage authorization when running these Robo tasks? If the user isn't logged in as a SuiteCRM admin, he shouldn't be able to do these tasks, should he? Or if he should (because he's admin enough in Linux), how can we get that Entry point check to pass?

I think you should be able to run this task even if you do not have SuiteCRM user.  Just login the server via ssh or if is a local machine throught console.

We have a similar tasks in a Makefile:

```bash
rebuild_extensions:
	printf "INICIANDO RECONSTRUCCION DE EXTENSIONES...\n"
	php tools/batch/rebuild_extensions.php
```

And the file `tools/batch/rebuild_extensions.php` is:

```php
<?php

set_include_path(realpath(dirname(__FILE__) . '/..') . PATH_SEPARATOR . get_include_path());

define('sugarEntry', 1);

require_once 'include/entryPoint.php';
require_once 'include/modules.php';
require_once 'include/language/es_ES.lang.php';
require_once 'modules/Administration/QuickRepairAndRebuild.php';
require_once 'modules/Administration/language/es_ES.lang.php';

global $current_user;

$_REQUEST['silent'] = false;

$current_user->is_admin = '1';

$tool = new RepairAndClear();
$tool->show_output = True;
$tool->rebuildExtensions();

echo "\n";
```

**Comment by pgorod** [comment]
Thanks José.

I added `define('sugarEntry', 1);` to the beginning of `lib/Robo/Plugin/Commands/RepairCommands.php` (before the `require`s) and it is now working.

It does throw a few ugly PHP errors on to the screen once the QR & R is running, but that is another issue.

**Comment by isleshocky77** [comment]
@Dillon-Brown First thing jumping out as me and my ocd, can you do namespace repair, so "repair:quick". This way we can eventually put all the other "repairers" in this namespace?

P.s I've been looking for this for so long.

**Comment by Dillon-Brown** [comment]
@pgorod You should be able to run this not logged in as Admin, you would see ```[error]  Unauthorized access to administration.``` if it was an access issue. ```Not A Valid Entry Point``` suggests something is wrong with the pathing as sugarEntry is defined in the bootstrap.

**Comment by isleshocky77** [comment]
This seemed to work fine for me as a quick let's get it out fix.  

My comments would be the following:

1. Change the name to repair:quick (noted above)
1. Looks like the Labels are not being converted (scroll right on line 3 below)
1. Need to update `$repair = new \RepairAndClear::repairAndClearAll(['clearAll'], ['All Modules']);` to return results or used a passed logger. Then have the web display it one way and this display it another
1. Need to do a better job of showing the user they have migrations they have to run
1.  [Feature] Need to create a new task for migrations (new PR and Issue)

## Command Output

```
$ docker exec -it suitecrm ./vendor/bin/robo repair:quick
➜  Starting Quick Repair and Rebuild
<h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3><h3></h3>LBL_MI_REBUILDING Include...<br>LBL_MI_REBUILDING Language...en_us<br>LBL_MI_REBUILDING ActionViewMap...<br>LBL_MI_REBUILDING ActionFileMap...<br>LBL_MI_REBUILDING ActionReMap...<br>LBL_MI_REBUILDING Administration...<br>LBL_MI_REBUILDING EntryPointRegistry...<br>LBL_MI_REBUILDING Extensions...<br>LBL_MI_REBUILDING FileAccessControlMap...<br>LBL_MI_REBUILDING Layoutdefs...<br>LBL_MI_REBUILDING GlobalLinks...<br>LBL_MI_REBUILDING LogicHooks...<br>LBL_MI_REBUILDING Menus...<br>LBL_MI_REBUILDING Include...<br>LBL_MI_REBUILDING ScheduledTasks...<br>LBL_MI_REBUILDING UserPage...<br>LBL_MI_REBUILDING Utils...<br>LBL_MI_REBUILDING Vardefs...<br>LBL_MI_REBUILDING JSGroupings...<br>LBL_MI_REBUILDING Actions...<br>LBL_MI_REBUILDING DC Actions...<br>LBL_MI_REBUILDING RelationshipsLBL_MI_REBUILDING TableDictionary...<br><h3> </h3><h1 id="rdloading"></h1><script type="text/javascript">document.getElementById('rdloading').style.display = "none";</script>
<h3></h3>
<p></p>
<form name="RepairDatabaseForm" method="post">
<input type="hidden" name="module" value="Administration"/>
<input type="hidden" name="action" value="repairDatabase"/>
<input type="hidden" name="raction" value="execute"/>
<textarea name="sql" rows="24" cols="150" id="repairsql">/* Table : meetings */
/*COLUMNS*/
/*MISSING IN DATABASE - gsync_id -  ROW*/
/*MISSING IN DATABASE - gsync_lastsync -  ROW*/
/* INDEXES */
ALTER TABLE meetings   add COLUMN gsync_id varchar(1024)  NULL ,  add COLUMN gsync_lastsync int(11)  NULL ;

</textarea>
<br/>
<input type="button" class="button" value="" onClick="document.RepairDatabaseForm.submit();"/> 
<input type="button" class="button" value="" onClick="document.RepairDatabaseForm.raction.value='export'; document.RepairDatabaseForm.submit();"/><div class='moduleTitle'>
<div class='clear'></div></div>
<h1 id="rdloading"></h1>➜  Quick Repair and Rebuild!
<script type="text/javascript">document.getElementById('rdloading').style.display = "none";</script><h3></h3>
```

**Comment by connorshea** [comment]
Any chance this'll be merged soon? :)

**Comment by connorshea** [comment]
This should probably be a PR on hotfix-7.10.x :)

**Comment by isleshocky77** [comment]
@Dillon-Brown This ever go anywhere?

**Comment by connorshea** [comment]
@isleshocky77 I think this can effectively be considered replaced by @Abuelodelanada's PR #7828.

**Comment by isleshocky77** [comment]
@connorshea 
> @isleshocky77 I think this can effectively be considered replaced by @Abuelodelanada's PR #7829.

So in your opinion should @Dillon-Brown be closing this then?

**Comment by connorshea** [comment]
@isleshocky77 unless he wants to use it to add the other repair tasks not covered by that PR, yeah

**Comment by Dillon-Brown** [comment]
Closing this in favour of #7829

**Pull request closed without merging**
