### PR TITLE
Fix pagination and "no results" in Unified Search

### PR DESCRIPTION
**Pull request by javitoron**
## Description
I have fixed the pagination presentation, making it to have the same structure as normal lists. So I had to add this pagination inside a table inside a thead's row and after column headers.

I have removed the "No results" from the Results table placing it on a paragraph.

You can see how it looked before and after changes in the attached images.

NOTE: I'm using the suitePImproved theme

## Motivation and Context
Pagination displayed ugly and buggy, and you couldn't see page number and total count because font color and background color were the same.

And the "No results" mesasage were shown inside an unnecessary table with column headers and pagination.

search_-_before

After changes:
search_-_now

search_-_no_results

## How To Test This
Make global search and look at the results (haven't tested out of suitePImproved theme)

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [X] My code follows the code style of this project found [here]
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by javitoron** [comment]
this is working in my system, and the travis CI is failing only for PHP 5.5, doesn't even fail for 5.4...

any help?

**Comment by Dillon-Brown** [comment]
Hi @javitoron, this was an issue with Travis that has been fixed and has nothing to do with your code changes. You will need to update your suitecrm fork on github in order to pass. Thanks for the contribution!

**Comment by javitoron** [comment]
ok, I synced my fork... is that the same than updating it? I don't know how to make my pull request pass the checks again...

**Comment by javitoron** [comment]
don't you like it? do I have to do something else?

**Comment by Dillon-Brown** [comment]
Hi @javitoron, no there is nothing else that you need to do for now. You just need to wait for this PR to get code reviewed and then given the "Ready to Merge" label before it will get merged.

**Comment by javitoron** [comment]
I'm messing all this out... I'm starting to understand importance of branches... yes, you all can laugh... :-( and, as I pulled this from the master branch of the fork I can do nothing on it until this pull gets merged... so... I'm going to "revert" last change I did until this get merged...

**Pull request closed without merging**
