### PR TITLE
#7285: allow filter of custom fields on V8 API Get Modules

### PR DESCRIPTION
**Pull request by YonatanRosemarin**
Allow custom fields filter on API

## Description

Fixes bug https://github.com/salesagility/SuiteCRM/issues/7285

## Motivation and Context

Fixing the bug

## How To Test This

Use Get Modules API (V8) - with filter of non-custom fields and of custom fields (steps to reproduce found on the issue)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by YonatanRosemarin** [comment]
If there is a better way to check if a field is custom or not, I will update it accordingly.

**Comment by chris001** [comment]
Nice fix.  Yet Travis build failed, and unfortunately no logs or screenshots due to #8497

**Comment by YonatanRosemarin** [comment]
> Nice fix. Yet Travis build failed, and unfortunately no logs or screenshots due to #8497

Thanks @chris001 . If I'm reading it correctly it fails on:
image

But when tested on my local environment I get the correct response:
image

I'm not sure it's related to my fix, but maybe I'm missing something

**Comment by YonatanRosemarin** [comment]
Hi @chris001 - it's looks like Travis build is OK now, waiting to be reviewed.
Thanks

**Comment by YonatanRosemarin** [comment]
Cannot sign CLA (I have already signed in the past):
image

**Comment by samus-aran** [comment]
Hi @YonatanRosemarin Can you try it again there was a API rate limit hit (due to rechecking the PRs). We only have records of CLA signed from members who have successfully merged into the master branch (or other branches) so they may be a chance you still will need to re-sign. Thanks for your cooperation.

**Review by mattlorimer — APPROVED** [review]

**Review by mattlorimer — APPROVED** [review]

**Pull request merged**
