### PR TITLE
Fix #5520 Do not clear existing attachments when loading a template

### LINKED ISSUE #5520: Emails - attachments are being removed when selecting a template
#### Issue
When I click on Compose E-mail, I add an attachment and afterwards I select a template, the selected attachment is being removed. 

This happens in any case - when I create a new email, add an attachment and select a template, the attachment is removed. When I click on "Send a PDF" from invoiced and/or quotas, the attachment is there, after I select the template *poof* the attachment is gone. 

This happens whether the template contains an attachment or not

#### Expected Behaviour
It should leave the attachment in it's place. When the template contains an attachment, it should keep the manually selected attachment(s) (or the automatically added attachment from the function Send a PDF) ánd the attachment in the template. If the template doesn't contain an attachment, it should keep the manually selected attachment(s) or the automatically added attachment from the function Send a PDF. 

#### Actual Behaviour
It removes any existing attachment in the mail. It's like the "OK" gives a clean all attachments function before it loads the template. This clean all attachment function shouldn't exist at all. 

#### Possible Fix
Remove the clean all attachment function. I'm no programmer but I think I traced the issue back to  /modules/Emails/include/ComposeView/EmailsComposeView.js. This javascript does something with attachment after pushing OK when a template is selected

FYI I installed a clean instance of 7.8.17 (where this works perfectly fine) and also a clean instance of 7.10.2 (where this problem occurs). 

#### Steps to Reproduce

1. Compose e-mail
2. Add attachment
3. Select template
4. *poof* attachment gone

#### Context
High priority! I can't send invoices and/or quotas anymore with the selected template. This means a tremendous manual amount of work. 

#### Your Environment
* SuiteCRM Version used: 7.10.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): any, 64 bit
* Environment name and version (e.g. MySQL, PHP 7): 
Env1. MariaDB 10.2, PHP7.2, Nginx 1.12.2, on Debian 9.4 
Env2. MariaDB10.0.32 PHP 5.6.33 and Nginx 1.10.3 on Debian 8.10

### PR DESCRIPTION
**Pull request by PedroErnst**
Change the behavior when selecting a template in Email compose view, so that current attachments are not removed.

## Motivation and Context

#5520 

## How To Test This

1. Compose e-mail
2. Add attachment
3. Select template
4. Attachment still exists, together with any template attachments

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jbrveen** [comment]
This commit fixes the delete of the attachment but it causes another problem with attachment

Scenario 1: Not selecting a mailtemplate - attachments gets send.
Scenario 2: Selecting a mailtemplate without attachment in template - attachments gets send.
Scenario 3: Selecting a mailtemplate with attachment in template - the attachment from the mailtemplate gets send. The original attachment doesn't.

In all scenario's I can see all the attachments in the composer. So that works. However, in scenario 3 the original attachment doesn't get send, although it shows in the composer.

**Comment by PedroErnst** [comment]
@jbrveen 

Thanks for your feedback. Have you made sure to run repair & rebuild, as well as clearing your browser cache in order to refresh the JS files?

I followed your steps but all the attachments arrived:

Add an attachments

image

Select a template that contains 2 attachments. Composer now shows 3 in total.

image

When sending the email all three attachments get sent

image

Maybe I'm doing something different than you?

Any input would be appreciated.

**Comment by jbrveen** [comment]
@PedroErnst 

I'm doing the same as you, however, it's not saying "Email Attachment".

**Selecting a mail with attachment**
screen shot 2018-03-23 at 15 05 07

**After selecting template with attachment**
screen shot 2018-03-23 at 15 05 31

So, I can see both attachments, so it _seems_ to work, however, when I receive the mail, only the machtigingsfile is being sent, not the Factuur file. And yeah, I rebuild everything.

**Comment by PedroErnst** [comment]
Thanks for taking the time to describe this.
Looking at the icons and the 'Email Attachment' part there seems to be a slight difference.

Also, where does the 3308-... thing come from? Is this a new email from scratch or is it a reply / forward of an existing email?

**Comment by jbrveen** [comment]
The 3308-201803-1.pdf is just the name of the generated PDF (invoice name.pdf). So I opened an invoice, clicked on send PDF and then after selected the template. However, this happens in any case (whether I upload an attachment myself or have it attached by the "Send PDF" function in quotas and invoices). 

However, with the fresh 10.2 installation and this commit, it does work. So there must be some weird code somewhere from the 7.8 upgrade to 7.10 that this doesn't work on my production environment.

**Comment by jbrveen** [comment]
There's btw something else as well - if you give your template **no name** it shouldn't overwrite the subject of the mail...

**Comment by PedroErnst** [comment]
Good to hear that it's at least partly working.

Have you tried in repair an rebuild to run all these processes?

image

Not very sure what else could be causing this.

Regarding the title I agree, but I think it's a different issue and shouldn't be in this PR.

**Comment by jbrveen** [comment]
Alright. Do you want me to submit another bug for the title?

I ran all the processes. Yet it isn't working. See https://pastebin.com/W6k1TE5w for the complete EmailsComposeView.js? However, might be it's not in that file, since the composer does show all the attachments, it's just not being sent.

**Comment by PedroErnst** [comment]
Yeah I think another issue for the title is a good idea.

I don't really know why this would work in a clean install but not in the upgraded instance.

Maybe @Dillon-Brown can tell us more?

**Comment by jbrveen** [comment]
@PedroErnst @Dillon-Brown I copied the whole Emails folder from a fresh 10.2 download to my production environment. Now it works. So I suppose something in the upgrade process fucks this up, however I should test it by upgrading a 7.8 test environment to 7.10 and I don't really have the time for that atm. Maybe one of the devs can check that and confirm there's an upgrade issue. Anyhoo, the workaround is

1. Copy Emails folder from a fresh 10.2 download to your production environment
2. Perform this commit.

**Comment by PedroErnst** [comment]
@jbrveen 

Thanks again. Which 'Send PDF' function is this exactly you mentioned?

**Comment by jbrveen** [comment]
Sorry, my mistake. I’m using it in a local version. It’s called EMAIL PDF (in for example quotas and invoice)

**Comment by PedroErnst** [comment]
Thanks for clarifying. I've found some issue and am working on it.

**Comment by PedroErnst** [comment]
The process of creating an email from a quote as you described works now, when you select a template that contains attachments, and also if you manually add a third attachment.

However the way attachments are handled is still fairly obscure, especially the older code in Email::handleMultipleFileAttachments()

I hope I didn't break anything else with these fixes. Probably a good idea to test this a bit more before merging.

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by samus-aran** [comment]
@PedroErnst Did you have a chance to review this feedback?
https://github.com/salesagility/SuiteCRM/issues/5520#issuecomment-374698502

**Comment by Mac-Rae** [comment]
Please rebase this pull request onto hotfix-7.10.x as the hotfix branch is now specifically for 7.11.x issues.

Please take a look at our contribution guidelines for more information.

**Comment by cameronblaikie** [comment]
@PedroErnst  Just a follow up from @Mac-Rae comment above, could this be rebased onto hotfix-7.10.x as the hotfix branch is now specifically for 7.11.x issues.
Please take a look at our contribution guidelines for more information.
Thanks,

**Comment by PedroErnst** [comment]
@cameronblaikie @Mac-Rae 
Yeah I can have a look at this when I get a chance.  
There are some conflicts to fix, plus the rebase, plus it should need to be tested again to see if it works on the 7.10.x branch as it should.

**Comment by Mac-Rae** [comment]
@PedroErnst 

Where you able to take a look at this?

**Comment by PedroErnst** [comment]
@Mac-Rae that's the rebase done, let's see what Mr. Travis says!

Also the whole thing needs testing, I have no idea if it still does what it's supposed to.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
