### PR TITLE
*WIP Fix/inspections language migration

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

- Use PHP_SAPI, PHP_VERSION and M_PI constant instead of function calls.
- Removed alias functions and instead call origin.
- Replace ```dirname(__FILE__)``` with ```__DIR__```.
- Replace ternary operator with ["Elvis operator"](https://en.wikipedia.org/wiki/Elvis_operator).
- ```instanceof``` can be used.
- Replace ```is_null``` with ```$var === null```.

## Motivation and Context

1. Constants for these functions have been available since [PHP 4](https://www.php.net/manual/en/function.phpversion.php).
2. Alias functions simply reference other functions, this can cause surprises like ```magic_quotes_runtime``` being dropped in PHP 7.0.
3. ```__DIR__``` is equal to ```dirname(__FILE__)```, see [docs](https://www.php.net/manual/en/language.constants.predefined.php).
4. Simplify ternary operator.
5. ```instanceof``` is a language construct and should be preferred.
6. ```$var === null``` should be preferred over function call ```is_null```.

## How To Test This

See Travis, this should not change existing functionality.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
I was going to suggest enabling a linter for enforcing the ternary Elvis, but unfortunately it doesn't look like PHPCSFixer has a lint for it yet :( https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3485

**Comment by Dillon-Brown** [comment]
@connorshea Yeah unfortunate that PHP-CS-Fixer doesn't have a lint for this yet, I've been using the PHPStorm plugin EA Ultimate for most of these inspection PRs.

Afaik we don't override those functions anywhere so these changes should all be safe.

**Comment by Mac-Rae** [comment]
Assessed by Travis +1

However, Needs conflicts sorted before merge

**Comment by serhiisamko091184** [comment]
Hello @Dillon-Brown

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @Dillon-Brown 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

**Pull request closed without merging**
