### PR TITLE
Apathetic cosmos develop google sync cleanup

### PR DESCRIPTION
**Pull request by gymad**
## Description

Fixing minor coding standars issues. related PR was: #6146 and #6539
TODO: still needs to add tests
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by ApatheticCosmos** [comment]
Tests are on my to-do list for today.

**Comment by ApatheticCosmos** [comment]
@gymad Would it be possible to point this PR to the develop branch on my fork? It would make merging it easy.

**Comment by ApatheticCosmos** [comment]
@gymad Nevermind... I figured out how to cherry-pick from pull requests. :)

**Comment by gymad** [comment]
@ApatheticCosmos
```
git remote add gymad https://github.com/gymad/SuiteCRM.git
git fetch gymad
git merge gymad/ApatheticCosmos_develop_google_sync_cleanup
```

**Comment by ApatheticCosmos** [comment]
@gymad Ah ok. Thanks for the heads up.

**Comment by ApatheticCosmos** [comment]
@gymad I've merged everything up to this point, and committed a couple minor fixes.

**Pull request closed without merging**
