### PR TITLE
FIXES #7547 Wrong Login Image on install.php

### LINKED ISSUE #7547: use correct login image on install.php
Install.php references the image sugrcrm_login.png which does not exist. The correct image should be suitecrm_login.php.

This was fixed in #249 but seems to have regressed.

### PR DESCRIPTION
**Pull request by mcarpenterjr**
## Motivation and Context

Install.php has a missing login image. Seems to be a regression.

## How To Test This

Run a silent install.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Travis is having issues again, will run on myfork and feedback results when i know of them

**Comment by Mac-Rae** [comment]
Travis has **PASSED** ingnore results shown below

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by horus68** [comment]
@Mac-Rae so many edits for a single image name change? maybe oudated branch?

**Comment by Dillon-Brown** [comment]
Original issue resolved.

**Pull request closed without merging**
