### PR TITLE
Fix Archive Folder Query

### PR DESCRIPTION
**Pull request by tsmgeek**
Replace subquery with JOIN for performance.

### CODE REVIEW

**Comment by tsmgeek** [comment]
I think this still needs more work as `count(*)` does not work correctly with the new query type due to the `GROUP BY`

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4960043&bid=16388869)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4960043&bid=16388869)

**Comment by Mac-Rae** [comment]
@Dillon-Brown Is this a test failing cause the query is not the same as the query it's expecting? If so that seems like a dumb test... 

Shouldn't it be checking the return of the query?

**Comment by tsmgeek** [comment]
Should I be changing the UT related to this?

**Comment by pgorod** [comment]
@tsmgeek what do you mean by "UT"?...

**Comment by tsmgeek** [comment]
> @tsmgeek what do you mean by "UT"?...

Unit Tests, seems it fails due to that but the query is working and valid.

**Comment by pgorod** [comment]
Ah thanks.

I'm not the authority on tests here, but I guess it makes sense to update the test if your code changes the expected query, and it's a working query...

**Review by Dillon-Brown — APPROVED** [review]
Squashed commits and did a minor code cleanup, LGTM!

**Review by jack7anderson7 — APPROVED** [review]

**Review by samus-aran — APPROVED** [review]

**Pull request merged**
