### PR TITLE
Improve Contacts duplicates list

### PR DESCRIPTION
**Pull request by QuickCRM**
Display city and account name facilitates identification of real duplicates

## Description

Added account name and primary_address_city in query

## Motivation and Context

Contacts duplicate identification is hard when you just display first name, last name and title.
Displaying account name and city makes it easier to find out if that contact is a real duplicate or not.

## How To Test This

Duplicate a contact, or convert a lead when a contact already exists with the same name

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Still appears to only be displaying the 3 default. Done R&R and rebuild relationships with no change. Anything I'm missing? :/

**Comment by QuickCRM** [comment]
Which version of SuiteCRM did you use?

--
Benoit Luquet
NS-Team
Tel. +33 (0)5 61 73 64 14 - +33 (0)6 64 50 59 08

**Comment by QuickCRM** [comment]
I tried again on a 7.10.21 and a 7.10.24 and it worked (Repair is not necessary).
Did your contact have an account?

**Comment by Mac-Rae** [comment]
Assessed :+1:

Think I was being a dafty cause it looks like its working fine now :/

**Review by samus-aran — APPROVED** [review]

**Comment by samus-aran** [comment]
Can not see why Codacy is failing, I would like to ignore that check for this PR.

**Pull request merged**
