### PR TITLE
Support Forum - admin menu link

### PR DESCRIPTION
**Pull request by horus68**
## Description

Wording fix for the admin submenu
## Motivation and Context

file include/language/en_us.lang.php has this string:
`'LBL_TRAINING' => 'Support',`
It is the entry on the admin menu to an external link (SuiteCRM Forum). 
It must be different value then other entries with same value "Support" when it refers to "Support management" for each user site (see the entry for the top menu) 
See \modules\Home\language\en_us.lang.php
`'LBL_HOME_PAGE_3_NAME' => 'Support',`

We need to have different values so they can be translated differently. If not the Crowdin will fill up with same content all entries when downloading.

So include/language/en_us.lang.php needs to be
`'LBL_TRAINING' => 'Support Forum',`
## How To Test This

This is the entry in the admin menu that links to SuiteCRM Forum. Both are "Support" in English, but the administrator link is just an external URL to a forum not a CRM feature. 
Now they will be translated differently (see pic with example for Portuguese pt_PT):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@samus-aran  @salesagility 
Clahub its impossible to work with: Not all contributors have signed the Contributor License Agreement.

- It is broken if submitting PR from git web interface and do not recognize that I have signed it
- I have submitted this PR again, now using github desktop (used to wortk fine) but now its also broken and also do not recognize that I have signed it.

Going to https://www.clahub.com/agreements/salesagility/SuiteCRM it states:
`You have signed this CLA. `

So please just remove this lock or remove the tool and take another direction.
Note: a PR with for a single word change on language value its now a time consuming task!

**Comment by horus68** [comment]
@samus-aran  the CLA lock has gone. Please merge this PR... its an easy one and required for non-english!

**Comment by horus68** [comment]
Requesting @pgorod and @likhobory another community review so this can be accessed and merged!
@shogunpol this is an easy one but required for non-english users!
Note: This is already solved on Crowdin master language, just want to make sure it will not be overridden in the future.

**Comment by likhobory** [comment]
Agree with @horus68 (in Russian lang. pack this string has been renamed to "Forum" several month ago).

**Comment by pgorod** [comment]
@likhobory, just a small tip: if you go into the "Files changed" tab of the PR, you can enter your assessment from the button "Review changes", with several sub-options `Approve`, `Comment`, `Request Changes`. 

(I don't think it's needed for this PR because there are already two reviewers, I'm just saying this for future occasions).

**Comment by likhobory** [comment]
@pgorod, thanks, I'll use it in the future.

**Pull request merged**
