### PR TITLE
Feature/robo api

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Created a robo task for setting up the V8 API. Also added CliRunnerTrait.php for accessing a db connection from CLI.

## How To Test This

1. Run ```composer install```.
2. Run ```./vendor/bin/robo api:configure-v8```.
3. Check that the ```Api/V8/OAuth2/``` private/public keys have been generated and given the correct permissions.
4. Check that the ```Api/Core/Config/ApiConfig.php``` constant ```OAUTH2_ENCRYPTION_KEY``` has been updated.
5. Check that the .htacess file has been rebuilt.
6. Check that the CLI output is correct.

Check that all the following tasks work:
```
  api:configure-v8           Configures the SuiteCRM V8 API with all defaults
  api:create-client          Creates OAuth2 client
  api:create-user            Creates a SuiteCRM user for the V8 API
  api:export-postman-env     Export a postman environment for the V8 API
  api:generate-keys          Generate OAuth2 public/private keys
  api:rebuild-htaccess-file  Rebuild .Htaccess file
  api:set-key-permissions    Sets the Oauth2 key permissions
  api:update-encryption-key  Update OAuth2 encryption keys
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by isleshocky77** [comment]
@Dillon-Brown Thoughts about making the paths on that configurable? Would like to be able to move the keys somewhere out of the library source directory. Also have the ability to add the `OAUTH2_ENCRYPTION_KEY` as a config variable or injected parameter.

**Comment by Dillon-Brown** [comment]
@isleshocky77 Yes, will definitely want all the paths here configurable. Ideally the ```Api/Core/Config/ApiConfig.php``` will need to be changed to be properly customisable too.

**Comment by connorshea** [comment]
Any progress on this? :) I'd appreciate it for being able to easily run the test suite locally.

**Comment by cameronblaikie** [comment]
Tried to test and could not get it to work :disappointed:

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
