### PR TITLE
Feature: New Operator AOR_Reports "Not Contains"

### PR DESCRIPTION
**Pull request by gunnicom**
## Description

Adding a new Operator for AOR Reports
## Motivation and Context

New Operator
## How To Test This

Use the new Operator
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist
- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by mattlorimer** [comment]
this is a nice addition but think my preference would be to add a NOT filed, instead of having to add a NOT for every operator

**Comment by LewMegas** [comment]
I've just tested this again and it is working for us at long last. Many thanks.

Hoping this will be upgrade proof!

**Comment by jssldb** [comment]
Is this going to be merged with the master branch anytime soon?

**Comment by pgorod** [comment]
@gunnicom is it ok to close this one in favor of #5775, since it includes both Workflows and Reports?

**Comment by gunnicom** [comment]
@pgorod Of course. I do not care how it works, i only care about that it works :D

**Pull request closed without merging**
