### PR TITLE
fixed - #2762 Pop up window under the header when edit dashlet

### PR DESCRIPTION
**Pull request by shogunpol**
Pop up window under the header when edit dashlet - fixed
## Description

Pop up window under the header when edit dashlet - fixed
References issue #2762

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Thanks for this Jerzy! I tried it on my system (theme is SuiteR) and it does work to bring the dashlet options on top of the status bar.

However, when editing options of my top dashlets, the dialog box positioning seems to be a bit too high, going off-screen... 

dashlet

Of course this wasn't caused by your fix, maybe the problem was there before, I just couldn't see it...

**Comment by shogunpol** [comment]
@pgorod , yes, unfortunately it still depending on resolution. For SuiteR and Suite7 (because backward compatibility), they not build for resizing screen responsiveness, the only what you can try do, is to find golden middle :) , i hope it helps something. For situation you pictured above, you can use scroll on mouse, it works quite well. And one question, what resolution you use in this screenshot?

**Comment by pgorod** [comment]
My screen is at 1920x1080 but the vertical size of the viewport is smaller (due to the menus and tabs).

I tried reducing the vertical size progressively and I find that the problem with the cropped top starts to happen slightly around 850px (vertical viewport size). At 780px the crop is so bad that none of the top bar of the "edit dashlet" dialog box is visible.

Scrolling with the mouse has no effect in my case...

**Comment by samus-aran** [comment]
z-index:10000000000000? Sounds like a meme. This should be adjusted to accurately reflect something... nicer.

**Comment by pgorod** [comment]
@samus-aran Pedro Ernst did a bunch of z-index fixes after this.

If you can try the original issue on a clean SuiteCRM 7.8 instance (just edit a dashlet and see if the pop-up is fully visible or hidden under the top menu), maybe you'll find out this can be closed.

**Comment by willrennie** [comment]
This is still an issue in the latest 7.8.x release in SuiteR. Worth assessing if we're happy to merge in, with the current z-index value as adjusted by @samus-aran

**Comment by Mac-Rae** [comment]
The top row of dashlets still have the exit bar hidden by the header, all others function fine

**Comment by Mac-Rae** [comment]
This pull request has been closed as the related issue is specific to version 7.8.x of SuiteCRM which has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate the issue this PR fixes in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this PR.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Pull request closed without merging**
