### PR TITLE
Fixed #8375 - Bump recommended PHP version to 7.3.0

### LINKED ISSUE #8375: Bump recommended PHP version to 7.2.0
#### Issue
Currently, SuiteCRM recommends PHP 7.1.0. That version is [EOL as of last week](https://www.php.net/eol.php).

We should update the recommended version in `php_version.php` to 7.2.0, or maybe even 7.3.0.

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Bumping the recommended PHP version up to 7.3 as 7.1 will be [EOL](https://www.php.net/eol.php).

## Motivation and Context

Issue reference: #8375 

## How To Test This

Install a fresh instance and check that the recommended PHP version is 7.3.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by pgorod** [comment]
I suggest adding the `Needs Documentation` label

**Comment by connorshea** [comment]
bump :)

**Review by craigpanton — DISMISSED** [review]
LGTM

**Review by code-ph0y — DISMISSED** [review]

**Review by jack7anderson7 — APPROVED** [review]

**Comment by jack7anderson7** [comment]
No longer needed for 7.12.x

**Comment by jack7anderson7** [comment]
No longer needed for 7.12.x

**Pull request closed without merging**
