### PR TITLE
Remove unused and inexistant mod string assignment

### PR DESCRIPTION
**Pull request by PedroErnst**
An assignment for a template variable that was not being used was causing a PHP notice.

## Motivation and Context

Removes a notice.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Hi @PedroErnst. Are you _sure_ it's not being used? 

We currently have made a big mess out of unused language strings, especially in cases like this where the label name is built from variables. We removed a lot of strings that should be there, and we'll have to reinstate them. I just want to make sure this is not one of them...

Please see #4291 
Thanks!

**Comment by PedroErnst** [comment]
I am _fairly_ sure.

The label appears to be built from variables, but in fact that variable is hard coded just a few lines further up in the function, and will always be LBL_IMPORT_CUSTOM_TITLE.

Which does not appear in any of the language files.

And the key, INSTRUCTIONS_TITLE does not appear anywhere either.

So, I'm not a 100% but really close.

**Comment by pgorod** [comment]
Ok... I think you might be right. :-)

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
