### PR TITLE
Fix opt in label in contacts filtering.

### PR DESCRIPTION
**Pull request by e-reeley**
## Description

Display label changed to make it more clear for the user to filter their search.

## How To Test This

1) Navigate to the 'Contacts' module
2) Select filter
3) Navigate to the bottom of advanced filter
4) View the labels in 'Opt in Primary Email'

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Excelent move!

**Comment by horus68** [comment]
Excelent move! @e-reeley please take a look into this one too
https://github.com/salesagility/SuiteCRM/issues/5205

**Comment by e-reeley** [comment]
Hi @horus68 

This is one that I also was not sure about, I think we will have a discussion and see if we can come to an agreement on how these labels should be displayed to make it most intuitive while remaining compliant with the GDPR rules.

We will look into this one though! 

Thanks.

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
