### PR TITLE
Optimistic Locking not working in some cases

### PR DESCRIPTION
**Pull request by gunnicom**
In some cases sugar retrieves more object of the edited type. This leads to that the optimistic locking id is not the one thats in the edit view, but some other (maybe from relation).
So if someone saves the same record in a different session, the one that saves later simply overwrites the first changes, and does not show the dialog for conflicting saves.
This change makes sure the id from the request is stored in the session, not the id from the last fetched record that maybe from a related bean.

## Motivation and Context
On conflicting saves under specific circumstances the conflict dialog is not shown.

## How To Test This
Not quite sure about the exact requirements for this bug. I assume it is some custom relationships, that relate to the same module, or to an other module and then to the same module again.

Expected:
When saving a record and someone else changed the record within the same time a dialog about that conflicting change should show.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by chris001** [comment]
1. Could you edit PR and change branch to `hotfix`.
2. What would be great, if you can, could you code up a phpunit test verify that with this code, and two sessions editing the same editview, it is saving the data correctly, and that without this code, two sessions in the same editview, one changes the data, the second also changes and saves the data, the save overwrites the first session's data without notification or warning, which equals bad data, it fails the test.

**Comment by gunnicom** [comment]
Sorry, i totally dont know how to do phpunit.

**Comment by pgorod** [comment]
@gunnicom you seem to have an extra commit (by samus-aran) in this PR, it seems you didn't start from a branch that was completely up to date with SalesAgility...

**Comment by gunnicom** [comment]
Ok, i do a new pull request, seems like switching the branch pulled in the other commit

**Comment by gunnicom** [comment]
Replaced by new PR in correct branch

**Pull request closed without merging**
