### PR TITLE
Bugfix 1338

### PR DESCRIPTION
**Pull request by ChangezKhan**
Fixed bug #1338 Print page - link issue

## Description
Provided fix to bug #1338 
As mentioned in the bug, this issue was with `SuiteP` and `SuiteR` themes. So, it was an issue in `Bootstrap` css. 
To reproduce, press `Ctrl+P` or take print out of the page.

## Motivation and Context
Now, user can take print out the page with clear name

## How To Test This
Just press Ctrl+P or take print-out of the page

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by mbates14** [comment]
I downloaded the patched CSS files, still doesnt work! does the same thing.

**Comment by ChangezKhan** [comment]
Hello @mbates14 , I am unable to reproduce the same error after patching css files. Kindly share some screenshots of screens, if possible.

**Comment by mbates14** [comment]
Yes, the only way I can get the links to disappear is if I go into the reports editor, and actually "uncheck" link. Then they go away on the print. But, I cant click on them anymore because I took the link away.

Also the problem exists in all of the Themes on my end. I can give you access to my CRM system for you to play around? Let me know. Also I noticed another issue which may or may not be related, is I cant "view" anything at all in the system. Accounts, cases, anything. I actually have to physically search for what I want to pull up, and that works. But I cant list anything. At one time I could, but something broke.

**Comment by ChangezKhan** [comment]
Hello @mbates14 , yes you can give me access to your system. But one thing I need to know, have you patch those css files correctly or not? Because it all matters on this. Can you share your css files as well. 
I am able to take a print of screen with a link also, without doing anything extra, apart from patching those css files.

**Comment by mbates14** [comment]
Yes the CSS was properly patched, And the CRM is running the latest repository 7.8.1 So if the patch was already here, its been downloaded and already on the server. I need an email address or something so I can privately get in touch with you to get you access to our CRM.

**Comment by ChangezKhan** [comment]
Hey @mbates14 , this patch is not merged yet. So, it wouldn't be available in 7.8.1.  
@shogunpol, please correct me, if I am wrong.

**Comment by mbates14** [comment]
I ended up blowing out and reinstalling my CRM due to a multitude of other issues I had ran across. Something was broken in the file system, or DB somewhere that was returning 0 search results, and when clicking View "anything" nothing would show. Anyways...

Upon re-installing the CRM and bringing by data back over, I used Git Clone from this repository to do the installation so it should be in there. BUt... again it still shows the links in print on my Sales Report unless I uncheck "link" in my edit form. So I have to create 2 reports basically. One for print, and one for use.

**Comment by ChangezKhan** [comment]
Hello @mbates14 , I have no idea why you are still facing the problem. Sorry, I have nothing to say now. Everything is working as it should. 
Just one thing you can do, just check in this file ` themes/SuiteP/css/bootstrap.min.css`, whether these lines of code are available or not 

     @media print {
         a[href]:after {
             content: none !important;
         }
     }

Let me know.

**Pull request merged**
