### PR TITLE
Fix #10207 #10209 - Multiple Elasticsearch indexing issues

### LINKED ISSUE #10207: Problem running ElasticsearchIndexerScheduler from cron
When Elasticsearch indexing is scheduled from admin-&gt;Elasticsearch (buttons "Schedule full indexing" and "Schedule partial indexing"), the resulting cron job fails.

#### Issue

Cron job "Index requested by an administrator" fails with an error (log or console if PHP cron.php run):
 ```
PHP Fatal error:  Uncaught Error: Object of class SchedulersJob could not be converted to string in /var/www/html/SuiteCRMFirst/modules/Schedulers/_AddJobsHere.php:910
Stack trace:
#0 /var/www/html/SuiteCRMFirst/modules/SchedulersJobs/SchedulersJob.php(529): runElasticSearchIndexerScheduler()
#1 /var/www/html/SuiteCRMFirst/include/SugarQueue/SugarCronJobs.php(191): SchedulersJob->runJob()
#2 /var/www/html/SuiteCRMFirst/include/SugarQueue/SugarCronJobs.php(233): SugarCronJobs->executeJob()
#3 /var/www/html/SuiteCRMFirst/cron.php(100): SugarCronJobs->runCycle()
#4 {main}
  thrown in /var/www/html/SuiteCRMFirst/modules/Schedulers/_AddJobsHere.php on line 910
```
#### Expected Behavior

The scheduled job should run with success.

#### Actual Behavior

The scheduled job fails with the above error message in the log/console.

#### Possible Fix

The problem seems to be caused by the following line (910) in modules/Schedulers/_AddJobsHere.php:
```
return \SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer::schedulerJob(json_decode((string) $data));
```

It is my belief that intention of ```json_decode((string) $data)``` is to convert an object contained in ```$data``` variable into an array (probably using ```jsond_decode(json_encode($data))``` . Changing this line to:
```
return \SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer::schedulerJob((array) $data);
```
Seems to solve the problem.

#### Steps to Reproduce

1. Schedule full or partial indexing from the Elasticsearch page in the Admin
2. Run cron manually or wait to be run automatically
3. Observe error messages
4. Check the status of the "Index requested by an administrator" job in the ```job_queue``` table in the database.

#### Context

I tried to run the Elasticsearch index to see what fields are sent to Elasticsearch.

#### Your Environment

* SuiteCRM Version used: 7.14.0 / Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 117.0.5938.92 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.1.2-1ubuntu2.14
* Operating System and version (e.g Ubuntu 16.04): 
XUbuntu
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

### PR DESCRIPTION
**Pull request by JanSiero**
This bugfix solves multiple issues concerning elasticsearch indexing, specifically https://github.com/salesagility/SuiteCRM/issues/10207 and https://github.com/salesagility/SuiteCRM/issues/10209

## Description
Elastic search indexing by cron has been broken for some time, especially due to some code reworking. This PR clears a series of bugs and issues which should make Elastic Search run more stable and user friendly

### `modules/Schedulers/_AddJobsHere.php`

- The method "runElasticSearchIndexerScheduler" is called from
https://github.com/salesagility/SuiteCRM/blob/54bc56c3bd9f1db75408db1c1d7d652c3f5f71e9/modules/SchedulersJobs/SchedulersJob.php#L525-L529

`call_user_func_array` is called with "$data" which is an array that consists out of two items:

1. $this - the SchedulersJob object
2. $this->data - the parameters with which elastic should run

Consequently the method runElasticSearchIndexerScheduler should contain _two_ arguments, of which only the second ($data) is used with as default value an empty JSON object: "{}"

- As the parameters are passed as a JSON String and a friggin' purifier htmlencodes them on saving, these need to be html-decoded.

- JSON_decode should output as an associative array, hence the "true" argument

_Rolled back changes of #10280_

### `lib/Search/ElasticSearch/ElasticSearchIndexer.php`
Coalesce with an empty array in case the index was not created to avoid PHP warnings

### `data/SugarBean.php`
With commit https://github.com/salesagility/SuiteCRM/commit/26c92909d0bd58da76cce33799c3887494f5335a the variable "$rows_found" was initialized at the start of the method process_list_query, 
https://github.com/salesagility/SuiteCRM/blob/54bc56c3bd9f1db75408db1c1d7d652c3f5f71e9/data/SugarBean.php#L4248-L4250
essentially turning the following:
https://github.com/salesagility/SuiteCRM/blob/54bc56c3bd9f1db75408db1c1d7d652c3f5f71e9/data/SugarBean.php#L4350-L4352 into dead code and pullNextBatch in
https://github.com/salesagility/SuiteCRM/blob/54bc56c3bd9f1db75408db1c1d7d652c3f5f71e9/lib/Search/ElasticSearch/ElasticSearchModuleDataPuller.php#L166-L174

returning null instead of the records that require indexing. Therefore the check has been changed to test `$rows_found == 0`

### `lib/Search/UI/SearchThrowableHandler.php` and `modules/Home/language/en_us.lang.php`

When for some reason for one or more modules no index has been created, then when using global search an unhelpful message "an unknown error has occurred" is displayed. The changes in these files make sure an appropiate error message and solution (perform full indexing) is provided.

### `modules/Administration/Search/ElasticSearch/Controller.php`

On the Admin / ElasticSearch page the last run of an elastic search job is displayed. If you are not located in the UK or PT, but in another time zone, the displayed time and the human readable time difference is off by one or more hours. "check_date_relationships_load" makes sure the times and time formats are according to the time zone location of the user.

### `lib/Search/Index/IndexingSchedulerTrait.php`

~~On the configuration page of elasticsearch there is checkbox to enable it. Until this is saved, elastisearch is still disabled,which inhibits the Full and Partial indexing (cron will skip it silently). It is counterintuitive that this setting has to be saved first, before being allowed to manually index elasticsearch.~~ 
~~This change will allow for manual (full or partial) indexing even when elastic search is still disabled: When running a manual index the $option array will contain {partial: true} or {partial: false}, else it will be empty.~~

~~This also enables an administrator to first check if indexing works correctly before enabling Elasticsearch systemwide.~~

_Rolled back changes of #10280_

### ~~`modules/Administration/Search/ElasticSearch/Controller.php` and~~ `modules/Administration/Search/ElasticSearch/scripts.js` and `modules/Administration/language/en_us.lang.php`

~~It is counterintuitive that a manual indexing will not use the entered host parameters. Pass the elastic host credentials when manually starting a full or partial indexing, save them so they will be used on the next scheduled indexing.~~

Check the return value for an indexing request and give a useful response

### `modules/Administration/Search/ElasticSearch/view.tpl`

The JavaScript file ajaxSubmit.js was removed in 7.14 and should not be referenced.

### `modules/Schedulers/Scheduler.php` and `modules/Schedulers/language/en_us.lang.php`

Create a Scheduler entry for Elasticsearch. As long as elasticsearch hasn't been enabled this scheduler will not attempt to index anything.

It should be considered to also create this entry when upgrading.

Changed `ElasticSearch` to `Elasticsearch` in language strings as per https://github.com/salesagility/SuiteCRM/pull/10275#issuecomment-1898295032

## How To Test This
See #10207 and #10209

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

Please also consider approving the documentation changes:
https://github.com/salesagility/SuiteDocs/pull/630

### CODE REVIEW

**Comment by JanSiero** [comment]
Hi @serhiisamko091184 

Here you go.

Note to self:
 - create diff
```
git reflog
git reset --hard c*******
git pull
git merge
```
 - apply diff
```
git commit -a -m ...
git push -f origin bugfix_*****
```

**Comment by serhiisamko091184** [comment]
Hey @JanSiero,

thanks for quick reply and changes you've done! 

Regards,
Serhii

**Comment by chris001** [comment]
Looks good.   @JanSiero  is the [CLA signed](https://cla.suitecrm.com/salesagility/SuiteCRM)?  It says "_Expected - waiting for status to be reported_".

**Comment by JanSiero** [comment]
> Looks good. @JanSiero is the [CLA signed](https://cla.suitecrm.com/salesagility/SuiteCRM)? It says "_Expected - waiting for status to be reported_".

Hi @chris001 Something seemed to have gone wrong with the CLA check, as I confirmed this a long time ago. I clicked on your link and now it seems confirmed again.

**Comment by chris001** [comment]
Also fixes #8899 from 2020.
Hope the team will review and if approved, merge ASAP!

**Comment by JanSiero** [comment]
> Also fixes #8899 from 2020. Hope the team will review and if approved, merge ASAP!

HI @chris001 a slightly different and suboptimal pull request #10280 was merged Friday.

**Comment by chris001** [comment]
@JanSiero Shouldn't this one be merged also as it fixes more issues and improves user experience?

**Comment by JanSiero** [comment]
Hi @chris001, I am not in a position to decide on this.

**Comment by chris001** [comment]
Sorry, I meant, this PR here has additional valuable fixes and improvements to quality of user experience, that 10280 does not have.  So it should definitely be code reviewed and if passes, merged.  Would you agree?

**Comment by clemente-raposo** [comment]
Hi @JanSiero!

Thank you for bringing this issue to our attention: 

- https://github.com/salesagility/SuiteCRM/pull/10280#issuecomment-1890449496

We've reviewed your PR and we would like to merge it, overriding part of our changes.

However, there are 2 points we would to go over with you:

**1. Saving the host and the credentials when scheduling a re-index or parting re-index**

We understand the reason for this changes, however we would prefer to keep the save process separate from the index scheduling process.

As such we would prefer to do a UI/UX change instead:
- Move the `Schedule full indexing` and `Schedule partial indexing` buttons to a new entry on the admin panel, called "ElasticSearch Indexing"
- Having these 2 on a separate entry would make things a lot cleared to the user, within the "ElasticSearch Indexing" admin entry we could disable the indexing buttons until the credentials are saved on the "Elastic Search" settings page.
-  A message with the reason for the buttons being disabled would also have to be displayed.

We would like to do these changes as part of another PR and if possible remove the changes related with saving the credentials from this PR, so it can get merged earlier.

**2. Allowing to index when ElasticSearch is disabled**

> lib/Search/Index/IndexingSchedulerTrait.php
> On the configuration page of elasticsearch there is checkbox to enable it. Until this is saved, elastisearch is still disabled,which inhibits the Full and Partial indexing (cron will skip it silently). It is counterintuitive that this setting has to be saved first, before being allowed to manually index elasticsearch.
> This change will allow for manual (full or partial) indexing even when elastic search is still disabled: When running a manual index the $option array will contain {partial: true} or {partial: false}, else it will be empty.
> his also enables an administrator to first check if indexing works correctly before enabling Elasticsearch systemwide.

The suggestion of adding a new  "ElasticSearch Indexing" admin entry on the admin menu would also impact this point. 
- As we would disable the buttons until the `Enable Elasticsearch`  is ticked (i.e. enabled) on the ElasticSearch settings screen
- A message with the reason for the buttons being disabled would also have to be displayed.

Like on the previous point we would like to do these changes as part of another PR and if possible remove the changes related with bypassing the `Enable Elasticsearch` from this PR, so it can get merged earlier.

Feedback regarding these 2 points above is welcome.

Yet again thank you for bringing this up.

**Comment by JanSiero** [comment]
Hi @clemente-raposo,

Thank you for your consideration! I can live well with your proposed changes to the UI-flow. If I was able to do this quickly, I'd done it myself.

I have updated the code as well as the description of this pull request according to your comments.

I haven't tested it this time before pushing, so please use with caution. Let me know if these changes were what you had in mind. Then I can also test this.

**Comment by clemente-raposo** [comment]
Hi @JanSiero! Yet again thank you.

You did well in reverting the changes from https://github.com/salesagility/SuiteCRM/pull/10280.

And I agree with the following:
> `empty(0) = true` and `empty('0') = true`, so this code portion will never execute when $assoc['c'] == 0 -> there is no need to revise the check.

We will pass this issue to our QA team before merging, as we usually do.

**Review by clemente-raposo — DISMISSED** [review]

**Comment by horus68** [comment]
On the language strings the proper name should be:
`Elasticsearch` and not `ElasticSearch`
https://www.elastic.co/

**Comment by JanSiero** [comment]
> On the language strings the proper name should be: `Elasticsearch` and not `ElasticSearch` https://www.elastic.co/

Thanks @horus68 , these strings were not part of this PR, but I corrected them anyway.

**Comment by clemente-raposo** [comment]
Hi @JanSiero, yup thank you for fixing those.

I've pushed a fix for the date diff (the are that says e.g. "58 min ago"). During testing @johnM2401 was getting a blank page with an error form some date user formats.

@horus68 thank your bringing this up.

**Review by clemente-raposo — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
LGTM!

Appears to be working well, tested the following:

- Manua Partial and Full Indexes running as expected, respective of which one was selected
- Neither Scheduled Job nor Manual Indexes run if ES is disabled in CRM
- New Scheduled Job works as expected and runs successfully via Cron
- Admin->ElasticSearch panel now renders the previous Scheduled Job run in the User's selected Date/Time format & Timezone.
- All above working in both PHP7.4 and PHP8.2

Thank you again!

**Pull request merged**
