### PR TITLE
Issue1783

### PR DESCRIPTION
**Pull request by emcrobert**
Fixed a broken if statement that caused the date in inline edit to always be set to the current date

## Description
Due to an incorrect if statement the code in inline edit always set the date to the current date. This fixes this issue. You can recreate it by setting any date value to a date other than the current date then try to edit it with inline edit and check the date you set is shown.

## Motivation and Context
To fix a bug with inline editing dates

## How To Test This
Inline edit a date and check it shows the value you expect

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- x[ ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Mausino** [comment]
duplicate of issue #1042

**Comment by willrennie** [comment]
@Mausino this is a pull request to fix the issue, not a duplicate issue being logged.

**Comment by Mausino** [comment]
@willrennie sorry my mistake...  i am still learning

**Comment by willrennie** [comment]
@Mausino it is however a PR for an issue that is a duplicate of issue #1042

**Pull request closed without merging**
