### PR TITLE
Fix/5094 case description

### PR DESCRIPTION
**Pull request by PedroErnst**
Call tinymce init again after the page is loaded on Cases create view.

## Description

A conflict arises due to the timing of the code which hides the updates field. The updates field is initialized first, but has to wait for a callback from an ajax request. By the time it comes back, the field -has been deleted by the code in Cases/views/view.edit.php L 70-75.

The solution is to hide the field instead of deleting them, and then manually calling tinyMCE init again.

## Motivation and Context

Issue #5094 
Issue #5659 

## How To Test This

1. Go to cases module
2. Create a new case
3. See the description fields displays wysiwyg editor.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by aarondglover** [comment]
This works when creating a Case. The wysiwyg editor appears.
The wysiwyg editor also appears when editing a case.

The wysiwyg editor DOES NOT appear if you use the "Save and Continue" or Navigate Next/Previous Buttons

**Comment by pgorod** [comment]
@Dillon-Brown this needs to be reopened because of the above comment by @aarondglover.

Also [on the Forums](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18759-case-description-field-text-entry-isn-t-saved-after-upgrading-to-7-10-4?start=15#66604) someone is saying that

> I analize the situation with my user and she register cases using the cases subpanel inside accounts module. When she register using cases module works fine. 

On the other hand, this other PR #5816 seems to overlap with this one? It's changing the same part of the same file.

**Comment by PedroErnst** [comment]
@pgorod 

#5816 addresses the scenario reported by @aarondglover 
It seems to fix the issue. But it's not yet merged.

Then there's also #5840, which replicates both this PR #5672 and #5816, but for 7.8.x, and the changes do not seem to have carried over into 7.10.5

It's a bit confusing.

I'm going to have a look at that forum post.

**Comment by lw9474** [comment]
I just upgraded to 7.10.5 hoping it would resolve this issue.
Unfortunately it  breaks it worse.
7.10.4 would not save description when ticket was created. But would save it if you edited an existing ticket and added the description.

After uppgrade to 7.10.5 and now it does not save when you edit the case either.

Thanks

**Comment by lw9474** [comment]
I just upgraded to 7.10.6 and it still does not save the description of the problem.

[Fri Jun 15 15:25:45 2018] [error] [client 192.168.101.10] PHP Notice:  Undefined property: aCase::$type in /var/www/html/suitecrm/modules/AOP_Case_Events/CaseEventsHook.php on line 74, referer: http://192.168.101.55/suitecrm/index.php

**Comment by pgorod** [comment]
@lw9474 [line 74 on that file](https://github.com/salesagility/SuiteCRM/blob/v7.10.6/modules/AOP_Case_Events/CaseEventsHook.php#L74), in 7.10.6, doesn't seem to have any reference to `$aCase`...

Is your file different? If so, why?

**Comment by lw9474** [comment]
Not to my knowledge.
I just applied the upgrade as normal.
I did check the dates on the modules cases directory and they were
yesterday so I assume the code is the 7.10.6 version.

THX



Wish Markwalter
Karz Systems, Inc.
706-651-0080  XT 209

**Comment by pgorod** [comment]
Well, does your file match the one in the link I gave you? If not, what does it contain?

**Comment by lw9474** [comment]
Sorry.  I did not see the link.  
There is no difference in file in the link and the one in production:

[root@lenny AOP_Case_Events]# diff CaseEventsHook.php /tmp/CaseEventsHook.php
[root@lenny AOP_Case_Events]#

**Comment by pgorod** [comment]
I can reproduce the behaviour of not being able to edit `Description` in a Case, but I can't get that error to show. Maybe it's not strictly related...

**Comment by pgorod** [comment]
@Dillon-Brown is this a matter of copying some PR into the 7.10 branch like @PedroErnst suggests? I am a bit confused...

**Comment by lw9474** [comment]
Do not call tiny mceAddControl on edit view #6165
This PR fixes the edit issue.
But it still does not save the description when a new case is created.
After making the patch there is not an error in the /var/log/httpd/error_log but nothing gets saved in the description.  My line 74 is the same as the one in the fix.

THX

**Pull request merged**
