### PR TITLE
FIX #5356 - The marker images URLs in Maps were wrong

### LINKED ISSUE #5356: No marker images in maps
#### Issue

The marker images in maps are not shown.

broken_image_2

#### Expected Behavior
The markers images should be visible.

#### Possible Fix

The URL of the images are wrong.

#### Steps to Reproduce

1. Create a map.
2. Show the map

#### Your Environment

* SuiteCRM Version used: 7.10.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 58
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6 + MySQL 5.7, Apache 2.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 17.10

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

The URL of marker images in Maps were wrong

## Motivation and Context

See #5356 

## How To Test This

1.- Create a Map.
2.- Show that map 
3.- Verify that marker images are shown

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Should'n the images be placed in a SuiteCRM folder? 
Would be useful for those using behind strict firewalls or internal network

**Comment by Abuelodelanada** [comment]
Hi @horus68

I think the same but for this PR I prefer not to change the way the images are retrieved.

Let me know if you prefer the images in a SuiteCRM folder I can do it in another PR

**Comment by horus68** [comment]
@Abuelodelanada I can agree with the easy fix to make things work. But this should be a rule of thumb: 
> Resources should be always part of software package and not served from remote

@Dillon-Brown The maps module requires a definitive fix as there are several PR on this:
See details on issues raised by an external URL for images and maps.
https://github.com/salesagility/SuiteCRM/pull/1422#issuecomment-231604303
https://github.com/salesagility/SuiteCRM/issues/1438

PR related
https://github.com/salesagility/SuiteCRM/pull/5071
https://github.com/salesagility/SuiteCRM/pull/3089
https://github.com/salesagility/SuiteCRM/pull/1777
https://github.com/salesagility/SuiteCRM/pull/5071

**Comment by samus-aran** [comment]
Hi @horus68 & @Abuelodelanada 
Ideally, as horus68 says, we would prefer to have a permanent location, but that would requiring the full library into the core and realistically that would be more overhead to maintain (though it is historical), bloat the application further and doesn't align with our vision to segregate third party libraries from the main application.

Couple of solutions here:
- introduce bower to dynamically pull this down and use that for the relative location
- move away from this library all together

But as it is an issue currently and there isn't an indication that this repo will be removed I would prefer to pull this suggested PR in and investigate a more permanent solution. 

As this is an old issue, can we make this PR to 7.8.x-hotfix? Then we can apply it to all the verisons?

**Comment by Abuelodelanada** [comment]
Hi @samus-aran @horus68 

In this PR #5521 is the fix for 7.8.x :)

**Comment by samus-aran** [comment]
Merged into 7.8.x instead.

**Pull request closed without merging**
