### PR TITLE
FIX #7675 - Add a function to compare properly indices definitios

### LINKED ISSUE #7675: Repair Required just after Fresh Install 7.11.7
#### Issue

Just after a fresh install, when I had a quick repair, It appended execute section.  where this code is appearning

/* Table : users */
/*COLUMNS*/
/* INDEXES */
/*INDEX MISMATCH WITH DATABASE - idx_user_name -  ROW <name> idx_user_name <type> index <fields>[0] => 'user_name'  [1] => 'is_group'  [2] => 'status'  [3] => 'last_name'  [4] => 'first_name'  [5] => 'id'  */
/* VARDEF - idx_user_name -  ROW<name> idx_user_name <type> index <fields>[0] => 'user_name'  [1] => 'is_group'  [2] => 'status'  [3] => 'last_name (30)'  [4] => 'first_name (30)'  [5] => 'id'  */
ALTER TABLE users   DROP INDEX idx_user_name,  ADD INDEX idx_user_name (user_name,is_group,status,last_name (30),first_name (30),id);

#### Expected Behavior

First repair must be clean repair, should not require anything to execute, that must be managed during installation time automatically.
#### Actual Behavior

At SuiteCRM Log:
08/01/19 08:49:36 [8300][-none-][FATAL] User update error: Temp User is not retrieved at ID 1, boolean given
08/01/19 08:49:36 [8300][-none-][FATAL] Email address save error
08/01/19 08:50:05 [8300][1][FATAL] Chart class not found.
08/01/19 08:50:07 [8300][1][FATAL] Chart class not found.
#### Steps to Reproduce

1. click on admin
2. click on quick repair and rebuild
3. scroll down to bottom

#### Your Environment

* SuiteCRM Version used: 7.11.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): 

PHP Version 5.6.38
MySQL Version 5.7.23 

--

* Operating System and version (e.g Ubuntu 16.04):
Windows , Using WAMP

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

This PR fixes #7675

## Motivation and Context

See #7675

## How To Test This

1. Go to on admin
2. Click on quick repair and rebuild
3. Verify that (if you have already created in DB) the following index it is not created again:

```sql
ALTER TABLE users DROP INDEX idx_user_name, ADD INDEX idx_user_name (user_name,is_group,status,last_name (30),first_name (30),id);
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by pgorod** [comment]
It seems there's a problem with part of this PR. As the function `fixIndexArrayFormat` was moved from `include/utils.php` to `include/utils/array_utils.php`, it seems some upgrades break because the function is called during the upgrade, but isn't there yet:

https://community.suitecrm.com/t/error-fixindexarrayformat-in-dbmanager-php-1041/73154

I don't know, but maybe that file should be added somewhere in here:
https://github.com/salesagility/SuiteCRM/blob/master/modules/UpgradeWizard/uw_utils.php#L725-L776

Those are the files that are pre-copied during "upload" step of upgrade wizard.

**Comment by Abuelodelanada** [comment]
Hi @pgorod 

May be it is a good approach, anyway do you know how to reproduce it?

**Comment by pgorod** [comment]
Generically speaking, I know this will happen in any upgrade with these conditions:
1. Coming from a version before `fixIndexArrayFormat` was moved
2. Going to any version after the move
3. The upgrader code executes this line:

https://github.com/salesagility/SuiteCRM/blob/master/include/database/DBManager.php#L1041

But I don't know what triggers no. 3... maybe you can run an upgrade a place a breakpoint there and examine the stack. But it is possible that in your case it won't go by that place...

**Pull request merged**
