### PR TITLE
Solves bugs #106, #107, #108

### LINKED ISSUE #106: No localization at SuiteCRM/modules/AOP_Case_Updates/Case_Updates.php
I found out that there is no localization for Case Updates Messages in https://github.com/salesagility/SuiteCRM/blob/master/modules/AOP_Case_Updates/Case_Updates.php#L104
Here we have
` $html .= "<span>".($update->internal ? "<strong>Internal</strong> " : '') .$name . " at ".$update->date_entered."</span><br>";`
Even We have a translation for such strings they just not used here.
For example we have Russian translation for that 
* [SuiteCRM/modules/Cases/language/ru_ru.lang.php](
https://github.com/salesagility/SuiteCRM/blob/934ac6b0296cbfbbc62c4566cd398566536bee49/modules/Cases/language/ru_ru.lang.php#L144) 
* [SuiteCRM/modules/AOP_Case_Updates/language/ru_ru.lang.php](https://github.com/salesagility/SuiteCRM/blob/934ac6b0296cbfbbc62c4566cd398566536bee49/modules/AOP_Case_Updates/language/ru_ru.lang.php), 
*  [SuiteCRM/custom/Extension/modules/Cases/Ext/Language/ru_ru.customcases_aop_case_updates.php](https://github.com/salesagility/SuiteCRM/blob/934ac6b0296cbfbbc62c4566cd398566536bee49/custom/Extension/modules/Cases/Ext/Language/ru_ru.customcases_aop_case_updates.php#L25).

### LINKED ISSUE #107: Incomplete ru_RU translation for letter templates
I've found out that string `$app_strings['LBL_AOP_EMAIL_REPLY_DELIMITER'] = '========== Please reply above this line ==========';` was not translated into Russian in
`custom\Extension\application\Ext\Language\ru_ru.AdvancedOpenPortal.php`
`custom\application\Ext\Language\ru_ru.lang.ext.php`
`include\language\ru_ru.lang.php`

I'll correct it and ask for the pull.

### LINKED ISSUE #108: Russian translation do not have a search icon on the tab in Emails
There is an error in translation file. The getImage has a localized icon name at 
`'LBL_EMAIL_SEARCH'                      => SugarThemeRegistry::current()->getImage('Search', 'align=absmiddle border=0', null, null, ".gif", '')`
It has 'Поиск' instead of 'Search'.

We shouldn't localize calls to 'getImage'.

### PR DESCRIPTION
**Pull request by r3code**
Please accept this Pull Request. The changes solves some UI and translation problems.
Fixed #108 getImage call corrected
suitcrm_ru_email_serach_icon_fix
Fixed #107 Replaced untranslated strings
Fixed #106 Corrected `modules\AOP_Case_Updates\Case_Updates.php`, added missing vars, EN, RU, ES language files updated accordingly.
Small fix for general translation 'FOR' was translated as ('на сумму') 'in the amount of' instead of 'для'('for/in').

### CODE REVIEW

**Comment by mattlorimer** [comment]
We have received your signed SLA Agreement, thanks. From what I have seen the code looks good, so this is likely something we will look to include in the next update.

**Comment by r3code** [comment]
@mattlorimer So when you will to accept this pull request?

**Comment by mattlorimer** [comment]
It has been pulled into the hotfix 7.1.5 branch, due for release soon, thanks

**Comment by likhobory** [comment]
Вопрос с FOR_AMMOUNT так и остался нерешенным.

**Pull request merged**
