### PR TITLE
Feature signature

### PR DESCRIPTION
**Pull request by daniel-samson**
Task: SCRM-602
Issue: #3639

## Description

This change adds the signature to the body of the compose view.

## Motivation and Context

*Fixes Issue

## How To Test This

* Repair minified js
* Repair JS Groupings
* Repair and Rebuild
* Create signature in the email settings
* Compose and email

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Works as expected

**Comment by samus-aran** [comment]
Looks fine - but still WIP

**Comment by RobinHind** [comment]
Worked for me, although my file is named controller.php not EmailsController.php, Thanks

**Comment by daniel-samson** [comment]
@samus-aran - Updated pull request.

**Comment by daniel-samson** [comment]
You can now use the email settings to select the signature and then use the from drop down in the compose view to change the signature.

**Comment by Dillon-Brown** [comment]
Works as expected

**Pull request merged**
