### PR TITLE
Add email account name to inbox button

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Small UI change to display the email account name on the folder button in order to make it easier to tell which account you are using.

gmail

## How To Test This

1. Setup personal email in user profile.
2. View the email module list-view and check the button accurately displays the account name.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mausino** [comment]
@Dillon-Brown i'm suggesting the name of email account with folder name have instead of title  "EMAILS" and as wrote i suggesting https://github.com/salesagility/SuiteCRM/issues/5757#issuecomment-452047124 add to inbox button the new string "Switch Inbox".

I think will more clearly if you will see the Folder + (name of email account) as title and index button will have more clear name. 

Problem i see if you have longer name of account like we Inbox (Unterkunft-Suche.Eu) or should exist longer email account names.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by Mausino** [comment]
@Dillon-Brown should get this pull request the some label + milestone label ? when was merged yet

**Comment by Dillon-Brown** [comment]
@Mausino Label + milestone has been added to related issue. 

Oh and as for your comment. Ideally we want to keep the module views consistent so i'm not sure changing the module title would be appropriate here. I unfortunately didn't have time this release to make any more UI changes but we can definitely think about this more, I'm sure there are small things we can do to make the email module more intuitive.

**Pull request merged**
