### PR TITLE
Fix #9918 - Update listview.scss for dashlet overflow

### PR DESCRIPTION
**Pull request by 2xaronl**
Prior to this change, overflow of the .list-view-rounded-corners (e.g. dashlet divs) were unset (default value 'visible'). Now they are set to auto to allow scrollbars when content overflows.

## Description

In my SuiteCRM instance, a dashlet report had a horizontal overflow due to an excessive number of columns to display.  This was rendered with the table columns overflowing either into the right-hand column (if the dashlet was placed into the left column) or off the screen (if the dashlet was placed into the right column).

## Motivation and Context

Though the ultimate solution for me was to reduce the number of columns in the report to avoid overflow when viewed on a 1080p monitor, the behavior when there was overflow was a nuisance.  Adding 'overflow: auto;' to the css class allows a horizontal scrollbar to be added if there is overflow which is a 'safe' way to render the overflow.

## How To Test This

Rebuild sass

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
One more time thank you, @2xaronl 

Would you be so kind to update your commit message to follow the formatting Fix #num - message. The number added in this case 9918.

Thanks in advance,
Serhii

**Comment by 2xaronl** [comment]
@serhiisamko091184 is this correct now?

**Comment by serhiisamko091184** [comment]
Yes, thank you for quick response and cooperation.

Regards, 
Serhii

**Comment by serhiisamko091184** [comment]
Hi, @2xaronl 
sorry, was not attentive, you have changed the title of PR, commit message is still the same. 

image

Could you please change it as well. 

Thanks, 
Serhii

**Comment by 2xaronl** [comment]
> Hi, @2xaronl sorry, was not attentive, you have changed the title of PR, commit message is still the same.

@serhiisamko091184 Sorry about that.  I'm learning as I go.  I think I've got both of my recent commits updated as needed now.  Please let me know if any further action is needed.  Thanks!

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Comment by serhiisamko091184** [comment]
Hello, @2xaronl 
thanks for your time and cooperation, 
both commit messages looks perfect now. 

Regards, 
Serhii

**Comment by johnM2401** [comment]
Hey

Issue looks largely resolved by this PR:
image

However, if the user adds a Chart to the Report Dashlet, it will still overlap:
image

**Comment by serhiisamko091184** [comment]
Hello, @2xaronl 

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @2xaronl 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

**Pull request closed without merging**
