### PR TITLE
SugarFeed content cut for UTF-8

### PR DESCRIPTION
**Pull request by Szellszi**
Consider the following scenario:
You want to save an Opportunity with a name exactly 28 bytes long and the Account name is exactly 35 bytes long. The default currency is Euro with it's sign (€) in the config and the amount of the opportunity is 2016,03.

With the text of the SugarFeed, this will be more than 255 bytes long (since the € sign takes 3 bytes) so Suite gonna try to cut it after 255 bytes. Since this is at the "middle" of the 3 byte € sign, it will cut it half which results in two invalid characters, which can give the database a hard time.

If we count the UTF-8 characters instead of the bytes of the string, and cut the string as UTF-8, then the problem disappears.

## Description
Changed the string functions to their multi-byte counterparts.
Issue #2796 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by shogunpol** [comment]
@Szellszi , can you create actual GitHub issue and link this PR with this issue?

**Comment by Szellszi** [comment]
@shogunpol done :)

**Comment by dfaure-kdab** [comment]
I just hit the same bug, thanks for this fix! I hope the developers notice it soon and merge it...

**Comment by horus68** [comment]
@shogunpol

**Pull request merged**
