### PR TITLE
Fixed #1716 - Rem word as a Remove abbreviation? [Language]

### LINKED ISSUE #1716: Rem word as a Remove abbreviation? [Language]
#### Issue

String `'LBL_REMOVE' => 'rem',` causes some trouble to translators as its not a proper word or even an abbreviation. You find it here: 
modules/Calls/language/en_us.lang.php
modules/Meetings/language/en_us.lang.php
modules/Project/language/en_us.lang.php
modules/Configurator/language/en_us.lang.php
modules/Campaigns/language/en_us.lang.php
See: https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=%27LBL_REMOVE%27+%3D%3E+%27rem%27&type=

#### Possible Fix
Why not a full word? At least it should be used an ending dot to show an abbreviation
`'LBL_REMOVE' => 'Remove',`

#### Context
"rem" is not a word and causes doubts to translators

#### Your Environment

- SuiteCRM Version used: Hotfix

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Updates LBL_REMOVE to be more consistent.

## Motivation and Context

Issue reference: #1716 

remove

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@Dillon-Brown for a merge?

**Comment by daniel-samson** [comment]
Assessed

**Comment by horus68** [comment]
@Dillon-Brown this is not merged yet!

**Comment by Dillon-Brown** [comment]
@horus68 It's now been merged into hotfix here: #6273 along with many other PRs. Ideally we'll look at merging hotfix-7.8.x into hotfix much more frequently.

**Pull request merged**
