### PR TITLE
Feature/robo coding standards

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Adds a robo task for automatically fixing coding standard issues and a dist file for PhpCsFixer configurations.

## How To Test This

1. Run composer update
2. Run ./vendor/bin/robo configure:phpCSFixer
3. Run ./vendor/bin/robo php:CSFixer

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Cool. Could this tool take care of updating the license header at the top of each file?

**Comment by Dillon-Brown** [comment]
@pgorod That's definitely something i'll look at before finishing with this PR. We can do it through .php_cs.dist but I don't think that's the best approach; for the language files it makes sense to update them all at once but for core files there's no real point in updating them unless the file itself is changed. The php_cs can't really be customised in the way we would need to make it work well with Suite so i'll probably end up creating a more specific robotask.

**Comment by isleshocky77** [comment]
> @pgorod That's definitely something i'll look at before finishing with this PR. We can do it through .php_cs.dist but I don't think that's the best approach; for the language files it makes sense to update them all at once but for core files there's no real point in updating them unless the file itself is changed. The php_cs can't really be customised in the way we would need to make it work well with Suite so i'll probably end up creating a more specific robotask.

I'm confused by "It can't work that way". Why not add the .dist file and only add the modules/files ready to cleaned up and kept clean? I know you working on cleaning up module by module. So you could just add those modules to the .dist file.

**Comment by connorshea** [comment]
This needs a rebase, also shouldn't we have travis fail on failed lints?

**Comment by jack7anderson7** [comment]
Assessed :+1:

**Pull request merged**
