### PR TITLE
Fix multiple notification emails on Lead Creation WF

### PR DESCRIPTION
**Pull request by PedroErnst**
Prevents a bug where workflows cause multiple Lead assignment notifications to be sent.

## Description

Fairly rare bug where each of the resaves of a workflow cause another email notification to be sent.

## How To Test This

1. Ensure outgoing emails are working
2. Ensure "Assignment Notifications" is enabled in Email Settings
3. Have another user created other than Admin, make sure this user has an email address in their profile
4. Create a Workflow to run on new Lead Records. 
5. Set no conditions on this WF. 
6. Set at least one "modify record" action on this WF, doesn't matter which, for example field title = foo.
7. As Admin user, create a new Lead, make sure you set assigned user to the one you created earlier.
8. See the user has received 2 emails notifying of a new Lead instead of only one.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Hi @PedroErnst, I'm still getting 2 mails when adding a new lead? Is this intended? (When setting the workflow to inactive I only get one)

**Comment by PedroErnst** [comment]
@Mac-Rae 

No, you're correct, that's exactly what should not happen :)

**Comment by PedroErnst** [comment]
@Mac-Rae Please re-test when you get a chance

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/AOW_Actions/actions/actionCreateRecord.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=3875240&bid=13501288)

**Comment by pgorod** [comment]
@PedroErnst from what I've heard others discuss, I gather that a simple way to re-trigger Travis is to add a new commit, even if it's an empty commit.

**Comment by PedroErnst** [comment]
@pgorod 
Thanks, but closing and opening the PR seems preferable to me, adding even an empty commit is clutter that will stay in git forever.

**Comment by serhiisamko091184** [comment]
Hello, @PedroErnst 

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @PedroErnst 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

**Pull request closed without merging**
