### PR TITLE
PDF templateParser.php - render 'wysiwyg' fields.

### PR DESCRIPTION
**Pull request by ApatheticCosmos**
## Description
This change allows 'wysiwyg' fields to render their html in PDF templates. Compatible with PHP7.

## Motivation and Context

When using the Wysiwyg field module, PDF templates would render the html code. 

## How To Test This

Add these four lines to the file, then include a wysiwyg field to a PDF template.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
@ApatheticCosmos 
Unfortunately the PR made is to the wrong branch - we don't merge into master directly, we use a hotfix branch to encourage end to end testing.
Ideally this fix will go into 7.8.x-hotfix and get pushed into 7.9.x and 7.10.x as this bug seems to be floating about for a while.
I would recommend that if you know the bug is on 7.8.x or 7.9.x then made a pr to that branch so when releases are made they trickle up the versions to ensure all releases have the same bug fixes :)

**Comment by Dillon-Brown** [comment]
It would be great if we could get this working for our native HTML fields. We would also need to consider the security implications of this before we could merge.

**Comment by ApatheticCosmos** [comment]
Oops! Yeah, I picked the wrong branch. Sorry! I'll create a new one against 7.8.x-hotfix, as that's the branch I'm using currently.
Btw, I second that SuiteCRM should have a native WYSIWYG field. It's very useful.

**Comment by ApatheticCosmos** [comment]
Folks,
Is there anything I need to do to help this get accepted? There's no way (that I can see) to make this change in an upgrade safe manor.

**Comment by ApatheticCosmos** [comment]
I just upgraded my SuiteCRM instance to 7.10.1 and reapplied this patch. It was overwritten by the upgrade (as I expected it would be). No issues with the patch in 7.10.1.

**Comment by ApatheticCosmos** [comment]
Also tested in 7.10.2. No issues.

**Comment by ApatheticCosmos** [comment]
I'm closing this pull request, since I didn't know enough about Github when I created it. I'll create a branch from on upstream to base the pull request on.

**Pull request closed without merging**
