### PR TITLE
Feature Reply To and Forwarding

### PR DESCRIPTION
**Pull request by daniel-samson**
Task: SCRM-582, SCRM-569 
Issue: #3616

## Description

This change adds the ability to reply-to, reply-to-all and forward emails. It also has a fix for the q-tips in the compose view.

## Motivation and Context

Adds missing features

## How To Test This

* Repair and rebuild
* Repair minifed js
* Repair js groupings
* Set up email account
* View Emails
* Select subject of an email
* In the action menu
* select reply to, reply to all and/or forward

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
1. The additional buttons are not highlighting when rolling over (thats if you have the action buttons not as a menu).

**Comment by Mausino** [comment]
@samus-aran @daniel-samson @Dillon-Brown @pgorod @chris001 

when user reply, reply to, forwward email.. system automaticaly import email, but is not related to any record.. only was imported. My question is: 

Could user import email first and after will send email 
or 
Will replied or forwarded email not imported autamaticaly

What is your opinion?

**Comment by chris001** [comment]
@Mausino 
My opinion about email import, reply, forward, related to records: 
**Look at the SugarCRM 7.x feature "Hint" and copy it.**
It scrapes 70 data sources from the web (including emails available on email accounts attached to the crm also, why not) to build a profile about a lead/prospect automatically in the background. Facebook pages, twitter, linkedin, probably 50 social media site, physical address, registered telephones, websites, google search results, etc.
https://www.theregister.co.uk/2017/06/28/facebook_hit_2_billion_users_today_and_sugarcrm_reminded_us_iyoui_are_zucks_product/

**Comment by Mausino** [comment]
@chris001 thank you.. i know the best way is looking on big players....  but i am not sure if we are in this position (maybe for few years) :) with butget + human resources :)  but i like your idea collect data from everywhere to know better our future clients 

But now i am asking about a small step to those bigs in future :) because isn't possible to go further without first step :) many of contributors are IT specialists, me only intermediate user :D

**Comment by chris001** [comment]
For sure they're taking Contact's name and phone number, which the CRM user enter has entered for the Contact, plus the CRM user's facebook login authorization OAuth2 token, turning around and "entering the phone number" into Facebook search (posting it to the facebook search form) , as you can do, and receiving back from facebook the public FB profile page associated with that phone number, and scraping the data off that public profile page.  A nice way to save the CRM user the effort of having to copy/paste all that FB profile info into the Contact Edit View form.  Same thing with Twitter.  For LinkedIn the CRM user needs to be a paid LinkedIn user if they're trying to gather info on an unconnected contact out of their network, or connected to the LinkedIn user. Otherwise they get just the public profile info which is limited.

**Pull request merged**
