### PR TITLE
Fixed #8489 - No validation when using header save button in AOS_Products

### LINKED ISSUE #8489: No validation when using header save button in AOS_Products
When you use the save button on top (header), the validation of the fields will not be triggered. If you use the lower one, everything works fine.
I have tested this is on a fresh 7.11.10 install - multiple times.

#### Issue
There is a difference between the top and bottom onclick functions:

Top onclick:
`var _form = (this.form) ? this.form : document.forms[0]; _form.action.value=‘Save’; if(check_form(’’))SUGAR.ajaxUI.submitForm(_form);return false;`

Lower onclick:
`var _form = document.getElementById(‘EditView’); _form.action.value=‘Save’; if(check_form(‘EditView’))SUGAR.ajaxUI.submitForm(_form);return false;`

#### Expected Behavior
Should trigger validation if header Save button is used.

#### Actual Behavior
Does not check if required fields are missing when using the header save button. The lower/bottom save button does check for required fields.

#### Possible Fix

Seems like some parts of the onclick method will not be rendered properly.

#### Steps to Reproduce

1. Create a new Product
2. Enter nothing into a required field (for example Name)
3. Use the upper/header button to save
4. It will be saved, even though the name has to be entered

#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 79.0.3945.130 (Official Build) (64-Bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.3.11
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.10

### PR DESCRIPTION
**Pull request by ChangezKhan**
It solves issue #8489 
## Description

In `EditViewHeader.tpl` file of `AOS_Products` module,  element `form_id` was missing.

## Motivation and Context

With this change, on click of header `Save` button, form will validate properly.

## How To Test This

1. Go to `Products` module.
2. Create new record.
3. Click on 'Save' button available on header section without filling any mandatory fields and check whether you gets an error or not.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by Mac-Rae** [comment]
Hi @ChangezKhan,

Please rebase this pull request onto hotfix-7.10.x as the hotfix branch is now specifically for 7.11.x issues.
For more information please take a look at our [contribution guidelines](https://docs.suitecrm.com/community/contributing-code/).

If you would like assistance please ensure you select "Allow edits from maintainers" checkbox and leave us a message @tagging me! 

Thanks :+1:

**Comment by ChangezKhan** [comment]
Hi @Mac-Rae, thanks for pointing that out. I completely missed that. I don't know how to rebase a branch here on GitHub. So, I would really appreciate your help. Thank you.

**Comment by pgorod** [comment]
@ChangezKhan for these simple one-file PR's, I find it's easier to just close this one and start a new one from the correct branch.

If you go [here](https://github.com/salesagility/SuiteCRM/blob/hotfix-7.10.x/modules/AOS_Products/tpls/EditViewHeader.tpl) and click the pencil icon to start an edit, GitHub will take care of creating an appropriate branch for you.

**Comment by ChangezKhan** [comment]
@pgorod got it. Thanks.

**Pull request merged**
