### PR TITLE
Language files - PR for code re-format only

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Single PR for the re-formatting of language files. As described by @horus68 in #4040.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@Dillon-Brown great work.
Just waiting to see this merged into Hotfix so I can then proceed and include changes into Crowdin project

**Comment by horus68** [comment]
@Dillon-Brown Is this planned to be merged soon or its on hold?

**Comment by Dillon-Brown** [comment]
@horus68 Will take a look. I think i'll need to create another PR for 7.8.x as well.

**Comment by horus68** [comment]
good work... lets wait for a quick merge!

**Comment by horus68** [comment]
Hope this also takes care of br tag format (couldn't check it all) https://github.com/salesagility/SuiteCRM/issues/1770

**Comment by horus68** [comment]
@Dillon-Brown can you please make this available in the hotfix so no new versions will be released without a code reformat for language files?

**Pull request merged**
