### PR TITLE
Fix API list total pages display

### PR DESCRIPTION
**Pull request by PedroErnst**
Fixes an issue where API filtering includes deleted records by default.

## Description

Adds a default filter parameter to use when no filters are specified.
Injects a deleted = 0 filter parameter when the list of filter parameters doesn't specifically include deleted records.

## Motivation and Context

Most API operations are unaffected by this issue because we use a Bean function to actually retrieve records, so deleted records are filtered.

However, for the `[meta][total-pages]` a count query is run which does not include the deleted = 0 parameter, and thus returns a number of pages based on the total rows in the db, deleted or not.

## How To Test This

1. Make sure your Accounts db table contains deleted records as well as non deleted records.
2. Do a call to `Accounts?fields[Account]=name,account_type&page[number]=1&page[size]=1`
3. Observe the `[meta][total-pages]` is accurate for the data in the db.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by isleshocky77** [comment]
I just ran across this exact issue. The patch definitely fixes the page count for case where you're only requesting records with no filter and would not expect to see deleted results; however,

Although I don't need it, I also decided to test this code with getting deleted records. I'm unable to get deleted records. I tried the following requests

```
# Returns a response stating no result
Api/V8/module/Accounts?fields[Account]=name,account_type&page[number]=1&page[size]=50&filter[deleted][eq]=1
```

```
# Returns the same result as not specifying a filter at all
Api/V8/module/Accounts?fields[Account]=name,account_type&page[number]=1&page[size]=50&filter[deleted][eq]=1&filter[operator]=or&filter[deleted][eq]=0
```

**Comment by PedroErnst** [comment]
Yeah the fix is only for the page count.

Not being able to retrieve deleted records is still an open issue.

**Comment by isleshocky77** [comment]
@PedroErnst Just noting that there is a separate issue in for retrieving deleted record #6379

**Comment by Dillon-Brown** [comment]
Issue reference: #7144

**Comment by willrennie** [comment]
Assessed as working on the fix branch using example test within Postman from the issue this resolves.

**Pull request merged**
