### PR TITLE
Fixed #3201 - Products_Quotes as a word in language files

### LINKED ISSUE #3201: Products_Quotes as a word in language files
#### Issue

`Products_Quotes` shows up in language file with an underscore like a single word to be translated.

#### Expected Behavior

Products Quotes should be 2 words

#### Actual Behavior

/modules/AOS_Products_Quotes/language/en_us.lang.php
```
    'LNK_LIST' => 'Products_Quotes',
    'LBL_SEARCH_FORM_TITLE' => 'Search Products_Quotes',
    'LBL_HISTORY_SUBPANEL_TITLE' => 'View History',
    'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Activities',
    'LBL_AOS_PRODUCTS_SUBPANEL_TITLE' => 'Products_Quotes',
    'LBL_NEW_FORM_TITLE' => 'New Product_Quote',
```
See: https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/AOS_Products_Quotes/language/en_us.lang.php#L48-L53

#### Context

Translators needs words not code!

#### Your Environment

* SuiteCRM Version used: 7.8.2

### PR DESCRIPTION
**Pull request by imtg-suitecrm**
## Description
Fix for Issue [3201](https://github.com/salesagility/SuiteCRM/issues/3201) - Products_Quotes shows up in language file with an underscore like a single word to be translated.

## How To Test This
Products Quotes should be 2 words

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@imtg-suitecrm are you on Salesagility team or just an user like me?

**Comment by chris001** [comment]
`Products_Quotes` It's code standing for a list of relationships between `Products` and `Quotes`, and should be hidden from translators in Crowdin.

**Comment by horus68** [comment]
@chris001 So this PR shouldn't be accepted as it removed the underscore?
```
-    'LBL_SEARCH_FORM_TITLE' => 'Search Products_Quotes',
+    'LBL_SEARCH_FORM_TITLE' => 'Search Products Quotes',

```
On the translations side its not possible to hide part of a sentence from translators, just the full string.
That is one more reason code should not appear in translations!
Then again, if code is placed inside brackets as in `Search [Products_Quotes]` Crowdin will consider it as a variable with a warning to not be translated. Not a perfect solution but a better one
Maybe

**Comment by chris001** [comment]
Good point, @horus68 .  It's ambiguous, would have to take a look at the code and see if the label is used to communicate to the user.
Also, the PR should probably be edited to be against the hotfix branch, not master branch.

**Comment by imtg-suitecrm** [comment]
Hi @horus68, not part of SalesAgility, I'm with the SuiteCRM Code Partner in Australia, IMTG.

@chris001 thank you for your help also, will take a look to see if the label is shown to users and amend the PR so it is against the right branch.

Thank you both for your help!

**Comment by samus-aran** [comment]
Hi everyone.  I don't see any issue with this PR.  It is a relationship based Module similar to AOP_Case_Updates.  Really begs the question do we need these labels in the first place if the User does not see them... something to consider culling in the future.

**Pull request merged**
