### PR TITLE
add setting for an large database, e.g. 2000000 contacts, for an faster list queue query

### PR DESCRIPTION
**Pull request by andre-karrlein**
## Description
We had a problem with our large database, that the contact list view load over 1 minute.
With this change it loads in several seconds.

## Motivation and Context
We had a problem with our large database, that the contact list view load over 1 minute.
The db query needs more than 40 seconds.

## How To Test This
Open the contact list view with over 2000000 contacts. Enable this feature via the config_override.php setting $sugar_config['large_table']['contacts'].

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Hi Andre, welcome!

Please direct your PR at somewhere else, not `master` branch... that would be `hotfix-7.10x` if we consider this a bug, or `develop` if we consider this a feature 🤔 . Please see https://docs.suitecrm.com/community/contributing-code/bugs/ to learn about our workflow.

Just a question - does the `$limit` variable include the `LIMIT` SQL keyword in it? Because if it's just a number your code will render as `ASC 20` instead of `ASC LIMIT 20`... unless I'm missing something...

Again, welcome and thanks for your contribution!

**Comment by andre-karrlein** [comment]
Hi pgorod,

thanks for the welcome and sorry for the inconvenience with my pr. I changed it now.

The $limit variable include the LIMIT SQL keyword.

**Comment by andre-karrlein** [comment]
Hi pgorod,

i checked it and forgot the limit part.
Added it to the method signature.

**Comment by pgorod** [comment]
Cool.

You're going to need to do a `git rebase` after changing the target branch, otherwise all these other commits appear here...

**Comment by andre-karrlein** [comment]
> Cool.
> 
> You're going to need to do a `git rebase` after changing the target branch, otherwise all these other commits appear here...

I made a new Branch with new PR, because of to much merge conflicts.
https://github.com/salesagility/SuiteCRM/pull/7894

**Comment by pgorod** [comment]
You can close the PR yourself.

(I can't)

Thanks

**Pull request closed without merging**
