### PR TITLE
Staging: Replace X templates on SubPanels with Smarty

### PR DESCRIPTION
**Pull request by daniel-samson**
## Description

Please see #2604.

## Testing

Please run the following first
- Rebuild Minified JS Files
- Rebuild JS Grouping Files

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
A few things:

Styling for for SuiteP points below. The functionality works, but occasionally it doesn't pick up the resizing and that the minimum size should be 1 field. 

subpanels3
subpanels

You also create an issue where you have the row expanded and sort the resizing doesn't kick in when it refreshes.

subpanels2
subpanels1

Also, if you change themes the styling is off as you see underneath for both list view and subpanels.

subpanels5
subpanels4

**Comment by daniel-samson** [comment]
I can fix the arrow as there is not enough space. However, I have removed footables from the list view, so that it is more consistent. And i have fixed footables in the subpanels

**Comment by gymad** [comment]
in FF some places show an incorrect "I beam" text cursor, see attached pic
image

**Comment by samus-aran** [comment]
@daniel-samson I think you'll need to show me on your instance as what I see is regression.
Being on SuiteR and Suite7 the subpanels look as expected. However I get a fatal on the action 'Filter' on History and the Events delegates subpanels.

smarty

I also don't see the subpanels reducing horizontal when resizing the window and when I hard refresh the page (Ctrl+F5) when I re-open the subpanels the results are gone.

smarty2

**Comment by samus-aran** [comment]
Hopefully (FX) last issue I've spotted is:

When on SuiteR you sort by column on Activities subpanel it creates a duplicate Activities subpanel underneath.

filter_3

**Pull request merged**
