### PR TITLE
New issue menu templates

### PR DESCRIPTION
**Pull request by samus-aran**
## Description

A suggestion raised by Community Member @horus68 to introduce a github feature to provide different templates for github issues to aid people choose a suitable template. 

You can learn more about the feature here:
https://help.github.com/articles/about-issue-and-pull-request-templates/

You can see a demonstration of these changes here:
https://github.com/samus-aran/SuiteCRM/issues/new/choose

new issue samus aran suitecrm

## Motivation and Context

Helps contributors to raise issues, suggestions in a clear and easily defined manner. Also allows contributors be aware what Github is not used for i.e. support tickets or security issues.

## How To Test This

Visit:
https://github.com/samus-aran/SuiteCRM/issues/new/choose

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
missing:
1- The actual issue template in use, only for confirmed bugs
The workflow would be: 
Confirmed bug on foruns or visible in Demo => Issue creation with "how to reproduce" => PR required
Note: include a link to forum and to demo version

2- Adding an improvement or a feature
(for those that will create a PR later).
The workflow would be: create an issue => Create a PR and link to the issue => PR merged will close the issue
Note: Please include a link to code contribution https://github.com/salesagility/SuiteCRM/blob/master/.github/CONTRIBUTING.md

**Comment by samus-aran** [comment]
Thanks @horus68. 
1. That makes sense. Though I feel we should be identifying the current processes that we do and help people follow that workflow instead of them stumbling into it. Something to add to the Docs pages?
2. I'll have a look at making multiple PR templates though I don't think it will be the same as the github menu selector when creating new issue which is a shame but we can add the templates via URLs to guide people to open either a Bug Fix PR and a Feature PR. Again, this should be shown as a nice workflow diagram and pushed up to the public space.

**Comment by Mac-Rae** [comment]
Please rebase this pull request onto hotfix-7.10.x as the hotfix branch is now specifically for 7.11.x issues.

Please take a look at our contribution guidelines for more information.

**Comment by samus-aran** [comment]
I'll update this, this week. 
I'm happy to also point it to the hotfix 7.10.x branch.

**Comment by serhiisamko091184** [comment]
Hello, @samus-aran 

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @samus-aran 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

**Pull request closed without merging**
