### PR TITLE
Fix #4176 date picker

### LINKED ISSUE #4176: Dashlet's calendar popup windows open in background partially hidden/unaccessible
#### Issue

When you have a dashlet which in edit mode has a date field with a calendar button next to it, when launched the calendar popup window appears underneath the previous popup hence disallowing to navigate the calendar. 

#### Expected Behavior

The popup should appear in the foreground
#### Actual Behavior

obraz

#### Steps to Reproduce

It's 100% repeatable on 7.9.4 as well as demo version.

#### Your Environment

   *  SuiteCRM Version used: 7.9.4
    * Firefox 55.0.3. 32-bit or Chrome 60.0.3112.113 (64-bit)
    * MariaDB 10.2.6. , PHP 7.1.8
    * CentOS Linux release 7.3.1611 (Core)

### PR DESCRIPTION
**Pull request by e-reeley**
Date picker was showing behind the popup display.

## Description

The z-index was changed to allow the date picker to be accessed and in full display.

## How To Test This

1) Have the 'Outcome By Month' dashlet on display
2) Click the edit icon
3) Click on the date icon to select a date

The css will need to be rebuilt for this change.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
@e-reeley this fix you made got me wondering - a few months ago we started having lots of different z-index issues around the app. It's hard to know how things will work out with z-indexes since what counts is their relative position to other screen elements, and in generic YUI functions we don't even know in which screens they will appear...

An example is this one #3902

**Comment by e-reeley** [comment]
@pgorod Yeah, this fix was a bit strange to me. I did seem to notice that there was a variety of z-indexes and altering only the values did not always make the expected difference.

It may be worth over time having a clean up of these values to allow us to alter them as we require.

**Comment by pgorod** [comment]
This is all a bit risky - in the same way that somebody changed something a few months ago, and we got unexpected side-effects, we can be changing things now and only find out later what we broke in some other screen. And these issues are simple, but they often break functionality for end-users.

So definitely a more coherent approach would be necessary... but I fear it's too big an effort.

Is #3902 something you can fix easily? We have users in the forums complaining about that one, and it seems it recently became worse. Before, it just affected calls records in dashlets, now it seems to affect all call screens.

**Comment by e-reeley** [comment]
Yeah, I agree, the simple removal of the z-index was something that was not the most well rounded fix, but it can often be rather difficult to test all areas which would be potentially impacted.

I agree, hopefully it is something that we can look into over time, but it looks like a big fix. This does not make it out of the question though, especially since this is hopefully the start of fixing this.

I will take a look into the linked issue and see what I can do. Thank you for adding this one in, it seems that not only have a lot of people experienced this issue, but there seems to be a lot of closely linked issues.

**Comment by Dillon-Brown** [comment]
Closing in favour of #4901

**Pull request closed without merging**
