### PR TITLE
*WIP Fixed #7298 - Emails 'Bulk Action' is disabled after upgrade to 7.10.16

### LINKED ISSUE #7298: Emails 'Bulk Action' is disabled after upgrade to 7.10.16
#### Issue
After upgrading to version 7.10.16 the 'BULK ACTION' button of the email inbox is disabled, so it is not possible to import multiple emails from the Inbox view.
Additionally, I am not able to open any email except from the 'default' Inbox account. If I chose a different folder on the default account or any folder of the other accounts the emails won't open, and therefore they won't be possible to imported individually either.

#### Expected Behavior
After selecting one or multiple messages in the inbox view, the 'bulk action' button should become available for choosing an action (ie. import).

#### Actual Behavior
After selecting one or multiple messages in the inbox view, the 'bulk action' button remains disabled (grayed out and not available for clicking)

#### Steps to Reproduce

1. Navigated to activities/emails
2. Select a few emails using the tick-box on the left

#### Your Environment

* SuiteCRM Version used: 7.10.16
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 66.0.5 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.6 LTS

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixes an issue with the bulk action button being disabled when selecting items in the list-view. This fix also fixes pagination and the "selected" counter functionality in the list-view.

## Motivation and Context

Issue reference: #7298 

## How To Test This

1. Check that you can use bulk action after selecting items in the list-view.
2. Check that pagination works with selected items on previous pages.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by kikobar** [comment]
@Dillon-Brown, is this part of the bug also addressed by this fix?

> Additionally, I am not able to open any email except from the 'default' Inbox account. If I chose a different folder on the default account or any folder of the other accounts the emails won't open, and therefore they won't be possible to imported individually either.

**Comment by Dillon-Brown** [comment]
@kikobar I wasn't able to replicate that, can you clarify what you mean by "the emails won't open"?

**Comment by kikobar** [comment]
@Dillon-Brown I meant that if I select a different folder than the INBOX (ie. sent emails), then when I click on the email the body of the email shows up blank and the IMPORT functionality fails.
I use multiple email accounts, all the INBOX folders are able to be opened and imported, while all the other folders fail (ie. sent emails).
I tried with both Gmail and standard IMAP folders with the same result, only the INBOX folders work.
Attach image of what I get when I click on an email inside a non-INBOX folder.
Screenshot from 2019-06-17 19-29-40

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by kikobar** [comment]
> @Dillon-Brown I meant that if I select a different folder than the INBOX (ie. sent emails), then when I click on the email the body of the email shows up blank and the IMPORT functionality fails.
> I use multiple email accounts, all the INBOX folders are able to be opened and imported, while all the other folders fail (ie. sent emails).
> I tried with both Gmail and standard IMAP folders with the same result, only the INBOX folders work.
> Attach image of what I get when I click on an email inside a non-INBOX folder.
> Screenshot from 2019-06-17 19-29-40
> Please note that I am now testing this on a 7.11.5 instance as I don't have any 7.10.16 any more.

@Dillon-Brown I've been experimenting more with this issue because I realised that the body of some emails were able to be displayed while some others not.
Then I realised that the messages sent from Thunderbird were not displayed while the messages sent from my phone were.
In my previous description of the issue I had wrongly associated the issue with being in a non-INBOX folder, because I use Thunderbird and thus all my sent mails were in the Thunderbird format, now I started to think that the issue was related to the format of the message instead, so I search for emails in my sent mails folder which had not been sent from Thunderbird but from my phone, and bingo!, I was able to display the body of those messages.
Then I tested the opposite, sending an email from Thunderbird to my INBOX and see if I was able to display it, and again, the email was not displayed either, therefore I confirmed that this issue had nothing to do with the folder but most likely the format or the headers of the message.
Finally I tried to import both the emails from my INBOX and from my SENT folders and I got different behaviors:
1.- If the message was displaying in the INBOX folder, the import process works as normal
2.- If the message was not displaying in the INBOX folder, the import process still works as normal, plus the message IS able to be displayed AFTER being imported.
3.- Regardless of whether the message was able to be displayed or not in a non-INBOX folder, in both cases the import process would fail and the body of the email would continue not being able to be displayed after the import process. Additionally, the message display window lands in a different message (which CAN be displayed) that has nothing to do with the message I am trying to import (moreover, it is ALWAYS the same message).
I hope this further description helps to address this issue.
On the other hand, I believe the above description is a different issue than the headline of this one (the 'bulk action' being disabled). Would you like me to open a separate issue for this?
Thanks!

**Comment by samus-aran** [comment]
@kikobar That does sound like a different issue. But there are a number of existing Email related issues. are you able to do a bit of searching on the GitHub tracker if anyone else has seen what you do? If not then yes, please create a new issue. :+1: 
I don't want this PR to be muddied by other issues that fails to complete an end-to-end process - this PR should help complete one section of the process hopefully (identified in https://github.com/salesagility/SuiteCRM/issues/7298)

So just to be clear, this PR does address part of this issue when this is merged? :question:

**Comment by kikobar** [comment]
@samus-aran I agree it is a different issue from the part that is being reviewed here, but it was part of the original issue #7298 which triggered this fix (probably misunderstood and misled by the headline).
This problem is not captured in any other issue, so I will open a new one.
To your question, I haven't reviewed the code or tested the fix myself, but from what I read, it would be addressing the part of the 'bulk action' button being disabled.

**Comment by kikobar** [comment]
Opened the issue #7464 for the 'unable to import from non-INBOX' part.

**Comment by kikobar** [comment]
Opened the issue #7466 for the 'unable to open the message body created with Thunderbird' part.

**Comment by Dillon-Brown** [comment]
Superseded by the following PRs:

- #7601
- #7538
- #7541
- #7542

**Pull request closed without merging**
