### PR TITLE
Removing space before Ellipsis

### PR DESCRIPTION
**Pull request by horus68**
## Description

Removing space before Ellipsis. 
Related to issue https://github.com/salesagility/SuiteCRM/issues/5074
Note: this file was already fixed to Hotfix 7.8 but not to Hotfix branch

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by Dillon-Brown** [comment]
Hi @horus68, we fixed some issues with the 7.9.x and 7.8.x released that required us to revert this PR and #5217. I'll remake them asap for the hotfix branch. Thanks!

**Comment by horus68** [comment]
@Dillon-Brown both PR not recreated until now!

**Comment by Dillon-Brown** [comment]
@horus68 Recreated in #5269

**Pull request merged**
