### PR TITLE
US 2.6

### PR DESCRIPTION
**Pull request by haris-raheem**
## Description

As a User I want the duration of a project or project template to be
calculated from the days between the start of the first project task and
the end of the last project task.
## How To Test This

open a project or project template gantt view, the gantt view start and end dates/days must be between start of first and end of last task
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [ ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@haris-raheem can you make this PR against the proper Branch (hotfix)?
There are also 3 Conflicting files to be solved

**Comment by haris-raheem** [comment]
i have moved it to hotfix and it passed all checks.

________________________________

**Comment by samus-aran** [comment]
Hi @haris-raheem is this PR required anymore? Does this other PR https://github.com/salesagility/SuiteCRM/pull/2248 contain the latest? If so can you close this PR please, thanks.

**Comment by haris-raheem** [comment]
closed all except 3204. rest were old ones so not needed anymore.

________________________________

**Pull request closed without merging**
