### PR TITLE
Fix #9971 - Workflow - Add filters to quick and advanced search view in AOW Processed module

### LINKED ISSUE #9971: Workflow - Add filters to quick and advanced search view in AOW Processed module
#### Issue
In the quick and advanced search view of the AOW Processed module (module not accessible from studio) not all the possible filters are shown, so we propose to add the following:
- add the Module, Record and Status fields to the quick search view.
- adds Date Created, Date Modified, Creator User, and Modifier User filters to the advanced search view.

#### Expected Behavior
That the AOW processed module shows a greater number of filters by default

#### Actual Behavior
In the quick and advanced search view of the AOW Processed module, not all the possible filters are shown.

#### Possible Fix

Modify in this file modules/AOW_Processed/metadata/searchdefs.php

```
'layout' => array(
     'basic_search' => array(
         'aow_workflow',
         'parent_type',
         'parent_name',
         'status',
         ),
     'advanced_search' => array(
         'aow_workflow',
         'parent_type',
         'parent_name',
         'status',
         'date_entered',
         'date_modified',
     ),
),
```

#### Steps to Reproduce
1. Access the AOW processed module and go to the search view
2. Check that the quick view only offers one filter and that the advanced view does not offer all possible filters

#### Context
Medium priority, I need to access certain filters not available

#### Your Environment

* SuiteCRM Version used: 7.12.9
* Browser name and version: Versión 107.0.5304.121 (Build oficial) (64 bits)
* Environment name and version: MariaDB 10.6.5, PHP 7.4
* Operating System and version : Ubuntu 20.04

### PR DESCRIPTION
**Pull request by SinergiaCRM**
- Closes #9971

## Description
This PR adds the code to add new filters in quick and advanced search view:
- adds the Module, Record and Status fields to the quick search view.
- adds the above fields plus Date Created, Date Modified, Creator User, and Modifier User filters to the advanced search view

## How To Test This
1. Access the AOW processed module and go to the search view
2. Check that offers the new filters in quick view and advanced view

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by clemente-raposo — DISMISSED** [review]
LGTM

**Comment by clemente-raposo** [comment]
Hi @SinergiaCRM, thank you for your PR.

**Comment by johnM2401** [comment]
Hey!

I've given this some testing.

However, it seems like there may be an issue when trying to filter by selecting a specific Record.


When filtering on a specific Record, the results appear to always return nothing.

image
image
image

Opening the filter view again shows that the Dropdown appears that the Record Module has been unselected:
image

Perhaps this is related?

What are your thoughts?

**Comment by SinergiaCRM** [comment]
> Hey!
> 
> I've given this some testing.
> 
> However, it seems like there may be an issue when trying to filter by selecting a specific Record.
> 
> When filtering on a specific Record, the results appear to always return nothing.
> 
> image image image
> 
> Opening the filter view again shows that the Dropdown appears that the Record Module has been unselected: image
> 
> Perhaps this is related?
> 
> What are your thoughts?

Hi, we didn't find a solution for this. So we decide to remove both parent_type and parent_record fields from the searches. 
Date fields are already really useful.

**Review by johnM2401 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]

**Pull request merged**
