### PR TITLE
FIXED #8155 - Unused PDF Settings

### LINKED ISSUE #8155: [language] Unused PDF Settings
https://github.com/salesagility/SuiteCRM/blob/v7.11.8/modules/Configurator/language/en_us.lang.php#L207-L343

Those labels have been used in SugarCRM PRO only!
This issue has been already iscussed [here](https://github.com/salesagility/SuiteCRM/issues/2468), but, unfortunately, it was resolved partially.

### PR DESCRIPTION
**Pull request by cameronblaikie**
## Description

https://github.com/salesagility/SuiteCRM/blob/v7.11.8/modules/Configurator/language/en_us.lang.php#L207-L343

Those labels have been used in SugarCRM PRO only!
This issue has been already iscussed here, but, unfortunately, it was resolved partially.
## How To Test This

Check PDF Labels are still set correctly
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by horus68** [comment]
self ping on language changes

**Comment by samus-aran** [comment]
Self ping for myself as well <_<

**Review by samus-aran — APPROVED** [review]

**Review by jack7anderson7 — APPROVED** [review]

**Review by jack7anderson7 — APPROVED** [review]

**Review by samus-aran — APPROVED** [review]

**Review by Mac-Rae — APPROVED** [review]

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Pull request merged**
