### PR TITLE
Fixed string quotes

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Changes newlines to use . PHP_EOL instead of \n when using single quotes.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Confirming that the changes makes no issues in Crowdin translation project.

**Comment by horus68** [comment]
Is this a change to be applied for all language files? 
Note there are many other files with `\n `for a new line, being in the end or in the beginning of a sentence as in \include\language\en_us.lang.php
`    'MSG_JS_ALERT_MTG_REMINDER_AGENDA' => "\nAgenda: ",`

Or in the middle of a sentence (1 or 2 lines) : \modules\Users\language\en_us.lang.php
`    'ERR_IE_MISSING_REQUIRED' => "Inbound Email settings are missing required information.\n  Please check your settings and try again.\n\nIf you are not setting up Inbound Email, please clear all fields in that section.",`

**Comment by Dillon-Brown** [comment]
@horus68 Those strings would be fine. The issue is with single quotes using \n that would not display correctly.

**Comment by horus68** [comment]
@Dillon-Brown ok for me, just noting that all values should be in single quotes!

For future reference, if values are delimited by single quotes  then Crowdin its ok for PHP_EOL  to be before or after the value, not in the middle.
As in:
`'MSG_ALERT' => . PHP_EOL 'Click OK to view this message.',`
or
`'MSG_ALERT' => 'Click OK to view this message.',  . PHP_EOL`

Regarding `\n` it gets downloaded with escapade sign only if value delimited by single quotes:

Upload as:
`'MSG_ALERT' =>  '\nClick OK to view this message.',`
Downloaded:
`'MSG_ALERT' =>  '\\nClick OK to view this message.',`

Note:
`PHP_EOL` (after or before the vaule) are not seen by translators, so the translations always keep them.
 `\n` are visible and can be removed by translators.

**Comment by horus68** [comment]
Administrator language file also have a similar string to ERR_UW_UPLOAD_ERROR

**Comment by daniel-samson** [comment]
Assessed

**Pull request merged**
