### PR TITLE
Fix #4636 Add template parsing to 7.8.x email

### LINKED ISSUE #4636: email variables are not filled properly in email template...
Using email template in any of the process that we would benefit from such an interresting feature; When we send an email and would like to add variables from the menu they do not get fulfilled.
This problem has been reported really often in the forum but I believe no one  reported here.

how to replicate, simply build an email template and insert variables, 99% of them won't work when you are sending emails...  the variable will not be filled up.

It would such a nice feature to bring to life...

### PR DESCRIPTION
**Pull request by PedroErnst**
Adds email template parsing to 7.8.x
Fixes #4636 
Takes code from aa1577ed62585530d5449aecc967fab60f034e26

## How To Test This

Create an Email Template 
Relate to Cases
Insert a few Case variables
Compose an Email
Load the template
Select related case
Send Email
See that variables are replaced

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by PaulMcRoar** [comment]
Sorry to say that we are still having major problems with this. On SuiteCRM 7.8.12 , the above works when you compose an email and then select a case, but not if you select an opportunity.

It also still does not work for cases if you select "Compose Email" from the activities tab of a case (which is a much more common workflow ).

**Comment by PaulMcRoar** [comment]
Managed to have a glance through what is being posted in the workflow method as opposed to the method where you compose an email.  When clicking from the activities tab, the parameters are data_parent_id0 etc as opposed to data_parent_id1

A change to line 569 to

if (!empty($_REQUEST['data_parent_id1'] || !empty($_REQUEST['data_parent_id0']))) {

and it works OK, although I'm unsure if that's the best way about doing it, as I've not dug under the hood of SuiteCRM much.

(when composing an email and then selecting the opportunity it DOES work, contrary to my initial testing above).

**Comment by PedroErnst** [comment]
Thanks @PaulMcRoar for spotting this. Your proposed solution does fix the issue, so I've made PR for it. It is maybe not the best way to do it, but it works, and this particular piece of code will be made obsolete by newer versions anyway.

**Pull request merged**
