### PR TITLE
FIX #7870 - Improvements in css for date_input and labels in EditView

### LINKED ISSUE #7870: Improvements in css for date_input and labels in EditView
#### Issue

The field `date_input` have many useless space and the witdget goes to a new line
fecha1

The label in EditView (when are long) overlaps

valor1

#### Expected Behavior

For the `date_input` field there is no point in having such useless free space and the widget in a new line.

The label should not overlap

#### Steps to Reproduce

1. Open an EditView with a `date_input` field and verify
2. Open an EditView with a long label, reduce the screen width and verify the overlap

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 69

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

Read #7870

`date_input` field fixed:

Before:

fecha1

After:

fecha2

Long labels does not overlaps:

Before:

valor1

After:

valor2

## Motivation and Context

Improve SuiteP theme

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Looks good other than the fix doesn't work in a low phone like resolution 
Screenshot from 2019-09-17 12-51-55

**Comment by Abuelodelanada** [comment]
Thanks for the feedback @Mac-Rae 

It's solved:

imagen

**Comment by Mac-Rae** [comment]
@Abuelodelanada Great!, will retest and get back to you

**Comment by Mac-Rae** [comment]
Could you push the branch again to resolve the conflicts or allow contributor access and we can do it for you.

**Comment by Abuelodelanada** [comment]
@Mac-Rae Let me know if everything is ok

**Comment by cameronblaikie** [comment]
@Abuelodelanada Looks good! Assessed :+1:

**Pull request merged**
