### PR TITLE
FIX 4803 - Now $aos_products_product_image is responsible in emails and PDFs

### PR DESCRIPTION
**Pull request by Abuelodelanada**
Now product images in templates are responsive.

## Description

This PR fixes: #4803

## Motivation and Context

Product images replaced by $aos_products_product_image variable are sized to 50px width and height.

## How To Test This

   

1. Create a PDF Template for Quotation including $aos_products_product_image variable
2. Create a Product with an image
3. Create a Quotation.
4. Email PDF this Quotation
5. Check that the image fits its container size

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Question: if `img-responsive` is a bootstrap thing, does it place any requirements on the people opening the emails, or reading the PDF's? Or does it work fine for everybody?

Sorry if this is a stupid question.

**Comment by Abuelodelanada** [comment]
Hi @pgorod PDF is ok.... In emails now I think we should include bootstrap...

**Comment by pgorod** [comment]
Including big CSS in emails also generates problems. Only a few days ago I had to explain to someone how to keep Gmail from "clipping" his emails, and it was because of a 122Kb `normalize.css`  framework he was including. Anything above 102Kb, Gmail clips.

Also, when you're dealing with mass emails, and many replies quoting those emails, even a few Kb multiplied by a large number, might bring you storage problems and giant Outlook folders.

So unless that Bootstrap is a very minimal thing I would advise including just a simple style definition for this purpose, and nothing else.

**Comment by Abuelodelanada** [comment]
May be we could include bootstrap from its [CDN](http://getbootstrap.com/docs/4.0/getting-started/download/#bootstrapcdn)

**Comment by pgorod** [comment]
That creates an Internet dependency - when using an Email client offline, you lose formatting when you view an email that you had previously downloaded.

It also uses mobile data for people reading email on their smartphones, and they might have limited connections or additional costs.

Is there any reason not to use whatever bootstrap uses for `img-responsive` directly, without referencing bootstrap? It should be just a few style tweaks.

**Comment by Abuelodelanada** [comment]
I add modify this line:

`$value = '';`

for this one:

`$value = '';`

Using the `img-responsive` styles.... In PDF look good, but the SuiteCRM email client modify the HTML with this:

``

**Comment by Abuelodelanada** [comment]
Hi @pgorod I really don not know where the Email client manipulate the HTML of a template.... may be @Dillon-Brown can help us...

**Comment by pgorod** [comment]
@labcerouno please refrain from doing these kinds of "shout-outs" to everybody... there are many issues here, and many PR's, we do our best to go through all of them, but it is impossible to satisfy everyone.

If you feel you really need to "bump" some PR or Issue, just comment and the people involved will get notified. Or mention _one_ person if you really think it's productive. 

Also you can think of how your comment can move the issue forward: can you say you tested and it works for you, or provide your use case if it adds something to the discussion? That's helpful. Any way, thanks for you input to this community, I _do_ appreciate it. :-)

**Comment by labcerouno** [comment]
OK @pgorod .  You are right. I was just trying to mention the ones involved in the last pending requirement, so one of them could try to complete it. As none of them were participants in this thread, I thought it was a forgotten issue. Sorry for the inconvenience.

Also I'd like to add that this solution **was tested and works well for me**. And I think it could be review and approved as soon as it is possible, because otherwise, sending Quotations with photos is quite useless.  

I'm looking forward to polish the Quotations modules the best we can. I don't have enough knowledge yet to propose fixes but I'm trying to improve myself in this area. I understand this is a community and not everyone will be satisfied, as you said. At the same time, I'd like to call for attention to some issues that are here a long ago and needs so little to be solved. I hope you understand.

Thank you and sorry again.

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
