### PR TITLE
Make email addresses display work in subpanels and inline edit

### PR DESCRIPTION
**Pull request by PedroErnst**
Removes a duplicate closing tag from the email link in listview after inline editing.
Removes dead code and makes use of the correct function EmailUI->populateComposeViewFields to show emails in subpanels

## Motivation and Context

Issue #5173 

## How To Test This

1. Go to Contact or other list view
2. Inline edit email address

1. View emails in subpanels

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by likhobory** [comment]
Test result: no problems with formatting, but Opt-in indicator is still not displayed.

**Comment by PedroErnst** [comment]
@likhobory 

Oh yes, missed that. Coming soon.

**Comment by likhobory** [comment]
Test result: Opt-in indicator and the address are displayed on different lines after inline editing.

default

**Comment by PedroErnst** [comment]
@likhobory 

I was encountering this problem as well, that's the reason I changed the 'optInStatusTick.tpl' file.

After a repair and rebuild it shouldn't do this.

**Comment by likhobory** [comment]
I did my previous test after QRR. Unfortunately it does not change this situation.

**Comment by likhobory** [comment]
FF (latest) and IE11 /Win 7

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
