### PR TITLE
Add an 'Other' category to the PR template.

### PR DESCRIPTION
**Pull request by connorshea**
## Description
Adds an 'Other' category for changes that don't fit in the current three.

This is a PR on `master` because I'm pretty sure it needs to be on master for the template to actually have any effect.

## Motivation and Context
I frequently open PRs that don't fit in the three categories provided, so this'd be a nice improvement to have :)

## How To Test This
Just review the change :)

## Types of changes
Other ;)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by Mac-Rae** [comment]
Could someone review and could @samus-aran assess also :+1:

**Comment by cameronblaikie** [comment]
Hi @connorshea Could you please rebase this to **Hotfix-7.10.x**? Once that is done we can get it properly reviewed and get it merged in :+1: 
Will also mark as an enhancement too
Thank you

**Comment by connorshea** [comment]
@cameronblaikie I can, but I'm fairly certain the PR Template is only used if it's on the master branch which is why I wanted to merge it into there. If you're sure we want to go through hotfix-7.10.x first I can do that.

**Pull request closed without merging**
