### PR TITLE
Feature codeception

### PR DESCRIPTION
**Pull request by daniel-samson**
## Description

This feature adds codeception to SuiteCRM. I have marked the problematic test as incomplete. Since this request is rather big. If we can merge this pull request in, we can then merge the fixes in smaller pull requests. Much of the changes is simply moving the tests into the unit folder.

Known Issues:
- Some test rely on the execution order of the test. Each test object needs to mock the data required first before running each test.
- The automated installer has alot of notices on php 7.1
- Some tests will only work after the installer has been run. 
- The code coverage needs to be improved

Going Forward:
- We need to update the test to reflect the product
- We need to create reusable tests based on the Sugar Templates: basic, person, company, file and sale.
- We need to create functional and acceptance testing
- We need to choose a java script testing framework so we can have client side tests
- We need to add selenium test for each browser and use browser stack to automate the test.

## Documentation
Get a LAMP stack environment
<pre>
docker run -d -P --name php-5 -v /var/www/html/:/var/www/html/ danielsamson/docker-php-5
</pre>

Open bash:
<pre>
docker exec -it php-5 bash
</pre>

Add ssh user account:
<pre>
adduser username
usermod -g www-data username
</pre>

Create test database
<pre>
CREATE DATABASE automated_tests;
CREATE USER 'automated_tests'@'localhost' IDENTIFIED BY 'automated_tests';
GRANT ALL PRIVILEGES ON automated_tests.* TO 'automated_tests'@'localhost';
exit;
</pre>

(Optional) Change the database details by editung tests/travis_config_si.php

set up composer
<pre>
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
chmod a+x /usr/local/bin/composer
cd /var/www/html/(instance of suitecrm)
composer install
</pre>

Install SuiteCRM using the installer or use the install script. Ensure that you set up the database correctly.

using script
<pre>
php tests/install.php
</pre>

If docker open terminal in container.

Run the tests in terminal:

<pre>
cd /var/www/html/(suitecrm instance)
./vendor/bin/codecept run -f unit
</pre>

## Motivation and Context

* Developers can easily run the same testing framework as Travis CI
* We can automated user testing, performance testing, and test installer / upgrade process
* I will encourage the contributors to add / update tests
* Integrates with IDEs
* Runs in command line

## How To Test This

* See documentation

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by chris001** [comment]
Thrilled to see you're adding this.  Quality and reliability should improve significantly.

**Comment by daniel-samson** [comment]
@chris001 these issues come from the existing test framework. I have simply moved the tests into the correctly place and disabled the really troublesome tests. I need @gymad  to review this and @samus-aran merge this into the product. If we can have codeception in the product. Then every contributor can help to make the tests much better.

**Comment by pgorod** [comment]
Watch out for multiple level directory creation, there is currently no way to do this 100% solid in SuiteCRM. If you pass the recursive flag to `sugar_mkdir`, it will create the multiple levels, but will not apply permissions correctly on all levels. 

Whether this will be a real problem will depend on other factors (sticky bits in parent directories, default permissions defined in config.php, etc.).

This is all explained in #2810, both in the main Issue text and in the follow-up discoveries.

This is just a warning in case you get problems; for the purposes of this Issue here, I'd say just add the flag and move on, if it works.

**Comment by chris001** [comment]
Error above ( `phpZipUtilsTest.php` ) is fixed by including the PHP library for ZIP.

In fact, the requirements for running the tests are not checked by the test code.
Instead of failing on an unexpected return value, this app, and these tests, should detect missing libraries and give that as the reason for the test failing or for the app erroring.
`apt install php-curl php-mbstring php-imap php-zip`  `yum install` on RPM OS.

Results:  `Tests: 1202, Assertions: 3557, Skipped: 18, Incomplete: 76.`

Detailed Results: 
[detailed-phpunit-test-results-2017-05-29.txt](https://github.com/salesagility/SuiteCRM/files/1036983/detailed-phpunit-test-results-2017-05-29.txt)

**Comment by daniel-samson** [comment]
Thanks @chris001 :D

**Comment by gymad** [comment]
Code quality is good, well done! I really would to see it in the repository :+1000:

**Comment by samus-aran** [comment]
Ok lets get this merged and started on it :+1:

**Comment by chris001** [comment]
For these tests to actually do the job and run on this github repo automatically and test the code, as they are intended to do, the tests from this `feature/codeception` branch PR #3600 must be merged to the `master`, `hotfix`, and `develop` branches, and the `.travis.yml` settings in each of the `hotfix` `feature`, `develop` and `master` branches must be updated to say that Travis should run tests on not only the `master` branch, but also the `hotfix`, `feature` and `develop` branches.

**Comment by chris001** [comment]
@samus-aran @daniel-samson What's going on with this `codeception` feature now.  It appears stuck in `feature/codeception` for 30 days.  This `codeception` must be added to `master` `hotfix` and `develop` because the old `phpunit` configuration there is broken, returning false build result codes.

**Pull request merged**
