### PR TITLE
Fix broken headings in Markdown files

### PR DESCRIPTION
**Pull request by bryant1410**
GitHub changed the way Markdown headings are parsed, so this change fixes it.

See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.

Tackles bryant1410/readmesfix#1

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
@bryant1410 Hi, can you please commit this PR to the hotfix branch and sign the clahub. Thanks.

**Comment by Dillon-Brown** [comment]
@bryant1410 Correct branch now!. If you could sign the contributor license agreement we can get this merged. Thanks.

**Comment by bryant1410** [comment]
Can you check if the CLA is signed now?

**Comment by Dillon-Brown** [comment]
All good now! Thanks for the contribution :)

**Pull request merged**
