### PR TITLE
Add Encrypt fields to Module Builder

### PR DESCRIPTION
**Pull request by chris001**
## Description

In Module Builder, add support for Encrypt field which was removed in SugarCRM CE 6.1 in 2011.

Solves issue #1755 

See forum request:
https://www.suitecrm.com/forum/developer-help/1740-securing-encrypting-a-custom-field
## Motivation and Context

These encrypted fields are required by law in many countries, for storing identity information, such as, social security number, drivers license number, date of birth, credit card number, etc.

SuiteCRM needs to comply with national laws requiring encrypted fields to safely contain personally identifying information, which is highly sought after by hackers and other unscrupulous sysadmins with root access seeking to commit financial fraud, identity theft, etc, by dumping the database and stealing such information needed to purchase items in the name of someone else.
## How To Test This

Go into Module Builder.  
You should be able to select field of type "Encrypt", label it "Social Security Number".
Add the field to your Quick Create, Detail and Edit views.
Save and click Deploy to make the the module active in your site.
Go into the module.
Create a new record.
Enter data into the Social Security Number field.
Save the new record.
Browse the database with phpMyAdmin.
Find the field for the new record you created.
The column for Social Security Number should be an illegible string of characters.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by chris001** [comment]
CLA was agreed to, yet github shows the contrary...

**Comment by chris001** [comment]
[quote="pgr" post=34846]This looks like a nice feature! Thanks!

But this encrypt field... what exactly does it use to encrypt/decrypt? Is it the user name, the user password, what?

I'm thinking about the implications of using such a field for backups, migrations, data access by multiple users, etc. 

In short: how could this go terribly wrong? : - )[/quote]

1.  It uses a single large global key, which is stored in a PHP file, to encrypt the field.
The CRM will encrypt the field just before writing it out to the database.
And, just as the CRM reads in the Encrypted field from the database, it decrypts the field.
So all the data inside the CRM is clear text.  And all the "Encrypt" field data on the database is Encrypted.

2. As long as you keep your website PHP code files together with your database , then your backups and migrations will be fine.
So, if you restore a backup to an instance without that key, or with a different key, they then Encrypt fields will decrypt incorrectly to garbage text.

I'd add better key management to SuiteCRM, to prevent any unexpected data garbling from occurring after a backup or migration to an instance without the original key.

**Comment by chris001** [comment]
@mattlorimer   There's been several forum comments on the thread (above) asking about the Encrypt field, and users hoping to use it.
Any questions or comments on re-adding this back into SuiteCRM?

**Comment by chris001** [comment]
A good reason to add back in the Encrypt field.  US health care providers, medical labs, etc, are mandated to comply with the national HIPAA (Health Insurance Portability and Accountability Act) regulations, which require privacy on electronic patient medical records, this means, encrypt fields containing sensitive "patient health information" (PHI).  Without Encrypt fields or something equivalent, SuiteCRM is legally useless to US hospitals, doctors offices, medical research centers, testing labs, etc, because it doesn't comply with the privacy requirements of HIPAA.
Read more about HIPAA: 
https://en.wikipedia.org/wiki/Health_Insurance_Portability_and_Accountability_Act

**Comment by ianscottgroup** [comment]
I would love to see this added to SuiteCRM. My business often requires that I store passwords for clients and having them in one place with customer information would be very helpful. 

Having that information encrypted is desirable.

**Comment by chris001** [comment]
@mattlorimer  Any reason this hasn't yet been merged? Cheers.

**Comment by levarberry** [comment]
I would like to see this as well.

**Comment by chris001** [comment]
@mattlorimer   Let me know if you need anything more.  Possibly adding an Admin page Encryption Settings.

**Comment by mattlorimer** [comment]
mostly I just need more hours in the day, but really I have a quick test and it seems to work, I will do further testing, plus need to check if there was a valid reason to remove it. The only minor thing I would say on the code is we should remove code as opposed to commenting it out, inline with our coding standards and as it would be flagged in in the sonarqube as an issue.

**Comment by chris001** [comment]
@mattlorimer  Commented code has been removed.
Do you need anything else before your merge this?

**Comment by samus-aran** [comment]
[Add support for Encrypt fields](https://trello.com/c/KDLKoHEu/86-add-support-for-encrypt-fields)

**Comment by boombata** [comment]
We would like to get this feature as well. thanks for this pull request.

**Comment by pgorod** [comment]
A user just commented on our Trello site that [GDPR](http://www.eugdpr.org/) requires this change.

Since @salesagility is already [communicating the need for organizations to be ready for GDPR](https://marketing.suitecrm.com/gdpr/gdpr), it would be nice to get this merged soon, it's becoming very relevant for anybody doing business in the EU.

**Comment by andrew-cascadegames** [comment]
Also agreeing that this would be very beneficial for my company's onboarding process for payroll.

**Comment by Sejwiur** [comment]
This is very needed feature, please add.

**Comment by pgorod** [comment]
I was wondering why this feature was removed in the first place. It occurred to me that maybe this encryption is crap, and somebody removed so no wrong expectations were created - it's arguable that it's better not to have an Encrypt field, than to have one that everyone can easily crack.

I am not a security expert, I don't know, but we could try and find out which encryption mechanism / Library it's using, and checking its reputation on Google.

**Comment by sergio91pt** [comment]
@pgorod If I'm remembering correctly the algorithm is blowfish, the same one used for smtp/imap passwords. The encryption key is/was a "Sugar GUID" generated in custom/blowfish/.

**Comment by pgorod** [comment]
Thanks @sergio91pt.

There was a nice discussion with Chris in [the original thread](https://www.suitecrm.com/forum/developer-help/1740-securing-encrypting-a-custom-field) about what additional developments this suggests. 

But if the encryption is basically sound, I say we should just go ahead with this merge and leave the rest for later... can you test and code review? Or any of the other people that expressed interest?

**Comment by Sejwiur** [comment]
Hi,

I've tested this solution localy, works for me  - SuiteCRM 7.9.5.

**Comment by goingsmart** [comment]
URGENT:
I'm not expert, but assume the previous SugarCRM field encryption approach is not valid in today's world without some type of "out-of-band-authentication". This need seems to require use of a Key Management Server? There are a few third-party solutions in the marketplace, but they are expensive.

I volunteer to be a Field-Level Encryption "Tester", if appropriate ;)

**Comment by pgorod** [comment]
@goingsmart you're mixing a few things there, I believe. Encryption is not the same thing as authentication. These fields are not authenticating anything, there is no out-of-band approach to apply here.

This is simple encryption, doesn't have to be too fancy for this purpose, I would say. Key management is important here (read Chris' suggestions on the thread linked above), but no server is required.

This encryption is useful in its current form, and could then be made better afterwards.

**Comment by goingsmart** [comment]
Some background: I am using SuiteCRM as a SaaS running in the Cloud. I need to be HIPAA compliant in the USA. Maybe my topic should be different than "Encrypt Fields"? e.g. "Field Encryption Compliance Requirements and Approaches".
My research indicates that I will not be compliant unless my encryption/decryption keys are managed outside my Cloud. AWS has a Key Management Server. Other CASB third-party services are available (StratoKey, SkyHigh,??) If my research is correct, this need must be supported by the "Encrypt Fields" code to be compliant. So this may be an Advanced Encrypt Fields Plugin?
Please advise.  THX

**Comment by pgorod** [comment]
Encryption of what? Of https network traffic? Of the server's disk? Of the database? Of fields? Of passwords stored on server? What if the requested encryption is impossible to implement in a particular case, does the regulation allow for that?

What defines a key management server? Is a key stored in in a simple server elsewhere good enough? Why not? 

My point is this: regulations are often very vague and confusing. The first thing you need to do is REALLY understand what they're asking, and have an architectural discussion to figure out if it applies and if it is possible, and with what costs.

**Comment by goingsmart** [comment]
Some Key USA HIPAA Data Security Considerations (D-R-A-F-T):
Goal#1: Encrypt/decrypt all Electronic Patient Health Information (ePHI) captured by SuiteCRM as Fields at REST in the Cloud .(e.g. Patient Name, Patient Email)
Goal#2: Retain the ePHI Encryption/Decryption Keys Outside the Cloud to promote out-of-band-authentication in compliance with CASB best practices.
Goal#3: Store all ePHI Data at REST (including Encryption/Decryption Keys) as High Availability (i.e. with secure, never lost appliances) to assure the data will always be available until archived (secure 100% hot fail-over or secure 100% recoverable).

**Comment by pgorod** [comment]
I don't understand Goal#2, what is this authentication they're talking about? Authentication is proving you are someone (like when you log in), what's the relationship with patient data stored in the Cloud?

Good luck with that "never lost", "100% secure" part, that sure is easy for a bureaucrat to write... :-)

And these Goals are they mandatory, or just "goals". Does everybody really need to have a complex architecture like CASB to operate in this HIPAA space?

If you do need it, you're in for a big, big project with lots of stuff to worry about. I would say SuiteCRM is just a small piece of the puzzle, and one that you can completely customize to your needs. Frankly, the costs of programming any encrypted fields in SuiteCRM aren't that high in that big picture, you can just code it yourself (and contribute it to the community).

**Comment by ianscottgroup** [comment]
pgorod.. stop spamming.

**Comment by pgorod** [comment]
@ianscottgroup wtf? I am having a conversation with a person on this Issue regarding the topic of this Issue. Why do you think that's spam? I didn't start asking the questions. Do you think it's better when nobody answers?

Maybe the quality of my intervention isn't satisfactory to you, I'll admit that I don't have much to add to this discussion. I'll make a future effort to make my participation have the quality of your contributions. Oh, wait, you haven't contributed anything yet, you're one of those guys who just comes here to ask for stuff... and complain.

There's an unsubscribe button, please click it.

**Comment by ianscottgroup** [comment]
"There's an unsubscribe button, please click it."

Just about to do that. :)

**Comment by goingsmart** [comment]
REMEMBER, I'M NOT EXPERT... THIS IS MY RESEARCH, TO DATE.. SO CORRECTIONS ARE WELCOME:
Goal#1 Has  2 components. The first is providing field-level encryption in SuteCRM. The second (which may properly be a different Topic), is implementing SuiteCRM field-level encryption in a manner that satisfies Compliance Requirements such as USA HIPAA. At a minimum, it would be important to include hooks and method extensions that will support Advanced Field-Level Encryption considering the following 2 Goals.
==============
Goal#2 Has 2 components. The most important component is locating the encryption/decryption keys on a server outside the SuiteCRM Cloud to increase security. See AWS Key Management Server.  This component is deemed mandatory for proper security compliance. The second component, "out-of-band-authentication" makes hacking an account more difficult by providing 2 separate and unconnected authentication channels to compromise.  The second component will be important to many potential "customers" considering using the SaaS Cloud, so this component is likely an Advanced Solution.
============== 
Goal#3 Has 2 components. The first is mandatory by providing some type of secure 100% persistence for the encryption/decryption keys AND the stored data to make sure the stored data will always be readable online until archived (i.e. NOT LOST). This can be accomplished without High Availability, except HA should be supported in the persistence model, as an option. The second component is important to discerning customers who value High Availability (HA) for the  application, so HA is optional and implementation specific, so this component is an Advanced Solution.

**Comment by goingsmart** [comment]
SOME IDEAS TO CONSIDER:

1) SuiteCRM Field-Level Encryption code: A) should have sufficient rigor to assure keys and encrypted data "cannot be lost"; and B) should include needed architecture, hooks, etc.. to support custom extensions for Advanced Security/Field-Level Encryption.

2) SuiteCRM should have some type of secure redundancy/fail-over/recovery for encryption/decryption Keys to prevent encrypted data from being lost. 

3) SuiteCRM should use a separate Key Management Server (e.g. AWS Key Management Server) for Field-Level Encryption to increase security.

**Comment by vanosg** [comment]
Just to throw my two cents in, I agree this is a feature that is very important and should be elevated in the priority queue for new features. Lack of encryption is the one thing 'missing' that is preventing me from transitioning over. Thanks to @chris001 and @mattlorimer for all you've done

**Comment by jsamelko** [comment]
Have tested this locally and verified working:

* SuiteCRM Version used: 7.10.2
* Environment name and version: MySQL Server 5.7 / PHP 4.7.4
* Operating System and version: Ubuntu 16.04 LTS

The proposed implementation above is fine for our needs at the moment, but I would agree that it would be great to see further development of encrypted fields. Particularly around access control and some documentation for the feature

Thanks to @chris001 for the fix

**Comment by goingsmart** [comment]
Please clarify the status if/when this is merged. 
1) Will it only restore the ENCRYPT field type that existed in SugarCRM that was dropped in 2011 using MD5?
2) Will there be any hooks to support a custom ENCRYPT function?
3) What is the current SuiteCRM  Roadmap for advanced ENCRYPT functionality?
THX.

**Comment by samus-aran** [comment]
We are closing this as we will not be implementing an encryption field without updating the encryption itself. This is on the roadmap but is not due in 7.11 anymore. We of course appreciate that this is a sought after feature but we feel adding it in now would cause more pain in the long run if people already start to use it and we force a new form of encryption.

**Pull request closed without merging**
