### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Incremented readme and suitecrm_version.php

#4556

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by isleshocky77** [comment]
@Dillon-Brown Do you guys have a policy on Issue & PR vs just a PR. As in I could have just submitted this as a PR since it was so small; however, some projects would like the Issue and PR.

P.s. Once again, I'm not sure if this is documented somewhere.

**Comment by horus68** [comment]
@isleshocky77 issue/PR (even if sometimes I don't do it too!)

See: 
> When committing to your individual bugfix branch, it helps to follow the message format below:
https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM

**Comment by isleshocky77** [comment]
@horus68 Any chance of getting some Github "Milestones" opened with the Issues/PRs pegged to them?

**Comment by horus68** [comment]
I'm not from SalesAgility! You need to wait for @Dillon-Brown reply

**Comment by Dillon-Brown** [comment]
@isleshocky77 If it's just a small change you don't necessarily need to create an issue, it does help with tracking / release notes though. The current documentation can be found on the [wiki](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) and the [contributing.md](https://github.com/salesagility/SuiteCRM/blob/master/.github/CONTRIBUTING.md). I'll look into milestones but we'll need to check how it would fit into our current processes. Thanks!

**Pull request merged**
