### PR TITLE
FIX #8143 - Add 'id' in label <div> in EditView

### LINKED ISSUE #8143: ID missing in EditView labels.
#### Issue

In EditViews would be very useful that the `<div>` that contains the LABEL of every FIELD has the `id` field so you can manipulate with JS it easily.

#### Expected Behavior

Example: 
```html
<div class="col-xs-12 col-sm-4 label" id="telefono_crecer" data-label="LBL_TELEFONO_CRECER">Teléfono Crecer XXI:</div>
```

#### Actual Behavior

Example: Nowadays the HTML is rendered like this:
```html
<div class="col-xs-12 col-sm-4 label" data-label="LBL_TELEFONO_CRECER">Teléfono Crecer XXI:</div>
```

#### Possible Fix

We can add the `id` field in TPL like this:

```diff
modified   themes/SuiteP/include/EditView/tab_panel_content.tpl
@@ -26,9 +26,9 @@
 
                         {*<!-- LABEL -->*}
                         {{if $smarty.foreach.colIteration.total > 1 && $colData.colspan != 3}}
-                            <div class="col-xs-12 col-sm-4 label" data-label="{{$fields[$colData.field.name].vname}}">
+                            <div class="col-xs-12 col-sm-4 label" id="{{$fields[$colData.field.name].name}}_label" data-label="{{$fields[$colData.field.name].vname}}">
                         {{else}}
-                             <div class="col-xs-12 col-sm-2 label" data-label="{{$fields[$colData.field.name].vname}}">
+                             <div class="col-xs-12 col-sm-2 label" id="{{$fields[$colData.field.name].name}}_label" data-label="{{$fields[$colData.field.name].vname}}">
                         {{/if}}
 
                                 {*label*}

```

#### Steps to Reproduce

1. Just see the HTML of an EditView ;-)

#### Context

We have many JS functionalities that hides/shows fields under certain conditions. In SugarCRM theme every field has its label field named like this: "field_name + _label". So it's quite simple to hide/show the field and its label because the label is always named the same way (field_name + '_lablel')

#### Your Environment

* SuiteCRM Version used: 7.10.20

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

Read #8143

## How To Test This

1. Open an EditView
2. Verify that now the label of every field has the `id` named `<field_name>`+`_label` like this:
```html
<div class="col-xs-12 col-sm-4 label" id="date_start_label" data-label="LBL_DATE">Inicio:</div>
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by HVStechnik** [comment]
That's true. However, I think that it is sufficient to clearly identify the `<div class="edit-view-row-item ...">` tag (the parent of the label tag) by the data-field attribute (as already merged in #7844). Thereby, you can then address any label by `.edit-view-row-item[data-field='assigned_user_name'] .label { color: red; }`. Of corse, it would also be possible to use an id attribute instead of the data attribute. That should not make a difference. However, I think that it is more valuable to identify the  `<div class="edit-view-row-item ...">` tag instead of the label tag. That is more flexible, because it also allows us to select the entire field and not just the label. Best wishes

**Comment by Abuelodelanada** [comment]
Hi @HVStechnik 

Yes, that's true.
Having the `id` too is inexpensive and will help many people migrating from SugarCRM CE to SuiteCRM, like we are doing right now ;-)

**Comment by Abuelodelanada** [comment]
Hi @Dillon-Brown 

Do you think we can merge this PR?

**Comment by pgorod** [comment]
@Abuelodelanada a similar issue is here #5294. It's an old one...

**Comment by Abuelodelanada** [comment]
Hi @samus-aran I'm cleanning my "Open PR" list.
Is still possible to merge this one, or should I close it?

**Pull request closed without merging**
