### PR TITLE
Fixed #4511 - Upgrade of TinyMCE to latest 4.9.x version

### LINKED ISSUE #4511: Upgrade of TinyMCE to latest 4.7.x version
In SuiteCRM we are using TinyMCE Version: 3.5.12 (2016-10-31)

The latest version 4.7.1    https://www.tinymce.com/download/ 

There is huge different between version 3.x and 4.x 

Our old one:
tiny3

New one:
tiny4

Issues which are maybe related to old version #4389 #3672 #4463

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Moving tinymce to composer.

## Motivation and Context

Issue reference: #4511. 

## How To Test This

1. Set editor to TinyMCE in user profile.
2. Create an email template.
3. See that the TinyMCE editor works as expected.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jack7anderson7** [comment]
Assessed :+1: 

[Approved with PullApprove](https://pullapprove.com/salesagility/SuiteCRM/pull-request/6699/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=salesagility/SuiteCRM)

**Comment by connorshea** [comment]
@Dillon-Brown should this PR have removed the tiny_mce at [`include/javascript/tiny_mce`](https://github.com/salesagility/SuiteCRM/tree/develop/include/javascript/tiny_mce) as well?

**Comment by Dillon-Brown** [comment]
@connorshea Ideally yes, there's an issue for it here: #6747

**Comment by CrazyGoose** [comment]
This only upgrades the Email editor.  It doesn't upgrade the TinyMCE for PDF Templates.

**Comment by vistar** [comment]
> This only upgrades the Email editor. It doesn't upgrade the TinyMCE for PDF Templates.

For it need to update /include/SugarTinyMCE.php

**Pull request merged**
