### PR TITLE
Workflow fix for custom relationship joins

### PR DESCRIPTION
**Pull request by FibreCRM**
Issue: WF does not work when condition is based on custom relationship

## Description
Create a custom relationship between two modules.  e.g. Create a one-many relationship between Contacts and Opportunities.  This should enable a single opportunity to be related to a single contact.  A contact can have many opportunities.

Create a WF where the primary module is Contacts.  The purpose of the WF is to send a personalised email to the Contact when an opportunity meets a specific condition.  For example, The opportunity last modified date is greater than 30 days.

Run the WF and it will fail.  The error.log will contain something like

The following was an extract from our sugarcrm.log file prior to the fix

Query Failed: SELECT contacts.id AS id, contacts_opportunities_1.id AS 'contacts_opportunities_1_id' FROM contacts LEFT JOIN contacts_opportunities_1_c ON contacts.id=contacts_opportunities_1_c.contacts_opportunities_1contacts_ida AND contacts_opportunities_1_c.deleted=0

LEFT JOIN opportunities contacts_opportunities_1 ON contacts_opportunities_1.id=contacts_opportunities_1_c.contacts_opportunities_1opportunities_idb AND contacts_opportunities_1.deleted=0
LEFT JOIN opportunities_cstm contacts_opportunities_1_cstm ON opportunities.id = contacts_opportunities_1_cstm.id_c  WHERE DATE(contacts_opportunities_1.date_closed) = Curdate() AND contacts_opportunities_1_cstm.service_item_c = '7PTAX' AND contacts_opportunities_1_cstm.job_sortable_status_c LIKE CONCAT('%', '7' ,'%') AND contacts.last_name != 'A' AND contacts.deleted = 0 : MySQL error 1054: Unknown column 'opportunities.id' in 'on clause'

## Motivation and Context
This change fixes a bug in the code by adding a check to see if the relationship is a custom one or not.

## How To Test This
As described

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by FibreCRM** [comment]
Sorry How do we change this?  We want to help but not sure how :)

**Comment by horus68** [comment]
@stevejenkin Yous commit to this PR was intended? Usually a PR is for a single issue only.

**Comment by david-pili** [comment]
I applied this to my SuiteCRM and it appears to work correctly. Furthermore this bug wasn't just caused by custom relationships, custom fields also caused this and are also fixed by this commit. Having a workflow with Notes as the workflow module with condition comparing a custom field on contacts against a custom notes field would fail.

**Comment by chris001** [comment]
@FibreCRM 
Travis is not failing this PR when it should: 2 failed unit tests, and the log is showing tons of fatal errors, maybe not related to your PR, maybe some are related.
Nonetheless, those fails are supposed to create a red flag icon, in place of the "green checkbox All checks have passed".  The tests have failed.
Can you run the phunit tests on your side?  Results?

**Comment by Dillon-Brown** [comment]
Closed due to inactivity.

**Pull request closed without merging**
