### PR TITLE
Fix #10353 - Fatal error in AOR Reports dashlet

### LINKED ISSUE #10353: Fatal error in AOR Reports dashlet
#### Issue
When loading the dashboard containing an AOR Reports dashlet which is linked to a deleted report a fatal error is thrown.
```PHP Fatal error:  Uncaught Error: Attempt to assign property "user_parameters" on bool in xx/modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php:44```

#### Expected Behavior
The dashboard should load without issue.

#### Actual Behavior
The dashboard fails to load and the following error is thrown:
```PHP Fatal error:  Uncaught Error: Attempt to assign property "user_parameters" on bool in xx/modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php:44```

#### Possible Fix
Check report exists before trying to use it.

#### Steps to Reproduce
1. Create a report
2. Add report dashlet to dashboard and select the newly created report
3. Delete the report
4. Reload the dashboard

#### Context
High priority - Dashboard unusable

#### Your Environment
* SuiteCRM Version used: 7.14.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 121.0.6167.140 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.2
* Operating System and version (e.g Ubuntu 16.04): Debian 11.8

### PR DESCRIPTION
**Pull request by fluffyballs**
## Description
Fix #10353 

## Motivation and Context
Fixes fatal error.

## How To Test This
Repeat procedure defined in issue.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hey @fluffyballs,

thanks for your contribution, 

I'd like to draw your attention to the commit: 

image

would you be so kind to update your commit message to the following format below: 

image

More useful information on how to contribute is available here:  
https://docs.suitecrm.com/community/contributing-code/bugs/

Many thanks in advance! 

Regards,
Serhii

**Comment by chris001** [comment]
Yes, @fluffyballs  in your commit message, you only need to add the missing `#` next to the `10353`, making it #10353

**Comment by fluffyballs** [comment]
Sorry, typo when writing the message. It should be updated now.

**Comment by serhiisamko091184** [comment]
Hi @fluffyballs,

thanks a lot for the quick response and update! 

Regards,
Serhii

**Comment by jack7anderson7** [comment]
Hi @fluffyballs,

Thank you for your contribution and the time you took to create the PR

We have ultimately chosen to go with another PR that resolves this issue: #10411 , so we will close this PR.

However we are still grateful for your time and contribution.

Thank you again
Jack

**Pull request closed without merging**
