### PR TITLE
Fixed - Error message in display maps. Added Google Maps API Key field.

### PR DESCRIPTION
**Pull request by daniel-samson**
## Description

References issue #3070 

After a user creates a map related to an account or contact that has a billing address in the Maps Module. When they try to display the map (look at the maps field), it comes up with and error.

This error is a run time error. It it produced when the API key is not specified in the script element.

I have added an API key field to the google maps admin panel. I have also added a link to the google maps API page. So that a user can easily get an API key. 

google_maps_api_key_config

When the API key is empty the display maps page will give an error instructing the user to set the API key in the admin panel.

google_maps_error

There are new language labels that will need to be translated.

## Motivation and Context

- Due to a change in the google API's with out the key you cannot use the google maps facility.

## How To Test This

- Create a map
- Relate it to an account with a billing address
- Save the map 
- Click on the map link in the Detail view

map

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
It should be noted that this is not affecting old installations but its required for installations after June 22, 2016

Google Map API requires you to register for your own key (this only apply to sites not using the API before June 22, 2016)
> We no longer support keyless access (any request that doesn't include an API key). Future product updates are only available for requests made with an API key.
https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update ).

To register for a key see: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by horus68** [comment]
@shogunpol this is a required PR for any new installation (not for old ones)

**Comment by chris001** [comment]
See also #3290 , both PR are required for perfect functioning of the new Google Maps Geocoding and Javascript APIs.

**Comment by chris001** [comment]
Confirmed after testing.  Both a Google Maps Javascript API key (PR #2536),  and a Google Maps Geocoding API key (PR #3290) are needed, for the Maps module to work.

**Comment by horus68** [comment]
@Dillon-Brown @samus-aran this PR needs to be merged as Maps module is not working

**Comment by chris001** [comment]
@Dillon-Brown @samus-aran 🤦‍♂️  you forgot to merge this one and #3290 for Maps module to work again.

**Pull request merged**
