### PR TITLE
Fix #9829 - Fatal error during upgrade to 7.12.8

### LINKED ISSUE #9829: Fatal error during upgrade on PHP 8.0 from 7.12 with custom user layouts
#### Issue
Performing a silent upgrade of 7.12.7 to 7.12.8 failed with a fatal error resulting in a broken system due to static call to a non-static method.

#### Expected Behavior
Upgrade should be performed successfully.

#### Actual Behavior
Upgrade fails part way throwing the fatal error
`PHP Fatal error: Uncaught Error: Non-static method MetaParser::hasMultiplePanels() cannot be called statically in crm/modules/UpgradeWizard/SugarMerge/EditViewMerge.php:611`

#### Possible Fix
Replace all static calls to MetaParser::hasMultiplePanels() with calls to an instance of the MetaParser class in the file modules/UpgradeWizard/SugarMerge/EditViewMerge.php

#### Steps to Reproduce
1. Install 7.12.7
2. Download SuiteCRM-Upgrade-7.12.x-to-7.12.8.zip upgrade package
3. Perform silent upgrade

#### Context
High priority - System is left broken

#### Your Environment
* SuiteCRM Version used: 7.12.7
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.0
* Operating System and version (e.g Ubuntu 16.04): Debian 11

### PR DESCRIPTION
**Pull request by FR-JS**
## Description
Fix #9829 

## How To Test This
Repeat procedure defined in issue.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by JanSiero** [comment]
Assessed  👍
 
Relevant changes are only in/around
lines 611 - 613
lines 697 - 701

**Review by JanSiero — APPROVED** [review]
Relevant changes are only in
lines 611 - 613
lines 697 - 701

Not sure if submitter should clean this up, or this can be done on merging.

Alternatively MetaParser::hasMultiplePanels could be made static, but this looks OK to me.

**Comment by JanSiero** [comment]
@SA: Please consider issuing an upgrade patch specific for PHP8, as this error leads to an upgrade lock which can only be circumvented by either downgrading to PHP 7.4 or manually editing the file.

Attached is an upgrade patch which replaces the EditViewMerge.php file.
[SuiteCRM_Upgrade_Patch_PHP8_1.0.0.zip](https://github.com/salesagility/SuiteCRM/files/14550837/SuiteCRM_Upgrade_Patch_PHP8_1.0.0.zip)

Enriching the existing SuiteCRM_Upgrade_Patch_1.0.1 module is not an option as when upgrading from 7.11.16 you would need to install the module twice:

1. to lift the installation to 7.12
2. to upgrade from 7.12 to a version greater than 7.14.3 as the file EditViewMerge.php wil have been overwritten in the intermediate upgrade, which requires a reinstallation of this module.

SuiteCRM however doesn't allow a repeated installation of the same module/version.

**Review by jack7anderson7 — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]

**Comment by jack7anderson7** [comment]
Hey @FR-JS,

We are closing this MR as we have merged: https://github.com/salesagility/SuiteCRM/pull/10470

Thanks,
Jack

**Pull request closed without merging**
