### PR TITLE
FEATURE Move OAuth2 Encryption Key into config.php

### PR DESCRIPTION
**Pull request by tsitle**
## Description

Store the OAuth2 Encryption Key in `config.php` instead of `Api/Core/Config/ApiConfig.php`.

## Motivation and Context

Currently this is done by changing/rewriting a core file
(`Api/Core/Config/ApiConfig.php`) in order to store the OAuth2 Encryption Key (ApiConfig::OAUTH2_ENCRYPTION_KEY).
Plus this is done in four different places - each one containing duplicated code.
IMHO it is much better to move this config value into the appropriate file
and also reduce duplicated code.
Another effect of this modification is that `Api/Core/Config/ApiConfig.php`
with a custom OAuth2 key won't accidently end up in a commit because the file has been changed.

## How To Test This

E.g. run the CI tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by mattlorimer** [comment]
I'm sure this will make many SuiteCRM Devs very happy, thank for a great contribution

**Comment by pgorod** [comment]
@tsitle shouldn't this be reflected in the Documentation?

**Comment by tsitle** [comment]
@pgorod Well yes, it should ;-) I've just created a PR in the Doc-Repo.

**Pull request merged**
