### PR TITLE
Fix duplicated code and broken braces introduced in a previous merge.

### PR DESCRIPTION
**Pull request by PedroErnst**
A previous merge commit (acf2960) introduced a bug in this file, duplicating some code and adding a brace that is never closed.

## Motivation and Context

Issue #6796

## How To Test This

See ##6796

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
@PedroErnst Does this need duplicated for hotfix-7.10.x?

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by PedroErnst** [comment]
@Dillon-Brown hotfix-7.10.x looks OK, it seems the bug was only in hotfix branch

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
