### PR TITLE
Fixed #6320 - Do not shows subpanels with records even if it's empty

### LINKED ISSUE #6320: Empty collapsed activities/history subpanels is always shown as a subpanels with some records
Subj.

1. Open users profile and enable Show collapsed subpanel hint option on layout options tab
2. Create any record with activities or history subpanel and open it in Detail View
3. Go to activities or history subpanel and check the result

#### Your Environment

    * SuiteCRM Version used: 7.10.8, clean installation with demo db
    * Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF latest, IE11
    * Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.9-1ubuntu4.25, MySQL 5.5.61
    * Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

### PR DESCRIPTION
**Pull request by gymad**
## Description

Fix for #6320
## Motivation and Context

see #6320
## How To Test This

see #6320
do a QRR
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by likhobory** [comment]
Not working as expected. Now subpanels with records are always shown as empty subpanels.

default

**Comment by samus-aran** [comment]
Hey @likhobory Are you able to test again?

**Comment by likhobory** [comment]
1. empty activities/history subpanels have the same colour as the filled ones.

default

2.  filled activities/history subpanels have the same colour as the empty subpanels and do not display any hints.

default

**Comment by gymad** [comment]
Hi @likhobory, can you please do a "quick repair and rebuild" in Admin page and also clear the cache if it's necessary. 
Thanks

**Comment by likhobory** [comment]
Applied color fix patch + QRR.
Works as expected.

**Pull request merged**
