### PR TITLE
Fix #2498 - Calendar Localization not working: days long and time slot

### LINKED ISSUE #2498: SuiteCRM 7.7.6 - Calendar Localization not working: days long and time slot
In SuiteCRM 7.7.6 Calendar is always in English language..
#### Issue

in SuiteCRM 7.7.6 the Calendar headers (days_long) and time slots are in English language even if all other dates and times are following the right Locale settings.

screen shot 10-27-16 at 10 39 am

### PR DESCRIPTION
**Pull request by Szellszi**
In fullcalendar 3.0 the lang property changed to locale.
Check: https://fullcalendar.io/docs/text/locale/

## Description

This is a fix for issue #2498 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Fix works OK under 7.9.0 for calendar module

**Comment by horus68** [comment]
Just wondering: from what file are the weekdays name coming? There are several entries on the system to be a candidate, I tested all I could find adding a code to differentiate the test, repair and rebuild, rebuild JS language files, empty caches.. different browsers,  but couldn't get any change! @Szellszi @pgorod 

Note: Month name is from `dom_cal_month_long` array in `\modules\Calendar\language\en_us.lang.php`

**Comment by pgorod** [comment]
@horus68 if I'm not mistaken, form a quick scan of the code, it comes from this line:

https://github.com/salesagility/SuiteCRM/blob/40f148803d60246dff9cf88e2dfe100d76d2fa05/modules/Calendar/fullcalendar/fullcalendar.js#L5400

So it uses the [PHP date.format](http://php.net/manual/en/function.date.php) function which is sensitive to the locale. If this is true, then these values simply do not come from SuiteCRM language files.

**Comment by horus68** [comment]
SuiteCRM  is getting the values from the file  `\modules\Calendar\fullcalendar\lang-all.js`
That file is from an outside source (Fullcalendar) that republishes after 2 code sources:
- Moment https://github.com/moment/moment/
-- I already did a PR there https://github.com/moment/moment/pull/3989
-- Also made the fix in SuiteCRM in hope it gets included sooner! https://github.com/salesagility/SuiteCRM/pull/3623

The second source for Fullcalendar is Datepicker | jQuery UI - https://github.com/jquery/jquery-ui
Also made a PR to make Monday the first day of the week. Its already merged :) so someday it will land here!
https://github.com/jquery/jquery-ui/commit/6fdd0e34a74789d2da214739ea0f5a8feff71d7e

**Comment by samus-aran** [comment]
@Szellszi - YOu need to apply this also to jssource/src_files/modules/Calendar/Cal.js

Good thing here to test @horus68 with Javascript changes does the fix still work after a RepairJS ^^ hence the above :)

**Comment by horus68** [comment]
@samus-aran as expected after a Repair / Rebuild JS Compressed Files the fix was reverted.
@Szellszi you need to make a second commit and edit  `\jssource\src_files\modules\Calendar\Cal.js`
line 919
from 
`       lang: global_langPrefix,`
to
`       locale: global_langPrefix,`

Sade Face note: This bug wouldn't happen if SuiteCRM had updated the Fullcalendar itself!
- `locale` changed in 3.0 from `lang` https://fullcalendar.io/docs/text/locale/
Actually SuiteCRM its using version 3.0.1 (26 Sep 2016) even if the actual version is now  3.4.0 (27 Apr 2017)

**Comment by margoux** [comment]
@horus68

> edit \jssource\src_files\modules\Calendar\Cal.js
line 919
from
lang: global_langPrefix,
to
locale: global_langPrefix,

works perfect with 7.8.5 / language DE

many thanks, margoux

**Comment by Dillon-Brown** [comment]
@Szellszi Can you make the changes described by horus in jssource? would be nice to get this merged along with #3623

**Comment by horus68** [comment]
waiting for a merge on this. @Dillon-Brown maybe you can recreate the PR to avoid branch conflicts?

**Comment by Dillon-Brown** [comment]
@horus68 Conflicts should now be resolved. I'll look at getting this code reviewed + merged.

**Pull request merged**
