### PR TITLE
Installation screens: choose language for wizard [Language]

### PR DESCRIPTION
**Pull request by horus68**
i18n for install screens. Install in local language. Languages for install screens are included (translated via Crowdin).
Full language packs needs to be installed as usual, after SuiteCRM is installed.

Note on this PR: Reposition of previous PR #950 (I had to delete my repo!)
# Details:

SuiteCRM installation screens will have 48 languages to choose from.
This is only for installation screens not for core screens.
2016-02-12 09_28_10-suitecrm
- Installation screen will have all languages available in Crowdin. Strings not translated will show as English
- SuiteCRM will install as it would in English but users will have their own language on installation screens
- After installation SuiteCRM will run and login as english
- Language packs needs to be installed as usual, with module loader.

Suggestion: There should be an alert/info on this procedure when installing SuiteCRM (I don't know how to do it, so leave it to coders!)

**Core language packs** 
Packs are ready to be downloaded by users from online translation project at Crowdin 
[](https://crowdin.com/project/suitecrmtranslations)

Note: language files for install screens are also available at Crowdin to be translated. They can be updated to github when required.

**Some localized install wizard screens:**

French
2016-02-12 09_28_44-assistant d installation suitecrm _ bienvenue dans suitecrm 7 5 1 assistant d in

Greek
2016-02-12 09_29_16-suitecrm setup wizard_ suitecrm 7 5 1

Arabic

German
2016-02-12 09_31_23-pesquisa

### CODE REVIEW

**Comment by horus68** [comment]
@mattlorimer @salesagility what does it takes to get this PR merged?
People translate it, PR was created, its a simple and useful feature required by non-english users but since July 2016 it only got a enhancement label 6 months ago?
I don't even know if this is a wanted feature or if is it worth the time to keep translation updated.
So please can you give some orientation on this one.

What do you say on this @pgorod @pribeiro42 @likhobory @urdhvatech @bmwtourer @SoapJson @Mausino ?

**Comment by Mausino** [comment]
@horus68  slovak language is translated on 84%, we're working on. Now many user don't know that exist something like cowdin... I suppose to link where user can download own language file on installation (like warning)... please your feedback if is good idea or not

**Comment by pgorod** [comment]
What can I say, it's obviously useful. I'm sure that, now that you've bumped it, it will get merged.

I hate to break it to you, but I think the license text in all those files is outdated, though. But let's wait until we hear from SalesAgility to know if it's worth the trouble of fixing.

**Comment by likhobory** [comment]
In this case I suppose that there should be a label or message informing users that it's the language for the **installation wizard** only, and the appropriate general language pack should be downloaded and installed in addition.

**Comment by pribeiro42** [comment]
Hi all, in the one hand, i like the idea of having a multitude of languages to choose from, on the other hand, i also agree with @Mausino regarding the knowledge of general people about the crowdin repository... People might even find ackward to get the installer from one side and language packs from another unrelated site...
Don't know if its better to endorse it through a link in install / language pack install or to merge all the languages into github.. .I guess it's a job for @salesagility to decide...

**Comment by horus68** [comment]
@Mausino and @likhobory  I too agree with the need to inform users. A top message would be perfect! 
I made a small PR to allow information on translations in the "About" pace (the first page visible after each update or install) but not merged yet: https://github.com/salesagility/SuiteCRM/pull/1877

On the messages system this would be perfect: https://github.com/salesagility/SuiteCRM/issues/3048

@pribeiro42 for me github can't handle the requirements for real translator work. I also don't think there is any gain to have SuiteCRM distribution code zip including all languages as unnecessary : its better to have each language pack installed independently.

@pgorod  on the outdated licenses... this is a common issue all over the code. On 7.8 only the edited files are getting a new info header with (when all needs to be updated... even if the same will be required next year because the copyright info that includes an ending year for it).
I have not updated the files because there was no reason for it: if this will be planned to merge I will updated the commit here, its an easy task on Crowdin (it takes just 1 file to be updated)

On a side note - Joomla works like this: Installer language files are on core zip, then after install people can download translations and install each language required (this is done directly in the admin area and from a common repository managed by Joomla .org ). Most languages are translated in Crowdin but each language team needs to create a language pack and upload it to Joomla .org  (In SuiteCRM we can have complete packs from Crowdin)

**Comment by chris001** [comment]
It's been 9 months, @samus-aran no objection from anyone, why is not auto merge this

**Comment by samus-aran** [comment]
As a general rule, there is no auto merge on any PR.  There is alot of progression with other PRs at the moment so things will be added to backlog until time is available to review and asses internally. :+1: Again, appreciate your patience and we are working on improving this process asap.

**Comment by pgorod** [comment]
@horus68 I was looking at this and I wonder if we really should put in all the language files for all the languages.

Wouldn't it be better to provide just 5 or 6 of the most used languages in the world, for the sake of simplicity?

I also worry that any updates to these files would be PR's here, without the benefit of delegating that work to Crowdin platform, like we have for the rest of the language files. This is why I would prefer not to have a ton of activity around these files here on GitHub, as all the languages slowly evolve towards being 100% translated.

You know, aim for 95% of the benefit of this PR while cutting it in half :-)

Maybe I would use only English, French, Italian, German, Russian, Chinese, Portuguese, Spanish, any other one?

**Comment by horus68** [comment]
@pgorod Usually the install language/translations needs to be in the core as there is no way to download and use a different language unless you recreate the install package. Its also difficult to cut down languages but no problem from me!

- There shouldn't be any individual language PR to this. The workflow would be:
1- Translators translate via Crowdin
2- When making a new release SA will download "install" translations from Crowdin
3- SA updates the "install" language files and merges it into the release pack, so only one PR for languages.

Note: SA don't need to download each language pack from Crowdin and look for the install file. Anyone can get from Crowdin the install language files in a ZIP folder, ready to be merged: the FULL zip download (see top button in the project front page https://crowdin.com/project/suitecrmtranslations) will download all translations organized by folders (where there is a folder with the required files in "`\install\language`" ). All install files now counting 3.5 MB uncompressed.
For clarification the ZIP for each single language has a different structure to be installed directly.

**Comment by horus68** [comment]
Yes its strange... its a side effect of opensource software!
Joomla has similar workflow, but even with a core translation manager and each language having its own manager things get messy some times.

**Comment by pgorod** [comment]
Can't you think of a way to omit languages that haven't even started translation of that file yet? Is it hard to achieve in Crowdin?

**Comment by horus68** [comment]
Not possible on Crowdin.

**Comment by pgorod** [comment]
Ok, so probably the best we could do is a campaign to push translators to work on these strings as soon as we include then, to minimize the "fraudulent" language options that only show English.

**Comment by pgorod** [comment]
Just a few updates on this:

- Crowdin seems to have [an API](https://support.crowdin.com/api/api-integration-setup/) and a [command-line client](https://support.crowdin.com/cli-tool/) that allows automated download of translations. 

- It even has a [GitHub integration](https://support.crowdin.com/github-integration/)! 

This might open the way for a more completely automated process, where users don't have to visit Crowdin for a separate download, instead they just click in the SuiteCRM UI to select their language of choice.

**Comment by chris001** [comment]
All that's needed for fluid approach is code that auto installs the full language pack of the user's chosen installer language.

**Pull request closed without merging**
