### PR TITLE
Making Quick Create more customisable (SuiteP)

### PR DESCRIPTION
**Pull request by daniel-samson**
## Description

I noticed that that you can't easily change the colors of the quick create button. So i have fixed the variables so that you now can.

## How To Test This

* Rebuild scss
* Change the variables under the quick create section

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by zebelcrm** [comment]
How do you apply these changes? Will they be included in the next release of SuiteCRM or do they have to be applied manually. If manually, then what do you need to do to rebuild and see the changes in the browser? - Thank you.

**Comment by chris001** [comment]
You could get it now if you download the 3 changed files and save them over the ones you have.  Or, you can probably just clone the hotfix branch, dump the browser cache, "quick repair rebuild", and good to go. Of course doing this will void your warranty (just kidding there is no warranty) and overwrite any changed core files if you've hacked on them in a non upgrade safe way, which isn't a good thing to do anyway, yet some do, be warned.

**Comment by zebelcrm** [comment]
Thank you for the information. So, am I to assume that this will not be included in any future versions or will it?
 
--------- Original Message --------- Subject: Re: [salesagility/SuiteCRM] Making Quick Create more customisable (SuiteP) (#3199)

**Comment by samus-aran** [comment]
Hi @zebelcrm 

Yes the fix provided will be in the next Release (7.8.3).  I would recommend you wait (unless you know how to set up Sass to rebuild the style.css to which carry on) so that the rebuild style.css for SuiteP is included in the package.

**Pull request merged**
