### PR TITLE
Fixed #3898 - 7.9.3 Duplicated language

### LINKED ISSUE #3898: Duplicated language strings (ver.7.9.3)
['ERR_DB_PRIV_USER']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L107
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L110

['LBL_DBCONFIG_SECURITY']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L212
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L216

['LBL_DBCONFIG_PROVIDE_DD']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L213
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L218

['LBL_DBCONFIG_CREATE_DD']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L214
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L219

['LBL_DBCONFIG_SAME_DD']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L215
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/install/language/en_us.lang.php#L220

['LBL_AM_PROJECTTEMPLATES_PROJECT_1_FROM_PROJECT_TITLE']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/AM_ProjectTemplates/language/en_us.lang.php#L145
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/AM_ProjectTemplates/language/en_us.lang.php#L147

['LBL_WIZARD_TARGET_MESSAGE1']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Campaigns/language/en_us.lang.php#L219
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Campaigns/language/en_us.lang.php#L223

['LBL_WIZARD_TARGET_MESSAGE2']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Campaigns/language/en_us.lang.php#L220
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Campaigns/language/en_us.lang.php#L224

['LBL_WIZARD_TRACKER_MESSAGE']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Campaigns/language/en_us.lang.php#L221
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Campaigns/language/en_us.lang.php#L225

['LBL_STEP_INFO_TARGET_LIST_NEWSLETTER']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Campaigns/language/en_us.lang.php#L501
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Campaigns/language/en_us.lang.php#L503

['ERROR_NO_SEARCHDEFS_MAPPING']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Connectors/language/en_us.lang.php#L93
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Connectors/language/en_us.lang.php#L97

['ERR_UW_LOG_FILE_UNWRITABLE']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/UpgradeWizard/language/en_us.lang.php#L60
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/UpgradeWizard/language/en_us.lang.php#L62

['ERR_UW_MBSTRING_FUNC_OVERLOAD']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/UpgradeWizard/language/en_us.lang.php#L61
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/UpgradeWizard/language/en_us.lang.php#L63

['LBL_CURRENT_PHP_VERSION']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/UpgradeWizard/language/en_us.lang.php#L257
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/UpgradeWizard/language/en_us.lang.php#L261

['LBL_PICK_TZ_DESCRIPTION']

https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Users/language/en_us.lang.php#L260
https://github.com/salesagility/SuiteCRM/tree/v7.9.3/modules/Users/language/en_us.lang.php#L262

### PR DESCRIPTION
**Pull request by horus68**
## Description

Fixed Duplicated language strings present in the ver.7.9.3
- Included some little double spaces cleanup (almost all linked to duplicated strings)

Issue reference: #3898 

## Motivation and Context

Make it easier for translators!

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
@horus68 Nice work! Travis issue should now be resolved.

**Comment by horus68** [comment]
@samus-aran Why did you missed this one for 7.9.4? It was important for translations file compare!

**Comment by samus-aran** [comment]
Hi @horus68,

It wasn't missed for any particular reason bar that the point where we began the process of building the upgrade/installer packs there was a cut off of PRs.

Apologies it didn't get into this 7.9.4 release, but we're planning a 7.9.x and 7.8.x release pretty soon.

**Comment by horus68** [comment]
please merge it so we can download as a Hotfix!

**Comment by samus-aran** [comment]
Done :+1:

**Pull request merged**
