### PR TITLE
Fix #9482 - Only save update fields on utf encoding repair

### LINKED ISSUE #9482: 7.12.3 Repairing utf8 data Tool deleting email address
The UTF8 repair tool deleted a lot of email, I used it with the ROBO CLI version from the official changelog (https://docs.suitecrm.com/admin/releases/7.12.x/) 
It updated a lot of entry : 
image

I have those errors log : 
image

And after running the code, nearly all the updated entry had their email deleted.

After investigation, comparing SQL file before and after running the tool, in the table "email_addr_bean_rel" bunch of entry have been updated and marked as deleted (from field deleted=0 to deleted=1)

#### Issue
The repair tool, used in Synchronous mode with ROBO CLI, used the code in the officiel changelog : 
https://docs.suitecrm.com/admin/releases/7.12.x/

#### Steps to Reproduce

1. Just run the tool using ROBO CLI : ./vendor/bin/robo repair:normalize-record-encoding --sync-run

#### Context
My users hate the search engine which is not really good, was thinking it would help.

#### Your Environment

* SuiteCRM Version used : 7.12.3
* Browser name and version : Chrome latest 97.0.4692.99
* Environment name and version : PHPMyAdmin 4.9.9, PHP7.4
* Operating System and version : Linux

### PR DESCRIPTION
**Pull request by clemente-raposo**
## Description

- Fix encoding repair tool.
- see: https://github.com/salesagility/SuiteCRM/issues/9482

## Motivation and Context

- When saving some modules, the email addresses get removed because the emails weren't previously loaded
- see: https://github.com/salesagility/SuiteCRM/issues/9482

## How To Test This

- Add several email addresses to a contact.
- Add a badly formated string to a field in that contact
- run the utf8 repair
- check that the contact's email addresses are all there 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by simonr44 — DISMISSED** [review]

**Review by pankaj0882 — APPROVED** [review]
All Look good to me.

**Review by simonr44 — APPROVED** [review]
Looks good from here

**Review by johnM2401 — APPROVED** [review]
Looks good from a testing perspective.

Script corrects data where field type is appropriate and does not fire unnecessarily.
(ie: Workflows/Email Functionality is not fired)

Functionality works on all scannable modules, as well as Custom Fields/Modules of specific Type

No data appears to be lost & Users appear to still have access to their accounts, if they contained UTF8 characters in Username/Password

**Review by jack7anderson7 — APPROVED** [review]

**Review by pankaj0882 — COMMENTED** [review]
LGTM

**Pull request merged**
