### PR TITLE
Extend Core Modules Part 1 - Bean Factory and Globals

### PR DESCRIPTION
**Pull request by Jason-Dang**
## Description

Add the ability to define custom core module classes in a non-breaking way. 

The next steps will provide full coverage so that every part of the CRM respects custom core module classes.

This PR can be merged as is without implementing the next steps as it will not impact any existing functionality. 

### Changes:
- Add new global variables to store custom meta for core modules.
- Change get bean method to check for custom bean classes.
- Add method to dynamically load core and custom bean class files.
- Add method to get custom/core bean class.
- Add method to get custom object name.
- Add method to get core bean file.
- Add method to get custom bean file.
- Add method to get bean meta info as array using above methods.
- Cleanup Bean Factory code.

##### Part 2 - Replace Explicit Instantiations.
- Use Script to iterate through entire bean list and replace all occurrences of explicit instantiations of bean class with bean factory usage.
##### Part 3 - Replace Dynamic Instantiations.
   - Occurrences of `new {ModuleClass}()` replace with `\BeanFactory::newBean('{ModuleName}')`
- Replace dynamic instantiations of core modules' classes with Bean Factory usage.
   - Occurrences of `new $moduleClass()` etc. replace with `\BeanFactory::newBean('{ModuleName}')`.
##### Part 4 - Replace Module Class Name used as Table.
- Replace usages of the lower-cased module name as the module table name in some queries.
   - Occurrences where the module name is retrieved from `beanList` key(s), lower-cased and used as the table name, replace with `$bean->getTableName();` (may need to instantiate a bean in some cases or better yet add a static property and method for static info like table names etc.).

**Note:** *For the above the module directory or plural name needs to be used instead of the class/object name such as `Accounts` instead of `Account`.*

## Motivation and Context

Previously unable to extend almost all core module classes without breaking system in various areas. Those that could be extended, don't have their custom classes respected everywhere in the CRM.

## How To Test This

- Run unit tests with `./vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/unit/phpunit/data/BeanFactoryTest.php` (There is a flag in BeanFactoryTestCase to indicate whether to test all modules - default is `false`).
- Smoke test the entire CRM with and without extending core module classes.
- Extend core modules using new custom global arrays (Example below).
 **Custom module classes will only be respected by areas that use the Bean Factory.**

```
$customBeanList['Accounts'] = 'CustomAccount';
$customObjectList['Accounts'] = 'CustomAccount';
$customBeanFiles['Account'] = 'custom/modules/Accounts/CustomAccount.php';
```

OR

```
$customBeanList['Accounts'] = 'CustomAccount';
$customObjectList['Accounts'] = 'CustomAccount';
$customBeanFiles['CustomAccount'] = 'custom/modules/Accounts/CustomAccount.php';
```

*As above, either the core class name or custom class name can be used as the key for the bean file entry.*

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

Stonks Up

### CODE REVIEW

**Comment by Ally-Robins** [comment]
Is there an update on this?

This would be great to get in the next release as this would fix a bunch of issues we have at the moment

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  1
- data/BeanFactory.php  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by connorshea** [comment]
@Jason-Dang any updates? :)

**Comment by Jason-Dang** [comment]
Hey @connorshea,

I believe the Product team are still reviewing/assessing this (lots of regression testing etc.). In the meantime, I was thinking to add some tests for the BeanFactory but had to jump off that. I’ll be looking to push some up this by next week.

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- data/BeanFactory.php  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 3
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  8
- data/BeanFactory.php  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 5
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  9
- data/BeanFactory.php  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 5
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  9
- data/BeanFactory.php  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 5
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 5
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 5
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 3
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  1
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 3
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  1
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 3
           

Complexity increasing per file
==============================
- tests/unit/phpunit/data/BeanFactoryTest.php  1
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 3
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  10
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 3
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 1
           

Complexity increasing per file
==============================
- tests/SuiteCRM/Test/BeanFactoryTestCase.php  9
- tests/unit/phpunit/data/BeanFactoryTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4097849&bid=14096483)

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by Mac-Rae** [comment]
Whoop Whoop!! :tada:

**Comment by Jason-Dang** [comment]
ErrrMahGawd. Now what’s the status with PII?

**Comment by samus-aran** [comment]
@Jason-Dang We're happy with the concept, just reviewing & assessing

**Comment by Jason-Dang** [comment]
@samus-aran Sweet, let me know if there’s anything needed from my side.

**Comment by thomas-ashcraft** [comment]
Referencing $bean in the 'customCode' property at the *viewdefs.php files do not respect those custom beans.

**Pull request merged**
