### PR TITLE
FIXED - PHP Notice: A non well formed numeric value encountered #3577

### PR DESCRIPTION
**Pull request by jobst**
This is a fix for an issue: PHP Notice: A non well formed numeric value encountered in SUITECRM/include/ListView/ListViewSmarty.php on line [102|108] #3577

The problem here a different themes/templates using PIXEL or PERCENT as width.
This fix checks which one is used and decides what to do. 
In case PIXELS are used some adjustments are required
in case PERCENT is used nothing needs to be adjusted.

## Description

The issue leads to constant exception calls which cost time.
In the original code in this foreach loop

  foreach($this->displayColumns as $name => $params) {
         $totalWidth += $params['width'];
   }

when it encounters 10% there is a problem leading to loads of exceptions (which cost time).
The fixed proposed checks this and makes sure that no adjustment is required.

## Motivation and Context

Ugly code, the issue leads to constant exception calls which cost time, log file clogging
It also leads to incorrect values that change the layout.

## How To Test This

Use a responsive theme, then open any subpanel that has any lists, check the log file, its full of the error.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by jobst** [comment]
Fully agreed "SuiteCRM should be theme agnostic", but there are still themes AND modules that use hard-coded pixel values. Also there are many spelling mistake in the (width) definitions of lists within the subpanel, I have seen "20s" and "20p" for example. I just put the code there to get rid of the constant exceptions and also added a DEBUG message in PHP.

**Comment by daniel-samson** [comment]
If there are still themes and modules that use hard coded pixel values. We need to refactor them. I propose that to need to fix the issues instead of fixing the symptoms. We should at least fix the core and the modules. We can live with templates in the old themes which have hard coded values. However in SuiteP, we must use the SCSS to handle this correctly. Since the SuiteP will be the only theme.

We could still keep the columns and slots in the metadata. This could act as our universal unit.

Since this issue is related to the subpanels. Would you be willing to refactor just the hard coded parts for the subpanels?

**Comment by jobst** [comment]
@daniel-samson: It's not only subpanels, I only specified subpanels in "How to test this" as it is a sure way to find these. It's everywhere where there are list displayed, even on the Dashboard.

I added a debug statement to show how often this occurs and where it needs to be fixed.

Adding the code will 
  - get rid of the exceptions for now till it's all clean speeding up processing
  - help to find all of them, once the code clean you can scrap the added code.

**Comment by judgej** [comment]
A fresh install on 7.9.4 was wriggled with these errors (ListViewSubPanel.php, line 103). Applying this change removes all these errors for me.

**Comment by hoenie-ams** [comment]
thanks @jobst, this fixed it for me too (PHP 7.1).

**Comment by connorshea** [comment]
seems like this was fixed by #5162?

**Pull request closed without merging**
