### PR TITLE
Manage delegate mssql

### PR DESCRIPTION
**Pull request by urdhvatech**
The query fails while managing event delegates in MSSQL while Performing Manage Delegates & Manage Acceptances 

## Description
Issue No: #6851 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Fixed the accidentally committed files, looks good to me!

**Comment by willrennie** [comment]
@urdhvatech please see @code-ph0y comments, would be good to get this adjusted, re-checked and merged. Thanks!

**Comment by urdhvatech** [comment]
> 
> 
> @urdhvatech please see @code-ph0y comments, would be good to get this adjusted, re-checked and merged. Thanks!

Committed

**Comment by code-ph0y** [comment]
@urdhvatech - Thanks, this looks good now. It will just need another assess (testing) and it should be good to merge.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by sjuvonen-delta** [comment]
I suggest also adding " AND deleted=0" to affect only active items instead of writing also to deleted items.

**Pull request merged**
