### PR TITLE
Fix #8785 - Incorrect Syntax in install.php

### LINKED ISSUE #8785: Can't upload logo when perform install
Hi.
You miss a bracket in line 263 file install.php.

Now: 
`echo "<script>window.top.window.uploadLogoCallback" . json_encode($result) . ");</script>";`
Need: 
`echo "<script>window.top.window.uploadLogoCallback(" . json_encode($result) . ");</script>";`

Without this bracket browther throw error:
`Uncaught SyntaxError: Unexpected token '{'`
and can't finish upload process.

Best regards, Aleksandr. ;)

### PR DESCRIPTION
**Pull request by IBlasterus**
Hi.
You miss a bracket in line 263 file install.php.

Now:
echo "<script>window.top.window.uploadLogoCallback" . json_encode($result) . ");</script>";
Need:
echo "<script>window.top.window.uploadLogoCallback(" . json_encode($result) . ");</script>";

Without this bracket browther throw error:
Uncaught SyntaxError: Unexpected token '{'
and can't finish upload process.

Best regards, Aleksandr. ;)

### CODE REVIEW

**Comment by IBlasterus** [comment]
> license/cla
I don't understand. What should I do about it?

**Comment by samus-aran** [comment]
Hi @IBlasterus 

You can sign the CLA via the link provided on SuiteBot's comment. [Contributor License Agreement](https://cla.suitecrm.com/salesagility/SuiteCRM?pullRequest=8810)

Here is a little more information on the why :+1: https://docs.suitecrm.com/community/contributing-code/contributor-agreement/

**Comment by IBlasterus** [comment]
Ok. I did it.
What about _continuous-integration/travis-ci/pr_? What should I do about it?

**Comment by samus-aran** [comment]
> Ok. I did it.
> What about _continuous-integration/travis-ci/pr_? What should I do about it?

If you click on 'Details' it will usually take you to the build itself and it will provide you its status. https://travis-ci.org/github/salesagility/SuiteCRM/builds/705423276
However it appears to be all passing just the webhook is saying it's pending.

So theoretically you don't need to do anything as we still have the power to merge the PR. :+1:

**Review by mattlorimer — APPROVED** [review]

**Pull request merged**
