### PR TITLE
#3736 fix(Import) - Pre-set import settings can't be deleted

### PR DESCRIPTION
**Pull request by re8260**
Fix Issue [Pre-set import settings can't be deleted #3736](https://github.com/salesagility/SuiteCRM/issues/3736)

## Description
Send `import_module` parameter that require in Import controller.php `function action_mapping()`
```
        if (!isset($_REQUEST['import_module'])) {
            $_REQUEST['message'] = $mod_strings['LBL_ERROR_IMPORTS_NOT_SET_UP'];
            $this->view = 'error';
            $this->_processed = true;
            return; // there is no module to load
        }
```

Improve layout for long importer title

image

## How To Test This

1. Go to any entity with enabled import and open Import screen

1. create pre-set import

1. try to delete pre-set import

1. refresh the page f5

## Expected Behavior
The pre-set import should be deleted

## Actual Behavior
The pre-set import not deleted, and you will see it after page refresh

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

j

### CODE REVIEW

**Comment by willrennie** [comment]
Please can you amend the branch to hotfix-7.10.x rather than just 7.10.x? Also, can you clarify the reason for the removal of the width="10%" attribute? Thanks for your contribution. :D

**Comment by Dillon-Brown** [comment]
The ```7.10.x``` branches and ```hotfix-7.10.x``` branched don't have any conflicts so I've gone ahead and rebased this for you.

@willrennie I believe the width stuff is shown in the screenshot, Imo we should try to remove width anyway since it's deprecated.

**Comment by re8260** [comment]
Hi @willrennie ,
I remove the ` width="10%"` to fix label, here is the list before my fix:

image

**Comment by cameronblaikie** [comment]
AssEsSSeD :1st_place_medal:

**Comment by cameronblaikie** [comment]
Reassessed :+1:

**Pull request merged**
