### PR TITLE
Fix/email quick create

### PR DESCRIPTION
**Pull request by PedroErnst**
Adds Quick Create buttons to Email Imported Detail View.

## Description

The Quick Create buttons existed in the Email module in 7.8.x but are not present in 7.10.
This PR aims to replicate this functionality.

## 7.8.x
screenshot from 2018-04-02 12-02-45

## 7.10.x
image

## How To Test This

Go into the Email module
Import an Email
Create one of each records using the Quick Create buttons

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
I've seen users in the Forums extremely disappointed with losing Quick Create from Emails when they upgrade SuiteCRM beyond 7.8. I'm really glad we're getting this back into the product, it's essential to some user's workflows.

**Comment by Mausino** [comment]
@pgorod I've seen users also in the Forums disappointed from #4818 which was also beyond 7.8

But it's great that some functions (ideas) from old email system come back, like this one.

**Comment by JoeyJoeJoeJrShabadoo** [comment]
Very useful and essential functionality. Thanks for bringing this back.

**Comment by pgorod** [comment]
@PedroErnst how does the screen look if you turn off this option

`Admin` / `System Settings` / `Display actions within menus:`

Doesn't that show too many buttons? I always use my SuiteCRM with that option off, saves a _lot_ of clicks.

**Comment by PedroErnst** [comment]
Good point!

Here's a screenshot:

screenshot from 2018-05-08 09-06-35

**Comment by pgorod** [comment]
In a perfect world, I guess each company will have their workflow and always create the same sort of thing: an opportunity, or a contact, or whatever is their initial step in the sales funnel. So it would be nice to go without a dropdown, and just directly press the button you want - if you could only choose which button you want there.

On the other hand, having too many buttons with long names is not very nice, and it takes up a lot of space on top, and makes you have to scroll to see your data.

I don't know what is the best option, unless we would actually want to go and add options in the Settings screens, but I'm not sure we do...

**Comment by labcerouno** [comment]
This will be VERY useful! Thank you guys!

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
