### PR TITLE
added LoginAttempts and checks on the table for IP

### PR DESCRIPTION
**Pull request by MikeyJC**
## Description

Adds a new module and table (LoginAttempts) in order to track all login attempts to the system, whether they are successful or not, and the IP of the one trying to login. Also takes how many times that IP has failed to login when locking a user out.

## Motivation and Context

Provides auditing for login attempts made to the CRM, which can be expanded to include whitelisting certain users or IPs from the user lockout system or blacklisting specific IPs.

## How To Test This

Set the maxfailedlogins in sugar config and purposefully fail that many times, and it should lock you out as normal. All attempts will be logged in the database.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by gunnicom** [comment]
Nice idea. For white- and blacklisting would definitly be nice to white/blacklist whole networks.

**Comment by horus68** [comment]
Is this PR related with this one or can be considered an additional step
Add User lockout and user unlock options by JimMackin · Pull Request #2897 · salesagility/SuiteCRM - https://github.com/salesagility/SuiteCRM/pull/2897

**Comment by horus68** [comment]
@Dillon-Brown Is there a future plan to include this module proposal in the CRM?

**Comment by Dillon-Brown** [comment]
@horus68 Hmm, looks like there were some PR's merged into the feature/user_lockout branch but that branch never got merged back into develop. Will see if I can figure out why and update you here.

**Comment by Mac-Rae** [comment]
@Dillon-Brown Should this one be closed?

**Comment by Dillon-Brown** [comment]
@Mac-Rae Honestly, no idea lol. I asked around but since this is from 2017 nobody was sure why it wasn't merged. I would say keep it open since it doesn't have conflicts and seems like a valid feature. For now I'll just mark it as an enhancement.

**Comment by SinergiaCRM** [comment]
Hi, 

We are interested in this functionality. There is a similar proposal here #2897. However this one seems more straight to the point. It seems these PRs got lost somewhere in history.

Do you think it might be worth if we open a new PR using this code and we try to validate and include it?

Cheers

PS: I tag users I see active lately @serhiisamko091184 , @clemente-raposo , @jack7anderson7

**Pull request closed without merging**
