### PR TITLE
Fixed #5468 - Usage of the word DROP [Language issue]

### LINKED ISSUE #5468: Usage of the word DROP [Language issue]
#### Issue
How should we translate the term `Drop parenthesis`: to delete/remove or to place/include a parenthesis?
Can someone include a screen or situation where this is used? 

The string is from modules/AOR_Reports/language/en_us.lang.php
```
    'LBL_ADD_CHART' => 'Add chart',
    'LBL_ADD_PARENTHESIS' => 'Drop parenthesis',
```
and used in  modules/AOR_Reports/tpls/EditViewFooter.tpl
```
            <table id="aor_condition_parenthesis_table">
                <tbody id="aor_condition_parenthesis_btn" class="connectedSortableConditions">
                <tr class="parentheses-btn"><td class="condition-sortable-handle">
                    <span title="{$MOD.LBL_ADD_PARENTHESIS}">( ... ) {$MOD.LBL_ADD_PARENTHESIS}</span>
                    </td></tr>
                </tbody>
            </table>
```
https://github.com/salesagility/SuiteCRM/blob/c6bece6ab3acd29365f5fc663ba8f3cc359a986b/modules/AOR_Reports/tpls/EditViewFooter.tpl#L83

#### Context

Transtaltors are taken opposite directions on the translation. I think there is also a problem when the value says `Drop` but the key says Add ( `LBL_ADD_PARENTHESIS`). So there are some doubts if the programmers realize that when using that key they want to say "to remove"!
Either way, the key or the value should be changed to make this clear!

#### Your Environment

* SuiteCRM Version used: All

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Changes a label to give translators more context.

## Motivation and Context

Issue reference: #5468 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
But its DROP used as "DRAG and DROP" or as in "Delete"?
The actual wording also needs to be changed so translators don't make errors when translating (almost all of them did!)

**Comment by horus68** [comment]
@e-reeley maybe this is not a proper change. please read this:
https://github.com/salesagility/SuiteCRM/issues/5468#issuecomment-372951325

**Comment by e-reeley** [comment]
@horus68  Thankyou, so in this instance it is the case that the word 'Drop' was to imply that this would insert a parenthesis?

Maybe we could change this to read 'Insert Parenthesis'?

**Comment by horus68** [comment]
I didn't test this yet as it doesn't worked in 7.10.1 (!) and I don't have time to test in other systems.
2 different users as now confirmed this command works as an "insert". So this must be reviewed in detail in all versions.

**Comment by horus68** [comment]
@Dillon-Brown 
Please see this issue: https://github.com/salesagility/SuiteCRM/issues/5661

**Comment by horus68** [comment]
@Dillon-Brown please merge this one!

**Comment by Dillon-Brown** [comment]
Assessed by @Gyula

**Pull request merged**
