### PR TITLE
V8 API swagger.json

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Created a route for the V8 API swagger (Technically a missing feature / bug fix as this was available in the v8 API).

## Motivation and Context

Noticed the [V8 API docs](https://docs.suitecrm.com/developer/api/developer-setup-guide/getting-available-resources/) still point to old v8 api swagger.json which is likely to cause confusion.

## How To Test This

1. Setup the V8-API using the documentation.
2. Attempt a GET request to ```{{suitecrm.url}}/V8/meta/swagger.json```.
3. Check the response returns the valid V8 API swagger schema.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Docs PR: https://github.com/salesagility/SuiteDocs/pull/339

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/SuiteCRM/SuiteCRM/pullRequest?prid=4132104&bid=14183679)

**Pull request merged**
