### PR TITLE
Create composer.json in order to get SuiteCRM installable via Composer

### PR DESCRIPTION
**Pull request by PatchRanger**
[Composer](http://getcomposer.org) is a great tool, which is widely spread and is de-facto the standard of managing PHP dependencies.
This commit introduces Composer support - so now SuiteCRM could be installed via Composer, just add these lines to `composer.json` of your own project:
```
        "repositories": [
                {
                        "url": "https://github.com/salesagility/SuiteCRM.git",
                        "type": "git"
                }
        ],
        "require": {
                "salesagility/SuiteCRM": "*"
        }
```

### CODE REVIEW

**Comment by crmwa-vincent** [comment]
This is not working.

**Comment by crmwa-vincent** [comment]
Ni valid composer.json was found in any branch or tag of https://github.com/salesagility/SuiteCRM.git, could not load a package from it.

**Comment by chris001** [comment]
See #855 
Also https://github.com/butschster/sugarcrm_dev/blob/master/composer.json
Possibly @butschster could contribute his version of composer.json to suitecrm since he's also added it to sugarcrm ce.

**Comment by jakubpas** [comment]
check my last commit to develop branch

**Pull request closed without merging**
