### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by frnklnrd**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
Hi @frnklnrd,

Thank you for contributing. Can you please fill in the pull request template provided? So that it it is clear what your improvements are for.

Also we are trying to improve the code quality of SuiteCRM, would be able and willing to provide tests for  this pull request?

We have a guide on our documentation https://docs.suitecrm.com/developer/appendix-c---automated-testing/

If you need any assistance, please feel free to ask, I would be happy to help.

**Comment by pgorod** [comment]
Hi @frnklnrd!

I'd like to know if we can progress this in some way. Can you please explain what is in the PR?

**Comment by frnklnrd** [comment]
> 
> 
> Hi @frnklnrd!
> 
> I'd like to know if we can progress this in some way. Can you please explain what is in the PR?

Hello, I am not very experienced in contributing to repositories, but I will do my best to give them more contributions. I belong to a solution development team based on SuiteCRM, and we would like to provide you with other contributions.

**Comment by pgorod** [comment]
Ok, that's very nice to hear!

I think something you could try is making more separated PR's, one PR for each new functionality. Maybe that's why you didn't fill in the Issue template with text explaining what this does... it does a lot of different things :-)

We will help you learn how to contribute, don't worry about asking questions or doing something wrong. Everybody needs a time to learn.

Thanks in advance for your contributions!

**Comment by willrennie** [comment]
@frnklnrd We'll close this PR as it is a PR from master to master with no description of the reason for the PR or detailing what is included in the PR. Can re-open if updated/issues addressed.

**Pull request closed without merging**
