### PR TITLE
Fixed #7648 - Case Module: Description field not showing after Save and continue

### LINKED ISSUE #7648: Case Module: Description field not showing after Save and continue
#### Issue

Description Text field disappears when browsing (edit mode) or after button "Save and Continue"

#### Expected Behavior

Field should be available for edits as the other fields (Subject or Resolution)

#### Actual Behavior

2019-07-26 16_21_38-Microsoft Edge

#### Steps to Reproduce

1. Open Case
2. Edit mode (Description field is visible and editable)
3. Hit "Save and Continue" or "NEXT button"
4. Now description field do not show up (even if it has some value in it)

#### Your Environment

* SuiteCRM Version used: Version 7.11.6 (Clean full install, with sample data)
* Browser name and version: Google Chrome, v. 75.0.3770.142 (32 bits)
* Environment name and version (e.g. MySQL, PHP 7): Wamp server, Apache 2.4.18, MySQL 5.6.17, PHP 7.2.14
* Operating System and version: Windows 10

### PR DESCRIPTION
**Pull request by 604media**
Fixed #7648 - Case Module: Description field not showing after Save and continue

### CODE REVIEW

**Comment by horus68** [comment]
This PR fixes the issue for me!

**Comment by pgorod** [comment]
Since this basically seems to revert this commit https://github.com/salesagility/SuiteCRM/commit/a1b73dd4757d2d1eb856d5f8f674438ccddb55c8#diff-684b30d5c1843c7fb82d410cfcb009af by @PedroErnst, please check if doesn't reinstate the old bug in Issue #6081

**Comment by PedroErnst** [comment]
Hi @pgorod 

At a quick glance it doesn't seem to revert it, but rather to add the same lines, or very similar ones.

**Comment by pgorod** [comment]
I'm probably seeing something wrong here, but you moved the `TinyMCE` call inside the `if`, this moves it back out... ?

**Comment by Mac-Rae** [comment]
Assessed :+1: - Altho i did notice that my Description field changed from longtext to wysiwyg not sure if thats something related to the changes however

**Comment by ftoledo** [comment]
Hi all i have this issue under 7.11.13. is this patch was merged in that branch too?

thanks!

**Pull request merged**
