### PR TITLE
Map add to targetlist - json reply

### PR DESCRIPTION
**Pull request by gody01**
in maps after clicking add to target list label was stuck in "Processing ...".

## Description
json_encode reutrned error 6.
Simplified object for json, and now Proccessing chages to target list name...

## Motivation and Context
Label on Maps stucked in Processing after clicking on Add to targetlist...

## How To Test This
Go to Map module/display map. Click Add to target List. Label should change to Processing and after few seconds to name of the target list ...

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [ ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by chris001** [comment]
Could you change branch to `hotfix`

**Comment by gody01** [comment]
Hello,
I will try. It seems that now in this branch I managed to merged all other changes and pull request become too big.
Will need some days to sort this out.

**Comment by gody01** [comment]
Hello, pull request is now against hotfix branch.

**Comment by chris001** [comment]
@gody01  It'd be a good thing to also do the PR to the original repo so that the maintainer could fix this bug in the original module for all other users.  https://github.com/jjwdesign/JJWDesign-Google-Maps/pulls

**Comment by horus68** [comment]
@chris001 I don't think JJWDesign-Google-Maps github is in use anymore (Changes 05/25/2015 to release the latest version 2.1.20)
I also question if this is not a dead project.
The site its almost dead (latest blog from 2014 http://www.jjwdesign.com/blog-posts/ )
Twitter latest is from 2014: https://twitter.com/jjwdesign

On 2014 there was already some red alerts:
> There's been a lot of frustration, on my end, over what to do with the JJWDesign Google Maps Project for SugarCRM. This project has taken an amazing amount of time to develop and manage. Regardless, I've decided that I can't let it die. It must go on.

@salesagility must consider to keep this a as an "old" module, to fork it and keep on the development or use something else.

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by samus-aran** [comment]
Been resolved in 10a440c41a298dd5333368d8ae2f5a5f5a0cceb8

**Pull request closed without merging**
