### PR TITLE
Update DeleteRelationship.php

### PR DESCRIPTION
**Pull request by QuickCRM**
after_relationship_delete logic hooks are not called for M2M relationships
(for example Accounts -> SecurityGroups)

## Description

Create an after_relationship_delete for Accounts.
For example:
```
	public function after_relationship_delete(&$account,$event,$args)
	{
		if ($args['related_module'] =='SecurityGroups'){
			$GLOBALS['log']->fatal('after_relationship_delete logic hook');
		}
	}
```
Remove a security group from the account.
The logic hook is not called.

## Motivation and Context

after_relationship_delete logic hooks are not called for M2M relationships

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Please rebase this pull request to the hotfix-7.10.x branch as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Comment by QuickCRM** [comment]
Thanks.
The PR was created in 2017 !!!
And at that time, hotfix-7.8.x was the correct branch.

**Comment by Dillon-Brown** [comment]
Yeah, the process has changed quite a few times since then. At least now that we have the "Wrong Branch" label applied to the old PRs it'll be fairly simple to go back and fix conflicts, rebase, etc, to hopefully get them merged.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
