### PR TITLE
Composerify Zend Lucene

### PR DESCRIPTION
**Pull request by connorshea**
## Description
This builds on top of the Zend packages moved to Composer in #7672.

## Motivation and Context

This is part of #7605, and it removes a lot of unnecessary files from the repository. It also makes it easier to upgrade the package, etc.

## How To Test This
Make sure the tests pass and that the AOD_Index module still works.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

Kind of a breaking change?

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
Alright, I've replaced all the Zend Lucene Search files with placeholders.

**Comment by connorshea** [comment]
@Dillon-Brown I'm fairly certain we were already on Zend Lucene Search 1.12, based on the release date mentioned in the PHPDocs for the files. Since this also uses 1.12, I wouldn't expect any class name differences.

**Comment by willrennie** [comment]
Assessed as working. AOD indexes and search is working with this PR. :+1:

**Comment by samus-aran** [comment]
Hey @connorshea  :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Pull request merged**
