### PR TITLE
Fix #9895 - Workflow - Copying Formatted values of a multienum to another field

### LINKED ISSUE #9895: Workflow - Copying values of a multienum to another text field
In a Workflow action that copies the value of a multienum field to a Text field, the content copies are the internal values of the list instead of its labels. This is happening in both Modify Record and Calculate Field Action. Even if the last was has selected the option "Formatted value":
MultiSelectWF

MultiSelectWF2

#### Issue
In a workflow action always copies the internal values of a multienum field

#### Expected Behavior
It should copy the labels of the internal values. Also called "Formatted values" in a Calculate field action.

Same behavior as in any other Dropdown field.

#### Actual Behavior
The internal values are copied.

#### Possible Fix
Modify the code that copies those field types

#### Steps to Reproduce

1. Create  a Multienum field in Accounts module with a list that contains different internal values than label. (assign aor_date_options list)
2. Create a Workflow base in Accounts with an Calculate Field action that copies the formatted values of the multiselect field to a Description field
3. Create an Account and check the description field was filled by the internal values of the multienum field

#### Context
If a user most probably will want to use the Labels, or Formatted values.

It should work as it does with Dropdown fields.

#### Your Environment

* SuiteCRM Version used: 7.12.8
* Browser name and version: Versión 107.0.5304.121 (Build oficial) (64 bits)
* Environment name and version: MariaDB 10.6.5, PHP 7.4
* Operating System and version : KDE Neon 5.26

### PR DESCRIPTION
**Pull request by SinergiaCRM**
- Closes #9895 

## Description
There was an error inside the function that goes through the array of the items of the multienum field. It should be using the "$val" argument provided by the array_walk function instead of the value of the whole field.

## Motivation and Context

This is an error and should be fixed

## How To Test This
1. Create  a Multienum field in Accounts module with a list that contains different internal values than label. (assign aor_date_options list)
2. Create a Workflow base in Accounts with an Calculate Field action that copies the Formatted values of the multiselect field to a Description field
3. Create an Account and check the description field was filled by the Formatted values of the multienum field

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by SinergiaCRM** [comment]
> Hello, @SinergiaCRM
> 
> thanks for your contribution,
> 
> sorry, did not manage to replicate expected behaviour (currently testing SuiteCRM versions 7.12.8 and 7.13.0), workflow action parameters image with proposed fix image give me the same result (keys populated, not values): image I've just changed function getMultiEnumTranslated slightly to test: image image
> 
> Would you please correct me if I'm doing wrong steps with your fix and not getting right result? Thanks in advance.
> 
> Regards, Serhii

There was a missing "&" in our code, so the parameter can be passed by reference. 

Now it should be working.

**Comment by serhiisamko091184** [comment]
Hello @SinergiaCRM,

thanks for the update, yes, it's working. 

One minor thing - could you please synchronize your branch with hotfix to make it up-to-date?

Thanks in advance! 

Regards,
Serhii

**Comment by SinergiaCRM** [comment]
> Hello @SinergiaCRM,
> 
> thanks for the update, yes, it's working.
> 
> One minor thing - could you please synchronize your branch with hotfix to make it up-to-date?
> 
> Thanks in advance!
> 
> Regards, Serhii

HI @serhiisamko091184 ,

Done.

**Comment by serhiisamko091184** [comment]
Hello @SinergiaCRM, 

thanks for the quick reply and update, at the same time I see branches are not synced at the moment: 

image

image

Could you, please, check it one more time? 

Many thanks in advance! 

Regards,
Serhii

**Comment by SinergiaCRM** [comment]
> Hello @SinergiaCRM,
> 
> thanks for the quick reply and update, at the same time I see branches are not synced at the moment:
> 
> image
> 
> image
> 
> Could you, please, check it one more time?
> 
> Many thanks in advance!
> 
> Regards, Serhii

Yes, sorry. Now it should be fine.

**Comment by serhiisamko091184** [comment]
Yes, thanks a lot!

Regards,
Serhii

**Review by johnM2401 — APPROVED** [review]

**Pull request merged**
