### PR TITLE
Windows V8 API - Key Permissions & Content Length Header

### PR DESCRIPTION
**Pull request by Jason-Dang**
## Motivation and Context

To make the API work on windows, hard-coded changes are currently required to vendor package files as below.

- Set `$keyPermissionsCheck` to `false` in `Vendor/league/outh2-server/src/CryptKey.php` line 34
- Set `ob_get_length > 4`, in `Vendor/slim/slim/Slim/App.php` line 624

Obviously, this is not appropriate so this PR attempts to address the issues more appropriately.

By setting the `addContentLengthHeader` value to `false` in slim settings, it no longer attempts to set it's own header which gets around issues with the output buffer and BOMS. Ideally and now likely required, is that the header is set correctly within the API after the response has been fully processed and ready to return.

**Note:** After applying fixes a `composer install` will be required. 

## How To Test This

1. Install Suite and setup V8 API on windows environment. 
1. Make some API calls and see them fail.
1. Apply changes and try again.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Api/V8/Helper/OsHelper.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4754974&bid=15859128)

**Comment by Dillon-Brown** [comment]
@Jason-Dang PHP 5.6 parse error:

```
PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in Api/V8/Helper/OsHelper.php on line 10
```

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Api/V8/Helper/OsHelper.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4754974&bid=15859128)

**Comment by jan-waterdrop** [comment]
Hey guys, any news on this? Is it gonna be released? Right now I am doing it manually cause API doesnt work properly on Windows.

**Pull request closed without merging**
