### PR TITLE
Fix for https://github.com/salesagility/SuiteCRM/issues/1563

### PR DESCRIPTION
**Pull request by gunnicom**
If max is less than 5 return 5, else return null so rgraph handles the scaling.
Fix for #1563

### CODE REVIEW

**Comment by horus68** [comment]
@gunnicom I'm not on the dev team but can you commit this PR to the proper branch (hotfix)?

**Comment by gunnicom** [comment]
I wont do that until i know if its worth the work. Waiting months, then when asked for change the branch. Done that within minutes, than the pull request is not wanted. That is totally demotivating.
See: https://github.com/salesagility/SuiteCRM/pull/2324

**Comment by horus68** [comment]
I do understand your point I also have some PR from me waiting (or ignored!). 
My request was a personal one and after been browsing some old PR loking for fixes I could use for myself.

Sometimes a PR could not be approved by a particular reason but it could be picked up later in a new direction. **It can also be used by other users for their own installations.**
And maybe this one gets better luck and be merged!

That's why its relevant to have it on the Hotfix branch and avoid it be totally ignored!
Note: there has been many PR merged these days (since 7.4.4) so I hope the backlog will be reduced.

**Comment by gunnicom** [comment]
Many PRs are merged ... mostly SuiteP theme PRs, because instead of fixing old bugs suite adds a complete new theme with many new bugs instead of fixing old ones.
One more thing that holds my motivation from rising.
Enough said on this topic. Maybe one day i will start doing something again, but not now.

**Comment by Dillon-Brown** [comment]
@gunnicom If you can change this to branch hotfix-7.8.x we can get this merged. Thanks.

**Pull request merged**
