### PR TITLE
Combined copyright revision

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Updating all language files:

- Copyright revision
- if statement for valid entry point
- License text comments

Superseding #3348

## Motivation and Context

As described by @horus68  #3346 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
@horus68 New PR for the license fix. This uses the updated version of the license so it should resolve #3434. Let me know if there is anything I missed.

**Comment by horus68** [comment]
@Dillon-Brown looking good to me!

**Comment by horus68** [comment]
@Dillon-Brown 2 files are missing any copyright info:
\modules\Connectors\connectors\sources\ext\rest\facebook\language\en_us.lang.php
\modules\Connectors\connectors\sources\ext\rest\twitter\language\en_us.lang.php

Double spaces still present in the copyright text for HTML files (they are not edited on your PR):
\include\language\en_us.notify_template.html
\modules\Studio\language\en_us.Portal.html

**Comment by Dillon-Brown** [comment]
@horus68 Was it just those two html files you wanted updated for this PR? or did you want every .html file?

**Comment by horus68** [comment]
@Dillon-Brown My copyright request was just for language files.
Any other code file I consider is Salesagility decision to update or not, I don't monitor them!
In order this PR can be merged sooner please do not change any other code file besides language files in this PR.
Lets see if a simple edit and a simple PR can get merged soon (before 7.9 version)!

**Pull request merged**
