### PR TITLE
Fix #9574 - Avoid calling method in a static way

### LINKED ISSUE #9574: Still Can't Rename Modules
Hello. I hope your day is going well. I just wanted to reach out, because I am having an issue with renaming modules.

ISSUE
Renaming modules seems to be broken

EXPECTED BEHAVIOR
Renaming a module should change the modules name via the label functionality.

ACTUAL BEHAVIOR
A white screen is shown and PHP errors logged.

STEPS TO REPRODUCE
Open Admin
Got to “Rename Modules”
Attempt to switch the name of any core module
See the error
Context
Attempting to rename a module is no longer possible.

ALTERNATE STEPS TO REPRODUCE
Open Admin
Go to "Configure Module Menu Filters"
Edit module names and/or move filters around
Click "Save & Deploy"
See Blank screen and no changes were made

LOG FILE ERRORS

PHP Warning: Undefined array key “moduleList” in /bitnami/suitecrm/cache/smarty/templates_c/%%F60^F609237E%%_headerModuleList.tpl.php on line 28PHP

PHP Warning: Undefined array key “Administration” in /bitnami/suitecrm/cache/smarty/templates_c/%%F60^F609237E%%_headerModuleList.tpl.php on line 72PHP

PHP Warning: Undefined array key “Administration” in /bitnami/suitecrm/cache/smarty/templates_c/%%F60^F609237E%%_headerModuleList.tpl.php on line 215PHP

PHP Warning: Undefined array key “LBL_SEARCH_BUTTON” in /bitnami/suitecrm/cache/smarty/templates_c/%%F60^F609237E%%_headerModuleList.tpl.php on line 662PHP

PHP Fatal Error: Uncaught Error: Non-static method StudioParser::buildImageButtons() cannot be called statically in /bitnami/suitecrm/modules/Studio/wizards/RenameModules.php:339\nStack trace:\n#0 /bitnami suitecrm/modules/Studio/wizards/RenameModules.php(284): RenameModules->display()\n#1 /bitnami/suitecrm/modules/Studio/wizards/StudioWizard.php(94): RenameModules->process()\n#2 /bitnami/suitecrm/modules/Studio/wizards/StudioWizard.php(64): StudioWizard->process()\n#3 /bitnami/suitecrm/include/MVC/View/SugarView.php()823): include_once(’…’)\n#4 /bitnami/suitecrm/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile()\n#5 /bitnami/suitecrm/include/MVC/View/SugarView.php(210): ViewClassic->display()\n#6 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(432): SugarView->process()\n#7 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(363): SugarController->processView()\n#8 /bitnami/suitecrm/include/MVC/SugarApplication.php(101): SugarController->execute()\n#9 /bitnami/suitec…’, referer: http://192.168.0.25/index.php?module=Administration&action=index

TROUBLESHOOTING STEPS
I have confirmed that all of the permissions on/in the suitecrm directory are correct by running the following commands (daemon is the default user for the VM instance created by Bitnami here: https://bitnami.com/stack/suitecrm/virtual-machine):

sudo chown -R daemon:daemon .
sudo chmod -R 755 .
sudo chmod -R 775 cache custom modules themes data upload
sudo chmod 775 config_override.php 2>/dev/null

Reference: https://docs.suitecrm.com/admin/installation-guide/downloading-installing/#_copying_suitecrm_files_to_web_server

It appeared to be a similar issue to this one (https://github.com/salesagility/SuiteCRM/pull/9496); however, I have verified that my DropDownHelper.php config file has the correct, updated values

ENVIRONMENT
SuiteCRM Version used: 7.12.5
PHP 8.0.17
Chrome and Firefox
I am using the Bitnami VM found here: [SuiteCRM Virtual Machines](https://bitnami.com/stack/suitecrm/virtual-machine)
Are there any work-arounds or patches that I can install?

Any help you could provide would be greatly appreciated.

Thank you in advance!

### PR DESCRIPTION
**Pull request by wuan**
## Description
With Php 8 static calls require static methods.

When pressing save in the Configure Module Menu Filters editor the following fatal error has shown up:

```
[30-Mar-2023 07:54:05 UTC] PHP Fatal error:  Uncaught Error: Non-static method TabGroupHelper::saveTabGroups() cannot be called statically in /bitnami/suitecrm/modules/Studio/SaveTabs.php:48
Stack trace:
#0 /bitnami/suitecrm/include/MVC/View/SugarView.php(824): include_once()
#1 /bitnami/suitecrm/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile()
#2 /bitnami/suitecrm/include/MVC/View/SugarView.php(210): ViewClassic->display()
#3 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(432): SugarView->process()
#4 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(363): SugarController->processView()
#5 /bitnami/suitecrm/include/MVC/SugarApplication.php(101): SugarController->execute()
#6 /bitnami/suitecrm/index.php(52): SugarApplication->execute()
#7 {main}
  thrown in /bitnami/suitecrm/modules/Studio/SaveTabs.php on line 48
```

This PR fixes part of #9574 by enabling saving module edits.

## Motivation and Context
It allows to save edits in the Module Filter running on Php 8

## How To Test This
Open the Administration page via the menu. Click on "Configure Module Menu Filters", perform and changes and press "Save & Deploy". The application will not show that fatal error on Php 8 any more

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hello @wuan ,

thank you for the contribution,

could you, please, update your commit message to follow the formatting Fix #num - message. The number added in this case would be the number of the PR (10005).

You can see more information on raising bugs/ PR's here:
https://docs.suitecrm.com/community/contributing-code/bugs/

Thanks in advance.

Regards, 
Serhii

**Comment by wuan** [comment]
Hi @serhiisamko091184 ,

have just updated the commit accordingly.

Best regards
Andreas

**Comment by wuan** [comment]
Done @serhiisamko091184 , but in you example the commit points to the relevant issue, which would be #9574 in this case.

**Comment by pgorod** [comment]
Looking at the contents of [modules/Studio/TabGroups/TabGroupHelper.php](https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Studio/TabGroups/TabGroupHelper.php), I wonder if we shouldn't simply change the two methods' declarations there to **`static`** 

And remove that unused class member **`public $modules = array();`**

In other words, this inconsistency that PHP 8.0 complains about can be solved in either direction, and I was wonderig if in this case we shouldn't take the other way.

**Comment by wuan** [comment]
@pgorod I'm fine with going into both directions. The method `saveTabGroups(...)` could be made static as well.

**Comment by serhiisamko091184** [comment]
> Done @serhiisamko091184 , but in the example PR the commit points to the relevant issue, which would be #9574 in this case.

Thank you @wuan , well spotted, 
the case is to make commit message and title of PR consistent: 
image
Thanks for that in advance. 

Allow me to clarify, are additional changes going to be made into code of this PR due to conversation above? Or PR has been ready for review now?

**Comment by wuan** [comment]
@serhiisamko091184, now it should be fine. The PR is fine for me. Refactoring the class to use static methods can be done any time.

**Review by clemente-raposo — APPROVED** [review]

**Comment by chris001** [comment]
Good PR!

However, there's many, many, many more lines of code where the original developers of SugarCRM violated the PHP language and made a `static call to a non-static method`.

All of these non-static methods called statically should be re-defined as `static`, so that PHP 8 won't continue to crash with `FATAL` error.

**Review by johnM2401 — APPROVED** [review]
LGTM, checked in php82 and php72, works as intended!

**Comment by isleshocky77** [comment]
Just a heads up, check out #7902 and #7048 which are probably related.

**Pull request merged**
