### PR TITLE
Move Zend, Smarty to composer, Introduce psr-4, add XTemplate, Sugar_Logger to psr-4

### PR DESCRIPTION
**Pull request by jakubpas**
The commit introduces moving external libraries to composer and also psr-4 in SuiteCRM
This will help keeping CRM code more light, and also help update external libraries to newer - more up to date versions. Also this will help to install SuiteCRM by packagist.
The change does not break compatibility

## Description

- introduces psr-4 autoloading for Sugar stuff and proper namespacing. As an example two class were moved to /src: simple one file XTemplate class  and more complex subdirectory, multifile  Sugar_Logger. 

- reduces unnecessary "require" directives and allow easier code refactoring in modern IDE’s

- allows to update in future old vendor's software like Zend libraries, recaptcha, tcpdf and so on & move it to the vendor dir.

- composer.json cleanup to help installation from packagist

Zend and Smarty libs were removed and replaced with composer. Some “require” directives for zend and other classes are removed as they are now autoloaded. Minor fixes in .gitignore. 

## Motivation and Context

This change is step forward to modern php programing techniques and standards in SuiteCRM. The aim is to go as far as it possible without breaking compatibility with older versions. 

## How To Test This

composer install

then run installator normally

also 

cd tests
../vendor/bin/phpunit

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x ] My change requires a change to the documentation.
- [x ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by HenrySmolin** [comment]
Good job

**Comment by chris001** [comment]
Looks very good.  Could you also update your packagist repo.

**Comment by jakubpas** [comment]
Packagist updated. You can install app by: 
`composer create-project jakubpas/suitecrm suitecrm --stability="dev"`

**Comment by chris001** [comment]
Three things I noticed with smarty package.
1. Sugar added about 42 more plugins into the `smarty/plugins` folder.  Since they don't come with the standard smarty package, they would have to be added there or copied to a folder for application defined plugins where smarty could autoload them from, so that when smarty package is update, composer doesn't overwrite the sugar smarty plugins.
2. Sugar added `Sugar_Smarty.php` to extend the `Smarty` class, this is good practice, yet it's missing from the vendor package obviously, it needs to be brought in in an upgrade safe way.  And, in an act of bad coding practice, they renamed the vendor class `Smarty_Compiler` to `Sugar_Smarty_Compiler`, renamed the file `Smarty_compiler.class.php` to `Sugar_Smarty_compiler.class.php`, only to add three lines for the purpose of handling another type, `theme_template`.  Probably not the way Smarty recommends adding template types.
3. Need to find some way of removing `include/Smarty` - it is no longer needed when composer installs the `smarty` vendor package from packagist - while obviously putting the added smarty plugins in a safe folder, because composer erases the package before updating it.   And decide on how to retain the added code from `Sugar_Smarty_Compiler.class.php`. without actually modifying the vendor library package's class name or file name.  Probably have to extend the base class `Smarty_Compiler.class.php` instead of rename it!

**Comment by jakubpas** [comment]
1. In my solution include/Smarty contains sugar specific plugins so no way to overwrite when updating smarty in composer.
2. The same for Sugar_Smarty
3. Sugar_Smarty uses $compiler_file to override default vendor compiler.
```
class Sugar_Smarty extends Smarty
{
    var $compiler_file = 'include/Smarty/Sugar_Smarty_Compiler.class.php';
    var $compiler_class = 'Sugar_Smarty_Compiler';
```
You may need to alter the compiler class when upgrading to much higher version in composer. So far I didn't find any better solution to alter those three lines you mentioned to keep templates right. Not without breaking compatibility. Other solution could be to user traits to inherite both Smarty and Smarty_Compiler class but this requres higher version of php - I guess 5.4 and SuiteCRM is backward compatibile up to 5.3 now.

**Comment by chris001** [comment]
Maybe now is a good time to look at upgrading to smarty 3.  Smarty 3.1.28 introduced run time template inheritance!  This would let us un-hack Sugar's cringeworthy modifications out of the vendor class `Smarty_Compiler.class.php`.
Maybe `require smarty/smarty-dev` is the way to go.  It installs `smarty`, `smarty-phpunit`, and `smarty-lexer`.
See more: https://packagist.org/packages/smarty/smarty

**Comment by jakubpas** [comment]
Looks like whiele this pull request was waiting there were some other pushes and conflicts appeared. Will you solve it or should I create another pull request?

**Comment by chris001** [comment]
Hello @samus-aran @mattlorimer @salesagility
Have tested this PR and it's working. A very good start toward full use of PSR-4 composer everywhere in the application.  Any comments about why you haven't merged yet.

**Comment by chris001** [comment]
@jakubpas Could you update this PR, by adding to your develop branch, or fast fowarding it, or whatever, to get the new versions of the recently merged files from the Emails module listed above.

**Comment by chris001** [comment]
Can we have comments from @daniel-samson @samus-aran @salesagility @gregsoper @mattlorimer about this PR.  Why isn't it merged yet.  What else do you need.  Thank you.

**Comment by opravil-jan** [comment]
Why this PR waiting to be merged to master? I think it is great improvement and should be merged? Can anyone give us an explanation, please?

**Comment by opravil-jan** [comment]
Why this PR waiting to be merged to master? I think it is great improvement and should be merged? Can anyone give us an explanation, please?

**Comment by jakubpas** [comment]
Sure!

**Comment by pgorod** [comment]
Hey guys, it's great to see this moving forward, thanks. 🥇 

I'm not really a PHP guy, can anybody please explain to me the difference between this PR here and the suggestion in Issue #3593 ?

**Comment by daniel-samson** [comment]
I am not sure @pgorod . But it is a closed issue.

Going forward we can look at this pull request. I have some minor changes to make.

**Comment by pgorod** [comment]
It's closed, but only because it's a suggestion that was moved to Trello :-)

I think that one uses a crawler to go through the entire codebase and record the locations of files and classes, and functions. Then it works without any `require`'s at all, I think.

This one here is to big for me to tell how it works :-)

**Comment by connorshea** [comment]
I'm pretty sure all of these have been resolved (or will be resolved by other PRs) now except for XTemplate. So we can probably close it.

**Comment by Dillon-Brown** [comment]
Indeed looks like everything mentioned here has been completed except for XTemplate (Which imo we should just remove) and SugarLogger (It looks like a PSR-3 SuiteLogger was added into lib/Utility but seems unused... Worth looking into).

It's a shame we never managed to get this merged in but nonetheless thanks for the contribution and for helping to push SuiteCRM in the right direction. Will close this for now unless anyone thinks there is value in keeping it open.

**Comment by chris001** [comment]
Why wasn't done the desired minor changes/rebasing on this PR from @jakubpas and merged 2.5 years ago, as would've saved a lot of time effort and resources by upgrading to the significant benefits of composer PSR-4 far sooner...?!

**Comment by connorshea** [comment]
Sorry, no time machine 🤷‍♂

**Comment by chris001** [comment]
More of a question for @daniel-samson

**Comment by connorshea** [comment]
In my experience it's far easier to get things merged when they're done in smaller pieces, trying to ram it in all at once just makes it harder to review, harder to test, harder to merge, harder to keep up to date, and more likely to introduce bugs.

That'd be my explanation, anyway.

**Comment by chris001** [comment]
That's a fine way of doing them, but at the time Daniel said it was good and just needed to make minor changes and rebase, asked for permission to modify, got it, and then... crickets

**Pull request closed without merging**
