### PR TITLE
Fixed #70.  This Is fix problem with AOP updates when case is created.

### LINKED ISSUE #70: AOP update when case is created
AOP updates a case with the initial case message/email when sent via email.

### PR DESCRIPTION
**Pull request by shogunpol**
## Description

The  saveUpdate() method from modules/AOP_Case_Events/CaseEventsHook.php needs aditional attributes in condition statement for checking the null/empty instances which is case when new is created. related issue  #70 

when the case is created via email, open the case and if case update/Case Updates Threaded: is empty, it means the case is created in correct. However if you see in Case Updates Threaded: replicated information from details of the case, means: bug still exist.

## Motivation and Context

Solve issue with AOP, when case is created? Prevent duplication of information in case module
## How To Test This

when the case is created via email, open the case and if case update/Case Updates Threaded: is empty, it means the case is created in correct. However if you see in Case Updates Threaded: replicated information from details of the case, means: bug still exist.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
@shogunpol can you please update the Pull Request with 'how to test' and what the issue is - even if it is a copy and paste from the issue description itself.  

If you supply as much info as possible people can test it quicker.  Thanks :smile:

**Comment by shogunpol** [comment]
Dear Ahley

Done

Jerzy

--
  Jerzy Brzezinski
  jerzy.brzezinski@salesagility.com



On Mon, Aug 1, 2016, at 11:57 AM, Ashley Nicolson wrote:
> @shogunpol[1] can you please update the Pull Request with 'how to
> test' and what the issue is - even if it is a copy and paste from the
> issue description itself.
> If you supply as much info as possible people can test it quicker.
> Thanks 😄
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>

Links:

  1. https://github.com/shogunpol
  2. https://github.com/salesagility/SuiteCRM/pull/1795#issuecomment-236550751

**Comment by Dillon-Brown** [comment]
Please resolve conflicts or tick the box allowing us to resolve them for you. Thanks.

**Comment by ijdavie** [comment]
This issue that this PR addresses has been fixed and now can not be replicated,

**Pull request closed without merging**
