### PR TITLE
Fix #4043 - Workflows with operator 'Equal To' on datetime fields not working properly

### LINKED ISSUE #4043: Workflows with operator 'Equal To' on datetime fields not working properly
Workflows with conditions of type `Start Date` `Equal To` `Now` `+` `5 Minut` never reaches the condition.

#### Steps to Reproduce

1. Create a new workflow with the following parameters
  - WorkFlow Module: Meetings
  - Run: Only In The Scheduler
  - Run On: All Records
  - Repeated Runs: NO
  - Add the following condition
    + Module: Meetings
    + Field: Start Date
    + Operator: Equal To
    + Type: Date
    + Value: Now + 5 Minut
  - Add the following action
    + Select Action: Send Email
    + Email Template: Create new email template with some text.
    + To Email: some_email@example.com
2. Save and activate the workflow.
3. Create a new meeting with a future start_date
4. Note that 5 minutes before the start date of the meeting, the emai is not sent.

#### Context

We want to send a custom email some time before (or after) of the start date of a meeting.

#### Issue

The AOW_WorkFlow build_query_where() method builds the resulting query considering the secconds on datetime fields. So if you create the workflow described on the `Steps to Reproduce` section you obtain a where condition like:

```
meetings.date_start = DATE_ADD(UTC_TIMESTAMP(), INTERVAL - 5 minute)
```

#### Expected Behavior

Receive an email 5 minutes before of the start_date of a Meeting.

#### Actual Behavior

The flow condition is never satisfied, so email is never sent.

#### Possible Fix

We have modified the build_query_where() method to ignore the secconds when comparing the date fields. So now the obtained query for the previos workflow would be:

```
DATE_FORMAT(meetings.date_start, '%Y-%m-%d %H:%i') = DATE_FORMAT(DATE_ADD(UTC_TIMESTAMP(), INTERVAL - 5 minute), '%Y-%m-%d %H:%i')
```

This is only tested using MySQL. We don't know if this fix works for MSSQL installations.

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Versión 59.0.3071.115 (Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.57 and PHP 5.5.9
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04.5 LTS

### PR DESCRIPTION
**Pull request by sanchezfauste**
Workflows with conditions of type `Start Date` `Equal To` `Now` `+` `5 Minut` never reaches the condition.

## Description

The AOW_WorkFlow build_query_where() method builds the resulting query considering the secconds on datetime fields. So if you create the workflow described on the `Steps to Reproduce` section you obtain a where condition like:

```
meetings.date_start = DATE_ADD(UTC_TIMESTAMP(), INTERVAL - 5 minute)
```

We have modified the build_query_where() method to ignore the secconds when comparing the date fields. So now the obtained query for the previos workflow would be:

```
DATE_FORMAT(meetings.date_start, '%Y-%m-%d %H:%i') = DATE_FORMAT(DATE_ADD(UTC_TIMESTAMP(), INTERVAL - 5 minute), '%Y-%m-%d %H:%i')
```

This is only tested using MySQL. We don't know if this fix works for MSSQL installations.

See issue #4043

## Motivation and Context

We want to send a custom email some time before (or after) of the start date of a meeting.

## How To Test This

1. Create a new workflow with the following parameters
  - WorkFlow Module: Meetings
  - Run: Only In The Scheduler
  - Run On: All Records
  - Repeated Runs: NO
  - Add the following condition
    + Module: Meetings
    + Field: Start Date
    + Operator: Equal To
    + Type: Date
    + Value: Now + 5 Minut
  - Add the following action
    + Select Action: Send Email
    + Email Template: Create new email template with some text.
    + To Email: some_email@example.com
2. Save and activate the workflow.
3. Create a new meeting with a future start_date
4. Note that 5 minutes before the start date of the meeting, the emai is not sent.
5. Apply the changes and see that now the email is received.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Please rebase this pull request onto hotfix-7.10.x as the hotfix branch is now specifically for 7.11.x issues.

Please take a look at our contribution guidelines for more information.

**Comment by sanchezfauste** [comment]
> Please rebase this pull request onto hotfix-7.10.x as the hotfix branch is now specifically for 7.11.x issues.
> 
> Please take a look at our contribution guidelines for more information.

Done, but needs to be tested properly.

**Comment by samus-aran** [comment]
Hey @sanchezfauste  :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Comment by sanchezfauste** [comment]
Hi @samus-aran,

I have submitted the form. Thank you !

**Pull request merged**
