### PR TITLE
Removed the License badge from README.md

### PR DESCRIPTION
**Pull request by helios1101**
## Description

As Github already displays the license in top-right along with what type of license it is irrelevant to include the licence badge again in README.md

## Motivation and Context

To avoid the information giving twice.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
I like the readme badge :(

**Comment by cameronblaikie** [comment]
Me too :( @Dillon-Brown

**Comment by Dillon-Brown** [comment]
Imo I think this would be worth keeping. While we do indeed see the license at the top of the repo, we'd probably want people pulling down the repo to see it when going through the README.

**Comment by helios1101** [comment]
License badge do look nice, but repeating the same information at two places doesn't look good.
Eg. If the sponsor button is present at the top, they will no sense of repeating the badge again in the readme. My opinion, open for discussion.

**Comment by Mac-Rae** [comment]
Hi @helios1101, The readme can be utilised in more just GitHub, for example opening the readme in a .md compatible text editor/viewer will show the licence badge. Realistically this is not requested as most if not all files have their licences printed at the top however to users I feel this offers a user-friendly experience.

**Comment by Mac-Rae** [comment]
I am closing this pull request due to receiving no response from the author. Please feel free to comment if you believe this PR should be reopened

**Pull request closed without merging**
