### PR TITLE
Error resetting modules  #7827

### PR DESCRIPTION
**Pull request by urdhvatech**
#7827 Error resetting modules

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jack7anderson7** [comment]
Hi @urdhvatech,

Could you please squash your commits into a single commit.

Thanks,
Jack

**Comment by urdhvatech** [comment]
> Hi @urdhvatech,
> 
> Could you please squash your commits into a single commit.
> 
> Thanks, Jack

Sorry, I am not sure what to do.

**Comment by jack7anderson7** [comment]
> > Hi @urdhvatech,
> > Could you please squash your commits into a single commit.
> > Thanks, Jack
> 
> Sorry, I am not sure what to do.

No worries, I have updated the PR.

Thanks,
Jack

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Review by jack7anderson7 — APPROVED** [review]

**Pull request merged**
