### PR TITLE
Calculate list price according to cost and utility values

### PR DESCRIPTION
**Pull request by davidbqzt**
## Description
Added a feature on Quotes modues to use or modify the cost of a product or service and specify an ammount or percentage of utility and calculate the value of List Price according to the cost and utility specified.

1. The procuct/service cost field have been made visible, this one was present but hidden.
2. Add, fields for utility and utility type (amount or percentage) similar to discount and discount type fields.
3. Utility type is like Discount type, a html select element to choose between Amount or Percentage, and depending on the type selected the list price will be calculated in two different ways.
4. Utility is a number, that is expected to represent an amount or a percentage that should be added to the cost in order to obtain the list price.
5. If Utility Type is amount then the list price will be the cost plus the utility.
6. If Utility Type is amount and the utility value is negative it's absolute value must not be greater than the cost, calculateLine function will change the value automaticly
7. If Utility Type is percentage, the list price will be calculated according to this formula:
> ListPrice = Cost /(1-(Utility/100))
- The value of Utility could be negative or positive between -1000 to 90
- Any value greater than 90 will be changed to 90 when calculateLine is executed
8. The field list price is now readonly and calculateLine will calculate its value.
9. All others fields will preserve its function as before.
10. All fields have been reorganized to fit the new fields.
11. Also some lines have been changed only to fit SuiteCRM's coding standards.

## Motivation and Context

Not all the products and services has a static cost all the times, some change from day to day or according to the provider that the company finds every time. Change constantly the cost of the product is difficult and not useful as it not allows a company to compare utility obtain in every sell.
Calculate the list price in a spreadsheet and copy it to quote module is a double process, calculated by hand (even in a calculator) could lead to errors, so leave this function to SuiteCRM could help to automate the process and reduce mistakes, even later on a company could create a report to calculate how much profit a sell or a group of sales have been earned.
 
## How To Test This

Create a few products, assign a cost and a list price.
Create a new quote
Add some products and services
The value of product's cost should be recovered from DB with all the other product's information as before.
Change the product's cost, assign an utility and choose an utility type, as you leave any of this fields you should see how list price and total price changes.
Change utility type between Percentage and Amount, it should change the amount on list price and all the other fields.
Compare the values to be sure that calculations have been made correctly as explained on point 6 and 7.
Save the quote, open it or edit it again, all values should be stored and recovered as you saved it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My change requires a change to the documentation.
- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [X] I have read the [**How to Contribute**]
(https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
I have just one question on how to translate "Utility" as this could be difficult in some languages.
Can you give an example of real usage? Maybe an alternative wording or even some translation for other languages?

**Comment by davidbqzt** [comment]
Hi @horus68 

Some synonyms for Utility could be profit, revenue or margin.

In spanish, people refer to this as utilidad, margen, ganancia.

The feature comes from a customer who request it, but I have think about it before, as I have see some companies who do it like that, and even I do it in that way.
The formula that I used to calculate the list price when utility price is Percentage was taken from a common formula used in my business and business of partners and customers, . I found two articles that describes it, but are in spanish, I can't found it in english:
https://clickbalance.com/blog/contabilidad-y-administracion/como-definir-el-margen-de-ganancia-de-un-producto/
https://www.administrabien.com/precio-de-productos-costo-mas-utilidad/

Hope that helps.

**Comment by horus68** [comment]
Thanks, I understand it now.

**Comment by Mac-Rae** [comment]
Please resolve the conflicts on this pull request bringing it up to date.

**Comment by davidbqzt** [comment]
Hi @Mac-Rae,

I took a look to Codacy, but it's the first time I've work with Codacy, so I'm not sure if I do it right.

I check all the issues on Codacy, made changes on my sources and commit it to my repo.

Let me know if there is something else that must be done.

Regards.

David

**Comment by serhiisamko091184** [comment]
Hello, @davidbqzt 

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @davidbqzt 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

**Pull request closed without merging**
