### PR TITLE
Fix #10237 - Range validation in inline edition

### LINKED ISSUE #10237: Inline edition do not validate ranges
#### Issue

Range validation does not work on an integer field in inline edition, in which a numerical range has been defined.
The problem occurs in the inline edition of any numerical field with a defined maximum and/or minimum: Inline edition does not validate that the new value is a value within the range.

However, it works correctly when editing from the edit view.

#### Expected Behavior

Validation should also be applied in inline edition.

#### Steps to Reproduce

1. In Studio, create an integer field, with Min Value 1 and Max Value 15
2. Add the field to the detail and list view and verify that we can add a value outside the defined range.
3. Verify that it works correctly in the editing view.

#### Your Environment

* SuiteCRM Version used: 7.14.0
* Browser name and version: Chrome Version 118.0.5993.70 (64-bit)
* Environment name and version: MySQL, PHP 7
* Operating System and version: Ubuntu 22.04.3

### PR DESCRIPTION
**Pull request by SinergiaCRM**
- Closes #10237

## Description

The inline edition did not validate that the new value is within the range of a numerical field with a defined maximum and/or minimum.

The implemented solution has two parts:
- **controller.php**: fills in ```$validate_array``` the parameters for the range validation: the ```type``` as the validation type (```range```), ```max``` and ```min```
- **inlineEditing.js**: checks this validation type and for fields to validate as ```range```, call the defined function ```addToValidateRange```

## How To Test This

1. In Studio, create an integer field, with Min Value 1 and Max Value 15
2. Add the field to the detail and list view.
3. Verify that we can not add a value outside the defined range.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hello @SinergiaCRM,

thanks for your contribution, 

would you be so kind to sign the CLA for the user who commited changes?

image

Thanks in advance!

**Comment by serhiisamko091184** [comment]
Hey @SinergiaCRM, 

Thanks for the changes! 

Regards, 
Serhii

**Review by clemente-raposo — APPROVED** [review]

**Comment by SinergiaCRM** [comment]
> Hey Folks!
> 
> Largely looking good, but found one possible issue on this PR.
> 
> If the user enters a text value into a numerical field while inline-editing, it is now being accepted.
> 
> See as follows:
> 
> When performed on 7.14.1 with this fix PR applied, it appears to accept Text values and convert them to simply "0":
> 
> inlineText [ inlineText ](https://user-images.githubusercontent.com/13675281/279081775-18b69bb3-40c2-40fb-9098-d8d43d70f5e0.gif) [ ](https://user-images.githubusercontent.com/13675281/279081775-18b69bb3-40c2-40fb-9098-d8d43d70f5e0.gif)
> 
> Whereas, on a vanilla 7.14.1 instance, it does not accept the text values:
> 
> inlineText714 [ inlineText714 ](https://user-images.githubusercontent.com/13675281/279081807-87984934-caa5-4ae7-b1e3-66de5a034cdb.gif) [ ](https://user-images.githubusercontent.com/13675281/279081807-87984934-caa5-4ae7-b1e3-66de5a034cdb.gif)
> 
> Would you be able to have a look?
> 
> Thanks!

We will have a look. Thanks.

**Comment by SinergiaCRM** [comment]
I just committed a change in order to validate int values ​​in range fields.
Sorry for taking so long to reply

**Comment by SinergiaCRM** [comment]
Ok, I also think it's better include all this changes in your PR.

I close this PR

Thanks!

**Comment by pgorod** [comment]
By the way, something very useful I learned when doing this: all the magic happens with this bit of code:

```
            $javascript = new javascript();
            $javascript->setFormName('EditView'); // this stays the same even when inline editing from List views
            $javascript->setSugarBean($bean);
            $javascript->addField($field, $fielddef['required'], '');
            $js =$javascript->getScript(showScriptTag: true, clearValidateFields: false);
```
I had never noticed this javascript Class (which lives in `include/javascript/javascript.php`) but it is used all over the place and is quite simple and useful to use. It basically handles the javascript associated with fields. Using it I am able to reuse all the existing code for validations without having to work through all the cases.

Just FYI :-)

**Pull request closed without merging**
