### PR TITLE
Rebrand the Search Filter in Modules

### PR DESCRIPTION
**Pull request by kdjmonaghan**
SCRM-205 - Replace occurrences of "Search" with "Filter" where the user could see them, especially in studio.
SCRM-204 - Remove "Search" from listview header.
Remove duplicated deceleration of 'LBL_ADVANCED_SEARCH' in en_us.lang.php

## Description

Changing labels for "Search" to "Filter".
Removing "Search" from List View headers.
Remove duplicate deceleration of 'LBL_ADVANCED_SEARCH' (Issue #2979)

## Motivation and Context

Occurrences of "Search" had to be replaced with "Filter" for the next release.
"Search"  had to be removed from the List View headers.

## How To Test This

Browse to locations "Search" was located previously such as Studio.
View any list view page and see if "Search" is included in the header.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@kdjmonaghan any special reason for this rebranding?

**Comment by mattlorimer** [comment]
really to differentiate between searching across the application (global search), to filtering data in modules, in line with the changes in 7.8

**Comment by horus68** [comment]
@kdjmonaghan after rebranding LBL_ADVANCED_SEARCH is also duplicated (include file)
See https://github.com/salesagility/SuiteCRM/issues/2979

**Comment by horus68** [comment]
@mattlorimer I would prefer to have the key also renamed, not just the value.
Else it will be difficult to know in some months (not just for translators on language files but also for programmers on the php files) when things like 'LBL_ADVANCED_SEARCH' is to be used as filter or as search
Examples on language files for 'LBL_ADVANCED_SEARCH' : 
"install" language file
or modules: SugarFeed / Home / Administration /

**Comment by samus-aran** [comment]
The decision to still maintain both the labels LBL_BASIC_SEARCH and LBL_ADVANCED_SEARCH currently is due to the extensiveness that these words play through the core including names of views and actions.  The next goal is to refactor those views and actions aswell, but will require thorough testing.  So the merge will only include KEYs which have minor impact on the system and the above action will be scheduled as a high TO DO to not increase technical debt.

**Pull request merged**
