### PR TITLE
hotfix merge

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Hotfix-7.10.x -> hotfix merge.

## Motivation and Context

Mostly want to get this merged asap for the statechecker/statesaver changes. 

## How To Test This

See Travis.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 92
- Added 73
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/SuiteCRM/SuiteCRM/pullRequest?prid=4526776&bid=15241755)

**Comment by connorshea** [comment]
🙄 Travis isn't working again

**Comment by Dillon-Brown** [comment]
>  Travis isn't working again

Yeah seems to be dead on hotfix for some reason :(.

**Comment by connorshea** [comment]
@Dillon-Brown have you tried closing this PR and opening a new one?

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 98
- Added 84
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/samus-aran/SuiteCRM/pullRequest?prid=4526776&bid=15241755)

**Pull request closed without merging**
