### PR TITLE
Fix Additional Details in Calendar for Tasks

### PR DESCRIPTION
**Pull request by samus-aran**
This fixes my reported bug for not translating the dropdown for Priority and Status for Tasks Module in Calendar when clicking the Additional Details button

### CODE REVIEW

**Comment by horus68** [comment]
@samus-aran can you please double check this to be closed or merged (some PR/issues related)

**Comment by horus68** [comment]
@mikebeck @pgorod  this PR has "Conflicting files".
You solution didn't work for me
In 7.7.8 only "Priority" isn't translated
2016-12-19 20_31_02-suitecrmhotfix

Related issue: https://github.com/salesagility/SuiteCRM/issues/1109

**Comment by pgorod** [comment]
@horus68 on my system running 7.7.8 everything works fine, all fields appear translated correctly.

This is without applying any fix, without changing any files as done in this PR: I'm just using the normal SuiteCRM system as it is shipped. I wonder what could be happening here...

**Comment by horus68** [comment]
I "hate" when it work for others! :)

**Comment by horus68** [comment]
Its working for me now too. I was testing on an old hotfix that was not really updated to newest version.
@shogunpol this PR should be closed as solved (same as the issues related)

**Comment by shogunpol** [comment]
@horus68 , @pgorod - thanks for testing an issue, due to your opinion i will close PR and issue.

**Pull request closed without merging**
