### PR TITLE
Updated CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kichloo**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Can you please change the target branch to 7.10.x ?
You can do it in this page

**Comment by kichloo** [comment]
@horus68 Done.

**Comment by horus68** [comment]
Something wrong on your side: you need to have your local fork synchronized with the branch you plan to submit a PR before making any improvements to your files. This is way you are seeing so many files to change on this PR.
You need to rebase your branch to t.10.x branch before start editing and then submit a PR

**Comment by kichloo** [comment]
I am a beginner. Can you please explain?
Thanks

**Comment by pgorod** [comment]
@kichloo if you don't know how to rebase, the easiest thing you can do is just close this PR, and start a new one _from the correct branch_.

First, switch to the branch you want (from the menu on the left, near the top of the page):

image

Then click the file you want to edit, edit it, commit, and create PR.

**Comment by Mac-Rae** [comment]
Hi @kichloo,

Please rebase this pull request onto hotfix-7.10.x as you change was made on the incorrect base branch.

For more information please take a look at our [contribution guidelines](https://docs.suitecrm.com/community/contributing-code/).

If you would like assistance please ensure you select "Allow edits from maintainers" checkbox and leave us a message @tagging me! 

Thanks :+1:

**Comment by kichloo** [comment]
@Mac-Rae I have selected the box and please help as I want to make my contribution for Hacktoberfest to SuiteCRM count!

**Comment by Dillon-Brown** [comment]
Hi @kichloo, I've rebased and approved. Thanks for the contribution!

**Comment by kichloo** [comment]
@Dillon-Brown Thanks!

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by Mac-Rae** [comment]
@samus-aran can you merge this, Travis is broke :/

**Comment by kichloo** [comment]
Thanks for merging PR but the name is not in the swag list. Was excited to receive my first swag from SuiteCRM :(

**Pull request merged**
