### PR TITLE
Fix #9665 - Set unique id for "Reset module" button in studio

### LINKED ISSUE #9665: In Studio "Reset module" & "Export customizations" have the same id  and name
#### Issue
The _Reset module_ button has the ID `exportBtn` which is already used in the _Export Customizations_ button that is already used at another point in the studio.

This complicates the selective application of any CSS or JavaScript rule on only one of the buttons and, in any case, it is a design error.
imagen

#### Expected Behavior
Each button should have an `id` and `name` property according to its function.

#### Actual Behavior

In study there are two buttons that have the same `id` and `name`

#### Steps to Reproduce

1. Open Studio, any module.
2. In browser inspector, look at the button _Reset module_ properties 

#### Context

In some developments we have to apply, through the general CSS some specific rule for one of these buttons and we cannot do it without affecting the other button, which shares the same id.

#### Your Environment

* SuiteCRM Version used: 7.12.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Versión 103.0.5060.114 Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB, PHP 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by SinergiaCRM**
## Description

- resolve [#9665](https://github.com/salesagility/SuiteCRM/issues/9665)

As described in issue, the button _Reset module_ has properties `id` y `name` _exportBtn_, that coincide with another study button.

This PR set an unique and appropriate `id` and `name`  for _Reset module_ button
## Motivation and Context

In some developments we have to apply, through the general CSS, some specific rule for one of these buttons and we cannot do it without affecting the other button, which shares the same id.

## How To Test This

1. Open studio
2. Open any module
3. With browser inspector look at the _Reset module_ button and check that the button has its own id and name

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jack7anderson7** [comment]
Hi @SinergiaCRM,

Could you instead point this PR to hotfix.

Thanks,
Jack

**Comment by serhiisamko091184** [comment]
Hello, @SinergiaCRM 
thank you very much, well spotted, 

I'd like to draw your attention to the Help panel on the right (shows useful information while user is hovering content). 
In this situation change of id and name do sets right attributes, it would be also handy to set an appropriate message into element with id="mbhelp" (by adding an element into language file of ModuleBuilder module): 
image

image

Would you be willing to add that into your PR? 

Thanks in advance,
Serhii

**Comment by SinergiaCRM** [comment]
> Would you be willing to add that into your PR?

Hi,@serhiisamko091184

Added the descriptive text for the Reset button.

**Comment by serhiisamko091184** [comment]
Hello @SinergiaCRM 
thank you very much for your cooperation, 

would you be so kind to squash commits in your branch into one (it means to combine multiple commits into single commit)?
Thanks a lot in advance.

Regards, 
Serhii

**Comment by SinergiaCRM** [comment]
> Hello @SinergiaCRM thank you very much for your cooperation,
> 
> would you be so kind to squash commits in your branch into one (it means to combine multiple commits into single commit)? Thanks a lot in advance.
> 
> Regards, Serhii

Done! @serhiisamko091184

**Comment by clemente-raposo** [comment]
Hi @SinergiaCRM thank you for your PR

**Review by johnM2401 — APPROVED** [review]

**Pull request merged**
