### PR TITLE
Fixed #7723 - Fix missing campaign analysis graphs

### LINKED ISSUE #7723: Campaign analysis page is blank in 7.9.19 LTS
#### Issue
In Campaigns list view the View Status icon brings a blank page. Using same database contents with 7.8.5 shows proper campaign data.

#### Expected Behavior
Should show campaign analysis results like in 7.8.5

#### Actual Behavior
Blank page with only name of campaign as title.

#### Possible Fix
Use 7.8.5

#### Steps to Reproduce
Assuming you have an ongoing campaign
1. Select "Campaigns"
2. Click the icon with horizontal bar graphics i.e. the View Status
3. One should see the status page, but no.
4. Revert to 7.8.5 and see how it is supposed to work

#### Context
I am trying to get an email campaign going.

#### Your Environment
* SuiteCRM Version used: 7.10.19 and 7.8.5 for testing
* Browser name and version: Firefox 68.0.1 (64-bit):
* Environment name and version 
* MySQL Ver 14.14 Distrib 5.7.27
* PHP 7.2.19-0ubuntu0.18.04.1 (cli)
* Operating System and version: Lubuntu 18.04.2

### PR DESCRIPTION
**Pull request by lazka**
## Description

Bring back the campaign statistics that were removed in #7663
This reverts the commits that removed it.

There exists a JSChart class, but it is missing an implementation and just returns null and empty strings everywhere, which isn't very helpful.
This brings back the Jit one.

Fixes #7723

## Motivation and Context

I'd like them back :(

## How To Test This

* View a campaign
* Click "View Status" in the top right
* The campaign stats graph should be visible

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
Is there a point to including the SWF file? Flash isn't supported by default in Firefox, Chrome, or Safari AFAIK, and support will be removed entirely next year.

**Comment by lazka** [comment]
No idea, this is just a simple revert.

**Comment by willrennie** [comment]
Assessed. Working as per description :+1:

**Comment by timo12357** [comment]
Hello, can something be done to allow merging? This is quite an important bug fix, too.

**Comment by pgorod** [comment]
This should also fix #8585

**Comment by QuickCRM** [comment]
Just tested this PR on Campaigns View Status, View ROI and graphs dashlets with (SuiteCRM 7.11.13 and 7.10.25).
It works perfectly !
I would appreciate if that could be merged in next version

**Comment by lazka** [comment]
Thank you!

**Pull request merged**
