### PR TITLE
Give Meeting different colors (patch-1), see github #3273

### PR DESCRIPTION
**Pull request by jobst**
The extra colors are defined in config_override.php, if they do NOT exist the default colors will be used.
E.G:
// light blue
$sugar_config['CalendarColors']['Planned']['border']="555555";
$sugar_config['CalendarColors']['Planned']['body']  ="D8EFFF";
$sugar_config['CalendarColors']['Planned']['text']  ="000000";

This is valid for anything that is defined in the dropdown editor in "meeting_status_dom", anything that is added can have a different color, you just need to refer to the "item name" (not display label).

Here is the code with comments:
      if (undefined !== global_colorList[element.module_name]) {
        // this if statement is in the original code
        // Only want this for meetings, calls etc not required
        if (element.module_name=='Meetings') {
          // just make sure it *IS* defind in config_override.php
          if(null == global_colorList[element['status']] ) {
            // yes, color is defined in config_override.php
            valueToPush["backgroundColor"] = '#' + global_colorList[element.module_name].body;
            valueToPush["borderColor"] = '#' + global_colorList[element.module_name].border;
            valueToPush["textColor"] = '#' + global_colorList[element.module_name].text;
          } else {
            // no, color is NOT defined in config_override.php, use the values from CalendarDisplay.php
            valueToPush["backgroundColor"] = '#' + global_colorList[element['status']].body;
            valueToPush["borderColor"] = '#' + global_colorList[element['status']].border;
            valueToPush["textColor"] = '#' + global_colorList[element['status']].text;
          }
        }
        else {
          // every other case we do the original stuff, use the values from CalendarDisplay.php
          valueToPush["backgroundColor"] = '#' + global_colorList[element.module_name].body;
          valueToPush["borderColor"] = '#' + global_colorList[element.module_name].border;
          valueToPush["textColor"] = '#' + global_colorList[element.module_name].text;
        }
      }

## Motivation and Context

It makes the calendar less bland.

## How To Test This

- replace Cal.js (patch-1)
- replace CalendarDisplay.php (patch-2)
- add the changes to config_override.php as shwon above
- load SuiteCRM
- go to the calendar
- create a meeting with "planned"
- instead of being the standard wierd blue its light blue (can be any color)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ X] My change requires a change to the documentation.
- [ X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
Please sign the clahub.

I like the idea. It would be better to put the colors in variables.scss and added the background colors as a set of css unique classes in the calendar.scss file. This is more inline with the direction we are taking with the product. 

You could then add each class in JavaScript. Your JavaScript changes need to be in jssource/src_files/modules/Calendar/Cal.js. modules/Calendar/Cal.js is the minified version. When someone repairs the javascript in the admin panel. Your changes will be over written.

**Comment by Dillon-Brown** [comment]
hi @jobst do you think you can you make the JavaScript changes in jssource/src_files/modules/Calendar/Cal.js described by daniel and then add the commits to #3337 ? you could then close this PR to keep things tidy :)

**Comment by samus-aran** [comment]
[checkActivity() does not properly handle meeting_status_dom](https://trello.com/c/P6iDVkzp/16-checkactivity-does-not-properly-handle-meeting-status-dom)

**Comment by jobst** [comment]
Ok, I will make the changes to the JS files ... but I will also enhance the checks in the files to make it bullet proof - currently there are many "assumptions".
There are a few things that need to be discussed, though - for example whether the configuration items in class CalendarDisplay $activity_colors should really be moved, IMHO they should be at the same place as my suggested settings and whether the configuration items should be set config_override.php

**Comment by jobst** [comment]
@Dillon-Brown how can I commit the changes I made in my fork to this pull-request #3337?
I can see them there as I referenced them, but I cannot see an option like "attach them to the 3337 pull request".

**Comment by Dillon-Brown** [comment]
@jobst Both this PR and #3337 are from unknown repo's. You are going to want to close them and create a new one if you are wanting to add changes.

Once you have a new PR up you can add changes to it without having to create a new PR for each change. This is done by adding commits to the same branch in your own repository which will then be automatically added to the PR.

**Pull request closed without merging**
