### PR TITLE
FIX #7912 - Avoid PHP Notices in getVardefs() method

### LINKED ISSUE #7912: PHP Notice in SugarWidgetField.php
<!--- Provide a general summary of the issue in the **Title** above -->
<!--- Before you open an issue, please check if a similar issue already exists or has been closed before. --->
<!--- If you have discovered a security risk please report it by emailing security@suitecrm.com. This will be delivered to the product team who handle security issues. Please don't disclose security bugs publicly until they have been handled by the security team. --->

#### Issue
<!--- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->

The method `getVardef()` in `include/generic/SugarWidgets/SugarWidgetField.php` is not checking that `column_key` and `reporter` are setted.


```php
    public function getVardef($layout_def)
    {
        $myName = $layout_def['column_key'];
        $vardef = $this->layout_manager->defs['reporter']->all_fields[$myName];

        if (!isset($vardef)) {
            // No vardef, return an empty array
            return array();
        }
        return $vardef;
    }
```


Because of this, many `PHP Notice` like these are register in php log:

```
[Mon Sep 23 15:17:45 2019] PHP Notice:  Undefined index: column_key in /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetField.php on line 233                                                                                    
[Mon Sep 23 15:17:45 2019] PHP Stack trace:                                                                                                                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   1. {main}() /home/jose/trabajos/gca-suitecrm7.10x/index.php:0                                                                                                                                                                
[Mon Sep 23 15:17:45 2019] PHP   2. SugarApplication->execute() /home/jose/trabajos/gca-suitecrm7.10x/index.php:80                                                                                                                                            
[Mon Sep 23 15:17:45 2019] PHP   3. SugarController->execute() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/SugarApplication.php:113                                                                                                                     
[Mon Sep 23 15:17:45 2019] PHP   4. SugarController->processView() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:375                                                                                                       
[Mon Sep 23 15:17:45 2019] PHP   5. CustomSugarView->process() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:435                                                                                                           
[Mon Sep 23 15:17:45 2019] PHP   6. ViewClassic->display() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/SugarView.php:108                                                                                                                    
[Mon Sep 23 15:17:45 2019] PHP   7. SugarView->includeClassicFile() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/views/view.classic.php:32                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   8. include_once() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/View/SugarView.php:818                                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   9. SubPanel->display() /home/jose/trabajos/gca-suitecrm7.10x/custom/modules/Contacts/SubPanelViewer.php:69                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP  10. SubPanel->ProcessSubPanelListView() /home/jose/trabajos/gca-suitecrm7.10x/include/SubPanel/SubPanel.php:238                                                                                                               
[Mon Sep 23 15:17:45 2019] PHP  11. ListViewSubPanel->process_dynamic_listview() /home/jose/trabajos/gca-suitecrm7.10x/include/SubPanel/SubPanel.php:222                                                                                                      
[Mon Sep 23 15:17:45 2019] PHP  12. ListViewSubPanel->process_dynamic_listview_rows() /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSubPanel.php:159                                                                                         
[Mon Sep 23 15:17:45 2019] PHP  13. LayoutManager->widgetDisplay() /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSubPanel.php:508                                                                                                            
[Mon Sep 23 15:17:45 2019] PHP  14. SugarWidgetFieldInt->display() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/LayoutManager.php:375                                                                                                                
[Mon Sep 23 15:17:45 2019] PHP  15. SugarWidgetReportField->display() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetFieldint.php:96                                                                                           
[Mon Sep 23 15:17:45 2019] PHP  16. SugarWidgetFieldFloatDecorated->displayList() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetReportField.php:104                                                                           
[Mon Sep 23 15:17:45 2019] PHP  17. SugarWidgetFieldFloat->displayList() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/generic/SugarWidgets/SugarWidgetFieldFloatDecorated.php:13                                                                      
[Mon Sep 23 15:17:45 2019] PHP  18. SugarWidgetField->getVardef() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetFieldfloat.php:49                                                                                             
[Mon Sep 23 15:17:45 2019] PHP Notice:  Undefined index: reporter in /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetField.php on line 234                                                                                      
[Mon Sep 23 15:17:45 2019] PHP Stack trace:                                                                                                                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   1. {main}() /home/jose/trabajos/gca-suitecrm7.10x/index.php:0                                                                                                                                                                
[Mon Sep 23 15:17:45 2019] PHP   2. SugarApplication->execute() /home/jose/trabajos/gca-suitecrm7.10x/index.php:80                                                                                                                                            
[Mon Sep 23 15:17:45 2019] PHP   3. SugarController->execute() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/SugarApplication.php:113                                                                                                                     
[Mon Sep 23 15:17:45 2019] PHP   4. SugarController->processView() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:375                                                                                                       
[Mon Sep 23 15:17:45 2019] PHP   5. CustomSugarView->process() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:435                                                                                                           
[Mon Sep 23 15:17:45 2019] PHP   6. ViewClassic->display() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/SugarView.php:108                                                                                                                    
[Mon Sep 23 15:17:45 2019] PHP   7. SugarView->includeClassicFile() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/views/view.classic.php:32                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   8. include_once() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/View/SugarView.php:818                                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   9. SubPanel->display() /home/jose/trabajos/gca-suitecrm7.10x/custom/modules/Contacts/SubPanelViewer.php:69                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP  10. SubPanel->ProcessSubPanelListView() /home/jose/trabajos/gca-suitecrm7.10x/include/SubPanel/SubPanel.php:238                                                                                                               
[Mon Sep 23 15:17:45 2019] PHP  11. ListViewSubPanel->process_dynamic_listview() /home/jose/trabajos/gca-suitecrm7.10x/include/SubPanel/SubPanel.php:222                                                                                                      
[Mon Sep 23 15:17:45 2019] PHP  12. ListViewSubPanel->process_dynamic_listview_rows() /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSubPanel.php:159                                                                                         
[Mon Sep 23 15:17:45 2019] PHP  13. LayoutManager->widgetDisplay() /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSubPanel.php:508                                                                                                            
[Mon Sep 23 15:17:45 2019] PHP  14. SugarWidgetFieldInt->display() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/LayoutManager.php:375                                                                                                                
[Mon Sep 23 15:17:45 2019] PHP  15. SugarWidgetReportField->display() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetFieldint.php:96                                                                                           
[Mon Sep 23 15:17:45 2019] PHP  16. SugarWidgetFieldFloatDecorated->displayList() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetReportField.php:104                                                                           
[Mon Sep 23 15:17:45 2019] PHP  17. SugarWidgetFieldFloat->displayList() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/generic/SugarWidgets/SugarWidgetFieldFloatDecorated.php:13                                                                      
[Mon Sep 23 15:17:45 2019] PHP  18. SugarWidgetField->getVardef() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetFieldfloat.php:49                                                                                             
[Mon Sep 23 15:17:45 2019] PHP Notice:  Trying to get property of non-object in /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetField.php on line 234                                                                           
[Mon Sep 23 15:17:45 2019] PHP Stack trace:                                                                                                                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   1. {main}() /home/jose/trabajos/gca-suitecrm7.10x/index.php:0                                                                                                                                                                
[Mon Sep 23 15:17:45 2019] PHP   2. SugarApplication->execute() /home/jose/trabajos/gca-suitecrm7.10x/index.php:80                                                                                                                                            
[Mon Sep 23 15:17:45 2019] PHP   3. SugarController->execute() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/SugarApplication.php:113                                                                                                                     
[Mon Sep 23 15:17:45 2019] PHP   4. SugarController->processView() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:375                                                                                                       
[Mon Sep 23 15:17:45 2019] PHP   5. CustomSugarView->process() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:435                                                                                                           
[Mon Sep 23 15:17:45 2019] PHP   6. ViewClassic->display() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/SugarView.php:108                                                                                                                    
[Mon Sep 23 15:17:45 2019] PHP   7. SugarView->includeClassicFile() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/views/view.classic.php:32                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   8. include_once() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/View/SugarView.php:818                                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP   9. SubPanel->display() /home/jose/trabajos/gca-suitecrm7.10x/custom/modules/Contacts/SubPanelViewer.php:69                                                                                                                   
[Mon Sep 23 15:17:45 2019] PHP  10. SubPanel->ProcessSubPanelListView() /home/jose/trabajos/gca-suitecrm7.10x/include/SubPanel/SubPanel.php:238                                                                                                               
[Mon Sep 23 15:17:45 2019] PHP  11. ListViewSubPanel->process_dynamic_listview() /home/jose/trabajos/gca-suitecrm7.10x/include/SubPanel/SubPanel.php:222                                                                                                      
[Mon Sep 23 15:17:45 2019] PHP  12. ListViewSubPanel->process_dynamic_listview_rows() /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSubPanel.php:159                                                                                         
[Mon Sep 23 15:17:45 2019] PHP  13. LayoutManager->widgetDisplay() /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSubPanel.php:508                                                                                                            
[Mon Sep 23 15:17:45 2019] PHP  14. SugarWidgetFieldInt->display() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/LayoutManager.php:375                                                                                                                
[Mon Sep 23 15:17:45 2019] PHP  15. SugarWidgetReportField->display() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetFieldint.php:96                                                                                           
[Mon Sep 23 15:17:45 2019] PHP  16. SugarWidgetFieldFloatDecorated->displayList() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetReportField.php:104                                                                           
[Mon Sep 23 15:17:45 2019] PHP  17. SugarWidgetFieldFloat->displayList() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/generic/SugarWidgets/SugarWidgetFieldFloatDecorated.php:13
[Mon Sep 23 15:17:45 2019] PHP  18. SugarWidgetField->getVardef() /home/jose/trabajos/gca-suitecrm7.10x/include/generic/SugarWidgets/SugarWidgetFieldfloat.php:49

```



#### Expected Behavior
<!--- Tell us what should happen -->

Avoid annoying PHP Notices ;-)


#### Actual Behavior
<!--- Tell us what happens instead -->
<!--- Also please check relevant logs (suitecrm.log, php error.log etc.) -->

A lot of PHP Notices are in the php log.

#### Possible Fix
<!--- Not obligatory, but suggest a fix or reason for the bug -->

We sould verify if `column_key` and `reporter` are setted with something like this

```php
        if (!empty($layout_def['column_key']) && !empty($this->layout_manager->defs['reporter'])) {
            $myName = $layout_def['column_key'];
            $vardef = $this->layout_manager->defs['reporter']->all_fields[$myName];
        }
```

#### Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug include code to reproduce, if relevant -->
1. Define a Float field in a subpanel
2. Check for Notices in PHP log


#### Context
<!--- How has this bug affected you? What were you trying to accomplish? -->
<!--- If you feel this should be a low/medium/high priority then please state so -->

#### Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* SuiteCRM Version used: 7.10.20
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.04

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

Read #7912

## Motivation and Context

Avoid annoying PHP Notices in php log

## How To Test This

1. Define a Float field in a subpanel
2. Check for Notices in PHP log

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Hey @Abuelodelanada,

I've been unable to replicate the error in the logs. Could you confirm;
Where you just on the detail view with the subpanel containing the float open?
Did you have to interact with the record or value?
And im using the Amount field on Opportunities for testing. What did you use?

Thanks :+1:

**Comment by Abuelodelanada** [comment]
Hi @Mac-Rae 

With this PR we only make sure that `$layout_def['column_key']` and `$this->layout_manager->defs['reporter']` are set, before using it.
And it improves the possibility that SuiteCRM is extended without PHP notices in the log.

We have a custom SugarWidgetField that inherits from `SugarWidgetFieldFloat` called `SugarWidgetFieldFloatD`. (The `D` is for `Decorated` ;-) )

We created this field to align float numbers to the right and add other specific CSS classes, not big deal.

This fix is simple as you can see, but to reproduce the bug it's a little `complex`:

1. Create a custom widget like this in `include/generic/SugarWidgets/SugarWidgetFieldFloatD.php`:

```php
class SugarWidgetFieldFloatD extends SugarWidgetFieldFloat
{
    public function displayList(&$layout_def)
    {
        return parent::displayList($layout_def);
    }
}
```
This is a simplification of what we have, but in `displayList` function you can add CSS for example taken from subpanel definition for example.

2. In the subpanel definition of the module you have to add the following:

```php
'widget_class' => 'FieldFloatD',
``` 

In our instance we have:

```php
        'saldoDeudorPesos' => array(
            'vname' => 'LBL_SALDODEUDORPESOS',
            'width' => '20%',
            'default' => true,
            'sortable' => false,
            'widget_class' => 'FieldFloatD',
            'style' => array(
                'text-align-right',
            ),
        ),
```

You can do the same in: `modules/Opportunities/metadata/subpanels/ForAccounts.php`

```php
        'amount_usdollar'=>array(
            'vname' => 'LBL_LIST_AMOUNT_USDOLLAR',
            'width' => '15%',
            'widget_class' => 'FieldFloatD',
        ),
```

3. Just to test this fix, in the Opportunities vardefs.php you should have the `amount_usdollar` like this:

```php
        'amount_usdollar' =>
            array(
                'name' => 'amount_usdollar',
                'vname' => 'LBL_AMOUNT_USDOLLAR',
                'type' => 'floatd',
                'group' => 'amount',
                'dbType' => 'double',
                'disable_num_format' => true,
                'duplicate_merge' => '0',
                'audited' => true,
                'comment' => 'Formatted amount of the opportunity',
                'studio' => array(
                    'editview' => false,
                    'detailview' => false,
                    'quickcreate' => false,
                ),
            ),
```

4. Quick Repair and Rebuild.

5. Reload an Account DetailView with a created opportunity in subpanel.

6. Check PHP log. You will not see the PHP Notices.

7. If you do the same without this fix you will see the Notices in the log

**Comment by Abuelodelanada** [comment]
Hi @Mac-Rae 

Could you read how to test this PR?

**Comment by Mac-Rae** [comment]
Sorry for the wait, I missed the notification that you had replied. Looks good to me :+1:

**Pull request merged**
