### PR TITLE
Fix search_by_module REST API

### PR DESCRIPTION
**Pull request by QuickCRM**
- Remove SugarCRM Pro code preventing search for Project tasks
- Remove duplicate code

## Motivation and Context
unified search using REST API does not work for Project Tasks

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by QuickCRM** [comment]
Yes. 
And the teams table does not exist either. 

--
support@quickcrm.fr
NS-Team
www.quickcrm.fr/mobile

**Comment by chris001** [comment]
Teams is replaced by "Security Groups".
It'd be good to add a compatibility interface so the add-on modules expecting to find "Teams" REST methods could run on Security Groups tables in the database without crashing.

**Comment by QuickCRM** [comment]
Not sure I agree. 

I believe this team table and function has nothing to do with Security teams. My understanding is this is about project members is SugarCRM Pro. 

And anyway, Security groups should be managed for all modules in that function. Not only for Project Tasks. 

We are doing that in QuickCRM REST API that overrides this one. We will certainly have another Pull Request for that later but this change already makes sense as the current function prevents all unified searches if Project Tasks is one of the modules. 





--
support@quickcrm.fr
NS-Team
www.quickcrm.fr/mobile

**Comment by Mac-Rae** [comment]
Please resolve the conflicts on this pull request bringing it up to date.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by samus-aran** [comment]
Hey @QuickCRM :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Comment by QuickCRM** [comment]
Hi Ashley,

Thanks. It was a pleasure to help. We have found a few other bugs in SuiteCRM 7.10 and 7.11 and we will try to send Pull Requests in the next few days.

Our address is

55 Chemin de Mervilla
31320 Auzeville
FRANCE

Benoit
--
Benoit Luquet
NS-Team
Tel. +33 (0)5 61 73 64 14 - +33 (0)6 64 50 59 08

**Pull request merged**
