### PR TITLE
Add OAuth connection to Inbound emails

### PR DESCRIPTION
**Pull request by clemente-raposo**
#### Update External OAuth Connection Module

- Add config.php entry to allow adding oauth external providers
- Add ExternalOAuthConnection module to allow getting access through OAuth from external providers
- Allow setting up Security groups for ExternalOuthConnections Emails

emails-oauth-external-oauth-connection

emails-oauth-personal-external-oauth-connection-edit

emails-oauth-personal-external-oauth-connection-detail

#### Update Inbound Emails Module
- Update Inbound email module views to user regular view defs
- Allow creating Personal, Group and Bounce emails through InboundEmails create/edit view
- Remove inbound email configuration from profile view configurations
- Allow setting up Security groups for Inbound Emails
- Allow selecting between basic auth and oauth on inbound email configuration
- Allow selecting an external oauth connection as the connection to use for authenticating in Inbound emails

emails-oauth-inbould-list-view

emails-oauth-personal-inbould-oauth

emails-oauth-personal-inbould-basic-auth

emails-oauth-profile-view

email-oauth-no-profile-personal-email-config

#### Update Outbound Emails Module
- Allow creating Personal outbound emails through Outbound email module create/edit view
- Remove outbound email configuration from profile view configurations
- - Allow setting up Security groups for Outbound Emails

emails-oauth-oubound-listview

emails-oauth-personal-outbound

#### Update IMAP connection library | Allow connecting with xoauth
- Add imap2 lib to handle in order to support xoauth login in imap
- Add Imap2Handler to be used to connect to IMAP for Oauth connections

https://user-images.githubusercontent.com/1140849/205695529-099579bd-d24a-4564-a5ef-659bbd03e4fb.mp4

## Motivation and Context

- Allow connecting to IMAP using OAuth connections
- Fix some bugs in current inbound and outbound email Configuration

## How To Test This

1. Configure a Microsoft connection provider using the following config.php configuration
```php
  'external_oauth_providers' => [
      'Microsoft' => [
          'type' => 'Generic',
          'client_id' => '<TO-REPLACE>',
          'client_secret' => '<TO-REPLACE>',
          'redirect_uri' => 'http://<TO-REPLACE>/index.php?entryPoint=setExternalOAuthToken',
          'authorize_url_options' => [
              'scope' => 'offline_access IMAP.AccessAsUser.All SMTP.Send User.Read',
          ],
          'extra_provider_params' => [
            'scopes' => 'offline_access imap.accessasuser.all smtp.send user.read',
            'urlAuthorize' => 'https://login.microsoftonline.com/<TO-REPLACE>/oauth2/v2.0/authorize',
            'urlAccessToken' => 'https://login.microsoftonline.com/<TO-REPLACE>/oauth2/v2.0/token',
            'urlResourceOwnerDetails' => '',
            'verify' => false
        ],
        'get_token_request_grant' => 'authorization_code', // optional
        'get_token_request_options' => [], // optional
        'token_mapping' => [ // optional
            'access_token' => 'access_token',
            'expires_in' => 'expires_in',
            'refresh_token' => 'refresh_token',
            'token_type' => 'values.token_type'
        ]
      ],
  ],
```

2. Go to Profile > External OAuth connection module and create new personal connection

3. Select Microsoft > Click Authenticate > Popup should appear

4. Add your credentials > Authorize > Connection fields should be field in with token information

5. Add a name > Save

6. Go to InboundEmail record

7. Change Auth Type from basic to OAuth

8. You should be able to see the records you and the ones you have access to by security groups

9 . Select a record > Save > The record should correctly save

10. Go to emails module. You should be able to see the emails sorted by received date

11. Try the filter panel you should be able to filter

12. You should not be able to sort or set sorting direction

13. You should be able to mark emails as read and unread

14. You should be able to flag and un-flag emails

15. You should be able to delete emails

16. You should be able to import emails

17. you should be able to go to the email detail view page

18. You should be able to see the email information in the detail view page

19 Configure  a group inbound emails. You will need to create a group ExternalOauthConnection

20. Auto email import for cases should work for group emails

21. Inbound email repair should work

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by johnM2401 — APPROVED** [review]
LGTM.

Able to connect using Oauth authentication, tested with office365.

CRM appears to still pull Emails & behave as expected

**Comment by pgorod** [comment]
Github tells me that on the post above, "Video can't be played because the file is corrupt"

**Comment by clemente-raposo** [comment]
@pgorod, strange I can see it just fine. Maybe a codec thing?

**Comment by pgorod** [comment]
The error appears directly on this page, even before I click to play. I am on Firefox.

I just tried on Edge and it played fine 🤷‍♂️

**Review by jack7anderson7 — APPROVED** [review]

**Comment by chris001** [comment]
> Maybe a codec thing?

Firefox latest version (108.0) gives this error:
suitecrm no video with supported format

**Pull request merged**
