### PR TITLE
Fix for salesagility/SuiteCRM#7312

### PR DESCRIPTION
**Pull request by ApatheticCosmos**
Clears the sync data from the users records if the 'SuiteCRM' Google Calendar gets deleted. Then recreates the Google calendar and re-syncs it.

## Description

If the User doesn't have a Google calendar named 'SuiteCRM', then we clear all the sync data from the records to be synced before we create the Google calendar and sync. This prevents the system from breaking if the user deletes the 'SuiteCRM' Google Calendar. Without this fix, syncing will break in a way that requires SQL commands to resolve. With this fix, deleting the 'SuiteCRM' calendar will trigger that fix automatically, and prevent it from breaking in the future.

## Motivation and Context

See issue #7312
## How To Test This

Sync with your Google Calendar.
Find the 'SuiteCRM' calendar in your Google account and delete it.
On the next sync, a new 'SuiteCRM' calendar will be created with all your meetings.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by ApatheticCosmos** [comment]
I just merged this PR with our production system. It instantly fixed the broken calendar syncs a couple of our users had due to this bug.

**Comment by Mac-Rae** [comment]
Hey @ApatheticCosmos,

 Looks like the related issue is closed, I'm assuming your still have these problems in the most up to date versions? If so could you drop a message on the related issue and we will reopen it. Also just to confirm that this issue only affects 7.11.x and not 7.10.x?

**Comment by Dillon-Brown** [comment]
@Mac-Rae The issue is linked in the PR title and Git commit: https://github.com/salesagility/SuiteCRM/issues/7312

**Comment by ApatheticCosmos** [comment]
@Mac-Rae Whoops! Typo in the issue number. It's #7312
This does only affect 7.11, since GoogleSync isn't in 7.10.

**Comment by parijke** [comment]
How can I apply this as a patch?

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by samus-aran** [comment]
Hey @ApatheticCosmos   :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Comment by samus-aran** [comment]
Hey @ApatheticCosmos 

Just to let you know that the submissions form for receiving your gifts is closing in least than 12 hours (5PM GMT)

Hope to see your submission!

**Comment by ApatheticCosmos** [comment]
I'm trying to, but it seems stuck at
'Sending. One moment please'

--
Benjamin Long

**Comment by samus-aran** [comment]
Oh that's strange.
We just re-tested it ourselves and it seemed to work as expected. 

What browser are you using?

IF you are still having issues then you ok for us to re-use the shipping details you had from the last event? Else you could send it to us via community@suitecrm.com

**Comment by ApatheticCosmos** [comment]
I'm using Firefox on Android right now. I'll try on the desktop when I'm in
front of it.
My info hasn't changed, so you can use it if I can't get it to work.

--
Benjamin Long

**Pull request merged**
