### PR TITLE
Enable server side spell checker in TinyMCE editor

### PR DESCRIPTION
**Pull request by chris001**
## Description

Activate spell cheker button in the rich text editor (TinyMCE).

## Motivation and Context

The server side spell checker plugin for TinyMCE rich text editor is installed with SuiteCRM however the button was not appearing in the user interface!
This PR activates the button so that it's now showing, and users can click it to check spelling - very important for many users to help correct typos etc.

## How To Test This

1. Send a new Email  - or do anything which requires the system to show you the rich text editor.
2. The SugarTinyMCE editor box and toolbar will appear - to let you edit rich text similar to office/word/docs/writer.
3. You should see a new button, the "Spell Check" icon button, in the button layout, at the top of the text editor.
4. Type or paste some words.
5. Click the spell check button.
6. The editor should run a spell check, using one of several spell checkers it detects installed on the SuiteCRM server - enchant, pspell, or google spell.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by mattlorimer** [comment]
That's a coincidence I was look lately at spell checking on TinyMCE, and I found that you easily enable browser spell checking http://archive.tinymce.com/wiki.php/Configuration3x:browser_spellcheck, which i thought worked quite well, I've not had that chance to try out your PR, but any thoughts on that?

**Comment by chris001** [comment]
The browser spell checking is disabled by default because some have complained, it relies on the built in spell check dictionaries which come with IE, Firefox, and Safari, to underline words in red.  

Server side spell check doesn't require you to be using any particular browser to get the benefit of spell check, it uses the linux packages for pspell, enchant, and google spell, tthe dictionaries and code logic reside on the server.  They can get updated any time.   This could raise privacy concern for many, to send all your words, typed, in emails and documents, to a less than totally transparent corp such as google for a spell check.  Yet, Google fixes spelling better than many static dictionaries because it tracks searches where someone has spelled something wrong, and then corrected their spelling, and redid the search, and for this, it dynamically scores those spell corrections higher.

To satisfy all, It'd be good to offer a config setting to let an admin select which spelling engines to use, with a list of check boxes.

**Comment by chris001** [comment]
Here's a spell check plugin for tinymce 4 which combines the benefits of server side spell checking with privacy of dictionaries on the server - it doesn't send all of your email conversations to google spell, where they would be logged forever.
http://tinymcespellcheck.com
Many different languages dictionaries are available to downloaded to the sutiecrm server and select from them, including special terminology dictionaries such as medical, engineering, etc.

**Comment by jack7anderson7** [comment]
Hi @chris001,

I have implemented your pr although when testing I was unable to see the spell checker button as it did not appear could you indicate me in anyway as to why this is, if you are able?

**Comment by samus-aran** [comment]
Closed due to inactivity and interest to apply. Any additional interest is welcome.

**Pull request closed without merging**
