### PR TITLE
Inline Edit: Help text containing quotes is not correctly displayed

### PR DESCRIPTION
**Pull request by QuickCRM**
## Description

In Studio, enter a help containing a quote text in a field
When inline editing that field, all text after the quote is removed

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jack7anderson7** [comment]
Hi @QuickCRM, 

I'm unable to replicate the issue related to your PR. Is there anything that was done specifically before this issue was arisen that would help me replicate it?
Thanks

**Comment by QuickCRM** [comment]
As I don't have an admin access to demo.suiteondemand.com, here is what you could try:

In Studio / Leads / Fields:
- edit Job title
- Enter the following in help: check the ' symbol
- Save
- Display a lead
- Enter inline edit on Job title
- Keep your mouse on the input field for a moment
- You will only see "check the"

I can send you screen captures if you wish.

**Comment by jack7anderson7** [comment]
After applying the fix, and re-checking the help text it then only displays: "check the \". Is this the intended solution?

**Comment by QuickCRM** [comment]
Hi again, @jack7anderson7 

Unfortunately, saving a field in studio does not clear the cached definition of the field in folder cache/include/InlineEditing (Yet another bug in SuiteCRM).
Remove all files in cache/include/InlineEditing and try again.
You will see the full help text.

**Comment by jack7anderson7** [comment]
I'm afraid that after refreshing cache, and other efforts to show the correct solution to the fix have been unsuccessful. It still appears as "check the \" on my end. I'm unsure of anything else to suggest, even when adding the same help text to another field as a test I'm having the same result

**Comment by QuickCRM** [comment]
My fix doesn't work in some cases (depending on how the help text is saved).
I just tried with $vardef['help'] = htmlspecialchars($vardef['help'],ENT_QUOTES);
It works fine.
I will update my pull request

**Comment by QuickCRM** [comment]
@jack7anderson7 

Can you please check this new version? (make sure you remove the cached file in cache/include/InlineEditing)

**Comment by jack7anderson7** [comment]
This is now working on my end, could you do one more thing and rebase the commits into a single commit and the PR will be approved on my end.

Thanks

**Comment by QuickCRM** [comment]
@jack7anderson7 

Sorry I have no clue how to merge these two commits.

**Review by jack7anderson7 — APPROVED** [review]

**Review by samus-aran — APPROVED** [review]

**Pull request merged**
