### PR TITLE
Fix #6022 - API v4_1 get_module_fields method does not return parentenum

### LINKED ISSUE #6022: API v4_1 get_module_fields method does not return parentenum
#### Issue

On API v4_1 `get_module_fields` method is not returning `parentenum` values.

#### Possible Fix

I will submit a PR later.

#### Steps to Reproduce

1. Call `get_module_fields` on `Cases` module.
2. See that `state` and `status` fields doesn't have `parentenum` value.

#### Context

I'm implementing an external application and I need this value to implement dynamicenum fields.

#### Your Environment

* SuiteCRM Version used: SuiteCRM 7.8.20 LTS
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Versión 67.0.3396.79 (Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.27 and mysql-server 5.5.9999
* Operating System and version (e.g Ubuntu 16.04): Debian 9

### PR DESCRIPTION
**Pull request by sanchezfauste**
## Description

See issue #6022

## Motivation and Context

On API v4_1 `get_module_fields` method is not returning `parentenum` values.

## How To Test This

1. Call `get_module_fields` on `Cases` module.
2. See that `state` and `status` fields doesn't have `parentenum` value.
3. Apply PR and repeat steps 1 and 2.
4. See that now `parentenum` value is pressent on `state` and `status` fields.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
Hi @sanchezfauste,

Can you please update this pull request so that it is up to date with hotfix 7.8.x? We are have updated the test suite. Would you be able and willing to help contribute unit tests for this pull request?

We have a guide on our documentation:
https://docs.suitecrm.com/developer/appendix-c---automated-testing/#_phpunit_tests

Let us know if you need any help.

**Comment by sanchezfauste** [comment]
Hi @daniel-samson ,
I have updated the PR branch with hotfix-7.8.x.
I will try to add some tests during this week.

**Comment by sanchezfauste** [comment]
I have tried to create a very simple test, but it seems that it does not work correctly. Could you tell me what I should modify to make it work correctly?

**Comment by gymad** [comment]
Hi @sanchezfauste, your test seems fine at first look. I think something else cause the problem in our hotfix-7.8.x branch. Let me investigate it first and I will let you know soon as I can.

**Comment by gymad** [comment]
@sanchezfauste: I just made a small change in a test in PR #6199, can you please apply my small change in your branch and let see if is travis passing?

**Comment by sanchezfauste** [comment]
@gymad, i have applied your changes and now travis is passing. Thanks for your help! I will add some tests in order to do a more sophisticated unit test.

**Comment by daniel-samson** [comment]
I looks like the stateless checker is flagging something in SchedulerTest::testderiveDBDateTimes. @gymad  do you have any ideas why?

```
1) SchedulerTest::testderiveDBDateTimes
SuiteCRM\StateSaverException: Some garbage state left in stack (did you pop everything?)
Needs to restore:
	[db_table.job_queue] => 'job_queue'
	[db_table.schedulers] => 'schedulers'
	[GLOBALS._POST] => '_POST'
	[GLOBALS._GET] => '_GET'
	[GLOBALS._REQUEST] => '_REQUEST'
	[GLOBALS._SESSION] => '_SESSION'
	[GLOBALS._SERVER] => '_SERVER'
	[GLOBALS._ENV] => '_ENV'
	[GLOBALS._FILES] => '_FILES'
	[GLOBALS._COOKIE] => '_COOKIE'
/home/travis/build/salesagility/SuiteCRM/include/StateSaver.php:108
/home/travis/build/salesagility/SuiteCRM/tests/tests/modules/Schedulers/SchedulerTest.php:165
/home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/composer/bin/phpunit:63
```

**Comment by gymad** [comment]
@daniel-samson yes, I do have. If you scroll a little bit down in the output and continue reading, you may will realised there is a failing assertation in the test. It couses that the test did not finished as expected and left some garbage state. specially in the database and superglobals as you see in the message. The real problem is the failed assert below.. also I don't realy understand why that assertation fails because I already been changed it and it was fine, now I revert it to original because it's fails againg... It seems totally random failing. do you have any idea why?

**Comment by gymad** [comment]
@sanchezfauste I made a small fix in the referenced PR above but also I think this PR should be fine. Do you have anything more addittional code what you want to add into this PR, If so can we merge it or you still working on it?

**Comment by sanchezfauste** [comment]
Hi @gymad, thanks for your effort to make this PR passing tests. For me it's okay and can be merged.

**Pull request merged**
