### PR TITLE
Fixed #6362 - mentioned fix to omit file data

### LINKED ISSUE #6362: API v8: File upload sends back to the client the whole file
I'm creating new Documents using the v8 API and I've noticed that on a successful POST you get the WHOLE uploaded file back in the JSON response ("filename_file" attribute). Is this necessary? Since I'm uploading multi-megabyte PDFs and I don't need the file back, it seems a bit of a waste.

Here's my call:
```
POST v8/modules/Documents
{'data': {'attributes': {'active_date': '2013-10-15 11:30:09',
                         'doc_type': 'Quote',
                         'document_name': 'Offer 129-PA-2013',
                         'filename': 'Offer 129-PA-2013.pdf',
                         'filename_file': '<BASE64-ENCODED FILE>',
                         'revision': '1'},
          'type': 'Documents'}}
```

and the relevant part of the response I receive:
```
{'data': {'attributes': {'active_date': '',
                           'assigned_user_id': '9a406189-3c4b-1625-69cb-5b43213c47b8',
                           'category_id': '',
                           'created_by': '9a406189-3c4b-1625-69cb-5b43213c47b8',
                           'created_by_name': '',
                           'date_entered': '',
                           'date_modified': '2018-09-28T07:42:52+00:00',
                           'deleted': 0,
                           'description': '',
                           'doc_type': 'Quote',
                           'document_name': 'Offer 129-PA-2013',
                           'document_revision_id': 'a195a043-9495-7abe-5cad-5baddb190375',
                           'exp_date': '',
                           'filename': 'Offer 129-PA-2013.pdf',
                           'filename_file': '<BASE64-ENCODED FILE>',
                           'is_template': False,
                           'last_rev_create_date': '',
                           'last_rev_created_name': '',
                           'modified_by_name': 'user',
                           'modified_user_id': '9a406189-3c4b-1625-69cb-5b43213c47b8',
                           'name': '',
                           'related_doc_id': '',
                           'related_doc_name': '',
                           'related_doc_rev_id': '',
                           'related_doc_rev_number': '',
                           'revision': '1',
                           'status': '',
                           'status_id': '',
                           'subcategory_id': '',
                           'template_type': ''},
[CUT]
```

If this is not required by the API spec, maybe the "*_file" attributes could be omitted? Something like this should be enough:
```
/lib/API/JsonApi/v1/Resource/Resource.php
@@ -177,7 +177,9 @@
                 continue;
             }
             if (in_array($attribute, $fields) === true) {
-                $response[self::ATTRIBUTES][$attribute] = $this->attributes[$attribute];
+                if (substr($attribute, -5) === "_file")
+                    $value = "<OMITTED>";
+                $response[self::ATTRIBUTES][$attribute] = $value;
             }
         }

```

I'm on SuiteCRM 7.10.9

### PR DESCRIPTION
**Pull request by gymad**
## Description

Fixed #6362 - mentioned fix to omit file data
## Motivation and Context

Issue #6362 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Will this be applied to the latest branch you have @gymad ?

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by gymad** [comment]
@samus-aran yes, it is.

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
