### PR TITLE
Workflow Enhancements 7.9.1 - Process Once Per Day.

### PR DESCRIPTION
**Pull request by stevejenkin**
We needed to find a solution of stopping a repeatable running workflow from triggering every time the Workflow schedule runs,

## Description

Conditions when this is an issue:

Time-based workflow condition which triggers on a particular day. On that day the conditions are met all day and the workflow will trigger every time the schedule runs (e.g. every minute). Repeated runs is required as the date may change to another value in the future and the record should be considered to be processed in the workflow again.

Proposed Solution:

Add checkbox next to the Repeated Runs checkbox called 'Trigger Only Once Per Day'.
When this checkbox is ticked, once it has run once for a particular record it will not run again for 24 hours for that particular record. There is also an Hour & Minute field to specify at what time each day this workflow should run.

## Motivation and Context

We needed to find a solution of stopping a repeatable running workflow from triggering every time the Workflow schedule runs. 

## How To Test This

Create a workflow using the module Accounts.

The condition is: When a date field in the Accounts module (e.g Last Contacted Date) > 60 days ago.

The action is: Create a new call.

What will happen in this instance is that each time the workflow scheduler runs a new call will be created, we cannot un-select the 'Repeated Runs' check box because the date in the field will change again and we want the record to be processed again in the future.

With our development we have implemented a check box which specifies that the workflow should only 'Trigger Only Once Per Day'. We have also added an hours and minutes field which allows the user to specify when that will be.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [X ] My change requires a change to the documentation.
- [X ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

[AOW_WorkFlow.zip](https://github.com/salesagility/SuiteCRM/files/1105288/AOW_WorkFlow.zip)

### CODE REVIEW

**Comment by pgorod** [comment]
Hi @stevejenkin thanks for the contribution!

This PR doesn't seem to be built correctly, though. 

There's an easy way to fork SuiteCRM into your repo and start a PR, which is:
- Go to SuiteCRM Github, click "Code", 
- underneath that select the intended branch `Develop`, 
- then navigate to the folder and file you want to change `AOW_WorkFlow`
- click the pencil button to edit the file. Github will automatically, fork, start a new branch on your fork, and prepare the PR to be submitted.

**Comment by stevejenkin** [comment]
Hi Salesagilty,

 

Steps followed as requested.

 

Kind regards,

Steve Jenkin
Technical Support Manager



+44 (0)203 598 0898
 <mailto:steve@fibrecrm.com> steve@fibrecrm.com
 <http://www.fibrecrm.com/> www.fibrecrm.com
 <http://uk.linkedin.com/pub/steve-jenkin/41/b7/88>  <https://twitter.com/SteveJenkin>  
Skype: fibrecrm

**Comment by pgorod** [comment]
Hi,

I'm just @pgorod, not SalesAgility :-)

This is a step in the right direction. But I don't know how you started the original PR, it's weird (no source repo?), and there's a "rogue" commit in there (by samus-aran). You will need to remove that, which might not be that easy... sometimes it's even easier to just start a new one correctly...

Also, I believe those comments about "hacks" should be removed, unless somebody from SalesAgility says otherwise...

Thanks

**Comment by stevejenkin** [comment]
Hi  <https://github.com/pgorod> @pgorod,

 

I simply followed your steps, where are you seeing the rogue commit by samus-aran?

 

We have a development team that has produced the file, I have simply uploaded the change as per your instructions.

 

I have removed the hack comments as requested.

 

Kind regards,

Steve Jenkin
Technical Support Manager



+44 (0)203 598 0898
 <mailto:steve@fibrecrm.com> steve@fibrecrm.com
 <http://www.fibrecrm.com/> www.fibrecrm.com
 <http://uk.linkedin.com/pub/steve-jenkin/41/b7/88>  <https://twitter.com/SteveJenkin>  
Skype: fibrecrm

**Comment by pgorod** [comment]
Please don't reply to the emails leaving the previous response text there... it really clutters GitHub... :-)

On the top of your PR you see
`stevejenkin wants to merge 1 commit into master from develop`

This is wrong, it should a merge from `stevejenkin/SuiteCRM:patch-1` to `salesagility/SuiteCRM:develop`

Then right below your initial text you see this
`7.9.1 develop [by samus-aran]			8a4b708`

This is probably caused by the initial error in the branch, that commit is basically the difference between those two branches, `develop` and `master` in salesagility's repo.

I think you did everything right the second time, but the confusion from the way you started this PR initially is still causing problems...

**Comment by stevejenkin** [comment]
Hi,

 

I have forked my own copy of salesagility/SuiteCRM, modified the code and the create a PR.

 

Does it now look correct?

 

Steve Jenkin
Technical Support Manager





---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by pgorod** [comment]
Yes the new PR #3806 looks correct.

You can close this one now. 

Thanks for your perseverance, GitHub (and the specific workflows of each project) can be daunting at first.

**Comment by stevejenkin** [comment]
Great, I will close this now.

**Pull request closed without merging**
