### PR TITLE
FIXED #5652 - Ending spaces in language strings 

### LINKED ISSUE #5652: Ending spaces in language strings
#### Issue

This is a general comment: languages strings should not end with a space when they are an ending text to be followed by a field data.
Spacing labels from data should be a code thing, not a translations thing. 
Note: this is not on those cases where a text is to be followed with a text from a different string, this is just on the situations where the following texts or values are data fileds
 
#### Expected Behavior

Spacing should be done by code, not by translations.

#### Actual Behavior

There isn't a rule on this. So many examples out there.

With ending spaces: /modules/Home/language/en_us.lang.php:
```
    'LBL_LOCATION' => 'Location: ',
    'LBL_STATUS' => 'Status: ',
```

without ending spaces modules/Activities/language/en_us.lang.php. 
```
    'LBL_STATUS' => 'Status:',
    'LBL_LOCATION' => 'Location:',
```
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Activities/language/en_us.lang.php

You can also find several examples with ending spaces here (36 occurrences!)
modules/Campaigns/language/en_us.lang.php
https://github.com/salesagility/SuiteCRM/blob/hotfix/modules/Campaigns/language/en_us.lang.php

#### Possible Fix

(...)

#### Context

Why?
- Reducing errors from translators (easy to miss even if Crowdin translation platform alerts users on the missing space)
- Faster translations: avoiding near-duplicated strings and there will be less strings to translate (Crowdin do not use auto-fill from translations memory if strings are not 100% the same).

#### Language numbers - FYI
Translatable words: 53 790 words
Actual Duplicates: 11 068 words (they are auto-filled when translating original ones)
suitecrm_strings

So we need more duplicated strings to reduce translation work. To accomplish that we need a consistency on using language strings.

### PR DESCRIPTION
**Pull request by cameronblaikie**
This is a general comment: languages strings should not end with a space when they are an ending text to be followed by a field data.
Spacing labels from data should be a code thing, not a translations thing.

This is just a work in progress as it is a big task to complete. If there is anything that needs to be changed please let me know as I work my way through completing this issue.
## Description

The following Strings have been updated: (This will update as I change/update more language strings)
'LBL_ALL_OPPORTUNITIES' => 'Total amount of all opportunities is',
'LBL_CREATED_ON' => 'Last run on',
'LBL_TOTAL_PIPELINE' => 'Pipeline total is',
'LBL_TITLE' => 'Title:',
modules/Roles/language/en_us.lang.php:46:    'LBL_ROLE' => 'Role: ',
modules/Roles/language/en_us.lang.php:47:    'LBL_LANGUAGE' => 'Language: ',
modules/Roles/language/en_us.lang.php:54:    'LBL_NAME' => 'Name: ',
modules/Roles/language/en_us.lang.php:55:    'LBL_DESCRIPTION' => 'Description: ',
modules/Roles/language/en_us.lang.php:56:    'LBL_ALLOWED_MODULES' => 'Allowed Modules: ',
modules/Roles/language/en_us.lang.php:57:    'LBL_DISALLOWED_MODULES' => 'Disallowed Modules: ',
modules/Roles/language/en_us.lang.php:58:    'LBL_ASSIGN_MODULES' => 'Edit Modules: ',

modules/Cases/language/en_us.lang.php:48:    'LBL_TOOL_TIP_TITLE' => 'Title: ',
modules/Cases/language/en_us.lang.php:49:    'LBL_TOOL_TIP_BODY' => 'Body: ',
modules/Cases/language/en_us.lang.php:50:    'LBL_TOOL_TIP_INFO' => 'Additional Info: ',
modules/Cases/language/en_us.lang.php:51:    'LBL_TOOL_TIP_USE' => 'Use as: ',
modules/Cases/language/en_us.lang.php:117:    'LBL_AOP_CASE_ATTACHMENTS' => 'Attachments: ',

modules/Emails/language/en_us.lang.php:120:    'LBL_MODULE_TITLE' => 'Emails: ',
modules/Emails/language/en_us.lang.php:192:    'LBL_REPLY_HEADER_1' => 'On ',
modules/Emails/language/en_us.lang.php:224:    'LBL_TO' => 'To: ',
modules/Emails/language/en_us.lang.php:228:    'LBL_ASSIGN_SELECTED_RESULTS_TO' => 'Assign Selected Results To: ',
modules/Emails/language/en_us.lang.php:289:    'LBL_EMAIL_DETAIL_VIEW_SHOW' => 'show ',

modules/Charts/language/en_us.lang.php:47:    'LBL_ALL_OPPORTUNITIES' => 'Total amount of all opportunities is ',
modules/Charts/language/en_us.lang.php:49:    'LBL_CREATED_ON' => 'Last run on ',
modules/Charts/language/en_us.lang.php:79:    'LBL_TOTAL_PIPELINE' => 'Pipeline total is ',
modules/Charts/language/en_us.lang.php:94:    'LBL_TITLE' => 'Title: ',

modules/Schedulers/language/en_us.lang.php:77:    'LBL_EVERY' => 'Every ',
modules/Schedulers/language/en_us.lang.php:78:    'LBL_FROM' => 'From ',
modules/Schedulers/language/en_us.lang.php:79:    'LBL_ON_THE' => 'On the ',
modules/Schedulers/language/en_us.lang.php:80:    'LBL_RANGE' => ' to ',
modules/Schedulers/language/en_us.lang.php:81:    'LBL_AND' => ' and ',
modules/Schedulers/language/en_us.lang.php:82:    'LBL_MINUTES' => ' minutes ',
modules/Schedulers/language/en_us.lang.php:132:    'LBL_CRON_LINUX_DESC1' => 'In order to run SuiteCRM Schedulers, edit your web server user\'s crontab file with this command: ',
modules/Schedulers/language/en_us.lang.php:133:    'LBL_CRON_LINUX_DESC2' => '... and add the following line to the crontab file: ',
modules/Schedulers/language/en_us.lang.php:135:    'LBL_CRON_WINDOWS_DESC' => 'In order to run the SuiteCRM schedulers, create a batch file to run using Windows Scheduled Tasks. The batch file should include the following commands: ',

modules/Users/language/en_us.lang.php:382:    'LBL_WIZARD_FINISH3' => 'Import Data ',
modules/Users/language/en_us.lang.php:388:    'LBL_WIZARD_FINISH9' => 'Configure the Application ',
modules/Users/language/en_us.lang.php:390:    'LBL_WIZARD_FINISH11' => 'Visit SuiteCRM Site ',
modules/Users/language/en_us.lang.php:392:    'LBL_WIZARD_FINISH14' => 'Documentation ',
modules/Users/language/en_us.lang.php:393:    'LBL_WIZARD_FINISH15' => 'Product Guides and Release Notes ',
modules/Users/language/en_us.lang.php:394:    'LBL_WIZARD_FINISH16' => 'Knowledge Base ',
modules/Users/language/en_us.lang.php:396:    'LBL_WIZARD_FINISH18' => 'Forums ',
modules/Users/language/en_us.lang.php:397:    'LBL_WIZARD_FINISH19' => 'Forums dedicated to the SuiteCRM Community to discuss topics of interest with each other and with SuiteCRM Developers ',
modules/Users/language/en_us.lang.php:547:    'LBL_REPLY_HEADER_1' => 'On ',
modules/Users/language/en_us.lang.php:577:    'LBL_TO' => 'To: ',
modules/Users/language/en_us.lang.php:581:    'LBL_ASSIGN_SELECTED_RESULTS_TO' => 'Assign Selected Results To: ',
modules/Users/language/en_us.lang.php:632:    'LBL_EMAIL_DETAIL_VIEW_SHOW' => 'show ',
modules/Campaigns/language/en_us.lang.php:46:    'LBL_FROM_ADDR' => '"From" Address: ',
modules/Campaigns/language/en_us.lang.php:47:    'LBL_REPLY_ADDR' => '"Reply-to" Address: ',
modules/Campaigns/language/en_us.lang.php:48:    'LBL_REPLY_NAME' => '"Reply-to" Name: ',
modules/Campaigns/language/en_us.lang.php:57:    'LBL_NAME' => 'Name: ',
modules/Campaigns/language/en_us.lang.php:66:    'LBL_MODIFIED' => 'Modified by: ',
modules/Campaigns/language/en_us.lang.php:67:    'LBL_CREATED' => 'Created by: ',
modules/Campaigns/language/en_us.lang.php:68:    'LBL_TEAM' => 'Team: ',
modules/Campaigns/language/en_us.lang.php:69:    'LBL_ASSIGNED_TO' => 'Assigned to: ',
modules/Campaigns/language/en_us.lang.php:72:    'LBL_CAMPAIGN_START_DATE' => 'Start Date: ',
modules/Campaigns/language/en_us.lang.php:73:    'LBL_CAMPAIGN_END_DATE' => 'End Date: ',
modules/Campaigns/language/en_us.lang.php:74:    'LBL_CAMPAIGN_STATUS' => 'Status: ',
modules/Campaigns/language/en_us.lang.php:75:    'LBL_CAMPAIGN_BUDGET' => 'Budget: ',
modules/Campaigns/language/en_us.lang.php:76:    'LBL_CAMPAIGN_EXPECTED_COST' => 'Expected Cost: ',
modules/Campaigns/language/en_us.lang.php:77:    'LBL_CAMPAIGN_ACTUAL_COST' => 'Actual Cost: ',
modules/Campaigns/language/en_us.lang.php:78:    'LBL_CAMPAIGN_EXPECTED_REVENUE' => 'Expected Revenue: ',
modules/Campaigns/language/en_us.lang.php:79:    'LBL_CAMPAIGN_IMPRESSIONS' => 'Impressions: ',
modules/Campaigns/language/en_us.lang.php:80:    'LBL_CAMPAIGN_COST_PER_IMPRESSION' => 'Cost Per Impression: ',
modules/Campaigns/language/en_us.lang.php:81:    'LBL_CAMPAIGN_COST_PER_CLICK_THROUGH' => 'Cost Per Click Through: ',
modules/Campaigns/language/en_us.lang.php:83:    'LBL_CAMPAIGN_TYPE' => 'Type: ',
modules/Campaigns/language/en_us.lang.php:84:    'LBL_CAMPAIGN_OBJECTIVE' => 'Objective: ',
modules/Campaigns/language/en_us.lang.php:85:    'LBL_CAMPAIGN_CONTENT' => 'Description: ',
modules/Campaigns/language/en_us.lang.php:95:    'LBL_MODIFIED_BY' => 'Modified by: ',
modules/Campaigns/language/en_us.lang.php:96:    'LBL_CREATED_BY' => 'Created by: ',
modules/Campaigns/language/en_us.lang.php:97:    'LBL_TRACKER_TITLE' => 'Tracker Details ',
modules/Campaigns/language/en_us.lang.php:98:    'LBL_TRACKER_KEY' => 'Tracker: ',
modules/Campaigns/language/en_us.lang.php:99:    'LBL_TRACKER_URL' => 'Tracker URL: ',
modules/Campaigns/language/en_us.lang.php:100:    'LBL_TRACKER_TEXT' => 'Tracker Link Text: ',
modules/Campaigns/language/en_us.lang.php:101:    'LBL_TRACKER_COUNT' => 'Tracker Count: ',
modules/Campaigns/language/en_us.lang.php:102:    'LBL_REFER_URL' => 'Tracker Redirect URL: ',
modules/Campaigns/language/en_us.lang.php:165:    'LBL_FROM_NAME' => 'From Name: ',
modules/Campaigns/language/en_us.lang.php:166:    'LBL_START_DATE_TIME' => 'Schedule Date & Time: ',
modules/Campaigns/language/en_us.lang.php:167:    'LBL_DATE_START' => 'Start Date ',
modules/Campaigns/language/en_us.lang.php:168:    'LBL_TIME_START' => 'Start Time ',
modules/Campaigns/language/en_us.lang.php:169:    'LBL_TEMPLATE' => 'Email Template: ',
modules/Campaigns/language/en_us.lang.php:170:    'LBL_TEMPLATE_FIELD' => 'Email Template: ',
modules/Campaigns/language/en_us.lang.php:171:    'LBL_SUBJECT' => 'Subject: ',
modules/Campaigns/language/en_us.lang.php:213:    'LBL_WIZ_NEWSLETTER_TITLE_STEP3' => 'Campaign Tracker URLs ',
modules/Campaigns/language/en_us.lang.php:237:    'LBL_NEWSLETTER WIZARD_TITLE' => 'Newsletter: ',
modules/Campaigns/language/en_us.lang.php:238:    'LBL_NEWSLETTER_WIZARD_START_TITLE' => 'Edit Newsletter: ',
modules/Campaigns/language/en_us.lang.php:239:    'LBL_CAMPAIGN_WIZARD_START_TITLE' => 'Edit Campaign: ',
modules/Campaigns/language/en_us.lang.php:261:    'LBL_COPY_OF' => 'Copy of ',
modules/Campaigns/language/en_us.lang.php:268:    'LBL_DEFAULT_LOCATION' => 'Default ',
modules/Campaigns/language/en_us.lang.php:349:    'LBL_AMOUNT_IN' => 'Amount in ',
## Motivation and Context

https://github.com/salesagility/SuiteCRM/issues/5652
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by isleshocky77** [comment]
How about either in this or a related ticket removing all of the inconsistent uses of colon ":" at the end of the strings as well. Same argument as you're making above.

**Comment by horus68** [comment]
Agree... colon ":" at the end should avoided as usually its not really useful or required
Note that some languages uses spaces diferently with :  `word:` and others uses `word :`

**Comment by pgorod** [comment]
@cameronblaikie are you checking the code where these labels are used? Or the screens where they are shown?

My concern is that the spaces need to be there, and removing them from the labels will often require adding them to the code that uses the labels. So a simple "find-and-replace" `trailing spaces` with `nothing` won't be enough here, I am afraid...

**Comment by cameronblaikie** [comment]
@pgorod Yes i am checking the front end when changing a label to make sure that it doesn't break anything. That is why i haven't done all of them that were in your list on the original issue :+1:

**Comment by Mac-Rae** [comment]
Assessed :+1: 

Colons defo need to go sometime soon as well

**Pull request merged**
