### PR TITLE
FIX #7923 - Verify the variable is an array

### LINKED ISSUE #7923: PHP Warning in 7.3 with SubPanelDynamic.tpl
#### Issue

Running SuiteCRM with PHP 7.3 we are having a lot warnings in php log:

```php
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/jose/trabajos/gca-suitecrm7.10x/cache/smarty/templates_c/%%EA^EA9^EA90381D%%SubPanelDynamic.tpl.php on line 67
PHP Stack trace:
PHP   1. {main}() /home/jose/trabajos/gca-suitecrm7.10x/index.php:0
PHP   2. SugarApplication->execute() /home/jose/trabajos/gca-suitecrm7.10x/index.php:80
PHP   3. CustomContactsController->execute() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/SugarApplication.php:113
PHP   4. CustomContactsController->processView() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:375
PHP   5. ViewClassic->process() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/Controller/SugarController.php:435
PHP   6. ViewClassic->display() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/SugarView.php:108
PHP   7. ViewClassic->includeClassicFile() /home/jose/trabajos/gca-suitecrm7.10x/custom/include/MVC/View/views/view.classic.php:32
PHP   8. include_once() /home/jose/trabajos/gca-suitecrm7.10x/include/MVC/View/SugarView.php:818
PHP   9. NonDBSubPanel->display() /home/jose/trabajos/gca-suitecrm7.10x/custom/modules/Contacts/SubPanelViewer.php:69
PHP  10. NonDBSubPanel->ProcessSubPanelListView() /home/jose/trabajos/gca-suitecrm7.10x/include/SubPanel/SubPanel.php:238
PHP  11. NonDBListViewSubPanel->process_dynamic_listview() /home/jose/trabajos/gca-suitecrm7.10x/include/SubPanel/SubPanel.php:222
PHP  12. Sugar_Smarty->display() /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSubPanel.php:162
PHP  13. Sugar_Smarty->fetch() /home/jose/trabajos/gca-suitecrm7.10x/vendor/smarty/smarty/libs/Smarty.class.php:1113
PHP  14. Sugar_Smarty->fetch() /home/jose/trabajos/gca-suitecrm7.10x/include/Sugar_Smarty.php:164
PHP  15. include() /home/jose/trabajos/gca-suitecrm7.10x/vendor/smarty/smarty/libs/Smarty.class.php:1263
```
 
AFAIK the problem is in the [line 93 the file themes/SuiteP/include/SubPanel/tpls/SubPanelDynamic.tpl](https://github.com/salesagility/SuiteCRM/blob/master/themes/SuiteP/include/SubPanel/tpls/SubPanelDynamic.tpl#L93)

```smarty
93: {if $ROWS_BUTTONS.$rowHeader|@count gt 0}
94:    {sugar_action_menu id="$rowHeader" buttons=$ROWS_BUTTONS.$rowHeader class="clickMenu subpanel records fancymenu button" flat=false}
95: {/if}
```

That piece of Smarty code is 'transformed' into a php file in `cache/smarty/templates_c` 

```php
<?php if (count($this->_tpl_vars['ROWS_BUTTONS'][$this->_tpl_vars['rowHeader']]) > 0): ?>
```
Sometimes `$this->_tpl_vars['ROWS_BUTTONS'][$this->_tpl_vars['rowHeader']]` is `null` and if you execute `count()` (with PHP 7.3) in a non `countable` object (like null) the Warning is raised

#### Expected Behavior

No Warnings in php log while running SuiteCRM with 7.3

#### Actual Behavior

A lot of warnings in PHP log ;-(

#### Possible Fix

Verify if `$this->_tpl_vars['ROWS_BUTTONS'][$this->_tpl_vars['rowHeader']]` is an array, so we can avoid counting it.

#### Steps to Reproduce

1. Run SuiteCRM with PHP 7.3
2. Load a DetailView with subpanels
3. Reload a Subpanle
4. Check PHP error log

#### Your Environment

* SuiteCRM Version used: 7.10.20
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.04

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

Read #7923

Now the Smarty code is 'transformed' into a php file in `cache/smarty/templates_c` with

```php
<?php if (is_array ( $this->_tpl_vars['ROWS_BUTTONS'][$this->_tpl_vars['rowHeader']] ) && count($this->_tpl_vars['ROWS_BUTTONS'][$this->_tpl_vars['rowHeader']]) > 0): ?>

```

As we can see if the variable is not an array, we do not count it, avoiding Warnings

## How To Test This

1. Run SuiteCRM with PHP 7.3
2. Load a DetailView with subpanels
3. Reload a Subpanle
4. Check this Warning is not in PHP error log

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Hi @Abuelodelanada,

Could you provide some more detailed testing & replication instructions as I have been unable to replicate the error in the latest version without your fix?

**Comment by Abuelodelanada** [comment]
Hi @Mac-Rae 

This happens when there is no button_row in a subpanel.

Try removing the row_buttons in, for example, in `modules/Opportunities/metadata/subpanels/ForAccounts.php`


```diff
-        'edit_button'=>array(
-            'vname' => 'LBL_EDIT_BUTTON',
-            'widget_class' => 'SubPanelEditButton',
-            'module' => 'Opportunities',
-            'width' => '4%',
-        ),
```

If you do this, you will get this in php log when you refresh (or re-order) the subpanel:

```
PHP Notice:  Undefined index: b9990462-021c-0176-f28d-5d8ba61c0243 in /home/jose/trabajos/SuiteCRM/cache/smarty/templates_c/%%8C^8C3^8C367BA2%%SubPanelDynamic.tpl.php on line 72
PHP Stack trace:
PHP   1. {main}() /home/jose/trabajos/SuiteCRM/index.php:0
PHP   2. SugarApplication->execute() /home/jose/trabajos/SuiteCRM/index.php:52
PHP   3. SugarController->execute() /home/jose/trabajos/SuiteCRM/include/MVC/SugarApplication.php:113
PHP   4. SugarController->process() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:373
PHP   5. SugarController->handleActionMaps() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:468
PHP   6. require_once() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:1087
PHP   7. SubPanel->display() /home/jose/trabajos/SuiteCRM/include/SubPanel/SubPanelViewer.php:96
PHP   8. SubPanel->ProcessSubPanelListView() /home/jose/trabajos/SuiteCRM/include/SubPanel/SubPanel.php:236
PHP   9. ListViewSubPanel->process_dynamic_listview() /home/jose/trabajos/SuiteCRM/include/SubPanel/SubPanel.php:220
PHP  10. Sugar_Smarty->display() /home/jose/trabajos/SuiteCRM/include/ListView/ListViewSubPanel.php:162
PHP  11. Sugar_Smarty->fetch() /home/jose/trabajos/SuiteCRM/vendor/smarty/smarty/libs/Smarty.class.php:1113
PHP  12. Sugar_Smarty->fetch() /home/jose/trabajos/SuiteCRM/include/Sugar_Smarty.php:164
PHP  13. include() /home/jose/trabajos/SuiteCRM/vendor/smarty/smarty/libs/Smarty.class.php:1263 
```

It's very strange, but before (when I open the issue) the error was slightly different:

`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in `

I was debuging some hours to find out why the error changed, but I could not find the reason.

Anyway we should check in `themes/SuiteP/include/SubPanel/tpls/SubPanelDynamic.tpl` file if `$this->_tpl_vars['ROWS_BUTTONS'][$this->_tpl_vars['rowHeader']]` is set.

**Comment by Abuelodelanada** [comment]
Hi @Mac-Rae 

Could you read how to test this PR?

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Pull request merged**
