### PR TITLE
Typo prevents duplicate accounts to be displayed

### PR DESCRIPTION
**Pull request by QuickCRM**
Typo in ShowDuplicates.php prevents duplicate accounts to be displayed

## Description

Fix a typo

Create account named a
Create another account named a
A duplicate is found but not displayed
The PHP error log shows PHP Notice:  Undefined variable: dublicate_id in ...

## Motivation and Context

duplicate records are not displayed when possible duplicates are found

## How To Test This

Create account named a
Create another account named a
A duplicate is found and displayed

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Please make this PR against hotfix 7.8.x
You should fix the 3 files where error shows: 
modules/Accounts/ShowDuplicates.php
modules/Contacts/ShowDuplicates.php
modules/Leads/views/view.showduplicates.php
See: https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=dublicate&type=

Note: This PR would allow 7.8.x version to get same fix that the Hotfix branch already got from https://github.com/salesagility/SuiteCRM/pull/5038

**Comment by QuickCRM** [comment]
Sorry for the wrong branch.
I just fixed the error I found and did not check if that also happened in Leads and Contacts.


—
support@quickcrm.fr
www.quickcrm.fr/mobile <http://www.quickcrm.fr/mobile>
Visit our FAQ <http://www.quickcrm.fr/mobile/en/content/16-faq>

**Comment by horus68** [comment]
those other 2 files are also typos and you can edit them in this same PR to be an easy merge

**Comment by horus68** [comment]
Duplicated here: https://github.com/salesagility/SuiteCRM/pull/5039

**Pull request closed without merging**
