### PR TITLE
Please review and merge the following fixes

### LINKED ISSUE #1302: JotPad dashlet doesn't save text when line break is added
Possibly related to this issue:
https://github.com/salesagility/SuiteCRM/issues/786
... which is supposed to be resolved in 7.5.x., but I'm getting this behavior in version 7.5.3., possibly it's a different thing.

Since I didn't get any response in my comments there, and I don't know if there is anybody hearing that conversation on a closed issue, I'm assuming the correct thing is to open a new issue (but correct me if I'm wrong).

The JotPad dashlet will save the text typed into it as long as there aren't any line breaks (even if the paragraph spans several lines). But as soon as the first carriage return character is inserted, when exiting the edit mode the text will disappear and be lost.

(A different issue, not to be confused with this one, is if all text is lost but you are seeing "$defaultText" shown on your JotPad; that is a bug with translation files coming from Crowdin platform; already solved in the latest builds).

### PR DESCRIPTION
**Pull request by 604media**
"JotPad dashlet doesn't save text when line break is added " issue has been fixed.

### CODE REVIEW

**Comment by 604media** [comment]
Same fix is working in my local. Can you please try with below change

**Comment by horus68** [comment]
I think you should make different PR by issue so its easy to tracker.
Workflow:
1- One time fork from the main repository
2- Create a branch from the main branch for each issue to solve. To avoid mistakes you can start by editing file from the main repository and save it. That will create a new branch on your fork where you can keep on working (but that do not allows you to rename the branch!)
3- After all edits done save and create a PR against main repository (you need to ensure it is done for the proper branch)
4- When your PR is merged you can delete your branch

create a new branch for another issue and keep on solving things!

**Comment by 604media** [comment]
Thanks for your comment. Hereafter will follow the above workflow

**Comment by samus-aran** [comment]
Hi @604media Unfortunately we can not accept this PR.

We will only accept PRs made to the 'hotfix' branch.

As @horus68 suggested, we would prefer a new branch for each fix you commit e.g. branch-issue-1302.  We do not merge a number of commits that reference different fixes as this leads to middling of fixes.

As an active contributor we appreciate your work and also your understanding as we are placing in these processes to make the project better to maintain and grow.

**Comment by 604media** [comment]
Thanks. Shall i request PR for these fixes to hotfix branch ?

**Comment by samus-aran** [comment]
Preferable each issue fix would have its own branch.  If you did this and make a PR to hotfix I will look at them for the next release.

Thanks

**Comment by 604media** [comment]
@samus-aran - Thanks.
Created two pull request to hotfix branch
https://github.com/salesagility/SuiteCRM/pull/1327
https://github.com/salesagility/SuiteCRM/pull/1329

Can you please confirm whether I'm in right track?

**Comment by samus-aran** [comment]
That is exactly right @604media !
Again, thanks for your contribution :+1:

**Comment by 604media** [comment]
Thanks for your quick reply

**Pull request closed without merging**
