### PR TITLE
Add ability to choose page size and orientation in pdf templates

### PR DESCRIPTION
**Pull request by sgaved**
## Description

Modify the current pdf templates so that you can choose the page size and orientation of the pdf. Addresses suggestion #628 
## Motivation and Context

Allows users to create pdfs in formats other than A4 Portrait.
## How To Test This

Create a new template and modify the orientation and page size, then create a pdf.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
I'm waiting for this PR to be merged!

**Comment by immhub** [comment]
Hello, i changed my files but when i hit save it does not do anything. (white page)
Please Help

**Comment by sgaved** [comment]
@immhub you would need to do a repair and rebuild and execute the query if you added this manually

**Comment by immhub** [comment]
Sorry for the noob question but what query do i have to execute ?

tkx in advanced 👍

**Comment by immhub** [comment]
Found it .... tks very much 🥇 👍

**Comment by samus-aran** [comment]
[PDF-templates: Allow selection of page format and orientation per template](https://trello.com/c/3NBkOsZ2/139-pdf-templates-allow-selection-of-page-format-and-orientation-per-template)

**Pull request merged**
