### PR TITLE
Fixed #2049 - 7.7.2 - Calendar Activities are off by 1 day

### LINKED ISSUE #2049: 7.7.2 - Calendar Activities are off by 1 day
#### Issue

When you add a call/meeting in the calendar, it displays in the week and month view (for both user and shared calendars) one day before the actual time the activity is scheduled. If you click on the activity to edit it, the appropriate date time is listed. Additionally, the date time for the activity is stored in the database correctly leading me to believe it is an issue with the Calendar view on the client side (Cal.js).
#### Expected Behavior

The event should display at the correct date and time in the calendar view.
#### Actual Behavior

The event is one day before the correct date in the calendar view.
#### Steps to Reproduce

1. Go to Calender module
2. Click Week view
3. Add a new event by clicking anywhere in the week view
4. Observe that the event is displayed one day before the event's actual date in the calendar view
#### Context

Trying to use the calendar is impossible with the entire calendar being off by one day. This is a high priority for the Calendar view itself but low priority in the scope of the larger project.
#### Your Environment

- SuiteCRM Version used: 7.7.2
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Occurs on Chrome and Safari
- Environment name and version (e.g. MySQL, PHP 7): PHP 5.6.20-0, mysql  Ver 15.1 Distrib 10.0.23-MariaDB
- Operating System and version (e.g Ubuntu 16.04): Debian 8

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixes a bug with calendar events being off by 1 day.

## Motivation and Context

Issue reference: #2049

## How To Test This

1. Go to Calender module.
2. Click Week view.
3. Add a new event by clicking anywhere in the week view.
4. Check that the event is displayed correctly.

*Try in various timezones

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Lets add an acceptance test for this.

**Comment by code-ph0y** [comment]
Tested commit - Although I have found that the Calendar doesn't refresh too show the event when you click on the save button. You have to too refresh the browser too show the created event.

**Comment by code-ph0y** [comment]
@Dillon-Brown ^

**Comment by willrennie** [comment]
@Dillon-Brown any movement on this PR as per latest updates from @code-ph0y

**Comment by Dillon-Brown** [comment]
@willrennie Haven't had a chance to take a look yet, i'll mark this as *WIP but I think the original issue would need re-assessed for 7.10.x and this PR re-based.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by Mac-Rae** [comment]
Please rebase this pull request to the hotfix-7.10.x branch as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Comment by Dillon-Brown** [comment]
Original issue resolved in latest hotfix and LTS.

**Pull request closed without merging**
