### PR TITLE
Waste variable removed from SubPanelTiles.tpl

### PR DESCRIPTION
**Pull request by PotyomkinSergey**
Remove undefined variable output

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by PotyomkinSergey** [comment]
Prevent message

> [Notice] Undefined index: date_created occurred

**Comment by Mac-Rae** [comment]
Hi @PotyomkinSergey,

Please rebase this pull request onto hotfix-7.10.x as pull requests directly to master are no longer accepted.
For more information please take a look at our [contribution guidelines](https://docs.suitecrm.com/community/contributing-code/).

If you would like assistance please ensure you select "Allow edits from maintainers" checkbox and leave us a message @tagging me! 

Thanks :+1:

**Comment by serhiisamko091184** [comment]
Hey @PotyomkinSergey ,

thanks for your contribution one more time,

would you be so kind to sign the CLA for further assessment:

image

Thanks in advance.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hello @PotyomkinSergey ,

thank you for the contribution,
we can accept your contribution only after signing CLA.
We appreciate if it would be possible to recreate this PR with signed CLA in the future.

Thank you!

Regards,
Serhii

**Pull request closed without merging**
