### PR TITLE
Temp PR

### PR DESCRIPTION
**Pull request by craigpanton**
This is a temporary PR required for travis testing. This will be removed once complete.

### CODE REVIEW

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 100
- Added 84
           

Complexity increasing per file
==============================
- tests/unit/phpunit/include/SugarLogger/LoggerManagerTest.php  2
- tests/unit/phpunit/include/TimeDateTest.php  1
- tests/SuiteCRM/Test/SuitePHPUnitFrameworkTestCase.php  3
- lib/Exception/NotAllowedException.php  1
- tests/unit/phpunit/include/database/DBManagerTest.php  1
- tests/unit/phpunit/include/Localization/LocalizationTest.php  1
- lib/Exception/NotFoundException.php  1
- include/TestCaseAbstract.php  5
- tests/unit/phpunit/data/SugarBeanMock.php  12
- tests/unit/phpunit/lib/SuiteCRM/Utility/SuiteLoggerTest.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4816738&bid=16017838)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 100
- Added 84
           

Complexity increasing per file
==============================
- tests/unit/phpunit/include/database/DBManagerTest.php  1
- tests/SuiteCRM/Test/SuitePHPUnitFrameworkTestCase.php  3
- lib/Exception/NotFoundException.php  1
- lib/Exception/NotAllowedException.php  1
- include/TestCaseAbstract.php  5
- tests/unit/phpunit/lib/SuiteCRM/Utility/SuiteLoggerTest.php  2
- tests/unit/phpunit/include/SugarLogger/LoggerManagerTest.php  2
- tests/unit/phpunit/include/TimeDateTest.php  1
- tests/unit/phpunit/data/SugarBeanMock.php  12
- tests/unit/phpunit/include/Localization/LocalizationTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4816738&bid=16017838)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 105
- Added 94
           

Complexity increasing per file
==============================
- lib/Exception/NotAllowedException.php  1
- tests/unit/phpunit/include/SugarLogger/LoggerManagerTest.php  2
- lib/Exception/NotFoundException.php  1
- tests/unit/phpunit/lib/SuiteCRM/Utility/SuiteLoggerTest.php  2
- tests/unit/phpunit/data/SugarBeanMock.php  12
- tests/unit/phpunit/include/Localization/LocalizationTest.php  1
- tests/SuiteCRM/Test/SuitePHPUnitFrameworkTestCase.php  3
- include/TestCaseAbstract.php  5
- tests/unit/phpunit/include/database/DBManagerTest.php  1
- tests/unit/phpunit/include/TimeDateTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4816738&bid=16017838)

**Comment by craigpanton** [comment]
No longer required.

**Pull request closed without merging**
