### PR TITLE
Fixed #1987 - Quick create arrow not aligning to the button text

### LINKED ISSUE #1987: Quick create arrow not aligning to the button text
#### Issue

The quick create button at the top of the page has an arrow which has a fixed background-position, so if the CREATE text is localized to a longer text (like ERSTELLEN in german) the arrow will be positioned inside the text.

image
#### Expected Behavior

The arrow should align after the text (or to the right side of the button), no matter how long it is.
#### Actual Behavior

The arrow positioned inside the text if the label is longer than the english CREATE label.
#### Possible Fix

Offset the background to the right instead of fixed position, like:
background-position: right 10px top;
#### Steps to Reproduce

Open SuiteCRM with a language pack installed where the CREATE label is localized to a longer text.
#### Your Environment

- SuiteCRM Version used: 7.7.1
- Browser name and version: Google Chrome 52.0.2743.116 m (64-bit)
- Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
- Operating System and version (e.g Ubuntu 16.04): Windows 10 / Windows Server 2012 R2

### PR DESCRIPTION
**Pull request by shogunpol**
Fixed - Quick create arrow not aligning to the button text
## Description

Fixed - Quick create arrow not aligning to the button text
References issue #1987 

Open SuiteCRM with a language pack installed where the CREATE label is localized to a longer text.

## Motivation and Context

Improve design and appearience of the quick search drop-down
## How To Test This

Repeat steps from replication issue section
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@shogunpol please revise the conflicting files: themes/SuiteP/css/style.css

**Comment by shogunpol** [comment]
@horus68 , done

**Comment by horus68** [comment]
@shogunpol Closed but not merged?
Changes are not required anymore by some other PR?

**Comment by shogunpol** [comment]
Just created new PR without branch issues: #2832

**Pull request closed without merging**
