### PR TITLE
Make sure deleted users are not used when validating users

### LINKED ISSUE #3440: User logins are checked against deleted users with same username
#### Issue
Resetting the password thanks to the 'Forgot password?' button did not seem to work for some users. We managed to find that those users where previously created and deleted with the same username. Later on we discovered that Suitecrm did not check if a user record was not deleted at all.

#### Expected Behavior
Forgot password email link might reset or not the current non deleted active user who requested the password reset. (I haven't checked that.)
I expect that when an user authenticates Suitecrm checks current credentials.
#### Actual Behavior
Forgot password email link might reset or not the current non deleted active user who requested the password reset. (I haven't checked that.)
When an user authenticates Suitecrm checks old deleted credentials and avoids the user to login.

#### Possible Fix
You can find current wrong code here: https://github.com/salesagility/SuiteCRM/blob/e1c3a1792ab3eb5f81c956d132902e36586d0a7a/modules/Users/User.php#L755-L762

Before:
```
	public static function findUserPassword($name, $password, $where = '', $checkPasswordMD5 = true)
	{
	    global $db;
		$name = $db->quote($name);
		$query = "SELECT * from users where user_name='$name'";
		if(!empty($where)) {
		    $query .= " AND $where";
		}
```

After:

```
	public static function findUserPassword($name, $password, $where = '', $checkPasswordMD5 = true)
	{
	    global $db;
		$name = $db->quote($name);
		$query = "SELECT * from users where user_name='$name'";
		if(!empty($where)) {
		    $query .= " AND deleted=0";
		    $query .= " AND $where";
		}
```

#### Steps to Reproduce
1. Create an user with id: user1
2. Delete that recently created user user1
3. Create another user with the same id: user1
4. If needed tweak the database so that LIMIT 0,1 returns the entry corresponding to the old entry and not the current one.
5. Try to reset your forgotten password
6. User is shown an error trying to enter when using the new password. I'm not sure what the message was but it was something similar to 'Expired credentials or cookies'.

#### Context
Resetting the password thanks to the 'Forgot password?' did not seem to work for some users. 

#### Additional notes
This might be a security concern if you deleted an user (e.g. from a no longer working employee at the company), created a new one with the same userid and somehow your old employee can login into the new user account but using his old credentials.

#### Your Environment

* SuiteCRM Version used: 7.3.1 (Checked the wrong code it's still present in develop branch)
* Chrome 57
* PHP 5.3
* Operating System and version: Ubuntu 14.04

### PR DESCRIPTION
**Pull request by adriangibanelbtactic**
Closes #3440 

## Description
When the user validates its login now it discards deleted users thanks to adding deleted=0 to the mysql query.

## Motivation and Context
After deleting and recreating a user then, depending on how mysql tables is handled then users cannot longer login. You can see similar problems when you try to reset the password and it does not work.

## How To Test This
Try to add duplicated users entries in the mysql users table where you change deleted=0 into deleted=1 and see if anyone of them is taken into account when logging it. If it is not then the bug has been succesfully fixed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by chris001** [comment]
@adriangibanelbtactic 
You should switch the branch to `salesagility:hotfix` because it's a bug fix.

**Comment by adriangibanelbtactic** [comment]
I have switched the base branch to salesagility:hotfix.
I don't see that actions triggers additional travis checks to make sure there are no conflicts (unless those tests were amazinly fast).

Was I expected to deleted the pull request and create a new pull request with new base branch?

Thank you.

**Comment by horus68** [comment]
you don't need to create a new PR, its fine just having to switch the branch.
Hotfix branch is where to merge when PR is a bug fix

**Comment by chris001** [comment]
@adriangibanelbtactic 
There were no additional tests run by Travis because unfortunately @salesagility has not yet added #3600 (all the unit tests) to the `hotfix` branch.

**Pull request merged**
