### PR TITLE
All of the changes on current CR list

### PR DESCRIPTION
**Pull request by haris-raheem**
All of the changes on current CR list
## Description
1. Project module and Project Templates
2. Gantt view
3. Resource Calendar
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [ ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by haris-raheem** [comment]
reopened the PR

**Comment by horus68** [comment]
This PR needs more detailed infos on the issue and what is expected to do.
Also there are some files with conflict, hope you can fix it!

**Comment by samus-aran** [comment]
Thanks @horus68 - I'm in direct contact with Haris in regards to this PR :)

**Comment by haris-raheem** [comment]
i am looking into it but it's too old and now i am trying to remember what we did there.
do you guys still need it in develop branch?

**Comment by haris-raheem** [comment]
it was actually created for projects_enhance branch but it was closed by matt lorimer and he told me to make it against develop branch.

**Comment by haris-raheem** [comment]
i have looked into the conflicts and they are minor which can easily be managed while merging.

can you guys let me know your  expectations on this PR? i-e what details you might need etc.

________________________________

**Pull request closed without merging**
