### PR TITLE
Fix #9781 Fetch existing Call/Meeting Reminder data in quickeditview …

### LINKED ISSUE #9781: Meetings and Calls quick edit via Calender does not populate correct reminders
Meetings and Calls quick edit via Calendar does not populate correct reminders

#### Issue

1. create a meeting/call with reminders different from user default reminder setting for example if email reminder setting is 30 minutes before call default for user change it 15 minutes before for this meeting/call
2. Edit the meeting/call via calendar edit functionality
3. The edit popup opened will show default user reminder settings
#### Expected Behavior

Editing a meeting/call via calendar should show the meeting/calls reminders not users default reminders

#### Actual Behavior

Editing a meeting/call via calendar shows users default reminders

#### Steps to Reproduce

1. create a meeting/call with multiple reminders
2. Edit the meeting/call via calendar edit functionality
3. The edit popup opened will show default user reminder settings (Not multiple reminders)

#### Context

Priority : Medium
#### Your Environment

* SuiteCRM Version used: 7.12.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 105.0.5195.102 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): Windows

### PR DESCRIPTION
**Pull request by abuzarfaris**
Fetch saved reminder data when opening quick edit view for existing Calls and meetings

## Description

Added code in view.quickedit.php in calendar module to assign reminder data from existing record to smarty variables
Steps to Produce Issue
1. create a meeting/call with reminders different from user default reminder setting for example if email reminder setting is 30 minutes before call default for user change it 15 minutes before for this meeting/call
2. Edit the meeting/call via calendar edit functionality
3. The edit popup opened will show default user reminder settings
## Motivation and Context

Allows users to correctly edit a meeting or call via calendar

## How To Test This

1. create a meeting/call with reminders different from user default reminder setting for example if email reminder setting is 30 minutes before call default for user change it 15 minutes before (different that default) for this meeting/call
2. Edit the meeting/call via calendar edit functionality
3. The edit popup opened will show correct reminder settings
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
The `loadRemindersDataJson` call seems to repeat the `loadRemindersData` call, and it will have a performance penalty since it calls get_full_list on the bean.

I'd say, if we really the data twice, one in JSON and one as an array, then we could just run the json_encode here, instead of going into the database twice. But probably we can just dispense with the JSON version...

**Comment by abuzarfaris** [comment]
In the ```loadRemindersData``` function the first if ```if (!isset(self::$remindersData[$eventModule][$eventModuleId]) || !$eventModuleId || $isDuplicate)``` checks if reminder data is already loaded it will not reload this data. So there isn't much performance penalty here

**Comment by pgorod** [comment]
You are right, I hadn't noticed that when I looked at the code, sorry. 👍

**Comment by jack7anderson7** [comment]
Hi @abuzarfaris,

Could you please redirect this PR to the `hotfix` branch

Thanks,
Jack

**Comment by abuzarfaris** [comment]
> Hi @abuzarfaris,
> 
> Could you please redirect this PR to the `hotfix` branch
> 
> Thanks, Jack

Changed the branch to ```hotfix```

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Review by jack7anderson7 — APPROVED** [review]

**Pull request merged**
