### PR TITLE
Filter email templates on Events

### PR DESCRIPTION
**Pull request by QuickCRM**
## Description

Added a new option in email templates types to make selecting events invite template easier

## Motivation and Context

Makes it easier to filter invite templates without all email and campaign templates

## How To Test This

Create a new event. 
Only templates with type event are proposed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by willrennie** [comment]
@QuickCRM hey benoit, do you have some updates for us as per @cameronblaikie comments?

**Comment by QuickCRM** [comment]
Sorry I missed that post from @cameronblaikie .
We are using that already on two production instances and have no problem.

**Comment by willrennie** [comment]
@cameronblaikie please can you review as per @QuickCRM comments?

**Comment by Mac-Rae** [comment]
Please rebase this pull request onto hotfix-7.10.x as the hotfix branch is now specifically for 7.11.x issues.

Please take a look at our contribution guidelines for more information.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
