### PR TITLE
All menu - Display module by alphabetical order

### PR DESCRIPTION
**Pull request by horus68**
## Description

All menu - Display module by alphabetical order
The admin "All" menu displays some entries to modules and their
associated modules as in "Products" and  "Product categories"
In english this allows they are listed next to each other, ordered by
the letter "P".
But when translating many language rotate the words on sentences, so it
turns into: "Produtos" and  "Categorias de Produtos" (example for Portuguese but its
the same on some other languages)... so they are placed in different
lines (here ordered by letters P and C)
This makes it difficult to browse for some modules with different
entries (as the Maps module)
Making a hard separation from the module name (products / maps) and the
dependent action (categories / cache / markers) makes it easy to
translators to have different translation form any similar wording from
the values on other language files!

**Note: this change is not a real alphabetical ordering (the feature should be available!) mas a workaround that allows each dependent modules be listed together**
## Motivation and Context
Easy list and navigation on the  "All menu"

## How To Test This

Apply changes in the "include" language file, reload!
See pic:

Same in selecting modules to menus (see Mapas)
2017-09-20 18_53_42-microsoft edge

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
  functionality to change)
### Final checklist
- [x] My code follows the code style of this project found
  [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to
  Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM)
  guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@samus-aran this should be an easy one to be merged!

**Comment by samus-aran** [comment]
@horus68 
A little clarification if possible - what do the dashes do that allows them to be order appropriately?

**Comment by horus68** [comment]
@samus-aran This is for translated UI on menus and also for better user experience when navigating menus to do a task.  We allways start by thinking on the module name and then its related dependencies. 
If we want to work on the Maps Cache we will look for maps and then its cache. 
When someone is looking in the menu to go edit a module related to working with maps he would expect that any maps module are next of each other in the menu. Then they pick one.
Entering ALL menu (the first time) it displays module names by first letter. This goes fine in english, not on other languages.

Example:
`Target Lists` translated to Portuguese, word by word, is Target=Alvos / Lists=Listas.
But Portuguese (and some other languages) rotate words on some expressions, so it would be translated as `Listas de alvos`  starting by L . But the Targets menu is translated as "Alvos" and listed by A. 

Using a dash here it will break the expression so it can be translated as `Alvos - Listas`
Note: `Listas de alvos` is a correct translation in a sentence (or other parts of SuiteCRM) but not ok for the ALL menu as it will not be listed near the module name for "Targets" (or "Alvos").

Same goes for Maps: Areas, Cache or markers (as shown in the image on the initial post)

Pinging some users, maybe they can explain it better then me or find a better way!
@pgorod @pribeiro42 @likhobory @urdhvatech @bmwtourer @SoapJson @Mausino

**Comment by gunnicom** [comment]
Yes the menu is annoying if translated ... always searching.
I definitly would prefer a solution like sorting by translated module name.

**Comment by maladrill** [comment]
It is one of the worst UX problems when using the menu. I searched for this fix multiple times over years

**Comment by horus68** [comment]
@Dillon-Brown conflicts solved. They will happen again in the future if this is not merged!

**Comment by Dillon-Brown** [comment]
@horus68 Can you make this for the develop branch? Thanks.

**Comment by horus68** [comment]
@Dillon-Brown Changed the base branch from hotfix to develop using the Github interface but now there are 45 files changed when originally I had just made edits to the file  include/language/en_us.lang.php

**Comment by Dillon-Brown** [comment]
@horus68 The easiest thing to do would probably be to make a new branch off of develop, pull in the changes from https://github.com/salesagility/SuiteCRM/compare/hotfix...horus68:All-menu-links and make a new PR to the develop branch.

**Comment by horus68** [comment]
@Dillon-Brown back to hotfix to show what is really edited. 
This is not a new feature proposal, this is only language edits to make it easy to translate.
A feature would be a function to sort module names on each the screens.
Not here, this is only edits in the language file.

**Comment by salesagility-davidthomson** [comment]
I would like to test this for 7.8.x but I cannot find a Portuguese language pack for this version. I actually cannot find any language packs for 7.8.x.

**Comment by horus68** [comment]
@salesagility => SuiteCRM versions: 7.8.x and 7.9.x = Download zip language packs from sourceforge: https://sourceforge.net/projects/suitecrmtranslations/files/
SuiteCRM version: 7.10.x = Download here to get latest zip from Crowdin https://crowdin.com/project/suitecrmtranslations

**Comment by salesagility-davidthomson** [comment]
@horus68 I can only see a language pack for 7.9.x there does not seem to be a pack for 7.8.x on sourceforge: https://sourceforge.net/projects/suitecrmtranslations/files/
Do you know where I can get the 7.8.x pack from?

**Comment by horus68** [comment]
Same pack for versions 7.8.x and 7.9.x

**Comment by salesagility-davidthomson** [comment]
@horus68 Ok thanks for letting me know I'll try it with the 7.9.x pack. I need to test with 7.8.x because that is the current LTS version.

**Comment by horus68** [comment]
named to "for_7.9.x_or_older_versions"  :)
https://sourceforge.net/projects/suitecrmtranslations/files/

**Comment by salesagility-davidthomson** [comment]
I have created a pull request
https://github.com/salesagility/SuiteCRM/pull/1866
for this into the hotfix-7.8.x branch. It was easier to create a new branch with the changes required that to try and fix the conflicts when pulling into this branch. This will be processed soon. This pull request should now be closed.

**Pull request closed without merging**
