### PR TITLE
Navbar module highlighting

### PR DESCRIPTION
**Pull request by jobvector**
Implemented highlighting of the currently active module.

Referring to & Fixing:
https://github.com/salesagility/SuiteCRM/issues/583

### CODE REVIEW

**Comment by jobvector** [comment]
Why is this a invalid enhancement, is their any other solution implemented to the suitecrm that has the same feature?

**Comment by samus-aran** [comment]
@jobvector - There is a planned new theme coming out in beta that would overwrite this.  That is why it was set to invalid.

**Comment by pgorod** [comment]
@samus-aran I have a question about closing this. Is the new theme is coming out with a different name (not SuiteR)? If so, I would still do something to SuiteR to fix it, because it's not going to disappear, people will still use older versions, older themes (sometimes due to some technical difficulty), and that theme would really benefit from having this improved. If the LTS version is going to have SuiteR on it, it should have a fixed SuiteR on it...

(BTW, I suggested a different visual solution in a comment on the Issue #583 .)

**Comment by jobvector** [comment]
for us any visual solution would be ok

**Pull request closed without merging**
