### PR TITLE
Fixed - #6310 Can't use collapsed subpanel row count feature on older…

### PR DESCRIPTION
**Pull request by samus-aran**
… PHP versions

Provides fix for https://github.com/salesagility/SuiteCRM/issues/6310
Able to replicate within PHP 7-
Error log showed :
PHP Fatal error:  Cannot access empty property in /var/www/html/SuiteCRM-7.10.8/include/SubPanel/SubPanelRowCounter.php on line 144, 

## How To Test This

0. Be on PHP 5.5.9
1. Open users profile and enable Show collapsed subpanel hint option on layout options tab
2. Open any account record in Detail View
3. Should be able to see subpanels.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by likhobory** [comment]
Tested on PHP 5.5.9, woks as expected, BUT
Empty activity subpanel is always shown as a subpanel with some records.

default

**Comment by samus-aran** [comment]
@likhobory Interesting. I haven't been able to replicate this yet..... When I run through this Activities/History doesn't flag up as relationships.. I'll see how we can work on this but ideally we want to get this PR in asap.

**Comment by likhobory** [comment]
OK, I'll open additional issue.

**Pull request merged**
