### PR TITLE
Remove HTMLPurifier ConfigForm.js file.

### PR DESCRIPTION
**Pull request by connorshea**
This probably isn't necessary and can be removed?

Just make sure the tests pass in CI.

### CODE REVIEW

**Comment by connorshea** [comment]
Flaky tests >.>

I guess we haven't merged the flaky test fixes into develop yet.

**Comment by Dillon-Brown** [comment]
Yeah looks like develop is still on 7.11.4.

**Comment by connorshea** [comment]
Rebased and CI passes now \o/

**Comment by connorshea** [comment]
@Dillon-Brown bump

**Comment by Mac-Rae** [comment]
Addressed by Travis :+1:

**Pull request merged**
