### PR TITLE
Fix user action menu support link

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fix for global support forum link.

## How To Test This

1. Check that the link still takes you to community forums.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed :+1: 

I will note that the link redirects on the same page where previously I believe it opens a new tab

**Comment by pgorod** [comment]
A new tab would definitely be better for this, imho

**Comment by Dillon-Brown** [comment]
> A new tab would definitely be better for this, imho

Agreed, the problem here is that these are loaded in dynamically but I'll see if I can add in a blank ref specifically for this link so that it opens in a new tab.

I'm generally opposed to opening another website in a new tab for security reasons but in this case, since it will only ever contain a link to our forums I guess it should be fine.

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Pull request merged**
