### PR TITLE
Closed #1764 by adding translations to SuiteSpots

### LINKED ISSUE #1764: SuiteSpots localization
Subj.
All this strings dispayed in English only: https://github.com/salesagility/SuiteCRM/blob/v7.7-rc/include/javascript/suitespots/suitespots.js#L346-L401

### PR DESCRIPTION
**Pull request by paulgodley**
## Description
Closed #1764 
This fix adds the localisation of labels for Suite Spots to allow for all of the labels and messages to be translated appropriately.
This has been tested with the French language pack.

As per https://github.com/c3js/c3/issues/1566, there is also a fix for the mouse over in Chrome (to stop throwing errors).

## Motivation and Context
This allows for the language labels and data to be translated appropriately for Suite Spots.

## How To Test This
Install a language pack and change language.  The spots module should reflect this on all of the labels and options.

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by likhobory** [comment]
@paulgodley 
I have been tested your PR with the [Russian](https://github.com/likhobory/SuiteCRM7RU) langpack and all combobox values in the heatmap table still displayed in English.
http://savepic.ru/10623600.png

**Comment by paulgodley** [comment]
Hi @likhobory.  Can you please go into cache/modules/Spots and delete all of the json files and then retry this?

**Comment by likhobory** [comment]
I did it, but nothing has changed.
[cache/modules/Spots](https://yadi.sk/d/6JpFjGZktg582)

**Comment by paulgodley** [comment]
Can you please check the json files in cache/modules/Spots and see what language they are in?

**Comment by paulgodley** [comment]
I have just installed the Russian language pack and it shows the correct labels, shown below:
image

**Comment by likhobory** [comment]
Please create another spot with simple pivot  table that displays some combobox values.
For example, I added account types field and I see only English labels in both cases:
sspot

**Comment by paulgodley** [comment]
Hi @likhobory can you please go into cache/modules/Spots and see what json files are there?  There should be some with "_ru" for the Russian language.  Can you please open these and check if the data contained therein is translated into Russian or if it is in English?

**Comment by likhobory** [comment]
Yes, there are some encoded json files with "_ru" ( I have [attached](https://yadi.sk/d/6JpFjGZktg582) them in the second post) and they don't contain any Russian text.

**Comment by paulgodley** [comment]
Hi @likhobory.  The problem is that I have translated the label values (for the pivot) but not the enum values for the data fields.  This will take me a bit of time to sort / test but I will let you know when this is live.

**Comment by likhobory** [comment]
ok, thanks!

**Comment by paulgodley** [comment]
I will create a new pull request once the translations are all sorted.  I have closed this one as I have been solidifying the spots code while working on this.

**Pull request closed without merging**
