### PR TITLE
FIX #7509 - Using prefix index to not hit Key threshold in MySQL5.6/UTF-8

### LINKED ISSUE #7509: Index hits Key threshold in MySQL5.6/UTF-8
#### Issue

A forum users has discovered that installing SuiteCRM 7.11.6 (>7.11.5 are not affected) produces a failure due to the combination of the fields to create a DB index. 
It appears that the issue is due to MySQL 5.6 hitting the threshold of 1000 characters (MyISAM) or 767 (InnoDB). MySQL 5.7 has a higher threshold which is 3072. However on top of that threshold character set also contribute to this.. in this case it's UTF8 which adds more characters rather than if it was e.g. latin1.

This issue was introduced by fix provided to resolve this issue #7351 and it wasn't picked up by tests - most tests run on MySQL 5.7 but our MySQL 5.6 environment also didn't fail.

#### Expected Behavior

1. Installation should not fail on MySQL 5.6+

#### Actual Behavior

1. Installation fails (appears) on MySQL 5.6 and using UTF-8

#### Possible Fix

Either:
1. Revert original fix by reducing the character limit from 255 to suggested 100
or
2. Cap the character set within the index itself (needs to confirm this is doable).

#### Steps to Reproduce

Can't replicate this locally or on travis (tho suspect that on travis the install is different)
Please see error logs of user's post.
https://suitecrm.com/suitecrm/forum/announcements/26612-suitecrm-7-11-6-7-10-18-7-8-31-maintenance-patch-now-available#86505

#### Your Environment

* SuiteCRM Version used: 7.11.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): See Post
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6
* Operating System and version (e.g Ubuntu 16.04): WAMP

@Abuelodelanada Are you able to have a wee look at this?

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

See #7509

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed by Travis :+1:

**Comment by gwsimon** [comment]
I just wanted to share an issue I had upgrading a local installation of SuiteCrm 7.10.11 to 7.10.19 using the 7.10.x to 7.10.19 upgrade package.  All went well until the final (5th) step of the installation when I received a database error.  I have attached the SQL error I was receiving.  You can see my MS-SQL server does not like the syntax where the index is trying to be built off of what appears to be a portion (first 30 characters) of the last_name and first_name fields.  After some trial and error I determined the way for me to get over this was to remove the (30) from both places in the CREATE INDEX sql statement.  That seemed to work fine and I am moving forward.  Here is a link to my community issue logged too:  URL : https://suitecrm.com/suitecrm/forum/installation-upgrade-help/27042-upgrade-packate-7-10-x-to-7-10-19-db-error-create-index-last-name-30-fails/88048 
[sqllog.txt](https://github.com/salesagility/SuiteCRM/files/3477766/sqllog.txt)

**Comment by Dillon-Brown** [comment]
Thanks for the information @gwsimon, this should also be related to #7675.

**Comment by Abuelodelanada** [comment]
I have been doing some research about MS SQL, and I think this DB engine does not supports prefixed indexes.

I can write a fix for that engine, but I have no way to test it. 
Any ideas about how to test it?

**Comment by pgorod** [comment]
This came up in the Forums again today:

https://suitecrm.com/suitecrm/forum/installation-upgrade-help/27334-database-error-upgrading-7-11-5-to-7-11-8/

**Comment by bunglex** [comment]
I also had to change the 'len' from 255 to 30 at lines 144 ad 151

**Pull request merged**
