### PR TITLE
Hotfix merge

### PR DESCRIPTION
**Pull request by craigpanton**
## Description

Preparation for 7.11.11 release.

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 208
- Added 378
           

Complexity increasing per file
==============================
- modules/Users/GoogleApiKeySaverEntryPoint.php  5
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchIntegrationTest.php  2
- modules/Administration/Search/View.php  1
- tests/unit/phpunit/lib/SuiteCRM/Search/TestCustomEngines/MockSearch.php  1
- include/Smarty/plugins/function.search_controller.php  1
- modules/Administration/Search/ElasticSearch/scripts.js  2
- include/GoogleSync/GoogleSync.php  7
- lib/Utility/ArrayMapper.php  7
- lib/Log/CliLoggerHandler.php  1
- lib/Search/SqlSearch/SimpleSqlSearchEngine.php  4
- lib/Search/UI/SearchResultsView.php  1
- tests/unit/phpunit/include/GoogleSync/GoogleSyncMock.php  3
- lib/Search/Index/Documentify/SearchDefsDocumentifier.php  9
- modules/MailMerge/controller.php  1
- include/SugarTheme/SugarTheme.php  1
- modules/AOW_WorkFlow/AOW_WorkFlow.php  1
- tests/acceptance/lib/Search/ElasticsearchCest.php  2
- modules/Home/Search.php  1
- modules/Administration/Search/scripts.js  1
- lib/Search/Index/Documentify/JsonSerializerDocumentifier.php  1
- lib/Log/SugarLoggerHandler.php  8
- modules/Home/Dashlets/ChartsDashlet/ChartsDashlet.php  1
- modules/Administration/Search/ajaxSubmit.js  2
- lib/Search/ElasticSearch/ElasticSearchClientBuilder.php  7
- tests/unit/phpunit/modules/Users/GoogleApiKeySaverEntryPointMock.php  1
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchInstallTest.php  5
- modules/AOR_Fields/AOR_Field.php  1
- lib/Search/SearchConfigurator.php  5
- lib/Search/UI/MVC/Controller.php  2
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchEngineTest.php  1
- lib/Search/ElasticSearch/ElasticSearchEngine.php  2
- modules/Administration/Search/Controller.php  2
- tests/unit/phpunit/lib/SuiteCRM/Search/AbstractDocumentifierTest.php  1
- lib/Search/SearchWrapper.php  7
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
+ include/LangText.php  -14
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by connorshea** [comment]
Looks like the composer.json/composer.lock got screwed up?

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by craigpanton** [comment]
> Looks like the composer.json/composer.lock got screwed up?

Yeah looks like it was an issue with the lock file during merge. That should be resolved now. Thanks for taking a look :)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- modules/MailMerge/controller.php  1
         

Complexity decreasing per file
==============================
+ install/installConfig.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4902210&bid=16232845)

**Pull request merged**
