### PR TITLE
Fixed #508 - Now we can add multiple JS files to a view in only one minified JS file

### LINKED ISSUE #508: Add multiple JS files to a view in only one minifyed JS file.
The most common way to add JS files to a view is through metadata files, such as editviewdefs.php.

editviewdefs_accounts

This way is simple, but has two problems:
- The application makes many requests as files included.
- Each file is not minifyed.

This produces unnecessary overload to the webserver and network.

We should implement a way to load multiple JS files from the constructor of the view, and the application should automatically join and minify all these files.
This will produce only one JS request per view

view edit php_accounts

### PR DESCRIPTION
**Pull request by Abuelodelanada**
The most common way to add JS files to a view is through metadata files, such as editviewdefs.php.

editviewdefs_accounts

This way is simple, but has two problems:
- The application makes many requests as files included.
- Each file is not minifyed.

This produces unnecessary overload to the webserver and network.

We should implement a way to load multiple JS files from the constructor of the view, and the application should automatically join and minify all these files.
This will produce only one JS request per view

view edit php_accounts

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Abuelodelanada** [comment]
FIX https://github.com/salesagility/SuiteCRM/issues/508

**Comment by chris001** [comment]
@Abuelodelanada Could this be adapted to override the existing default function for adding javascript to a page.

**Comment by samus-aran** [comment]
[Add multiple JS files to a view in only one minifyed JS file.](https://trello.com/c/4Fnb2OhF/146-add-multiple-js-files-to-a-view-in-only-one-minifyed-js-file)

**Comment by Abuelodelanada** [comment]
Hi @samus-aran 

We have made this feature for [our big implementation](https://www.gcoop.coop/gestion-de-contacto-con-el-asociado-banco-credicoop).
For us was **very** useful in performance terms. 
@chris001 suggested to override the existing default function for adding javascript to a page.

We did it this way so that both are available and to avoid generating conflicts with what was already there.

Do you think it's worth working on resolving the conflicts that appeared after we did the PR, or do you think we should follow Chris's suggestion?

There is also the possibility that this is not a feature that you want in SuiteCRM and it's fine ;-)

**Comment by Abuelodelanada** [comment]
Hi @clemente-raposo 
I'll take a look at your suggestion

**Comment by Abuelodelanada** [comment]
Closed because PR #6672 is a better solution.

**Pull request closed without merging**
