### PR TITLE
Fix for issue: #7558 Contract Reminder Call get wrong parent_id

### PR DESCRIPTION
**Pull request by gody01**
When Contract is created coresponding Reminder Call get AccountId as parent_id.
Wher Contract is edited, coresponding Reminder Call get ContractId as parent_id 

## Description
Relocated call 
  $this->createReminder(); 
below 
  $return_id = parent::save($check_notify);
since createReminder needs id of Contract to determine parent_id.

Also removed call to $this->createLink(); and removed function createLink, since it creates wrong parent for Call.

Issue: #7558

## Motivation and Context
Contract generated Reminder Calls should have consistent parent_id on creation and subsequent edit/saves.
parent_id should be Contract_id, as explained in the issue #7558

## How To Test This
- Create Contract with Reminder Date
- Check generated Reminder Call
- Call should have Contract as parent_it (related to)

- Edit Contract
- Save Contract
- Check generated Reminder Call
- Call should still have Contract as parent_id

## Types of changes

- [ X] Bug fix (non-breaking change which fixes an issue)

### Final checklist

- [X ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by cameronblaikie** [comment]
Assesed :+1:

**Comment by cameronblaikie** [comment]
Hi @gody01 This seems to be to the wrong branch, could you rebase this to hotfix-7.10.x
Thanks.

**Comment by craigpanton** [comment]
It looks like the addition of this creates a new issue where it will create a new call every time. This is likely because it is bypassing the createLink() call.

**Comment by serhiisamko091184** [comment]
Hello, @gody01 

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @gody01 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

**Pull request closed without merging**
