### PR TITLE
Auto-close success message boxes in ModuleBuilder

### PR DESCRIPTION
**Pull request by tsitle**
## Description

Auto-close annoying success message boxes in Module Builder.

## Motivation and Context

When working with the Module Builder every 2nd click a success message box
pops up which then requires clicking on the tiny "close" link.
This makes working with the Module Builder an unnerving task.

## How To Test This

Create a new package + module in Module Builder, create some fields, etc.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Review by samus-aran — DISMISSED** [review]

**Review by jack7anderson7 — DISMISSED** [review]

**Review by clemente-raposo — APPROVED** [review]
code looks ok

**Review by mattlorimer — APPROVED** [review]
LGTM 👍🏻

**Review by johnM2401 — APPROVED** [review]
Looks good from a QA perspective. 
Appears to auto-close popup messages in Studio & Module Builder

**Pull request merged**
