### PR TITLE
Fixed - Single quotes breaking tracker URL link in emails from campaigns

### PR DESCRIPTION
**Pull request by 604media**

### CODE REVIEW

**Comment by samus-aran** [comment]
Hey there @604media 

Have a wee look at our workflow process for submitting bugs. https://docs.suitecrm.com/community/contributing-code/bugs/
We don't merged directly into master, so if you want your fix to apply to a particular LTS (8 or 10) then change your base branch to the relevant hotfix branch.

Also Travis is failing, have a quick look why that is and we can help identify how to get it to pass.

**Comment by 604media** [comment]
Thanks @samus-aran 
I will create new PR to hotfix-7.10x instead of master. Thanks for providing support document
While coming to Travis - Can you please help to understand my Travis check result

https://travis-ci.org/salesagility/SuiteCRM/builds/542200430?utm_source=github_status&utm_medium=notification

 
image

Travis passed for PHP 7.1/ MYSQL 5.7 and failed for other versions

image

I'm sure this error not related to our fix - Please suggest me on this.

**Comment by samus-aran** [comment]
Hey @604media Well if it passed one environment I suspect its down to .. well. travis being flaky unfortunately. I don't want to restart these just to have to do the whole thing again when you create your new PR to the appropriate branch.

Why don't you close this one down and if Travis fails on the new PR then we'll troubleshoot it then.

**Comment by samus-aran** [comment]
This has been superseeded by https://github.com/salesagility/SuiteCRM/pull/7366

**Pull request closed without merging**
