### PR TITLE
Vardefs definitions and custom data from view to JS DOM

### PR DESCRIPTION
**Pull request by Abuelodelanada**
When developing some complex JS functionality is very useful to have module vardefs definitions in the DOM so you can read it from JS.

Adding vardefs.php definitions to a specific view is very simple:

view edit php

After that, you can access vardefs definitions from JS easily

accounts_edit

But we can also add other relevant information to the DOM, like for example developer's data ;-)

view edit php 2

And this data can be retrieved like this:

accounts_edit_2

### CODE REVIEW

**Comment by Abuelodelanada** [comment]
Hi! 
do you need some modification or explanation in order to aprove this pull request?

**Comment by horus68** [comment]
@Abuelodelanada I'm not on the dev team but can you commit this PR to the proper branch (hotfix)?
Hope then it gets proper attention!

**Comment by Abuelodelanada** [comment]
@horus68 ok, just give me some days, and I'll do it.!

**Comment by Abuelodelanada** [comment]
@horus68 Here you have :D https://github.com/salesagility/SuiteCRM/pull/2440

**Pull request closed without merging**
