### PR TITLE
Introduction of two additional Charts into the SuiteCRM Dashlets.

### PR DESCRIPTION
**Pull request by ricktimmis**
```
1.) Module Actitivy:

This provides the ability to select period, user and modules. It charts newly created records across modules, and groups by user for the period specified.
This chart is really useful for identifying who is actively using the SuiteCRM system, and what modules they are using.

FIXME: One problem I came up against was the loading of the language and label files, I could not get the lang.php field lable definitions to be interpreted.
In the interest of getting something working I have hardcoded the labels into this report, and commented out the language configurable alternatives until such
time as I can figure out why it is behaving this way. I am probably just missing something small.

2.) Pipeline By Sales Agent:

This is a return to a legacy chart from SugarCRM, but I believe that Sales Teams really need this chart. It presents Opportunities, by Sales Stage, by Agent
It is really helpful to be able to see who is working on what opportunties, at what stage. It enables sales managers to qualify the activity of their sales
team.

FIXME: The langauge translation files for Russian, and Spanish are both incorrect for both Charts. Hopefully these transalations can be reviewed and corrected
in due course.

Module Activity report has a complicated SQL statement construction, so I have left Debug logging entries in that function.

tail -f sugarcrm.log | grep 'Module Activity'

Is your friend to see exactly what the query is and whom the search is being performed for.

Here's hoping you find this useful, Best Wishes Rick..
```

### CODE REVIEW

**Comment by horus68** [comment]
Hi, please delete the spanish and russian translation language files
Translations are done with crowdin system at https://crowdin.com/project/suitecrmtranslations

Language files would be added via the language packs, not in suiteCRM core install
(I already uploaded english file so it will be translated to all languages)

**Comment by horus68** [comment]
@ricktimmis 
in SuiteCRM/modules/Charts/Dashlets/PipelineBySalesAgentDashlet/PipelineBySalesAgentDashlet.en_us.lang.php 

if the title is Sale Agent
`'LBL_TITLE'       => 'Pipeline By Sales Agent',`
shouldn't the description be changed too? actually is "Sales Stage"
`'LBL_DESCRIPTION' => 'Horizontal Bar Chart of Sales Stage Pipeline',`

It looks like taken from the description field for PipelineBySalesStageDashlet Dashlet

**Comment by horus68** [comment]
When will it be merged?

**Comment by ricktimmis** [comment]
Ah sorry folks - So this review request has been sitting in my GitHub message queue, and I only just found this. My bad, I need to spend more time working on GitHub to get used to it.

I will work some more on this Charts feature in September when I return from Holidays, and I will update it to work with the latest development release.

**Comment by horus68** [comment]
@ricktimmis how about your 2016 holidays?! Don't wait to make more big feature changes, just verify if this is working to be merged. You can always improve it in the future!
@salesagility this PR needs your love (june 2015)!

**Comment by ricktimmis** [comment]
OK - All changes done. and fixes applied ( see commit logs )

I am unable to sign the clahub thing, as it crashes everytime I try

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

All the best Rick

**Comment by horus68** [comment]
@ricktimmis your clahub looks fine
You need to make this PR against Hotfix Branch as the master branch do not allow PR merges.

**Comment by ricktimmis** [comment]
Ah right OK, I think I might have to do some juggling around and pull the HotFix from upstream, Merge my changes in Master to HotFix, and then run a Pull Request from my HotFix.

Sound right ?

**Comment by ricktimmis** [comment]
Closing as now superceded by, Pull Request 3552, which incorporates the changes within the HotFix branch rather than Master :-)

https://github.com/salesagility/SuiteCRM/pull/3552

**Pull request closed without merging**
