### PR TITLE
Fix/parsecsv

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Moved the parsecsv lib to composer but kept the file intact for backwards compatibility.

## How To Test This

1. Composer install.
2. Looks like this is only used by the ```CsvAutoDetect``` class so I would do a general regression test of CSV features like importing. 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
Don't forget to add this to #7744 :)

**Comment by Mac-Rae** [comment]
Appear to be white screening when trying to import contacts right after hitting go.
Screenshot from 2019-10-10 11-22-53

```
Thu Oct 10 10:18:52 2019 [32][1][FATAL] Caught error: stat(): stat failed for upload/import/status_1.csv
Thu Oct 10 10:18:52 2019 [32][1][FATAL] Caught error: touch(): UploadStream::stream_metadata is not implemented!
Thu Oct 10 10:19:35 2019 [31][1][FATAL] error loading relationship project_resource
Thu Oct 10 10:19:35 2019 [31][1][FATAL] error loading relationship am_projecttemplates_resources
```
Heres the fatal errors found in my logs

**Comment by Dillon-Brown** [comment]
@Mac-Rae Fixed.

**Comment by connorshea** [comment]
@Dillon-Brown `composer validate` seems to have failed 🤔

**Comment by connorshea** [comment]
Passes CI now :) @Mac-Rae

**Comment by connorshea** [comment]
Merge conflicts

**Review by code-ph0y — DISMISSED** [review]

**Comment by Mac-Rae** [comment]
Could be a test issue here?, Travis is failing on composer due to .lock not being uptodate.

**Pull request closed without merging**
