### PR TITLE
fixed - #2795 Checkbox Internal on Cases Detail View is without label

### PR DESCRIPTION
**Pull request by shogunpol**
Checkbox Internal on Cases Detail View is without label - fixed
## Description

Checkbox Internal on Cases Detail View is without label - fixed
References issue #2795

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@shogunpol  I think there is a missing string in line 165
`    'LBL_CONTACT_CREATED_BY' => 'Created by',`

this is called from \modules\Cases\vardefs.php
`                'vname' => 'LBL_CONTACT_CREATED_BY',`

**Comment by shogunpol** [comment]
@horus68 , Is this related to this issue? Namely 'LBL_AOP_INTERNAL' => 'Internal', label?

**Comment by horus68** [comment]
No. This should be a separated issue.
My personal master file already included both strings (the LBL_AOP_INTERNAL and the LBL_CONTACT_CREATED_BY ) but only later I found when it was removed. 
Will open a new issue

**Comment by shogunpol** [comment]
@horus68 , can you create issue and PR, so can be "fast" implement into next release?

**Comment by daniel-samson** [comment]
I have a fix for this - which I will include in my next pull request. So hopefully it should be in the next release.


cases

**Comment by horus68** [comment]
@shogunpol  Done: https://github.com/salesagility/SuiteCRM/pull/2813

**Comment by samus-aran** [comment]
Closing PR as applying this would revert a previous fix.

**Pull request closed without merging**
