### PR TITLE
Fix typo in InboundEmail.php

### PR DESCRIPTION
**Pull request by lex111**
## Description
Fix typo referred to in issue #3860.

## Motivation and Context
See issue #3860.

## How To Test This
Look at file InboundEmail.php

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by lex111** [comment]
@Dillon-Brown done! :heavy_check_mark:

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by samus-aran** [comment]
Hey @lex111  :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Comment by lex111** [comment]
@samus-aran wow, submitted form, thank you too!

**Pull request merged**
