### PR TITLE
Fixed #2651 - Different size of icons on sidebar

### LINKED ISSUE #2651: SuiteP - Different size of icons on sidebar
#### Issue

sidebar

#### Expected Behavior

All icons on sidebar will use same size

#### Actual Behavior

Some module icons are bigger.

#### Your Environment

* SuiteCRM Version used: 7.7.7 
* Browser name and version: Chrome 54.x 64bit
* Environment name and version: MySQL PHP 5.6
* Operating System and version: Win 10 Home

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Updated SuiteP sidebar .svg files to be 20x20px. This makes the sidebar icons consistent with each other.
image_sizes

Issue reference: #2651 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
@horus68 - Just to check if the thumbs up was that you were able to test this or confirming its a good fix? :D

**Comment by horus68** [comment]
@samus-aran my thumbs up is just done so I can be related to an issue or a fix I want to get notices from github, normally on language issues or issues/PR I agree on the direction or the need for it.
I can't test this now but there is a need for a PR to fix the issue.

**Comment by horus68** [comment]
@samus-aran  tested with 7.9 rc (windows 10/ Firefox) and working. Good to be merged!
2017-05-17 10_25_39-pesquisa

**Comment by Dillon-Brown** [comment]
Superseded by #5273

**Pull request closed without merging**
