### PR TITLE
Fixed #6340 - From Dropdown on Email Compose has utf-8 issue

### LINKED ISSUE #6340: From Dropdown on Email Compose has utf-8 issue
#### Issue
it is just the display bad char in from Dropdown on Email Compose. I think there is an utf-8 issue.
screenshot_1

#### Expected Behavior
It should be shown like user full name with utf-8 support.

#### Steps to Reproduce

1. Open Email Compose
2. Look at from dropdown
3. See non standard utf-8 char

#### Your Environment

* SuiteCRM Version used: 7.10.9
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 62 (64 bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

screenshot_1

## Motivation and Context

Issue reference: #6340 

## How To Test This

1. Open Email Compose.
2. Look at from dropdown.
3. Check that encoding is correct.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mausino** [comment]
@samus-aran @Dillon-Brown you fixed the utf-8 "From" dropdown... but you broked the signatures... when change again to old code.. From dropdown is broken and signature is withou any isssue
46288312-8eafac80-c585-11e8-9606-97dca1ac12dd

**Comment by Mausino** [comment]
@jack7anderson7  do you mean like this  FROM "Email name ťčžýáíé@example.com" or  "ščťžýžť Email name test@test.sk" ???

**Comment by Dillon-Brown** [comment]
@jack7anderson7 That will be due to the [RFC Spec](http://en.wikipedia.org/wiki/E-mail_address#RFC_specification ). You won't be able to send an email (Or test email) with an invalid "From" Address, but we can still utf8_encode so it displays correctly. Perhaps better logging is needed here instead of the generic "Contact Administrator".

**Comment by jack7anderson7** [comment]
@Dillon-Brown, yes the encoding is correct and doesn't display any errors as well as in the body of the email.

**Comment by jack7anderson7** [comment]
Assessed :+1:

**Pull request merged**
