### PR TITLE
Fix #9191 - Update antixss lib dependency

### LINKED ISSUE #9191: Big problem with UTF-8 charaters between 7.11.18 anf 7.11.20
It looks like something major changed between 7.11.18 and 7.11.20.

We have existing DB with UTF-8 data (tried with utf8 and utf8mb4 encoding).

In 7.11.8 everything (Basic search, filters, ...) works normaly.
In 7.11.20 existing strings with utf-8 data are not found any more.

We tried to compare records saved in 7.11.18 and 7.11.20 and found, that 7.11.20 started to save utf-8 characters diferent.

Before characters were saved in NFC normalization and with 7.11.20 they are saved in NFD normalization.

This is huge problem, since there is no convert process on upgrade so existing data are not compatilba and SuiteCRM can't find existing data any more.

I prepared video with example on 7.11.18 and 7.11.20:
https://www.gody.si/suite-crm-issue-utf8/

One more anoyance is, that when one tries to delete UTF-8 character in input field, it first changes from ž to z and only second backspace does remove character.

#### Issue
Existing data is not searcheable if UTF8 characters are in strings after upgrade to 7.11.20

#### Expected Behavior
Existing data should be converted to new format, if format changed.

#### Actual Behavior
Existing data were not fomrated on upgrade.

#### Steps to Reproduce
- install 7.11.8
- enter contact with utf-8 character in name f.e. (Matjaž)
- Upgrade to 7.11.20
- try filter in contact list for Matjaž -> record is not found
- See video: https://www.gody.si/suite-crm-issue-utf8/

#### Context
Existing records are not searcheable any more.

#### Your Environment
* Upgrade from SuiteCRM 7.11.18 -> 7.11.20
* PHP 7.3 & 7.4
* Mariadb
* Apache
* OpenSuSE Leap 15, CentOS 7.x

### PR DESCRIPTION
**Pull request by clemente-raposo**
## Description

- Fix https://github.com/salesagility/SuiteCRM/issues/9191
- Current version of the lib was wrongly encoding special characters
- Update to antixss library fixes the problem

## Motivation and Context

- Fix https://github.com/salesagility/SuiteCRM/issues/9191

## How To Test This

- see: https://github.com/salesagility/SuiteCRM/issues/9191
- Need to set specific enconding
- Create records with special characters
- Check if the match character encoding done on previous versions 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by simonr44** [comment]
Looks good from here

**Review by pankaj0882 — APPROVED** [review]
@clemente-raposo all the changes look good to me.

**Review by jack7anderson7 — APPROVED** [review]

**Review by pankaj0882 — APPROVED** [review]
Changes Look Good To Me.

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Review by Mac-Rae — APPROVED** [review]

**Pull request merged**
