### PR TITLE
added back missing files for correct Dynamic Dropdown working in studio

### PR DESCRIPTION
**Pull request by adamjakab**
added back missing files for correct Dynamic Dropdown working in studio

### CODE REVIEW

**Comment by adamjakab** [comment]
I added these files in custom but probably they should go in `modules/DynamicFields/templates/Fields`

**Comment by mattlorimer** [comment]
Thanks for your input please nay future bug fixes to the hotfix branch, and if you reference the issue after the keyword 'Fixed'  in your commit it will auto close the the issue when it goes live e.g. 'Fixed #929'

**Comment by adamjakab** [comment]
Ok, I will - Do you have guidelines somewhere out there on how to contribute?
Thanks

**Comment by mattlorimer** [comment]
We are currently putting this a more comprehensive guide together for this

**Comment by DarkRonak** [comment]
Hello adam,

I am facing the same problem, can you please guide me step by step on what to do to rectify this.
Thank you in advance.

-Ronak

**Pull request closed without merging**
