### PR TITLE
Translations acknowledge on About page

### PR DESCRIPTION
**Pull request by horus68**
## Description

Community translations acknowledge on the about page
Text can also be translated by each team on Crowdin
## Motivation and Context

To make a reference to Crowdin collaborative translations at
https://crowdin.com/project/suitecrmtranslations
## How To Test This

Apply changes, quick repair, reload!

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Fine tunning (non-breaking change - do not adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
  functionality to change)
### Final checklist
- [x] My code follows the code style of this project found
  [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to
  Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM)
  guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Hi @horus68 - We'll need to check first if http://www.disytel.com can be taken off :smile: But certainly I would think the Crowdin is suitable.

**Comment by horus68** [comment]
I just removed because es_ES is no longer provided with SuiteCRM.
You could also include a reference to other language packs not from Crowdin (I'm not an english user so its more difficult to me to create a good text!)

**Comment by horus68** [comment]
@samus-aran any news?

**Comment by horus68** [comment]
@salesagility  @mattlorimer this looks like a PR that require management decision.
Its time to revise this one!

**Comment by horus68** [comment]
My proposal only includes Crowdin language packs that includes all languages on translation.

I think it should also include mentions for other well know individual language packs:
- Russian ru_RU by @likhobory https://github.com/likhobory/SuiteCRM7RU
- German de_DE by Diligent https://www.dtbc.eu/en/product/the-free-german-language-pack-for-suitecrm-2/
(a project that uses different language strings format)
- Italian it_IT by DEVILA SNC http://www.devila.net/download

As I'm not an english users, will leave the wording for how knows better then me!

**Comment by mattlorimer** [comment]
Thanks for the feedback I will look into it

**Comment by pgorod** [comment]
This is obviously incomplete as it is missing a proper mention of horus68 himself as a major contributor, surely one of the greatest. The project owes him hundreds of hours of work, and it is ongoing. Also, as this is his professional work, I'm sure the mention would benefit him, it's probably a relevant part of his CV.

: - )

**Comment by horus68** [comment]
I don't need personal mention as this is related with my professional work, so already payed! I don't even place it in my CV!

**Comment by samus-aran** [comment]
Thanks @horus68 ! :+1: At the moment having the generic acknowledgement of the crowdin translation would be great as an extensive list of individual partners providing languages would be cumbersome. :)

**Pull request merged**
