### PR TITLE
Give Meeting different colors (patch-2), see github #3273 

### PR DESCRIPTION
**Pull request by jobst**
The only customisation required for this to work is to add a few lines for each meeting status into the config_override.php.

Example here for the standard "Planned" meeting statius (light blue).
$sugar_config['CalendarColors']['Planned']['border']="555555";
$sugar_config['CalendarColors']['Planned']['body']  ="D8EFFF";
$sugar_config['CalendarColors']['Planned']['text']  ="000000";

If this is NOT defined, the standard colors as defined in CalendarDisplay.php (public $activity_colors = array(...) are used.

## Description

This is a pull request due to github #3273 
It allows Meeting to have different colow

## Motivation and Context

Makes the calendar less bland.

## How To Test This

- replace Cal.js (patch-1)
- replace CalendarDisplay.php (patch-2)
- add the changes to config_override.php as shwon above
- load SuiteCRM
- go to the calendar
- create a meeting with "planned"
- instead of being the standard wierd blue its light blue (can be any color)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ x] My change requires a change to the documentation.
- [x ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@jobst  You need to sign the Clahub Contributor License Agreement

**Comment by pgorod** [comment]
@jobst thanks for this fix, very nice work!

You also need to edit the target branch, it should be `hotifx` (for bugs) or `develop` (enhancements), but never `master`.

Is there any reason why you didn't change the two files in a single PR?

**Comment by jobst** [comment]
@pgorod A few things are new to me, so excuse my little stuff ups, please!

**Comment by pgorod** [comment]
There is nothing to excuse, you are doing fine and you are contributing valuable code!

I am also just a community member like you and I am also learning all this Github stuff, which can be pretty complicated sometimes, so it's perfectly understandable if some details fail when you're learning.

Thanks.

**Comment by chris001** [comment]
@jobst 
If you want to try, you can squash-merge your branches `patch-1` and `patch-2` this will make the two PR become just one PR, it's more united this way.
You do the squash-merge by doing a PR from your fork, branch `patch-2` to `patch-1`, and accept it.

**Comment by pgorod** [comment]
By the way, if you want another tip to tidy up things, you can add more commits to the same branch in your own repository, and they will be automatically added to the Pull Request here, without the need for any other action.

So you can add the commit in the other PR to this one by simply committing the changes to `jobst/patch-2`, and then you can close the other PR.

So, generally speaking:
- a PR can include several commits, even ones that were committed after the PR was created;
- so, the PR tracks the current state of a branch, no matter how many commits it includes, or when they happened
- even a single commit can include several file changes.

I hope this helps.

**Comment by pgorod** [comment]
There is an update to this regarding custom fields here:

https://suitecrm.com/suitecrm/forum/developer-help/18905-colorize-calls-in-calendar-based-on-custom-fields#65544

There is a comment about difficulties using these changes, and a solution, here:

https://suitecrm.com/suitecrm/forum/developer-help/13406-defining-and-using-different-colors-in-the-calendar-for-different-types-of-entries#58486

**Comment by Mac-Rae** [comment]
Please resolve the conflicts on this pull request bringing it up to date.

**Comment by jobst** [comment]
> Please resolve the conflicts on this pull request bringing it up to date.

Not sure whether I should start again, as this is based on code 2 years old.

Also I clicked on the "Details" link for the Codacy stuff (i.e. not up to coding standards), expecting to get some where to fix the code but it only got more complicated (plus so much stuff to read about).

I also tried to find the code pieces that are incorrect. I do not mind to change them, but how? I really would like to help but all of this does not make it easy, it seems I need a PhD just to provide some code fragments .... 

Please consider I help/contribute to many projects by finding bugs and adding new stuff - but every repository, plugin provider, RPM, CMS, project, app, program uses different ways to contribute and ALL of them are getting out of hand ....  but please make it easy for a person who's main job is NOT adding stuff to SuiteCRM.

**Comment by jobst** [comment]
> 
> There is a comment about difficulties using these changes, and a solution, here:
> 
> https://suitecrm.com/suitecrm/forum/developer-help/13406-defining-and-using-different-colors-in-the-calendar-for-different-types-of-entries#58486

It is hard for me to have a look at the person's files in the SuiteCRM directories, so I do not know what it wrong.

I know it works, has been working for every SuiteCRM version I have been using, but I add this manually every time I upgrade - takes me about 15 minutes to change the two files:
 1) backup cal.js
 2) unminify cal.js
 3) make the changes
 4) backup calendardisplay.php
 5) make the changes.

My config file already contains the info.

If the code is integrated all other people have to do is to add the code fragments to the config_override.php for each color/field combo they want to use. If they forget to add one it will simply default to the original color.

**Comment by horus68** [comment]
> Not sure whether I should start again, as this is based on code 2 years old.

Agree wit this. This recent clean up using "update/resolve conflicts/old version not supported" its not a proper way to solve.
Users have been providing code to fix issues but they have not been accepted for years. 
If SalesAgillity is now trying to sort them, its better they take care of the PR and make a proper PR because users has already lost they time and you can't expect someone will jump in again with joy to a forgotten PR.
Requesting @Dillon-Brown to join in!

**Comment by Dillon-Brown** [comment]
@horus68 Agreed and I can understand the frustration when being asked to resolve conflicts with PRs that are years old. Ideally, this is the situation that we're looking to prevent from occurring again in the future.

For the "old version not supported" issues. We're only looking to close them if they are confirmed to no longer be an issue on a supported version and will gladly take over a 7.8.x PR to rebase to 7.10.x/7.11.x if the owner wants.

For the "update/resolve conflicts" PRs, I agree we probably could have worded this better. Going forward this hopefully won't be something that we need to do again as we now have a handle on the older PRs (How many need rebased, have conflicts, still relevant, etc) and will be looking to automate this process for new PRs along with improved documentation and processes.

Thanks for the feedback!

**Comment by Dillon-Brown** [comment]
@jobst Taking a look at codacy, it looks like it didn't actually pick up this PR and just takes you to the homepage (I'm guessing because this PR comes from an unknown repo). Codacy isn't actually a required check though (It often has false positives) so we can merge PRs that fail this check.

If you're still interested in having this feature looked at I'd be willing to make a new PR with these changes. Thanks!

**Comment by jobst** [comment]
> 
> If you're still interested in having this feature looked at I'd be willing to make a new PR with these changes. Thanks!

@Dillon-Brown happy to help and contribute ...

As I said above, I know it works and if someone does not want to add colors/fields the default colors are used, plus once the changes are part of the standard code the only changes anyone has to do is to add lines to the config override ... which also could be done at a later stage by changes to the color editor.

My current version is 7.10.16 - so my patches would be based on that.
I can provide patches, codes snippets whatever is needed - so tell me how I can help.

**Comment by serhiisamko091184** [comment]
Hello @jobst, 

closing this one as the branch is unavailable: 
image

Feel free to reopen it when it's convenient for you. 

Many thanks! 

Regards,
Serhii

**Pull request closed without merging**
