### PR TITLE
RFC:  travis-ci: add a job for PHP 7.3 

### PR DESCRIPTION
**Pull request by lazka**
This depends on #7124 (this PR includes it for now)

Turns out the tests pass now with two small fixes.

## Motivation and Context

Don't regress with php7.3 by testing in CI

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Nice! I had been meaning to take a look at getting 7.3 running at some point. Will see about getting #7124 merged.

**Comment by lazka** [comment]
Meh, it worked on my fork :(

**Comment by Dillon-Brown** [comment]
@lazka Yeah it was flaky tests, re-ran and it's now passing.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
