### PR TITLE
Fixed #5515: Due date not showed anymore

### LINKED ISSUE #5515: Due date not showed anymore
In the account module, history calls do not show the due date anymore.

Versions 7.10, 7.10.1, 7.10.2

### PR DESCRIPTION
**Pull request by anhnhatuit**
## How To Test This

1. Go to any module has History, Activities subpanel (Accounts, Contacts, Cases,...)
2. From Activities subpanel create new task or call or meeting record (MUST fill date for Due Date or End Date field, if is call record. Due Date value will auto calculate from Date Start and Duration) MUST set status is (Held, Not Held or Complete)
3. Save > System will auto reload History subpanel.

Expected:
* Due date need display in History subpanel

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
Hi @anhnhatuit 
Please fill in the template when creating a pull request, including how to test your pull request.

**Comment by horus68** [comment]
This is just to link to the issue:
https://github.com/salesagility/SuiteCRM/issues/5515

**Comment by anhnhatuit** [comment]
Hi @daniel-samson ,

Yes. I'll update after fix complete. I  did not fix completed. Can you tell me know, how to edit multiple files in one pull request? This issue need fix more in subpanel metadata 

Thanks,

**Comment by anhnhatuit** [comment]
Hi All,

I've fixed complete. Can someone help me test.

Thanks,
Nhat

**Comment by Dillon-Brown** [comment]
Also related: #5560

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by nejck-ikservis** [comment]
I think, the fix should be applied to ForActivities.php file also. 

`		  'date_start'=>array(
		    'vname' => 'LBL_LIST_DUE_DATE',
		    'width' => '10%',
		    'alias' => 'date_due',
		    'sort_by' => 'date_due'
		),`

**Comment by PedroErnst** [comment]
@labcerouno 

On current hotfix branch (which includes #5535 since it's merged) I'm looking at a Contact's detail view, with activities subpanel open and a Task being displayed, and I'm not getting any SQL errors.

Does the error say anything else? Like a line number or maybe a stack trace? 
Also, I assume you're running 7.10.7?

**Comment by labcerouno** [comment]
That's right, @PedroErnst , it's related to certain users only, which is strange... We're using 7.10.7. In the next week we are performing a fresh install with a different approach on importing the database, as it might be dragging some old errors. It's one of our hypothesis, because we have many errors that other people cannot replicate. Thank you for your time!

**Pull request merged**
