### PR TITLE
SuiteR and Suite7 Theme dont work anymore in 7.8.21

### PR DESCRIPTION
**Pull request by gunnicom**
Updated from 7.8.18 
Problems with DatePicker and Editview. includign yui.css again fixes this.

### CODE REVIEW

**Comment by gunnicom** [comment]
EditView, Tabs messed up:
grafik
DatePicker:
grafik

**Comment by horus68** [comment]
related? 
https://github.com/salesagility/SuiteCRM/issues/3038

**Comment by gunnicom** [comment]
@horus68 Don't know if this is related. As my fix does work for me, i assume, that the yui.css is there. Maybe i am lucky that it is there from my upgrade path and an old version.

**Comment by gunnicom** [comment]
@horus68  But it is definitly related to the merge in #3038 
https://github.com/Dillon-Brown/SuiteCRM/commit/2877d6d3454d14fee31bdf294d281ba0957b2e45#diff-00229f20307932bd77990d84328ad002L604

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
