### PR TITLE
Fixed #7271 - Email Template selection in email module is not working for 7.10.16

### LINKED ISSUE #7271: Email Template selection in email module is not working for 7.10.16
#### Issue

Selecting email template when composing the email, it does not work. There is no action.
#### Expected Behavior

It should be working like expected.
#### Actual Behavior

There is no log. I tried it new installation of SuiteCRM
#### Steps to Reproduce

1. Open email module
2. Compose
3. Select email template
4. There is no action when template selected.

#### Context

medium priority
#### Your Environment

* SuiteCRM Version used: 7.10.16
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 66.0.5 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04):  Ubuntu 16.04

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixes an issue with the email compose buttons not returning data from the popups.

## Motivation and Context

Issue reference: #7271 

## How To Test This

1. Open email module
2. Compose
3. Select email template

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by pgorod** [comment]
This is also in 7.11.5, right? 

Because there seems to be some problem... https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/24698-email-templates-not-loading?start=15#85477

**Comment by Dillon-Brown** [comment]
@pgorod Yeah it's in 7.11.5. I'm not able to replicate, seems to work fine for me.

**Comment by kikobar** [comment]
I upgraded from 7.10.16 to 7.11.5 in one step and I still have this issue.

**Comment by pstevens71** [comment]
I'm experiencing this issue in 7.11.4.  The 2 JS files referenced changes do not seem to fix the issue for me either.

**Comment by pstevens71** [comment]
Update.... I'm using cloudflare, cleared the cloudflare cache after replacing the files and after re-building the  JS files (quick repair and rebuild plus the rebuild JS files options) and it now works!   Thank you!!

**Comment by kikobar** [comment]
@pstevens71 could you please list the exact steps you took to make it work?

**Comment by pstevens71** [comment]
The trick is:
1. replace the two JS files with the versions here:
 https://github.com/salesagility/SuiteCRM/pull/7282/files

2. Admin/Repair/Quick repair and rebuild
3.Admin/Repair/Repair JS Files

I also am using cloudflare so had to clear the cache AND Shift F5 to clear the browser cache (in Chrome) and it works!

If your hosting is using a cache you might want to make sure that's clear too.

**Comment by kikobar** [comment]
Thanks! I will give it a shot and will post back here.

**Comment by kikobar** [comment]
@pstevens71 @Dillon-Brown thanks a lot!
I confirm this did the trick for me too!

**Comment by kikobar** [comment]
In my case the real issue in my case was the browser cache (silly me!!) because I tried in a new private window before trying anything else and if actually worked.
Apologies if I misled someone!

**Pull request merged**
