### PR TITLE
Fixed #7407 - "Users may send as themselves" broken - Invalid address: (punyEncode)

### LINKED ISSUE #7407: "Users may send as themselves" broken - Invalid address:  (punyEncode)
#### Issue
users are not able to send mails, if checkbox "Users may send as themselves:" is activated

chrome_f1H7uTkFWK

CRM-Settings:

- EMAIL SETTINGS: OUTGOING MAIL CONFIGURATION is configured, "outbound mail" contains only the "system" item (sending test-mails from the admin-backend works)
- checkbox "Users may send as themselves:" is checked as shown above
- test user has two mail addresses set up in his profile

#### Expected Behavior
- click on a contacts mail address opens mailer
- user is able to choose one of his own addresses and add content
- and can send the mail

#### Actual Behavior
- after clicking the "send" icon, an error message appears:

> Error Sending Email. Please contact your administrator for assistance.
chrome_PASYuvGElf

- log:
`Mon Jun 17 09:27:55 2019 [16712][1][FATAL] SugarPHPMailer encountered an error: Invalid address:  (punyEncode) Administrator <test.test@test.com`
**- note the missing ">"!**

#### Possible Fix
- I've debugged into it. Found the issue in `\include\phpmailer\class.phpmailer.php`, line 1252 (validateAddress returns false instead of true)
- I changed therefore (only for testing) the condition to
` if (false && !$this->validateAddress($this->$address_kind)) {`
- result: mail is sent. 

- E: var $address in validateAddress() is set to `some.thing@test.org` for all receiving addresses, but the from-address is set to `Administrator <test.test@test.com` and the following preg_match fails

#### Steps to Reproduce
as described above

#### Your Environment
- SuiteCRM Version 7.10.17
Sugar Version 6.5.25 (Build 344)

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixed an issue where the from and reply to address would be formatted incorrectly preventing emails from being sent.

## Motivation and Context

Issue reference: #7407 

## How To Test This

1. Create a system outbound email.
2. Add an email address to user profile (Profile edit view, not profile email settings).
3. Compose an email and check that the username is not duplicated and the email sends correctly.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Cool!

I asked on the corresponding Forum thread for people to help with testing:

https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/26658-error-when-send-mail-from-mail-s-module#86696

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by pstevens71** [comment]
Just tested, it does indeed get rid of the missing ">" problem and associated errors.  However, still getting the "Thu Jul  4 13:56:35 2019 [1172][1][FATAL] SugarPHPMailer encountered an error: SMTP Error: Could not authenticate." error.  I have tested both the system and user SMTP addresses and they work fine in to test, just not when you send an email as a user.  I'll do some further testing and see if I can get to the bottom of the authentication error.

**Comment by pstevens71** [comment]
OK, I ran a debug and here is the error:
Thu Jul  4 14:35:32 2019 [2790][1][ERROR] Invalid email from address or name detected before sending. Details:
From field is not set.
From-name is not set.
From address and name pair is empty.
codes:1, 7, 14

**Comment by pstevens71** [comment]
**Success! OK**, I tried repair and rebuild, no luck, then I tried to re-add the system email and save it (after the code fix).  Now it works.  Also, flushed my browser cache.

One other problem, don't know if it's related, but it will allow me to send through the system as "the system" and will allow me to send from me through the "system email".   But, when I add my own SMTP credentials as another outbound email account, it's not available as an option in email compose dropdown???

**Comment by Dillon-Brown** [comment]
@pstevens71 I believe the current functionality is that you can send an outbound email with just system outbound but if you want to use personal outbound you must also set up personal inbound.

**Comment by pstevens71** [comment]
Thanks @Dillon-Brown, yes I did testing with it this morning and that is the case.  You need an inbound account set up if you want to route email through a personal outbound account.  To confirm, the fix does solve the problem in this thread.  Thanks so much!

**Comment by phil8900** [comment]
I can confirm that this fixed the problem for me, thanks :)

**Pull request merged**
