### PR TITLE
Fix #10488 - Expand the number of filters in message queue views

### LINKED ISSUE #10488: Not all filter options are displayed in the message queue
### Issue

The message queue module is not shown in the study and, consequently, can only be modified by introducing changes directly in the files, so it is proposed to adapt the initial configuration:

1. List view: The fields for creation date, modification date, user and modified by are added as hidden fields.
2. Basic search view: The fields that appear by default in the list view are added as filters, including those in point 1.
3. Advanced search view: The fields that do not appear by default in the list view are added as filters, plus those in point 2.

### Possible Fix

_No response_

### Steps to Reproduce the Issue

```bash
1. Create a campaign with contacts, accounts, leads and users.
2. Send one or more marketing emails.
3. Access the message queue view and verify that the different filters added work correctly
```

### Context

_No response_

### Version

7.14.3

### What browser are you currently using?

Firefox

### Browser Version

128.0.3 (64-bit)

### Environment Information

MySQL, PHP Version 7.4.33

### Operating System and Version

Ubuntu 22.04.4 LTS

### PR DESCRIPTION
**Pull request by SinergiaCRM**
## Description
This PR expands the number of filters available for the Email Queue module.

## Motivation and Context
https://github.com/salesagility/SuiteCRM/issues/10488

## How To Test This
1. Create a campaign with contacts, accounts, leads and users.
2. Send one or more marketing emails.
3. Access the message queue view and verify that the different filters added work correctly

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hello @SinergiaCRM, 

thanks for your contribution, 

would you be so kind to check the suggested changes in the vardefs.php file as there might be some discrepancies:   

image

Thanks in advance! 

Regards,
Serhii

**Comment by SinergiaCRM** [comment]
> Hello @SinergiaCRM,
> 
> thanks for your contribution,
> 
> would you be so kind to check the suggested changes in the vardefs.php file as there might be some discrepancies:
> 
> image
> 
> Thanks in advance!
> 
> Regards, Serhii

Hi @serhiisamko091184, removed lines added by mistake to the user_id field. 
Thanks!

**Comment by serhiisamko091184** [comment]
Hello @SinergiaCRM,

thanks for the quick reply and changes to the PR! 

Regards,
Serhii

**Review by jack7anderson7 — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
LGTM, new filter options make sense and work as expected.

**Pull request merged**
