### PR TITLE
Fix/invalid sequence for imap function

### PR DESCRIPTION
**Pull request by PedroErnst**
Make sure the sequence passed to imap_fetch_overview is not invalid.

## Motivation and Context

Sometimes the sequence would contain negative numbers or be otherwise invalid.
Issue #4718 
Issue #4746

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by fcorluka** [comment]
Do anyone knows when this will be on master branch?

I have a fresh installation of 7.10.7  and have the same issue!
I thought the is a problem in my code (error in .zip) so I went into SuiteCRM DEMO, and there is the same issue. I will try this fix, but it I believe this needs to be fixed ASAP because this way seems that Email module is broken.

**Comment by Dillon-Brown** [comment]
Hi @fcorluka, so far I haven't been able to replicate this on 7.10.9 but I do encounter an issue with the SMTP connection in demo, i'll investigate further and get back to you (Just to note, I wouldn't suggest setting up personal email on demo as this is publicly visible to everyone using the instance).

**Comment by fcorluka** [comment]
Hi @Dillon-Brown,
these are screeshots taken from Offical Demo.
If I am doing something wrong please correct me.
Under emails there are none shown:
demo-email1

Under accounts there are mails (under History subpanel):
demo-email2

When I apply filter in Emails, againg none are shown:
demo-filter

On my local instance (v. 7.10.7) when I apply filter I can see mails regarding to the filter.
Best regards,
Filip

**Comment by Dillon-Brown** [comment]
@fcorluka The emails under "History" have been archived to that account which is why you can see them. The emails that should appear in the "Emails" module come from the personal account you set up in user profile here: 
email

**Comment by fcorluka** [comment]
Hi @Dillon-Brown,
but how is than a situation where I can on my local instance set filter and see emails (that were not in INBOX), but can not see them when a search is cleared?
Can I have multiple INBOX accounts and be able to show all emails to all users?

Best regards,
Filip

**Comment by Dillon-Brown** [comment]
@fcorluka Is it possible you are searching in a different email folder (And thus having results returned) then when you clear the filter it's taking you back to inbox?

emails

**Comment by fcorluka** [comment]
Hi,
I made some progress in understanding how EMAIL module works. As for your advice, I have set up mail accounts (inbound), and really can see all mail from that accounts (in separate folders); and that is OK for me.

Another problem is that I can not see attachments and creating case from emails is not working.
I will try now fresh 7.10.9 to see is the problem presists.

**Comment by Dillon-Brown** [comment]
@fcorluka Did you make sure to select an "Account Name" on the "Create Case" popup? it seems to be working for me on 7.10.9. I do however see the issue with the attachments, if you import an email you can see the attachments in the "attachments" sub-panel but the the "Has attachments" column doesn't display anything, this looks like a bug.

**Comment by fcorluka** [comment]
@Dillon-Brown I am not sure what popup do you mean?
So far I had numerous problems with EMAIL module, that I don't know where to start and does it even has the sense to write it here in comments, or to open Issue.

I had set up this:
inbound-mail

I had two inbound emails and could see both in Emails.
What I could not is:
- see subpanel in the mail (including attachments)
- get CASE to be created

I did some modification, deleted and returned Inbound mail account, and now:
- can not see other folders (other mail accounts)

Deleted all and recreated only 1:
- can not see any mail

**Comment by Dillon-Brown** [comment]
@fcorluka For the attachment issue, did you import the email? you won't see any subpanels until you do, this is what I see on 7.10.9:

attachment


When you were unable to see any mail after recreating inbound email did you make sure you set it to active? this can be done in user profile -> settings:

email_settings

If you can reliably replicate any of these issues then yes I would suggest raising a separate issue for each one instead of a comment, that way we can prioritise it and investigate further.

**Comment by fcorluka** [comment]
Hi @Dillon-Brown ,

I haven't imported email, I have just set up email inbound account and all were there, but not attachments.

Also, 'Active' status was checked. 
I must recreate each of these scenarios (screenshots) and create issues, as You suggested.

Best regards,
Filip

**Pull request merged**
