### PR TITLE
Fixed #1918 - Translation issues. Duplicated lang. strings in ver. 7.7

### LINKED ISSUE #1918: Translation issues. Duplicated lang. strings in ver. 7.7
--------------------

['project_priority_default']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L463
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2456

'project_priority_options'['High']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L459
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2458

'project_priority_options'['Medium']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L460
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2459

'project_priority_options'['Low']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L461
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2460

['moduleList']['KBDocuments']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L111
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2490

['LBL_LISTVIEW_OPTION_CURRENT']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L1753
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3253

['LBL_LISTVIEW_OPTION_ENTIRE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L1754
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3254

['LBL_LISTVIEW_NONE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L1752
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3255

['case_status_default_key']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L383
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3274

'dom_email_distribution_for_auto_create'['roundRobin']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L756
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3292

'dom_email_distribution_for_auto_create'['leastBusy']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L757
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3293

['product_category_dom']['']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L593
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3464

['LBL_NUMBER_OF_COLUMNS']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L2173
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3910

['moduleList']['AOBH_BusinessHours']

https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L59
https://github.com/salesagility/SuiteCRM/tree/v7.7/include/language/en_us.lang.php#L3939

--------------------

['ERR_CHECKSYS_CALL_TIME']

https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L63
https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L65

['ERR_CHECKSYS_SAFE_MODE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L92
https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L93

['LBL_STEP1']

https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L427
https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L429

['LBL_STEP2']

https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L428
https://github.com/salesagility/SuiteCRM/tree/v7.7/install/language/en_us.lang.php#L430

--------------------

['LBL_DESCRIPTION']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L51
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L101

['LBL_TASK_NAME']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L83
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L116

['LBL_START']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L111
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L119

['LBL_FINISH']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L112
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L120

['LBL_PREDECESSORS']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L84
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L121

['LBL_PERCENT_COMPLETE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L107
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L122

['LBL_REMOVE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L58
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/AM_ProjectTemplates/language/en_us.lang.php#L146

--------------------

['LBL_MODULE_NAME']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L44
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L51

['LBL_AGENDADAY']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L45
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L65

['LBL_AGENDAWEEK']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L46
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Calendar/language/en_us.lang.php#L67

--------------------

['LBL_NEWSLETTER_TITLE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Campaigns/language/en_us.lang.php#L56
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Campaigns/language/en_us.lang.php#L529

--------------------

['LBL_WIZARD_LOCALE_DESC']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Configurator/language/en_us.lang.php#L418
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Configurator/language/en_us.lang.php#L436

--------------------

['LBL_CHOOSE_EMAIL_PROVIDER']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/OutboundEmailAccounts/language/en_us.lang.php#L82
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/OutboundEmailAccounts/language/en_us.lang.php#L95

--------------------

['LBL_PROJECT_TASKS_SUBPANEL_TITLE']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L97
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L131

['LBL_DESCRIPTION']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L58
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L141

['LBL_STATUS']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L64
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Project/language/en_us.lang.php#L159

--------------------

['LBL_WIZARD_LOCALE_DESC']

https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Users/language/en_us.lang.php#L555
https://github.com/salesagility/SuiteCRM/tree/v7.7/modules/Users/language/en_us.lang.php#L560

--------------

See also #1772

### PR DESCRIPTION
**Pull request by shogunpol**
Fixed - Translation issues. Duplicated lang. strings in ver. 7.7
## Description

Fixed - Translation issues. Duplicated lang. strings in ver. 7.7
References issue #1918 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Why PR like this (easy simple fix) are not merged in Hotfix.
There is no point for an hotfix branch if a simple PR is not merged so people can test it before stable release!

**Comment by horus68** [comment]
This PR (and some others language related) missed the 7.7.6 release.
So sad 👎 @salesagility

**Comment by mattlorimer** [comment]
Thanks @horus68, but don't worry we have a dedicated resourse starting in weeks, to prevent this happening!

**Comment by horus68** [comment]
@mattlorimer Allways good to know on the project future feature! Sometimes its what it takes, to know where are we going, even if we are not there yet.

**Pull request merged**
