### PR TITLE
fix bug on clicking Update when changing Date parameter field in report detail view

### PR DESCRIPTION
**Pull request by YonatanRosemarin**
Fixes display bug in report's DetailView screen with date as parameter

## Description
Steps to reproduce the bug:
1. Create a report with date field as parameter
2. Go to the Report's DetailView screen and click on "Update"
Before clicking "Update":
image

After clicking "Update":
image

## Motivation and Context
Fixes the bug described above

## How To Test This
1. Create a report with date field as parameter
2. Go to the Report's DetailView screen and click on "Update"
3. Date fields should remain the same as before clicking "Update"

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by YonatanRosemarin** [comment]
image

**Comment by daniel-samson** [comment]
Hi @YonatanRosemarin,

It seems that you have commits from two user accounts. Both accounts must sign the clahub, before we can review you changes.

**Comment by YonatanRosemarin** [comment]
@daniel-samson - thanks - I have now understood the problem (I have 2 emails at work so I have signed with the second one also).

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by samus-aran** [comment]
Appears to be resolved at another point. Thank you for your contribution!

**Pull request closed without merging**
