### PR TITLE
Prevent securitygroups mass assign damage

### PR DESCRIPTION
**Pull request by eapunk**
## Description
Make `$_SESSION['export_where']` digest to be sending in request from "Security Groups: Mass Assign" panel.

## Motivation and Context
Create two records: account "test1" and "test2", for example. Create any group.
Go to "View Accounts". Apply filter: Name = test1
Open another browser tab, go to "View Accounts". Apply filter: Name = test
Return to first browser tab. Click "Select All (1)" in list view.
In "Security Groups: Mass Assign" panel choose group and click assign.
Alert asks "Are you sure you want to update the 1 selected record(s)?". Confirm.
Look at test2 account. It is updated with new group too.

## How To Test This
When fixed, error message will be shown, group relationships will not be modified.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Hey Jason! @eggsurplus Any input on this? Or this good to go? Could this be applied else where?

**Comment by eggsurplus** [comment]
Give me a day to look this over to see if this needs to be applied elsewhere as well. Thanks!

**Comment by eggsurplus** [comment]
This works great and since applying a filter forces the page to not use Ajax UI it should be safe. I'm not seeing any other immediate places where this logic could be used with the Security Groups module. Good to go. Nice work!

**Comment by Mac-Rae** [comment]
Please rebase this pull request to the hotfix-7.10.x branch as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Pull request closed without merging**
