### PR TITLE
Primary Email property is kept after adding an Email address field

### LINKED ISSUE #9271: Primary Email property is lost after adding an Email address field
Primary Email property is lost after adding an Email address field.

#### Issue
If you have a Contact with an Email address marked as Primary email, after adding the second or third email, the property of Primary Email is lost, and it needs to be selected again manually

#### Expected Behavior
The Primary email property should be maintained, even if added more emails.

#### Actual Behavior
The Primary Email property is lost and it needs to be set manually

#### Possible Fix
Modify jssource/src_files/include/SugarEmailAddress/SugarEmailAddress.js
Adding 288-317:
```
// Primary checkbox

      /**/ SinergiaCRM- When a new radio button is added dinamically in the HTML, all buttons with same name are unchecked
      // Retriving current primary value, if any
      var primaryPreviousValue = $("input[name='"+ _eaw.module + "0emailAddressPrimaryFlag']:checked").val();
      // END SinergiaCRM**

      var primaryCheckbox = lineContainer.find('input#email-address-primary-flag');
      primaryCheckbox.attr('name', _eaw.module + '0emailAddressPrimaryFlag');
      primaryCheckbox.attr('id', this.module + _eaw.id + 'emailAddressPrimaryFlag');
      primaryCheckbox.attr('value', this.module + _eaw.id + 'emailAddress');
      primaryCheckbox.attr('tabindex', tabIndexCount);
      primaryCheckbox.attr('enabled', "true");
      primaryCheckbox.attr("checked", (primaryFlag == '1'));

      if (_eaw.totalEmailAddresses == 0 && primaryFlag != '1') {
        primaryCheckbox.prop("checked", true);
      }


      // Prevent users from removing their primary email address
      if (this.module == 'Users' &&  primaryCheckbox.attr("checked")) {
        removeButton.prop('disabled', true);
      }

      **// SinergiaCRM - Checking the original radio button for the primary email flag
      if (!primaryFlag && primaryPreviousValue) {
        $('input[value="'+primaryPreviousValue+'"].email-address-primary-flag').prop("checked", true);
      }
      // END SinergiaCRM**
```

#### Steps to Reproduce
1. Create a record in Contacts module with an Email address set as Primary
2. Add a second email
3. Check that the primary property has been lost
4.

#### Context
The Primary Email shouldn't be lost.

#### Your Environment

    SuiteCRM Version used: Version 7.11.21
    Browser name and version: Chrome Versión 92.0.4515.131 (Build oficial) (64 bits)
    Environment name and version: MySQL, PHP 7
    Operating System and version: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by SinergiaCRM**
Closes #9271 and #8361

## Description
As the Issue mentions, the primary email property is lost after adding a new email address. 

This PR adds the code that will make sure that the primary address property is kept after adding new ones.

## Motivation and Context
the primary email address shouldn't be lost.

## How To Test This
1. Create a record in Contacts module with an Email address set as Primary
2. Add a second email
3. Check that the primary property is kept

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by jack7anderson7 — APPROVED** [review]

**Comment by mattlorimer** [comment]
Requires license CLA to be sign by all contributors

**Comment by SinergiaCRM** [comment]
> Requires license CLA to be sign by all contributors

Done!

**Comment by mattlorimer** [comment]
@SinergiaCRM both commit are by @AlbertoSTIC so they will need to sign it also

**Comment by SinergiaCRM** [comment]
> @SinergiaCRM both commit are by @AlbertoSTIC so they will need to sign it also

Hi @mattlorimer . Now all commits are made by sinergiacrm. Does it work?

**Comment by SinergiaCRM** [comment]
> > @SinergiaCRM both commit are by @AlbertoSTIC so they will need to sign it also
> 
> Hi @mattlorimer . Now all commits are made by sinergiacrm. Does it work?

The user email was missing. It should be fixed now.

**Review by jack7anderson7 — DISMISSED** [review]

**Comment by samus-aran** [comment]
Hey @SinergiaCRM 
This came from the code review, we also check the commit messages to ensure they are understandable and provide a brief context of the issue (as we use them for the release notes)

Are you able to update the commit message to reflect what the documentation provide as a guide.

https://docs.suitecrm.com/community/contributing-code/bugs/#_providing_a_bug_fix

Using the format of:

Fixed #<ID of Issue> - <the subject of the issue>

Much appreciated! :+1:

**Comment by SinergiaCRM** [comment]
> Hey @SinergiaCRM This came from the code review, we also check the commit messages to ensure they are understandable and provide a brief context of the issue (as we use them for the release notes)
> 
> Are you able to update the commit message to reflect what the documentation provide as a guide.
> 
> https://docs.suitecrm.com/community/contributing-code/bugs/#_providing_a_bug_fix
> 
> Using the format of:
> 
> Fix #[ID of Issue] - [the subject of the issue]
> 
> Much appreciated! +1

@samus-aran . Done +1

**Comment by jack7anderson7** [comment]
> 

Hi there @SinergiaCRM,

Following up everything is looking good for your commit message, but could you please update `Fixed` to `Fix` and that should all that needs changed here.

Thanks,
Jack

**Comment by SinergiaCRM** [comment]
> > 
> 
> Hi there @SinergiaCRM,
> 
> Following up everything is looking good for your commit message, but could you please update `Fixed` to `Fix` and that should all that needs changed here.
> 
> Thanks, Jack

Done. The documentation will need an update regarding this last keyword :+1: 
https://docs.suitecrm.com/community/contributing-code/bugs/#_providing_a_bug_fix

**Review by jack7anderson7 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]
code looks ok

**Comment by Mac-Rae** [comment]
Looks good to me!

**Review by Mac-Rae — APPROVED** [review]

**Comment by cyb456** [comment]
On a very old instance of suite that I have to maintain, I found the issue to actually be due to this line here: https://github.com/salesagility/SuiteCRM/blob/hotfix/include/SugarEmailAddress/templates/forEditView.tpl#L89

Since the checked is true in the template, any time a new email address is added when the editview page is created the newly checked radio button from the template steals any existing primary button check since only one radio button can be checked at a time

**Pull request merged**
