### PR TITLE
Fixed #7838 - 'Undefined index: docType' PHP notice

### LINKED ISSUE #7838: 'Undefined index: docType' PHP notice
#### Issue
I noticed some undefined index errors when I uploaded an attachment to the CRM:

```
[09-Sep-2019 19:45:21 UTC] PHP Notice:  Undefined index: docType in /Users/connorshea/code/sites/SuiteCRM/include/SugarFields/Fields/File/SugarFieldFile.php on line 158
[09-Sep-2019 19:45:21 UTC] PHP Notice:  Undefined index:  in /Users/connorshea/code/sites/SuiteCRM/include/SugarFields/Fields/File/SugarFieldFile.php on line 158
[09-Sep-2019 19:45:24 UTC] PHP Notice:  Undefined index: preview in /Users/connorshea/code/sites/SuiteCRM/download.php on line 241
```

For `doctype` as well as `preview` if you preview the uploaded attachment.

@Abuelodelanada provided the full backtrace from his logs as well, and he has the same notice:

```
[Mon Sep  9 19:17:47 2019] PHP Notice:  Undefined index: docType in /home/jose/trabajos/SuiteCRM/include/SugarFields/Fields/File/SugarFieldFile.php on line 158
[Mon Sep  9 19:17:47 2019] PHP Stack trace:
[Mon Sep  9 19:17:47 2019] PHP   1. {main}() /home/jose/trabajos/SuiteCRM/index.php:0
[Mon Sep  9 19:17:47 2019] PHP   2. SugarApplication->execute() /home/jose/trabajos/SuiteCRM/index.php:52
[Mon Sep  9 19:17:47 2019] PHP   3. NotesController->execute() /home/jose/trabajos/SuiteCRM/include/MVC/SugarApplication.php:113
[Mon Sep  9 19:17:47 2019] PHP   4. NotesController->process() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:373
[Mon Sep  9 19:17:47 2019] PHP   5. NotesController->handle_action() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:468
[Mon Sep  9 19:17:47 2019] PHP   6. NotesController->pre_action() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:494
[Mon Sep  9 19:17:47 2019] PHP   7. NotesController->pre_save() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:508
[Mon Sep  9 19:17:47 2019] PHP   8. SugarFieldFile->save() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:664
```

#### Expected Behavior
The uploads works without any errors/notices in the `php_errors.log`

#### Actual Behavior
There's a notice, though the upload still works.

#### Possible Fix

This is the line from the backtrace:

https://github.com/salesagility/SuiteCRM/blob/v7.10.19/include/SugarFields/Fields/File/SugarFieldFile.php#L158

Not much else I can really offer here in terms of help, off the top of my head.

#### Steps to Reproduce
1. Go to a Lead
2. Scroll down to the History subpanel.
3. Click "Create Note or Attachment"
4. Attach a file in the form that opens, it can an image or text file, the file type doesn't really seem to matter.
5. Submit the form
6. Check the PHP Error logs and you should see a notice similar to the ones I've mentioned above. 

You can also preview the file and it'll give an `undefined index: preview` notice as well.

#### Context
PHP Notices are annoying :)

#### Your Environment
* SuiteCRM Version used: 7.10.19, 7.10.20
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 70
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): macOS Mojave 10.14.6

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixed undefined index in document upload and download.

## Motivation and Context

Issue reference: #7838

```
Tested in 7.10.20:
[Mon Sep  9 19:17:47 2019] PHP Notice:  Undefined index: docType in /home/jose/trabajos/SuiteCRM/include/SugarFields/Fields/File/SugarFieldFile.php on line 158
[Mon Sep  9 19:17:47 2019] PHP Stack trace:
[Mon Sep  9 19:17:47 2019] PHP   1. {main}() /home/jose/trabajos/SuiteCRM/index.php:0
[Mon Sep  9 19:17:47 2019] PHP   2. SugarApplication->execute() /home/jose/trabajos/SuiteCRM/index.php:52
[Mon Sep  9 19:17:47 2019] PHP   3. NotesController->execute() /home/jose/trabajos/SuiteCRM/include/MVC/SugarApplication.php:113
[Mon Sep  9 19:17:47 2019] PHP   4. NotesController->process() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:373
[Mon Sep  9 19:17:47 2019] PHP   5. NotesController->handle_action() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:468
[Mon Sep  9 19:17:47 2019] PHP   6. NotesController->pre_action() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:494
[Mon Sep  9 19:17:47 2019] PHP   7. NotesController->pre_save() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:508
[Mon Sep  9 19:17:47 2019] PHP   8. SugarFieldFile->save() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:664
```
```
Mon Sep  9 19:32:13 2019] PHP Notice:  Undefined index: preview in /home/jose/trabajos/SuiteCRM/download.php on line 241
[Mon Sep  9 19:32:13 2019] PHP Stack trace:
[Mon Sep  9 19:32:13 2019] PHP   1. {main}() /home/jose/trabajos/SuiteCRM/index.php:0
[Mon Sep  9 19:32:13 2019] PHP   2. SugarApplication->execute() /home/jose/trabajos/SuiteCRM/index.php:52
[Mon Sep  9 19:32:13 2019] PHP   3. HomeController->execute() /home/jose/trabajos/SuiteCRM/include/MVC/SugarApplication.php:113
[Mon Sep  9 19:32:13 2019] PHP   4. HomeController->process() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:373
[Mon Sep  9 19:32:13 2019] PHP   5. HomeController->handleEntryPoint() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:468
[Mon Sep  9 19:32:13 2019] PHP   6. require_once() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:1020
```

## How To Test This

1. Upload a document and check for PHP notices.
2. Download the uploaded document and check for PHP notices.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
@Abuelodelanada Thanks! should be fixed now.

**Comment by connorshea** [comment]
I think you got the issue reference wrong :)

**Comment by Abuelodelanada** [comment]
No notices now @Dillon-Brown !

Assessed +1

**Comment by Dillon-Brown** [comment]
> I think you got the issue reference wrong :)

Fixed, thanks!

**Pull request merged**
