### PR TITLE
zend-crypt

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Add zend-crypt to composer.

## Motivation and Context

Reverts a breaking change for the 4_1 API and OAuth due to a missing Zend/Crypt/Hmac.php

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by isleshocky77** [comment]
@Dillon-Brown This still throws an error. I believe because of loading Zend stuff from /Zend and from /vendor/zendframework and it not having all of the files.

**Comment by isleshocky77** [comment]
So, it looks like this has some work that needs to be done. The original Zend files were Zend Framework 1.10, then it was replaced with a composer version which is actually Zend Framework 2. The closest I could find is zf1/zend-oauth which actually is Zend Framework 1.12 which is still missing the Zend_Oauth_Provider class which is used in this project.

**Comment by Dillon-Brown** [comment]
@isleshocky77 Can you provide a stack trace? from what I can see Zend/Oauth/Signature/Hmac.php isn't actually in use anywhere, do you have any customisation that might be using it?

**Comment by isleshocky77** [comment]
@Dillon-Brown Yeah, I'll try to recreate it if I have time. 

I honestly gave up and decided to rewrite my connectors for the new v8 API. 

Like I said, I was having an impossible time of getting it to work with composer; I realized I probably should have just went and reverted part of 1f29eed901a0c8adba078aa0a456c34e8b22b0e2 and I probably would have been better off rather than attempting to get a different version of zend through composer.

**Comment by isleshocky77** [comment]
@Dillon-Brown I actually tracked down the log files I was looking for; however, I don't remember which traces were from the clean branch, the clean branch with this PR, and the branch with my changes. But I'll put all of it here including one with HTML_Purifier I ended up hitting.

### This has the earliest timestamp, so this was probably clean branch

```[Tue Jun 12 20:21:36.006570 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP Warning:  require_once(Zend/Crypt/Hmac.php): failed to open stream: No such file or directory in /var/www/Zend/Oauth/Signature/Hmac.php on line 26
[Tue Jun 12 20:21:36.006597 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP Stack trace:
[Tue Jun 12 20:21:36.006606 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   1. {main}() /var/www/service/v4_1/rest.php:0
[Tue Jun 12 20:21:36.006613 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   2. require_once() /var/www/service/v4_1/rest.php:53
[Tue Jun 12 20:21:36.006619 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   3. SugarRestService->serve() /var/www/service/core/webservice.php:66
[Tue Jun 12 20:21:36.006624 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   4. SugarRestJSON->serve() /var/www/service/core/SugarRestService.php:133
[Tue Jun 12 20:21:36.006630 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   5. call_user_func_array:{/var/www/service/core/REST/SugarRestJSON.php:91}() /var/www/service/core/REST/SugarRestJSON.php:91
[Tue Jun 12 20:21:36.006635 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   6. SugarWebServiceImplv3_1->get_available_modules() /var/www/service/core/REST/SugarRestJSON.php:91
[Tue Jun 12 20:21:36.006641 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   7. SugarWebServiceUtilv4->checkSessionAndModuleAccess() /var/www/service/v3_1/SugarWebServiceImplv3_1.php:446
[Tue Jun 12 20:21:36.006646 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   8. SugarWebServiceUtilv4->checkOAuthAccess() /var/www/service/v4/SugarWebServiceUtilv4.php:468
[Tue Jun 12 20:21:36.006651 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   9. SugarOAuthServer->__construct() /var/www/service/v4/SugarWebServiceUtilv4.php:478
[Tue Jun 12 20:21:36.006656 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP  10. Zend_Oauth_Provider->checkOAuthRequest() /var/www/include/SugarOAuthServer.php:175
[Tue Jun 12 20:21:36.006661 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP  11. Zend_Oauth_Provider->checkSignatureMethod() /var/www/Zend/Oauth/Provider.php:300
[Tue Jun 12 20:21:36.006666 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP  12. require_once() /var/www/Zend/Oauth/Provider.php:205
[Tue Jun 12 20:21:36.006676 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP Fatal error:  require_once(): Failed opening required 'Zend/Crypt/Hmac.php' (include_path='/var/www/include/..:.:/usr/share/php') in /var/www/Zend/Oauth/Signature/Hmac.php on line 26
[Tue Jun 12 20:21:36.006680 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP Stack trace:
[Tue Jun 12 20:21:36.006685 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   1. {main}() /var/www/service/v4_1/rest.php:0
[Tue Jun 12 20:21:36.006696 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   2. require_once() /var/www/service/v4_1/rest.php:53
[Tue Jun 12 20:21:36.006701 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   3. SugarRestService->serve() /var/www/service/core/webservice.php:66
[Tue Jun 12 20:21:36.006705 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   4. SugarRestJSON->serve() /var/www/service/core/SugarRestService.php:133
[Tue Jun 12 20:21:36.006709 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   5. call_user_func_array:{/var/www/service/core/REST/SugarRestJSON.php:91}() /var/www/service/core/REST/SugarRestJSON.php:91
[Tue Jun 12 20:21:36.006713 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   6. SugarWebServiceImplv3_1->get_available_modules() /var/www/service/core/REST/SugarRestJSON.php:91
[Tue Jun 12 20:21:36.006718 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   7. SugarWebServiceUtilv4->checkSessionAndModuleAccess() /var/www/service/v3_1/SugarWebServiceImplv3_1.php:446
[Tue Jun 12 20:21:36.006722 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   8. SugarWebServiceUtilv4->checkOAuthAccess() /var/www/service/v4/SugarWebServiceUtilv4.php:468
[Tue Jun 12 20:21:36.006726 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP   9. SugarOAuthServer->__construct() /var/www/service/v4/SugarWebServiceUtilv4.php:478
[Tue Jun 12 20:21:36.006730 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP  10. Zend_Oauth_Provider->checkOAuthRequest() /var/www/include/SugarOAuthServer.php:175
[Tue Jun 12 20:21:36.006734 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP  11. Zend_Oauth_Provider->checkSignatureMethod() /var/www/Zend/Oauth/Provider.php:300
[Tue Jun 12 20:21:36.006738 2018] [:error] [pid 57] [client 172.21.0.1:56382] PHP  12. require_once() /var/www/Zend/Oauth/Provider.php:205
```

### Later on missing other parts of Zend `Zend_Oauth_Provider` which is relied upon by the Oauth Server in Sugar code

```
[Tue Jun 12 20:35:46.581208 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP Fatal error:  Class 'Zend_Oauth_Provider' not found in /var/www/include/SugarOAuthServer.php on line 167
[Tue Jun 12 20:35:46.581231 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP Stack trace:
[Tue Jun 12 20:35:46.581239 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   1. {main}() /var/www/service/v4_1/rest.php:0
[Tue Jun 12 20:35:46.581252 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   2. require_once() /var/www/service/v4_1/rest.php:53
[Tue Jun 12 20:35:46.581258 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   3. SugarRestService->serve() /var/www/service/core/webservice.php:66
[Tue Jun 12 20:35:46.581262 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   4. SugarRestJSON->serve() /var/www/service/core/SugarRestService.php:133
[Tue Jun 12 20:35:46.581267 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   5. call_user_func_array:{/var/www/service/core/REST/SugarRestJSON.php:91}() /var/www/service/core/REST/SugarRestJSON.php:91
[Tue Jun 12 20:35:46.581272 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   6. SugarWebServiceImplv3_1->get_available_modules() /var/www/service/core/REST/SugarRestJSON.php:91
[Tue Jun 12 20:35:46.581277 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   7. SugarWebServiceUtilv4->checkSessionAndModuleAccess() /var/www/service/v3_1/SugarWebServiceImplv3_1.php:446
[Tue Jun 12 20:35:46.581281 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   8. SugarWebServiceUtilv4->checkOAuthAccess() /var/www/service/v4/SugarWebServiceUtilv4.php:468
[Tue Jun 12 20:35:46.581285 2018] [:error] [pid 57] [client 172.21.0.1:57050] PHP   9. SugarOAuthServer->__construct() /var/www/service/v4/SugarWebServiceUtilv4.php:478
```

**Pull request closed without merging**
