### PR TITLE
Feature/email addresses audit

### PR DESCRIPTION
**Pull request by napalmCore**
## Description

New Module to audit email_addresses and email_addr_bean_rel  tables

## Motivation and Context

Record changes done on email_addresses and email_addr_bean_rel tables

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How To Test This

-open an account/contact in edit mode
-edit the email addresses field by changing its value or any of the others option like invalid/op tout
-save the changes
-open the account/contact in detail view 
-click on the change log link next to the email field
-you should be able to see the change log

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Review by e-reeley — DISMISSED** [review]

**Comment by Mac-Rae** [comment]
Please resolve the conflicts on this pull request bringing it up to date.

**Comment by pgorod** [comment]
I believe this should be integrated into the existing Audit feature, instead of being a separate module.

**Comment by serhiisamko091184** [comment]
Hello @napalmCore

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @napalmCore 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

**Pull request closed without merging**
