### PR TITLE
Removed PHP closing tag

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Removed the redundant ?> tags from PHP files. This resolves the "Closing tag "?>" should be omitted on files containing only PHP" issues in SonarQube.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Language files too?

**Comment by Dillon-Brown** [comment]
@horus68 would removing them cause any issues for you? I can split out the language files into a different PR if that makes things easier.

**Comment by horus68** [comment]
@Dillon-Brown no problem here, go for it on all files at once!

**Comment by pgorod** [comment]
I must say this PR makes me nervous... I agree the closing tags should be removed, however with our current state of testing, anything touching 1700+ files is cause for concern. And SuiteCRM has some very non-standard ways of handling PHP, writing files, reading them, combining them, etc. I hope none of this causes an unexpected behaviour somewhere. Fingers crossed...

**Pull request merged**
