### PR TITLE
Fix maps clustering images

### PR DESCRIPTION
**Pull request by gody01**
Since URL:
google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m
is no longer available I changed cluster images to local resource and downloaded them from github.

## Description
Cluster images in Maps module didn't display. Changed to local resources.

## Motivation and Context
To make Maps module working with cluster images.

## How To Test This
Go to Maps, create maps, look at results (You have to have geocoded Your addresses first)

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [ ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
@gody01 your Pull Requests should be made targeting the `hotfix` or `develop` branches, not the `master` branch. You can read about that in the "Contribution Guidelines" (there's a link above)

**Comment by chris001** [comment]
You can edit the branch you're requesting the PR be merged into. It lets you change it from master to hotfix.

**Comment by gody01** [comment]
Hello, PR is now against hotfix.

**Comment by horus68** [comment]
Looks duplicated from https://github.com/salesagility/SuiteCRM/pull/1777

**Comment by Dillon-Brown** [comment]
Closing as duplicate

**Pull request closed without merging**
