### PR TITLE
Fixed #7761 htaccess issue

### LINKED ISSUE #7761: .htaccess file causing file loading issues
From the 7.10.20 release the .htaccess file is causing issues when loading in files, this can be seen if you view, the network out put on your browser (403 errors) 

#### Expected Behavior
All files load correctly with (Status 200)

#### Actual Behavior
Files are not loading correctly (Status 302) and are bring shown to be forbidden.

#### Possible Fix
Update the modules/Administration/UpgradeAccess.php to allow the files to load correctly.

#### Steps to Reproduce
Download 7.10.20
Access Administration Panel.
Repair
Rebuild .htaccess File

Press F12 and Click Network Tab

Hard Refresh SuiteCRM (Ctrl + F5)

View the files that are not getting loaded.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

### PR DESCRIPTION
**Pull request by code-ph0y**
This PR will fix the loading issue with files.

## Description
The current .htaccess file is causing issues with loading, the requests are responding with 302 code with Forbidden.

## Motivation and Context
This PR will allow the correct files to be loaded.

## How To Test This

Install SuiteCRM
Access Administrator Panel
Access Repair
Access Rebuild .htaccess file

Hard Refresh Browser (Disable cache if possible)
View Network tab and check all files are loaded correctly.

Test System to check all functionality is as expected.

Example of generated .htaccess file:
```
# BEGIN SUGARCRM RESTRICTIONS
RedirectMatch 403 (?i).*\.log$
RedirectMatch 403 (?i)/+not_imported_.*\.txt
RedirectMatch 403 (?i)/+(soap|cache|xtemplate|data|examples|include|log4php|metadata|modules|vendor|custom)/+.*\.(php|tpl)
RedirectMatch 403 (?i)/+emailmandelivery\.php
RedirectMatch 403 (?i)/+.git
RedirectMatch 403 (?i)/+.cache/
RedirectMatch 403 (?i)/+tests
RedirectMatch 403 (?i)/+RoboFile\.php
RedirectMatch 403 (?i)/+composer\.json
RedirectMatch 403 (?i)/+composer\.lock
RedirectMatch 403 (?i)/+cache/+diagnostic
RedirectMatch 403 (?i)/+files\.md5$

<IfModule mod_rewrite.c>
    Options +SymLinksIfOwnerMatch
    Options -Indexes
    RewriteEngine On
    RewriteBase /SuiteCRM
    RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&modulename=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&modulename=$1&lang=$2 [L,QSA]
    RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&module=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&module=$1&lang=$2 [L,QSA]

    # --------- DEPRECATED --------
    RewriteRule ^api/(.*)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule ^api/(.*?)$ lib/API/public/index.php/$1 [L]
    # -----------------------------

    RewriteRule ^Api/(.*)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule ^Api/access_token$ Api/index.php/access_token [L]
    RewriteRule ^Api/V8/(.*?)$ Api/index.php/V8/$1 [L]
</IfModule>
<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_URI} (.+)/$
        RewriteRule ^ %1 [R=301,L]
</IfModule>
# END SUGARCRM RESTRICTIONS
<IfModule mod_rewrite.c>
    Options +SymLinksIfOwnerMatch
    RewriteEngine On
    RewriteBase /SuiteCRM
    RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&modulename=app_strings&lang=$1 [L,QSA]
    RewriteRule ^cache/jsLanguage/(\w*)/(.._..).js$ index.php?entryPoint=jslang&modulename=$1&lang=$2 [L,QSA]

    # --------- DEPRECATED --------
    RewriteRule ^api/(.*)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule ^api/(.*?)$ lib/API/public/index.php/$1 [L]
    # -----------------------------

    RewriteRule ^Api/(.*)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule ^Api/access_token$ Api/index.php/access_token [L]
    RewriteRule ^Api/V8/(.*?)$ Api/index.php/V8/$1 [L]
</IfModule>
<FilesMatch "\.(jpg|png|gif|js|css|ico)$">
        <IfModule mod_headers.c>
                Header set ETag ""
                Header set Cache-Control "max-age=2592000"
                Header set Expires "01 Jan 2112 00:00:00 GMT"
        </IfModule>
</FilesMatch>
<IfModule mod_expires.c>
        ExpiresByType text/css "access plus 1 month"
        ExpiresByType text/javascript "access plus 1 month"
        ExpiresByType application/x-javascript "access plus 1 month"
        ExpiresByType image/gif "access plus 1 month"
        ExpiresByType image/jpg "access plus 1 month"
        ExpiresByType image/png "access plus 1 month"
</IfModule>
<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_URI} (.+)/$
        RewriteRule ^ %1 [R=301,L]
</IfModule>
```
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
@code-ph0y if you rename the issue to `Fixed #7761 htaccess issue`, adding a hashtag before 7761, only then will Github correctly pick up the relationship between the Issue and the PR.

**Comment by pgorod** [comment]
Sorry, I meant rename this PR (not the Issue). My mistake

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by adriangibanelbtactic** [comment]
@samus-aran : Is there any ETA on releasing Suitecrm 7.10.21 LTS which, if I'm not mistaken, will include this https://github.com/salesagility/SuiteCRM/pull/7762 pull request?

The current Suitecrm 7.10.20 LTS from August 2019 is unusable after an initial installation because of this #7761 bug.

Feel free to point to me to another issue/place where to discuss about this if this is not the appropiated place.

Thank you very much!

**Comment by jalbaiges** [comment]
Thank you for the PR, @code-ph0y.

I see that some paths like /upload (which I feel is the most important, but also others like /service or /jssource) that used to be protected in .htaccess are not anymore. Is that right?

Thank you very much.

**Review by Zako77xx — COMMENTED** [review]
modules/Administration/UpgradeAccess.php

**Pull request merged**
