### PR TITLE
Check for existance of the global variable, do not use it in isset()

### PR DESCRIPTION
**Pull request by isleshocky77**
## Description

Bug #5918 documents that the Activity feed now shows all items being from 0 seconds ago. This fixes that.

## Motivation and Context

Want to know when the activity occurred. 

## How To Test This

Open up 7.10.5's home page with activity feed on 7.10.5 and this PR.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by isleshocky77** [comment]
@gymad It looks like you added code in 13bacd7b818106ff919b4ab9666581ec1b41dba8 for #5718 to SugarFeed to get it to pass the test suite; however, that fix makes the actual display fail. Think you could lend a hand in fixing it for both? If not I would recommend removing the test is it's not correctly testing ut.

**Comment by isleshocky77** [comment]
@Dillon-Brown Will you not mark this as assessed because it has a failing test? You guys broke the actual application in order to have a test pass which is kind of bad. If you want I'll delete the test?

**Comment by Dillon-Brown** [comment]
@isleshocky77 Just hadn't had a chance to take a look and mark it as assessed yet. I'll see if I can push a fix to resolve Travis failing. Thanks.

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
