### PR TITLE
1 Hour tasks in the calendar consumes 2 spaces

### PR DESCRIPTION
**Pull request by stevejenkin**
It appears a task in the calendar that is for 1 hour duration displays as 2 hours.

## Motivation and Context

We have modified the way a task is displayed in the calendar, now a one hour task will only consume one space in the calendar as opposed to two spaces before.

## How To Test This

Create a task that has a duration of 1 hour.

Look for the task in your calendar, it will consume two spaces giving the user the impression that the task is for 2 hours.
## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Does this replace #3365? you also need to change the branch to hotfix-7.8.x. Thanks for the contribution!

**Comment by stevejenkin** [comment]
Hi Dillon,

 

Yes it does and base updated as requested.

 

Kind regards,

Steve Jenkin
IT & Development Manager



+44 (0)203 598 0898
 <mailto:steve@fibrecrm.com> steve@fibrecrm.com
 <http://www.fibrecrm.com/> www.fibrecrm.com
 <http://uk.linkedin.com/pub/steve-jenkin/41/b7/88>  <https://twitter.com/SteveJenkin>  
Skype: fibrecrm

**Comment by Dillon-Brown** [comment]
Hi @stevejenkin, Unfortunately I don't think this would work as a proper fix for tasks. This PR modifies how tasks are shown on the calendar by replacing the date_due with date_start which would work fine for 1 hour long tasks but not so much for longer, multi-month tasks.

**Comment by stevejenkin** [comment]
Hi @Dillon-Brown, we tested this on 7.8.1 and it appeared to fix the issue for us going forward however I understand your comment. There is definitely a bug here which needs to be fixed.

We do not like to apply non-upgrade-safe code to our systems which this is we will have to apply the fix again post upgrade. Can you reproduce the issue and will you be able to fix it?

**Comment by samus-aran** [comment]
Closing due to being unresolved. Thank you for supplying a contribution!

**Pull request closed without merging**
