### PR TITLE
fix extra heading space

### PR DESCRIPTION
**Pull request by zoltankocsardi**
## Description
Fix unnecessary empty space in heading in different resolution.

## How To Test This
- go to a module and try to expand/contract the browser
before
after
- see if there is no huge space in heading.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Instead of a link to your local install, you should place a picture with a before/after

**Comment by zoltankocsardi** [comment]
Fixed

**Comment by Mausino** [comment]
@zoltankocsardi #4553 thanks... you fixed the main point of my suggestion

**Comment by Dillon-Brown** [comment]
[SuiteCRM 7.10 beta - Refined SuiteP theme - to much space above header](https://trello.com/c/9jroX3Y2/230-suitecrm-710-beta-refined-suitep-theme-to-much-space-above-header)

**Comment by Dillon-Brown** [comment]
@zoltankocsardi style.css.map?

**Comment by zoltankocsardi** [comment]
Removed.

**Pull request merged**
