### PR TITLE
templateParser.php - render 'wysiwyg' fields in PDFs

### PR DESCRIPTION
**Pull request by ApatheticCosmos**
This makes fields from thw 'wysiwyg' addon field render in PDFs
properly.
This commit is the 2nd one I've done. The first was to my
'master' branch and had to be reverted and put into it's
own branch, in the hopes that it will be accepted upstream.

## Description
See issue #241 which is currently closed.

## Motivation and Context

When using the Wysiwyg field module, PDF templates would render the html code. 

## How To Test This

Add these four lines to the file, then include a wysiwyg field to a PDF template.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by ApatheticCosmos** [comment]
It conflicts...
I guess I should be working from the hotfix branch so I'm up to date with changes... lesson learned.

**Comment by ApatheticCosmos** [comment]
I'd like to fix this patch, but the hotfix branch seems to have broken PDF creation completely. It's probably in the middle of some changes. This means I can't fully test the changes. When the PDF creation works, I'll test again and provide a working patch, unless this can be integrated by someone with a working hotfix setup before then.

**Comment by ApatheticCosmos** [comment]
@pstevens71 Thanks!

**Comment by pstevens71** [comment]
Anything new on this?  Just upgraded to 7.10.10 and had to apply the fix again. (It works by the way).  How do we get this pushed into the next version?

**Comment by samus-aran** [comment]
This can be done in an upgrade safe way by extending the entrypoints and calling custom classes. It would be of interest to apply this into core as a permanent fix with extended functionality but at the moment this PR is invalid as there is no issue to fix.... Perhaps someone can raise a PR to make templater parser to be more extend friendly... or post a tutorial <_<

**Pull request closed without merging**
