### PR TITLE
Typo: Missing Quote

### PR DESCRIPTION
**Pull request by gunnicom**
Typo: Missing Quote

### CODE REVIEW

**Comment by ghermans** [comment]
You are making the pull request to the wrong branch, the correct branch to get your pull request accepted is **hotfix**

**Comment by gunnicom** [comment]
Is this true for all pull requests? Since when? Why does nobody communicate that?

**Comment by ghermans** [comment]
FYI http://www.jsmackin.co.uk/suitecrm/contributing-to-suitecrm/

**Comment by gunnicom** [comment]
Do you know if its possible to simply change the branch for this pull request?

**Pull request closed without merging**
