### PR TITLE
Stay on Tab when going from DetailView to EditView

### PR DESCRIPTION
**Pull request by gunnicom**
When on a Tab on Detailview and going to EditView, always the first Tab is open again.
This Patch stays on the Tab that was open on DetailView.
One Commit of the patch is a minor Bugfix, but is needed for the Complete Patch.
The other three patches are the ones that add the enhancement.

Invalidates pull request #93 that did only work in development mode because of template caching.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Appears to no longer work correctly. Please change branch to hotfix-7.8.x

**Comment by Dillon-Brown** [comment]
Closing for now. This would need to be re-made for hotfix-7.8.x.

**Comment by gunnicom** [comment]
That is a good way to get rid of PRs *sarkasmoff*

**Comment by Dillon-Brown** [comment]
@gunnicom There's nothing stopping you from re-opening if you want to continue this. I don't see much point in having a 2 year old non-working PR up though.

**Comment by gunnicom** [comment]
It is not working _anymore_ because of salesagility, not because of me.

**Pull request closed without merging**
