### PR TITLE
Fix Issue when importing non UTF-8 CSV file

### PR DESCRIPTION
**Pull request by QuickCRM**
[Cases_with_accents.xlsx](https://github.com/salesagility/SuiteCRM/files/3609364/Cases_with_accents.xlsx)

## Description

Removed translateCharset that were already executed in earlier steps of the Import

#6442

## Motivation and Context

Special characters are not imported correctly.

## How To Test This

Save attached file in CSV format with Excel/Windows and try import it

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Hey @QuickCRM Travis is failing due to PHP 5.5 and Chrome not being compatible. So we would put this down to a false negative.

**Comment by samus-aran** [comment]
@Mac-Rae & @cameronblaikie Are you able to assess this please?

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
