### PR TITLE
Fixed #7696 - Folder "include/SugarCharts/Jit" missing in 7.11.7 installation

### LINKED ISSUE #7696: Folder "include/SugarCharts/Jit" missing in 7.11.7 installation
#### Issue
The folder "include/SugarCharts/Jit" was removed from the installation .zip between 7.11.6 and 7.11.7.
This causes not being able to modify the Dashlets on the start page.
The suitecrm.log states this as "[FATAL] Chart class not found."

#### Expected Behavior
The folder "include/SugarCharts/Jit" including the recend files and subdirectories should be in the 7.11.7 installation .zip
You should be able to add, modify or delete Dashlets on the start page.

#### Actual Behavior
The folder "include/SugarCharts/Jit" including the recent files and subdirectories are non-existant.
Clicking on the action buttons to add, modify or delete Dashlets causes no action (no error message, no loading screen)

#### Possible Fix
Include the folder "include/SugarCharts/Jit" including the recend files and subdirectories again in the next version

Current Workaround: Copy folder "include/SugarCharts/Jit" from 7.11.6 installation .zip into the 7.11.7 installation

#### Steps to Reproduce
1. Open 7.11.7 installation-zip
2. Open 7.11.6 installation-zip
3. Compare folders "include/SugarCharts/" and see the missing "Jit" folder

#### Context
Cant modify Dashlets

#### Your Environment
* SuiteCRM Version used: 7.11.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): multiple
* Environment name and version (e.g. MySQL, PHP 7): Apache 2.4, MariaDB 7.2, PHP7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS7

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixed an issue with missing ```include/SugarCharts/Jit``` causing the homepage dashlets to fail.

## Motivation and Context

Issue reference: #7696 
Issue reference: #7688

## How To Test This

Test all homepage dashlets and modules that contain charts.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by MyBlissIT** [comment]
I downloaded latest version, 7.11.7 zip file from SuiteCRM website. Following the Upgrade instruction, when I attempt to Upload Package I get an error message that "The zip file is missing a manifest.php file. Cannot proceed."

image

**Comment by Dillon-Brown** [comment]
Hi @MyBlissIT, I can't seem to replicate this. Which upgrade pack were you attempting to upload?

**Comment by MyBlissIT** [comment]
> Hi @MyBlissIT, I can't seem to replicate this. Which upgrade pack were you attempting to upload?

It is SuiteCRM 7.11.7

**Comment by Dillon-Brown** [comment]
@MyBlissIT, ah were you looking at the 7.11.7 installer? the download page you are likely looking for is actually here: https://suitecrm.com/upgrade-suitecrm/. An installer like the one found on https://suitecrm.com/download/ is for installing SuiteCRM for the first time while the upgrade packs (Which contain the manifest file) allow you to update an existing SuiteCRM instance.

**Comment by MyBlissIT** [comment]
> @MyBlissIT, ah were you looking at the 7.11.7 installer? the download page you are likely looking for is actually here: https://suitecrm.com/upgrade-suitecrm/. An installer like the one found on https://suitecrm.com/download/ is for installing SuiteCRM for the first time while the upgrade packs (Which contain the manifest file) allow you to update an existing SuiteCRM instance.

Thanks @Dillon-Brown  I have just downloaded the upgrade package

**Comment by Dillon-Brown** [comment]
@MyBlissIT 👍 let me know if you run into any issues.

**Comment by MyBlissIT** [comment]
> @MyBlissIT 👍 let me know if you run into any issues.

I think its my internet speed, it is taking forever to "Upload Package"

**Comment by MyBlissIT** [comment]
> @MyBlissIT 👍 let me know if you run into any issues.

I just got this message"The uploaded file is not compatible with this version of SuiteCRM: 
SuiteCRM System Version: 7.10.18"

**Comment by Dillon-Brown** [comment]
@MyBlissIT Hmm, interesting. Was this the upgrade pack you were trying to use? https://suitecrm.com/files/162/SuiteCRM-7.11-Upgrades/458/SuiteCRM-Upgrade-7.10.x-to-7.11.7.zip

**Comment by MyBlissIT** [comment]
I tried this one https://suitecrm.com/files/162/SuiteCRM-7.11-Upgrades/457/SuiteCRM-Upgrade-7.8.x-to-7.11.7.zip

**Comment by Dillon-Brown** [comment]
@MyBlissIT is your current version of SuiteCRM 7.8.x? the warning you received "The uploaded file is not compatible with this version of SuiteCRM: SuiteCRM System Version: 7.10.18" implies you are actually on version 7.10.8 which would mean you would be looking to use the 7.10.x upgrade pack: https://suitecrm.com/files/162/SuiteCRM-7.11-Upgrades/458/SuiteCRM-Upgrade-7.10.x-to-7.11.7.zip

**Comment by MyBlissIT** [comment]
> @MyBlissIT is your current version of SuiteCRM 7.8.x? the warning you received "The uploaded file is not compatible with this version of SuiteCRM: SuiteCRM System Version: 7.10.18" implies you are actually on version 7.10.8 which would mean you would be looking to use the 7.10.x upgrade pack: https://suitecrm.com/files/162/SuiteCRM-7.11-Upgrades/458/SuiteCRM-Upgrade-7.10.x-to-7.11.7.zip

These is actually my current version: Version 7.10.18
Sugar Version 6.5.25 (Build 344)

**Comment by MyBlissIT** [comment]
The upgrade was a success @Dillon-Brown , however, my Dashboard still does not show any dashlets

**Comment by Mac-Rae** [comment]
Assessed :+1: 

Needs CRed @code-ph0y ?

**Comment by MyBlissIT** [comment]
I think I will delete and re-download again

**Comment by samus-aran** [comment]
> I think I will delete and re-download again
@MyBlissIT the resolve hasn't been released yet so the current packages you are downloading wouldn't resolve the issue.
Best to wait until we have released to try the latest version.

**Comment by MyBlissIT** [comment]
Ohh great then. I was under the impression the issue is isolated to my
system...

I have about 4 prospective people that want me to assist them with
installation of SuiteCRM

**Comment by MyBlissIT** [comment]
I have performed a new install on a separate domain and the dashboard, albeit without any modifications on the system yet, it is the latest version.

image

**Comment by holdusback** [comment]
I had this issue in 7.11.8.

Checked the fix https://github.com/salesagility/SuiteCRM/pull/7697/commits/7e21c5806f1b23db91e32ec88a654bab518cfbc6 and after checking I dont had thoses file in my instance (last version of 7.11.8) so I've manually added the SugarCharts folde rfrom the update to my working instance and It fixed my issue. Maybe a new problem with the 7.11.8 ... Will post it on this topic :

https://suitecrm.com/suitecrm/forum/installation-upgrade-help/27257-upgrage-from-7-11-7-to-7-11-8-failed?start=15#88674

**Pull request merged**
