### PR TITLE
Allow workflow to send plain text emails

### PR DESCRIPTION
**Pull request by cyb456**
## Description

Workflows always send html email as reported here https://community.suitecrm.com/t/workflow-send-email-send-text-only-always-sending-as-html/33987 this change fixes this issue allowing plain text emails to be sent if the template is selected to be plain text only.
## Motivation and Context

Trying to send a plain text email with a workflow
## How To Test This

Set up a workflow to send a email template that has plain text checked
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
I am curious, what is the reason why someone would want to send a plain text email in 2023?

**Comment by chris001** [comment]
Many. Email-to-SMS.  Email-to-MMS.  Some organizations are high security, preferring text only, don't want HTML email due to past phishing, ransomware attacks.

**Comment by serhiisamko091184** [comment]
Hello @cyb456 ,
thanks a lot for the contribution!

Regards,
Serhii

**Review by clemente-raposo — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
LGTM, Plaintext Email templates now sending as text/plain type emails.
HTML Email Templates seem unnaffacted by this change, able to send as normal.

**Review by johnM2401 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]

**Pull request merged**
