### PR TITLE
Show hour on datetime fields when parsing AOS_PDF_Templates

### PR DESCRIPTION
**Pull request by sanchezfauste**
When you add a datetime field on a template, the final result is to show only the date part. We have modified the behaviour of template parser to show only the date part of the field if the field is defined as data type. If the field is of type datetime, the final result is to show the date and the time.

## Description

We store the type of each field on an array when we load all the variables needed to parse the template, to be able to check the type of field when we parse the template later.

The actual behaviour is to display only the date part of a field if the name of the field contains 'date' or 'expiration'. We have modified this behaviour to show the only the date part if the field is of type date. So the datetime fileds will display the date and the time.

Issue #2694

## Motivation and Context

We need to create a template to notify the date and the time of a meeting to the related Customer. A part of showing the start date of the meeting it's also important to show the time.

## How To Test This

1. Create a email template and insert a datetime field in email body/subject.
2. Send email via workflow.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by LuminisIndia** [comment]
@sanchezfauste , Thanks for proposing the solution.  I am able to receive the email via WorkFlow and date & time are being parsed.  However, time is being parsed only in UTC time.  I want it to be parsed it as I mention it.  Where do I need to make changes?

With thanks,

RK

**Comment by sanchezfauste** [comment]
Hello @LuminisIndia, we have a workaround for this. See my comment on #3468

**Comment by Mac-Rae** [comment]
Please resolve the conflicts on this pull request bringing it up to date.

**Comment by sanchezfauste** [comment]
> Please resolve the conflicts on this pull request bringing it up to date.

Hi! Done.

**Review by Dillon-Brown — APPROVED** [review]

**Comment by willrennie** [comment]
@sanchezfauste Your PR here is for PDF templates, but the issue you are fixing #2694 appears to be related to Email Templates. Also, I have tested the functionality and this is working in the latest SuiteCRM releases i.e. date time fields are represented as such in Email and PDF Templates. Please can you clarify if your fix is still valid and if so what bug specifically you are addressing? Thanks.

**Comment by serhiisamko091184** [comment]
Hello @sanchezfauste 

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hey @sanchezfauste 

Closing this PR due to inactivity. 
Thank you.

Regards,
Serhii

**Pull request closed without merging**
