### PR TITLE
Select database character encoding on Install UI

### PR DESCRIPTION
**Pull request by dominicchinkh**
Allow selecting database character set on installation

## Description
Add "Advanced Database Configuration" session under "More options". Under "Advanced Database Configuration", add "Collation" and "Character Set" combo box. The collations list and character set list can be configured with install/suite_install/collations.php file.

This feature only work if the other pull request is in place: https://github.com/salesagility/SuiteCRM/pull/6461.

## Motivation and Context
This feature enable first-time user to select a collation/character set that work in their environment without messing around with config_override.php file.

## How To Test This
Remove config.php file and point browser to the SuiteCRM instance to start to installation process.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Abuelodelanada** [comment]
Wonderful @dominicchinkh !!

**Comment by horus68** [comment]
@dominicchinkh this PR should be made against the HOTFIX branch, not the Master branch. You can change the branch directly in the Git web interface

**Comment by samus-aran** [comment]
Hey @dominicchinkh Are you able to review the comments made?

**Comment by dominicchinkh** [comment]
Sorry for late response. Was in a long holiday and busy since then. I have made the requested change and commit. Thank you.

**Comment by pribeiro42** [comment]
Alert to @SuiteCRM-Core

**Comment by Mac-Rae** [comment]
Please resolve the conflicts on this pull request bringing it up to date.

**Comment by dominicchinkh** [comment]
This pull request is ages old and is now out-of-sync with master. I created another pull request under
https://github.com/salesagility/SuiteCRM/pull/7790. Also merge the changes from another related pull request https://github.com/salesagility/SuiteCRM/pull/6461.

**Pull request closed without merging**
