### PR TITLE
Unused language strings

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Combined PR for the removal of unused strings

## Motivation and Context

- Issue reference:  #3930 
- Issue reference:  #3935 
- Issue reference:  #3937 
- Issue reference:  #3939 
- Issue reference:  #3940 
- Issue reference:  #3941 
- Issue reference:  #3942 
- Issue reference:  #3943 
- Issue reference:  #3944 
- Issue reference:  #3945 
- Issue reference:  #3946 
- Issue reference:  #3947 
- Issue reference:  #3948 
- Issue reference: #3949
- Issue reference: #3950
- Issue reference: #3951
- Issue reference: #3952
- Issue reference: #3953
- Issue reference: #3954
- Issue reference: #3955
- Issue reference: #3956
- Issue reference: #3957
- Issue reference: #3958
- Issue reference: #3959
- Issue reference: #3960
- Issue reference: #3961
- Issue reference: #3962
- Issue reference: #3963
- Issue reference: #3964
- Issue reference: #3965
- Issue reference: #3966
- Issue reference: #3967
- Issue reference: #3968
- Issue reference: #3969
- Issue reference: #3970
- Issue reference: #3971
- Issue reference: #3972
- Issue reference: #3973
- Issue reference: #3974
- Issue reference: #3975
- Issue reference: #3976
- Issue reference: #3977
- Issue reference: #3978
- Issue reference: #3979
- Issue reference: #3980
- Issue reference: #3981
- Issue reference: #3982
- Issue reference: #3983
- Issue reference: #3984
- Issue reference: #3985
- Issue reference: #3986
- Issue reference: #3987
- Issue reference: #3988
- Issue reference: #3989
- Issue reference: #3990
- Issue reference: #3991
- Issue reference: #3993
- Issue reference: #3994
- Issue reference: #3995
- Issue reference: #3996
- Issue reference: #3997
- Issue reference: #3998
- Issue reference: #3999
- Issue reference: #4000
- Issue reference: #4001
- Issue reference: #4002
- Issue reference: #4003
- Issue reference: #4004
- Issue reference: #4005
- Issue reference: #4006
- Issue reference: #4007
- Issue reference: #4008
- Issue reference: #4010
- Issue reference: #4011
- Issue reference: #4012
- Issue reference: #4013
- Issue reference: #4014
- Issue reference: #4015
- Issue reference: #4016
- Issue reference: #4018
- Issue reference: #4019
- Issue reference: #4022
- Issue reference: #4023
- Issue reference: #4024
- Issue reference: #4025
- Issue reference: #4026
- Issue reference: #4027
- Issue reference: #4029
- Issue reference: #3926
- Issue reference: #3926

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Hi @horus68, I saw you posting on another issue, are you back from holidays? Hope you had a great rest.

I think this PR here is a nice way to welcome you back, it's good news for the translation effort. I was worrying that this would be released while you were away, it probably involves some work by you on Crowdin, right? Or do I worry too much? :-)

**Comment by horus68** [comment]
Yeah .. I did see this only today (back from holidays)!
This will be massive work for me, specially because my Crowdin english files also includes strings from some PR not merged yet.
I will back to this next week as I'm now more in "urgent tasks" mode!

**Comment by pgorod** [comment]
I'm sure @Dillon-Brown can work with you to make sure the release data works well for you. From what I gather, it seems we're building up to a security release (lots of security-related merges lately! Great!) and these language PR's will be inside that.

**Comment by horus68** [comment]
Done in Crowdin

**Pull request merged**
