### PR TITLE
FIX  #7268 - Fatal Error with PHP 7.3

### LINKED ISSUE #7268: Fatal Error with PHP7.3 with LoggerManager.php
#### Issue

When running SuiteCRM 7.10.x with PHP7.3.x the following Fatal error is raised

```bash
[Tue May 07 14:47:54.341575 2019] [php7:notice] [pid 24387] [client 127.0.0.1:42204] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /home/jose/trabajos/gca-suitecrm7.10x/include/SugarLogger/LoggerManager.php:169
Stack trace:
#0 /home/jose/trabajos/gca-suitecrm7.10x/custom/include/SugarLogger/SuiteWSLogger.php(83): LoggerManager::setLevel('webservices')
#1 /home/jose/trabajos/gca-suitecrm7.10x/include/SugarLogger/LoggerManager.php(219): SuiteWSLogger->__construct()
#2 /home/jose/trabajos/gca-suitecrm7.10x/include/SugarLogger/LoggerManager.php(88): LoggerManager->_findAvailableLoggers()
#3 /home/jose/trabajos/gca-suitecrm7.10x/include/SugarLogger/LoggerManager.php(180): LoggerManager->__construct()
#4 /home/jose/trabajos/gca-suitecrm7.10x/include/entryPoint.php(156): LoggerManager::getLogger()
#5 /home/jose/trabajos/gca-suitecrm7.10x/index.php(48): require_once('/home/jose/trab...')
#6 {main}
  thrown in /home/jose/trabajos/gca-suitecrm7.10x/include/SugarLogger/LoggerManager.php on line 169, referer: http://localhost/gca-suitecrm7.10x/index.php?module=Home&action=index
```
In include/SugarLogger/LoggerManager.php line 169 we have:

```php
public function setLevel(
    $name
    ) {
    if (isset(self::$_levelMapping[$name])) {
        $this->_level = $name;
    }
}
```

We should use:

`self::$_level = $name;`

instead of:

`$this->_level = $name;`

#### Expected Behavior

Not having a Fatal error using PHP 7.3.x, [the current stable version](https://www.php.net/downloads.php#v7.3.5)

#### Actual Behavior

A Fatal error is raised

#### Possible Fix

```diff
modified   include/SugarLogger/LoggerManager.php
@@ -48,7 +48,7 @@ if (!defined('sugarEntry') || !sugarEntry) {
 class LoggerManager
 {
     //this the the current log level
-    private $_level = 'fatal';
+    private static $_level = 'fatal';
 
     //this is a list of different loggers that have been loaded
     protected static $_loggers = array();
@@ -79,7 +79,7 @@ class LoggerManager
     //only let the getLogger instantiate this object
     private function __construct()
     {
-        $level = SugarConfig::getInstance()->get('logger.level', $this->_level);
+        $level = SugarConfig::getInstance()->get('logger.level', self::$_level);
         if (!empty($level)) {
             $this->setLevel($level);
         }
@@ -100,14 +100,14 @@ class LoggerManager
         $message
         ) {
         if (!isset(self::$_levelMapping[$method])) {
-            $method = $this->_level;
+            $method = self::$_level;
         }
         //if the method is a direct match to our level let's let it through this allows for custom levels
-        if ($method == $this->_level
+        if ($method == self::$_level
                 //otherwise if we have a level mapping for the method and that level is less than or equal to the current level let's let it log
                 || (!empty(self::$_levelMapping[$method])
                     && (
-                            (isset(self::$_levelMapping[$this->_level]) ? self::$_levelMapping[$this->_level] : null) >=
+                            (isset(self::$_levelMapping[self::$_level]) ? self::$_levelMapping[self::$_level] : null) >=
                             (isset(self::$_levelMapping[$method]) ? self::$_levelMapping[$method] : null)
                     ))) {
             //now we get the logger type this allows for having a file logger an email logger, a firebug logger or any other logger you wish you can set different levels to log differently
@@ -130,12 +130,12 @@ class LoggerManager
     public function wouldLog($method)
     {
         if (!isset(self::$_levelMapping[$method])) {
-            $method = $this->_level;
+            $method = self::$_level;
         }
-        if ($method == $this->_level
+        if ($method == self::$_level
                 //otherwise if we have a level mapping for the method and that level is less than or equal to the current level let's let it log
                 || (!empty(self::$_levelMapping[$method])
-                        && self::$_levelMapping[$this->_level] >= self::$_levelMapping[$method])) {
+                        && self::$_levelMapping[self::$_level] >= self::$_levelMapping[$method])) {
             return true;
         }
         return false;
@@ -166,7 +166,7 @@ class LoggerManager
         $name
         ) {
         if (isset(self::$_levelMapping[$name])) {
-            $this->_level = $name;
+            self::$_level = $name;
         }
     }
```

#### Steps to Reproduce

1. Run SuiteCRM 7.10.x in PHP 7.3.x
2. Verify Fatal error in PHP log.

#### Your Environment

* SuiteCRM Version used: 7.10.x
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 66.0.3
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.3.5
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 19.04

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

See #7268

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
Failing on the flaky ActivitiesCest test. Need to get #7263 merged.

**Comment by Abuelodelanada** [comment]
Another PR related to PHP7.3: #6630

**Comment by Abuelodelanada** [comment]
@Dillon-Brown 

> @Abuelodelanada
> 
> ```
> 1) SuiteLoggerTest::testLogEmergency
> Accessing static property LoggerManager::$_level as non static
> /home/travis/build/salesagility/SuiteCRM/include/SugarLogger/LoggerManager.php:243
> /home/travis/build/salesagility/SuiteCRM/tests/unit/phpunit/lib/SuiteCRM/Utility/SuiteLoggerTest.php:33
> /home/travis/build/salesagility/SuiteCRM/vendor/phpunit/phpunit/phpunit:52
> ```

Fixed in https://github.com/salesagility/SuiteCRM/pull/7269/commits/ed16f8a6080c0e4ea303ffab516529cd470e5cd9

**Comment by Abuelodelanada** [comment]
@Dillon-Brown Give some hours before merging this PR... We found a bug when having 2 Logger class

**Comment by Abuelodelanada** [comment]
It's ok @Dillon-Brown It was no bug when having 2 Logger classes... my mistake.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
