### PR TITLE
Fixed #5656 - ListViewDisplay Incorrectly Checking for $this->email to be 'Set' Instead of True/False

### LINKED ISSUE #5656: ListViewDisplay Incorrectly Checking for $this->email to be 'Set' Instead of True/False
#### Issue
On line 330 of include/ListView/ListViewDisplay.php you see the following:

```
// compose email
 if (isset($this->email)) {
                $menuItems[] = $this->buildComposeEmailLink($this->data['pageData']['offsets']['total'], $location);
            }
```

This is actually causing modules such as the Employees Module to still display the "Email" link on the ListView despite the fact that in modules/Employees/views/view.list.php in the `preDisplay()` function, you actually have the code:

```
public function preDisplay()
 	{
 		$this->lv = new ListViewSmarty();
 		$this->lv->delete = false;
 		$this->lv->email = false;
 		if (!$GLOBALS['current_user']->isAdminForModule('Users')){
            $this->lv->multiSelect = false;
        }
 	}
```

The problem is that `$this->lv->email` is set to false, however, in order to exclude it, you would need to set this variable to null or unset the variable.

#### Expected Behavior
I should be able to set `$this->lv->email` to false to exclude it from the menu.

#### Actual Behavior
`$this->lv->email = false` does not exclude it from the menu

#### Possible Fix
On line 330 of include/ListView/ListViewDisplay.php, change the code simply to:

```
// compose email
            if ($this->email) {
                $menuItems[] = $this->buildComposeEmailLink($this->data['pageData']['offsets']['total'], $location);
            }
```

#### Steps to Reproduce
1. Go to the employees module
2. See that the 'Email' actions menu option is still visible
3. Go to modules/Employees/views/view.list.php and see that `$this->lv->email = false`

#### Context
I noticed that the option was there and did not want the option to be there, so I was confused when I saw that you were already excluding it in view.list.php. We have a heavily customized Employees module that allows non-admin users to edit and create users from this panel.

#### Your Environment
* SuiteCRM Version used: 7.5.1
* Browser name and version: Version 65.0.3325.181 (Official Build) (64-bit)
* Environment name and version: PHP 7.1.12, MySQL 5.6.38
* Operating System and version: macOS Sierra 10.12.3

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixes a bug that prevents $this->lv->email = false; from having an effect on showing the email link in the list-view.

## Motivation and Context

Issue reference: #5656 

## How To Test This

1. Go to employees module..
2. Check that the email link next to bulk action is gone.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by e-reeley** [comment]
Assessed

**Comment by jshwhitlow** [comment]
@daniel-samson, why do pull requests like this one take so long to be assessed? As a developer I know things take a long time, but given the high volume of pull requests just sitting out there, it seems like assessments are really falling behind (almost 2 years in some cases). 

This isn't an area where the community can assist, so I guess I'm just asking if more time can be dedicated to assessing pull requests. Thanks!

**Comment by Dillon-Brown** [comment]
Hi @jshwhitlow, in this particular case it's mostly due to me forgetting my own PR's! i'm normally the one doing most of the assessing so usually my own pull requests tend to take a bit longer to get merged in. It's definitely something we are aware of and are actively working on at the moment (23 PR's merged in the last 2 days!).

I disagree that this isn't an area that the community can assist in however, just leaving a simple "works for me" as a comment greatly assists us when it comes to looking at PR's to merge and increasing our confidence that it works on multiple setups.

**Comment by jshwhitlow** [comment]
@Dillon-Brown, thanks for the reply! I'll dedicate some time each month to reviewing some pull requests to ensure they work, and doing as you suggest.

Thanks!

**Comment by daniel-samson** [comment]
Assessed

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
