### PR TITLE
Update contributing.md

### PR DESCRIPTION
**Pull request by Mac-Rae**
## Description

Update Labels & descriptions
Update references to 7.8.x & develop

## Motivation and Context

Recently update labels so these also needed to be updated

PR to doc site also coming soon

## How To Test This

View the file and ensure the links work as expected

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by cameronblaikie** [comment]
LGTM - Assessed :+1:

**Comment by pgorod** [comment]
How does one browse this `contributing.md` file? Is there a menu option where GitHub shows it, apart from navigating the code folders and opening it?

I am also asking this in order to consider whether we should just move all these label descriptions to the Docs site, if they have more visibility there.

**Comment by Mac-Rae** [comment]
Hey @PedroErnst,

I have made a PR to update the Docs site already :)
Im not sure the best place to view the contribution.md but it can be found by opening in github

**Comment by Dillon-Brown** [comment]
@pgorod Agreed that the doc site is the preferred place to link people to. The ```contributing.md``` and ```security.md``` are really just there for best practice reasons (And to get rid of the GitHub notice if you don't have them :P), I doubt most people will notice them tbh but some developers will check the ```.github``` directory after pulling down a repo for the first time.

**Pull request merged**
