### PR TITLE
Fix php 8 issue with old user preferences null values

### PR DESCRIPTION
**Pull request by JanSiero**
This PR fixes an issue were old user preferences containing null values conflict with PHP 8

## Description
In SuiteCRM installations which were previously upgraded from SugarCRM the user preferences may contain null values for Dashlet preferences. When upgrading the PHP version to version 8, these null values become an issue as the php count() method throws an error when feeded with this null value.

## Motivation and Context
This PR solves issues when migrating from PHP 7 to PHP 8 that have user preferences from earlier versions of Suite or SugarCRM.

## How To Test This
- Install SuiteCRM 7 on a system with PHP 8.0
- On the Home page, click on "Actions", "Add Dashlet" and click on the tab "Charts"
- Add one or more of the following chart dashlets:
    - All Opportunities By Lead Source By Outcome
    - All Opportunities by Lead Source
    - My Pipeline By Sales Stage
    - Outcome By Month
    - Pipeline By Sales Stage
 - Go to Admin / Module Loader and load the following module
[bogusprefs.zip](https://github.com/salesagility/SuiteCRM/files/8311166/bogusprefs.zip)
This module injects null values to the user preferences of these charts which simulates user preferences found in installations migrated from SugarCRM
 - After installation, go back to the home page

**Expected results**
The Home page displays normally with the activated dashlet(s)

**Observed behaviour**
The home page is empty, none of the dashlets is shown

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jack7anderson7** [comment]
Hi @JanSiero,

Could you please update your commit message to `Fix #num`, as this does not pertain to an issue created could you add the number of the PR.

Thanks,
Jack

**Comment by pgorod** [comment]
Having a preference set to `null` can be a valid, meaningful option. I wonder if we shouldn't keep that as a possibility (I'm not sure, but there could be backwards-compatibility issues changing this).

Where is the `count` that throws an error with nulls on PHP 8.0?

**Comment by JanSiero** [comment]
Hi, I added a commit that solves this issue by checks for the affected count methods.

You can choose to use either the first two commits or the last commit.

**Comment by jack7anderson7** [comment]
Hi @JanSiero,

Can you please squash your commits into a single commit.

Thanks,
Jack

**Comment by JanSiero** [comment]
Hi @jack7anderson7 I don't know how to do this safely without using "reset".

Would it be possible to only use this last commit and ignore the other two?
 
https://github.com/salesagility/SuiteCRM/pull/9542/commits/c9fe46f0497837cdcdaff25135cad023023728f2

**Comment by JanSiero** [comment]
Hi @jack7anderson7 I changed this to only include the commit with the relevant changes and removed the commits with the changes which @pgorod objected to, so now you have one single commit.

**Review by clemente-raposo — APPROVED** [review]

**Comment by clemente-raposo** [comment]
Hi @JanSiero, thank you for your PR

**Review by johnM2401 — APPROVED** [review]
LGTM - Checked in PHP80/81/82, Homepage successfully loads with charts.

**Pull request merged**
