### PR TITLE
Remove unused webDriverHelper variables

### PR DESCRIPTION
**Pull request by connorshea**
## Description
Throughout the acceptance test suite the webDriverHelper was unused. After #7418 removed repetitive URL visits throughout the test suite, it was no longer necessary in most cases.

This cleans all of those up.

## Motivation and Context
Getting rid of dead code.

## How To Test This
Make sure Travis CI passes.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
Codacy made this fail 🤷‍♂

**Comment by Dillon-Brown** [comment]
Wow, Codacy sure is brutal lol. It's not a required check though so this PR should be good to get code-reviewed and merged in.

**Comment by connorshea** [comment]
@Dillon-Brown could this be merged as well? :)

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
