### PR TITLE
Remove Robofile.php + Update composer.lock

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Removes the Robofile.php as robotasks should be defined either in custom or lib/robo. Also made a small change for windows compatiblity in php-csfixer command and updated composer.lock.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
Should this mention where to put custom Robo commands? https://docs.suitecrm.com/developer/automatedtasks/

**Comment by Dillon-Brown** [comment]
Interesting, I can't actually see any errors when removing this file and running Robo. I wonder if we can just remove it.

**Comment by connorshea** [comment]
I removed it locally from our fork and Robo doesn't seem to care either, so it seems like you can safely remove this.

**Comment by Dillon-Brown** [comment]
Closing this in favour of #7008 which will get merged into hotfix.

**Pull request closed without merging**
