### PR TITLE
add not contains and is not null conditions operator to workflow and reports

### PR DESCRIPTION
**Pull request by oc666**
## Description

* Add not contains condition to workflow and reports.
* Add is not null condition to workflow.

## Motivation and Context

There is condition of contains of varchar.
## How To Test This

add new workflow or report with condition of not contains.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by gunnicom** [comment]
Duplicate: https://github.com/salesagility/SuiteCRM/pull/2324

**Comment by oc666** [comment]
@gunnicom 
My PR includes also workflow in addition to reports.

**Comment by amariussi** [comment]
I think that, since there is a PR for this we could also add some other missing operators that may be useful:
. Not Starts With
. Not Ends With
. Is Null (only for AOR Reports)
. Is NOT Null

Looking at the modifications you made it should take only a few minutes to implement these as well.

Alternatively we could add a NOT operator (but I presume it is more difficult, so these would be great to have immediately!).

**Comment by oc666** [comment]
@amariussi currently we do not find the resources to do so. Please push this PR forward and we will push your new request on our next version.

**Comment by amariussi** [comment]
These are alle the changes that I can think of:
(mine are marked with a '+' in front)

`include/language/en_us.lang.php
...
...
...
$app_list_strings['aor_operator_list']['Starts_With'] = 'Starts With';
+$app_list_strings['aor_operator_list']['Not_Starts_With'] = 'Not Starts With';
$app_list_strings['aor_operator_list']['Ends_With'] = 'Ends With';
+$app_list_strings['aor_operator_list']['Not_Ends_With'] = 'Not Ends With';
+$app_list_strings['aor_operator_list']['is_null'] = 'Is Null';
+$app_list_strings['aor_operator_list']['is_not_null'] = 'Is Not Null';
...
...
...
$app_list_strings['aow_operator_list']['Starts_With'] = 'Starts With';
+$app_list_strings['aow_operator_list']['Not_Starts_With'] = 'Not Starts With';
$app_list_strings['aow_operator_list']['Ends_With'] = 'Ends With';
+$app_list_strings['aow_operator_list']['Not_Ends_With'] = 'Not Ends With';
$app_list_strings['aow_operator_list']['is_null'] = 'Is Null';
+$app_list_strings['aow_operator_list']['is_not_null'] = 'Is Not Null';
...
...
...



modules/AOR_Reports/AOR_Report.php
...
...
...
$aor_sql_operator_list['Starts_With'] = 'NOT LIKE';
$aor_sql_operator_list['Ends_With'] = 'NOT LIKE';
...
...
...
                         case 'Starts_With':
+                         case 'Not_Starts_With':
                             $value = "CONCAT(" . $value . " ,'%')";
                             break;
                         case 'Ends_With':
+                         case 'Not_Ends_With':
                             $value = "CONCAT('%', " . $value . ")";
                             break;
...
...
...



modules/AOR_Reports/controller.php
...
...
...
                $valid_opp = array('Equal_To', 'Not_Equal_To', 'Contains', 'Not_Contains', 'Starts_With', 'Not_Starts_With', 'Ends_With', 'Not_Ends_With',);
...
...
...



modules/AOW_WorkFlow/AOW_WorkFlow.php
...
...
...
                 case 'Starts_With':
+                 case 'Not_Starts_With':
                     $value = "CONCAT(".$value." ,'%')";
                     break;
                 case 'Ends_With':
+                 case 'Not_Ends_With':
                     $value = "CONCAT('%', ".$value.")";
                     break;
...
...
...
     function compare_condition($var1, $var2, $operator = 'Equal_To'){
         switch ($operator) {
             case "Not_Equal_To": return $var1 != $var2;
             case "Greater_Than":  return $var1 >  $var2;
             case "Less_Than":  return $var1 <  $var2;
             case "Greater_Than_or_Equal_To": return $var1 >= $var2;
             case "Less_Than_or_Equal_To": return $var1 <= $var2;
             case "Contains" : return strpos($var1,$var2);
             case "Not_Contains" : return strpos($var1,$var2) === FALSE;
             case "Starts_With" : return strrpos($var1,$var2, -strlen($var1));
+             case "Not_Starts_With" : return strrpos($var1,$var2, -strlen($var1)) === FALSE;
             case "Ends_With" : return strpos($var1,$var2,strlen($var1) - strlen($var2));
+             case "Not_Ends_With" : return strpos($var1,$var2,strlen($var1) - strlen($var2)) === FALSE;
             case "is_null": return $var1 == '';
+             case "is_not_null": return $var1 <> '';
             case "One_of":
                 if(is_array($var1)){
                     foreach($var1 as $var){
                         if(in_array($var,$var2)) return true;
                     }
                     return false;
                 }
                 else return in_array($var1,$var2);
             case "Not_One_of":
                 if(is_array($var1)){
                     foreach($var1 as $var){
                         if(in_array($var,$var2)) return false;
                     }
                     return true;
                 }
                 else return !in_array($var1,$var2);
             case "Equal_To":
             default: return $var1 == $var2;
         }
     }
...
...
...
 

 
modules/AOW_WorkFlow/controller.php
...
...
...
                $valid_opp = array('Equal_To','Not_Equal_To','Contains', 'Not_Contains', 'Starts_With', 'Not_Starts_With', 'Ends_With', 'Not_Ends_With', 'is_null');
...
...
...

`

**Comment by Dillon-Brown** [comment]
Hi @oc666, new features/enhancements should go into the develop instead of master (Bugfixes go into hotfix). I'd suggest waiting for us to merge #6456 if you don't want to have to remake this PR to the other branch.

**Comment by oc666** [comment]
@Dillon-Brown I've changed the target branch.

**Comment by oc666** [comment]
I've added support for _is not null_ condition.

**Comment by Mac-Rae** [comment]
Please resolve the conflicts on this pull request bringing it up to date.

**Comment by oc666** [comment]
@Mac-Rae I did not find any conflict, but I've sync the branch to be up to date.

**Comment by oc666** [comment]
@Mac-Rae any news about this PR? It includes important features and we've already deploy for a few of our deployments and it's working fine.

**Comment by oc666** [comment]
I've signed the CLA but it's still written I did not signed.

This is the form I've filled:

image

**Comment by mattlorimer** [comment]
It looks like some of the commit are from a different email address, that is not linked or detected with your GitHub account, so it treats it as a second contributor and thus requires all contributors to sign the agreement

hence why it suggest this may fix it:-

>Ofer Cohen seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, [please add the email address used for this commit to your account.](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)

**Comment by oc666** [comment]
I've added the second email to my account. Let me know if it's ok now.

**Comment by mattlorimer** [comment]
thanks  CLA looks good now :+1:

**Comment by oc666** [comment]
Any news about this PR?

**Comment by oc666** [comment]
I'll create new one because this PR is behind.

**Comment by pgorod** [comment]
@oc666 did you create the new PR? I can't find it.

This is being asked about on the Forums:
https://community.suitecrm.com/t/operator-is-null-is-not-available-in-report-module/91408

**Pull request closed without merging**
