### PR TITLE
Fixed #2464 - Logo upload function is not working

### LINKED ISSUE #2464: Logo upload function is not working
#### Issue

The logo upload function is not working. A message with the type of supported images is shown even though a supported image is uploaded.
#### Expected Behavior

The logo image should be uploaded.
#### Actual Behavior

A message indicating supported image types is shown.
#### Possible Fix

The variable '$upload->temp_file_location' includes a path with the extension 'tmp' in the file 'modules/Configurator/UploadFileCheck.php'
#### Steps to Reproduce
1. Login
2. Go to the administration section
3. Click on system settings
4. Attempt to upload a image with a supported extension

image
#### Context

I was trying to change the logo that is shown on the login screen of SuiteCRM.
#### Your Environment

SuiteCRM 7.7.4 using Microsoft SQL Server and PHP 7 on IIS.

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixed an issue when uploading logos that contain whitespace.

## Motivation and Context

Issue reference: #2464 

## How To Test This

1. Admin -> System settings.
2. Upload a logo that has a space in the name.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Doesn't appear to be working :-1:

**Comment by cameronblaikie** [comment]
works for me @Mac-Rae

**Comment by Dillon-Brown** [comment]
@Mac-Rae It looks like this is actually technically not a bug, I hadn't noticed that the help-text informs the user not to use spaces in the filename.

I've gone ahead and fixed it anyway though by just renaming the files on upload to replace whitespace with underscores.

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by horus68** [comment]
I would not change the help text (NEW_LOGO_HELP) to avoid any future non working spaces replacement by software.

**Pull request merged**
