### PR TITLE
Verify if $bean is_subclass_of SugarBean so we can check access

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

Read #7903

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Hi @Abuelodelanada,

Me again :rofl:, Testing on the current version when you delete a record it is removed from the favourites bar before you are able to click it. Could you explain if I'm missing anything?

**Comment by Abuelodelanada** [comment]
Hi @Mac-Rae , so long! 😃

We are trying to get the bean with:

```php
$bean = BeanFactory::getBean($params['module'], $params['record']);
```

The `getBean` method returns a `SugarBean` or a `bool` if no bean could be retrieved.
This PR only verifies that we have a Bean when doing:

```php
$bean->ACLAccess($params['action']);
```
Because doing an `ACLAcess` in a `bool` produces an error.


To test this: 

1. Go to a DetailView of any record so after that it will be in "Recents".
2. Delete that record from the database with a real delete (`DELETE FROM table WHERE...`)
3. Verify that the 'Pencil' it's not shown in 'Recent'

**Comment by Abuelodelanada** [comment]
Hi @Mac-Rae , me again ;-)

Could you read how to test this PR?

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Pull request merged**
