### PR TITLE
Fix #7735: Added try catch on ListView when parsing subpanel query

### LINKED ISSUE #7735: Catch ListView SubPanel query fail
#### Issue

When a subpanel inside a modules DetailView fails its queries it does not show the other subpanels but reverts to showing that a failure was detected. 

> Database failure. Please refer to suitecrm.log for details.

#### Expected Behavior

Only show which subpanel failed its query and render all the other subpanels.

#### Actual Behavior

All subpanels do not render. And displays that an error occurred as a text.

#### Possible Fix

Doing a try catch finally on the SugarBean::get_union_related_list inside ListView.php -> processUnionBeans will fix this issue.

#### Steps to Reproduce

1. Create a custom subpanel or use an existing one
2. Try to do a modification on the subpanel definition so that it fails and throws an exception (for testing)
3. Go to the module that the subpanel exists and go to a record 
4. DetailView will not render the subpanels but instead show an error as a text

#### Context

The main problem i had with this is that when a subpanel failed for some reason the UI failed to render other subpanels and you had to clear the browser cookies and PHPSESSION to restore the subpanels to be then displayed.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 76.0.3809.100 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

### PR DESCRIPTION
**Pull request by zpangrsic**
#### Issue

When a subpanel inside a modules DetailView fails its queries it does not show the other subpanels but reverts to showing that a failure was detected. 

> Database failure. Please refer to suitecrm.log for details.

#### Expected Behavior

Only show which subpanel failed its query and render all the other subpanels.

#### Actual Behavior

All subpanels do not render. And displays that an error occurred as a text.

#### Possible Fix

Doing a try catch finally on the SugarBean::get_union_related_list inside ListView.php -> processUnionBeans will fix this issue.

#### Steps to Reproduce

1. Create a custom subpanel or use an existing one
2. Try to do a modification on the subpanel definition so that it fails and throws an exception (for testing)
3. Go to the module that the subpanel exists and go to a record 
4. DetailView will not render the subpanels but instead show an error as a text

#### Context

The main problem i had with this is that when a subpanel failed for some reason the UI failed to render other subpanels and you had to clear the browser cookies and PHPSESSION to restore the subpanels to be then displayed.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 76.0.3809.100 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

### CODE REVIEW

**Comment by pgorod** [comment]
Hi @zpangrsic! This looks interesting, thanks for contributing.

A couple of small tips about the process:

- please rename your PR to `Fix #7735: Added try catch on ListView when parsing subpanel query`. This will make Github properly link the Issue with its PR and has several advantages.

- please edit your PR to direct it to the `hotfix-7.10.x` branch instead of `master`. This will eventually find its way into `master`, but right now that's how our workflow is intended to work (see https://docs.suitecrm.com/community/contributing-code/bugs/).

**Comment by zpangrsic** [comment]
Hi @pgorod,

Thanks for the tips.

I am having a small issue to direct it to the hotfix-7.10.x branch (am a novice at git). What would you recommend doing since my branch is from the master (rebase to hotfix-7.10.x maybe ?). 

Thank you for your help.

**Comment by pgorod** [comment]
@zpangrsic yes, a rebase is what you need.

Since you are a novice with git and this change only affects one file, you might find it easier to just start a new PR from the correct branch. You could do this from the Github site, without the `git` command-line.

Start by going to the correct branch: 

image

Then navigate the directories into the file you want to change, click the pencil icon to edit it, and make your changes. Github will automatically create a new branch on your forked repo, based on this branch, and then offer to create the PR for you.

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by samus-aran** [comment]
Hey @zpangrsic  :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Comment by communig8-public** [comment]
Just came across this issue using 7.11.10 and the try/catch isn't in ListView.php yet. When will (or has) it been merged into a Production release? Thanks Richard.

**Comment by tsmgeek** [comment]
> Just came across this issue using 7.11.10 and the try/catch isn't in ListView.php yet. When will (or has) it been merged into a Production release? Thanks Richard.

You are on an old version of 7.11.x, this change was merged in for 7.11.11

**Comment by communig8-public** [comment]
> > Just came across this issue using 7.11.10 and the try/catch isn't in ListView.php yet. When will (or has) it been merged into a Production release? Thanks Richard.
> 
> You are on an old version of 7.11.x, this change was merged in for 7.11.11

Thanks for the info.

**Pull request merged**
