### PR TITLE
Fix iCal car encoding

### PR DESCRIPTION
**Pull request by chandon**
Fix iCal problem with Cyrilic charset

### CODE REVIEW

**Comment by horus68** [comment]
@chandon can you please submit this PR to the proper branch (Hotfix)?

**Comment by glaz123** [comment]
That change breaks cyrillic character in iCAL in 7.10.7. utf8_decode converts any UTF8 character to ISO8859-1, and therefore any non ISO8859-1 characters will be shown as question marks.

**Comment by bukbr** [comment]
Hi! I did exactly as directed, however, the .ics file continues to be generated without the accentuation of the Portuguese language. Could anyone help? What should I do to get the characters accented? Version 7.10.7

**Comment by glaz123** [comment]
What solve the problem with cyrillic for me, is change the string in this commit from:
        return htmlspecialchars_decode(preg_replace("/&#([0-9]+)\\\\;/", '&#$1;', utf8_decode($str)));
to 
        return htmlspecialchars_decode(preg_replace("/&#([0-9]+)\\\\;/", '&#$1;', $str));

**Comment by bukbr** [comment]
> What solve the problem with cyrillic for me, is change the string in this commit from:
> return htmlspecialchars_decode(preg_replace("/&#([0-9]+)\\;/", '&#$1;', utf8_decode($str)));
> to
> return htmlspecialchars_decode(preg_replace("/&#([0-9]+)\\;/", '&#$1;', $str));

Thanks very much, it worked! :-)

**Comment by timo12357** [comment]
Works for me, too. When can this be included in a release, @Dillon-Brown ?

**Comment by Dillon-Brown** [comment]
Hi @timo12357, thanks for highlighting this. I'll make a PR with this change and if it works as expected then it should go into the next release.

**Comment by Dillon-Brown** [comment]
Fix here: #7691

**Pull request merged**
