### PR TITLE
Fix #4646 - Hard coded messages in Surveys module

### LINKED ISSUE #4646: [language] Hard coded messages in Surveys module
Some messages in these files are hard coded:

Question, Text, Type, New Question
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/tpls/detailsurveyquestions.tpl#L4-L13
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/tpls/editsurveyquestions.tpl#L4-L17

Add option
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/tpls/editsurveyquestions.tpl#L143

Responses, Surveys Sent, Distinct Surveys Sent
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/tpls/reports.tpl#L3-L14

Draft
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L51

Submit
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L124

Satisfied
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L132

Neither Satisfied nor Dissatisfied
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L140

Dissatisfied
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L148

Stars
https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/views/view.reports.php#L187-L196

Module, Body, Border, Text
https://github.com/salesagility/SuiteCRM/blob/master/themes/SuiteP/modules/Calendar/tpls/settings.tpl#L194

Some labels without value:
LBL_SURVEYQUESTIONS_SURVEYQUESTIONOPTIONS_FROM_SURVEYQUESTIONS_TITLE

### PR DESCRIPTION
**Pull request by jack7anderson7**
Fix #4646

## Description

Update Survey module to contain labels instead of hard coded values

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by likhobory** [comment]
@jack7anderson7 

Please add translation for Show/Hide responses:

https://github.com/salesagility/SuiteCRM/blob/7.11.x/modules/Surveys/javascript/Survey.js#L9

**Comment by likhobory** [comment]
@jack7anderson7 

Thanks, also add please translation for those strings:

Question
https://github.com/salesagility/SuiteCRM/blob/7.11.x/modules/SurveyResponses/tpls/detailquestionresponses.tpl#L6

Response
https://github.com/salesagility/SuiteCRM/blob/7.11.x/modules/SurveyResponses/tpls/detailquestionresponses.tpl#L9

Question type
https://github.com/salesagility/SuiteCRM/blob/7.11.x/modules/Surveys/tpls/detailsurveyquestions.tpl#L24

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Review by johnM2401 — APPROVED** [review]
LGTM, all labels changed in survey module are translatable when lang pack is used.

**Comment by SinergiaCRM** [comment]
@jack7anderson7, @clemente-raposo, @johnM2401, @likhobory and @Dillon-Brown

We have detected that this change is generating an error as the CRM treats the LBL_DRAFT value as a text string and not as a label:

https://github.com/salesagility/SuiteCRM/blob/v7.10-beta-2/modules/Surveys/vardefs.php#L51

It seems to work since when the LBL_DRATF value is not found in the list associated with the field, the first result of the list is returned, which in this case is Draft.

We think you should revert the change and leave the value 'Draft'. Also, we think the LBL_DRAFT tag can be removed from the language file, as it is not used elsewhere.

**Pull request merged**
