### PR TITLE
Fixed #5424 - Missing add product menu while using PL language - 7.10.1

### LINKED ISSUE #5424: Missing add product menu while using PL language - 7.10.1
#### Issue
While using PL language i cannot see product menu, but if i change language to eng while login menu is right on place.

PL
image

ENG
image

#### Your Environment
SuiteCRM Version used: 7.10.1
Browser name and version (e.g. Chrome 64.0.3282.186
Environment name and version (e.g. MySQL, PHP 7):
Operating System and version CentOS

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

While using a language pack certain modules like products do not show the sidebar menu.

## Motivation and Context

Issue reference: #5424 

## How To Test This

1. Install a language pack such as PL.
2. Go into "Products" module.
3. Check that the sidebar displays correctly.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by zoltankocsardi** [comment]
code +1

**Comment by AdminPL** [comment]
Seem to be working fine on 7.10.1. All modules have menu

**Comment by horus68** [comment]
I can also confirmed this is working now with 7.10.1 (php 7)
Please consider that the file as some code format to be solved (as regressions) but maybe only because this is against the 7.8.x branch

**Comment by daniel-samson** [comment]
Assessed

**Comment by MichalNowacki** [comment]
I am not sure that the solution is correctly.
In my opinion you should change 664 line, not remove it.
Working example:
`if ( count($topTabs) >= $max_tabs - 1 && $key !== $app_strings['LBL_TABGROUP_ALL'] && in_array($tabGroup['modules'][$moduleTab], $tabGroup['extra']) ) { //fix`

**Comment by Dillon-Brown** [comment]
@MichalNowacki This was just a simple revert as a quickfix. Still, can't believe I actually missed that :laughing: . I'll give it a test and put up a PR but it looks like you are completely correct. Thanks!

**Comment by MichalNowacki** [comment]
I'm happy that my opinion is valuable :)

**Pull request merged**
