### PR TITLE
Fixed #1840 - Meetings in scheduler shifted by one hour

### LINKED ISSUE #1840: Meetings in scheduler shifted by one hour
#### Issue

Scheduler in Meeting/calls module show occupation blue boxes shifted by one hour from the start date and time As on the attachments
#### Expected Behavior

Occupation boxes (accepted) should be posistioned in the time in wich the meeting/call actually are planned
#### Actual Behavior

Occupation boxes are shifted by an hour, as seen in the attachments
#### Steps to Reproduce

In demo version of suite (edit of an existing meeting)
http://demo.suiteondemand.com/index.php?module=Meetings&offset=2&stamp=1470126825007969600&return_module=Meetings&action=EditView&record=127e4c60-5148-e7fa-9b3b-578e93d6e20a
1. Create new meeting
2. Save and edit again
3. See results on scheduler section
#### Context

For my company it is important to see the correct availability timeslot of the employees in order to schedule a meeting in the right time.
#### Your Environment
- SuiteCRM Version used: Bug only on version >7.6 (it is ok on 7.5.2)
- Browser name and version: affect every browser
- Environment name and version (e.g. MySQL, PHP 7): mysql 5.5, php 5.3
- Operating System and version: tested in both Windows 10 and ubuntu server 12.4

suitecrm_meeting_scheduling_demo

suitecrm_meeting_scheduling

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixes the meetings scheduler displaying the wrong time.

## Motivation and Context

The meeting scheduler was displaying created meetings shifted along to the right by 1 hour regardless of the users set timezone.

Issue reference: #1840

## How To Test This

1.  Rebuild Minified JS Files
2. Clear cache + hard reload
3. Create a meeting.
4. Open the meeting and check the scheduler is at the right time.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by oceanmedianow** [comment]
Just confirming that this fix works on my live instant Version 7.9.4
Sugar Version 6.5.24 (Build 509) with no issues.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by TB-effective** [comment]
Can confirm that this still fixes the (persisting) issue in our 7.11.18 install.

Will this fix at some point also make it into the normal release?

**Pull request merged**
