### PR TITLE
Fixed #8361 - Contact Without Primary E-mail Address

### LINKED ISSUE #8361: You are able to save a Contact without a primary e-mail address
#### Issue
I can save a Contact without a primary e-mail address.

#### Expected Behavior
1. When adding an extra email address, the currently selected radio button has to stay selected
2. When you try to save a Contact without a primary e-mail address you should get the message; no primary e-mail address, set a primary e-mail.

#### Actual Behavior
You are able to save a Contact without a primary e-mail address.

#### Possible Fix
I do not know.

#### Steps to Reproduce
1. Create a new Contact (or Lead / target)
2. Click on the Plus (+) to add a second e-mail addresses
3. Note that the radio button is empty for both addresses
4. Do not check the checkbox primary e-mail address
5. Save the Contact

#### Context
Busy with adding new Contacts

#### Used system
SuiteCRM Version used: 7.10.22
Browser name and version: Version 78.0.3904.97 (Official Build) (64-bit)
Environment name and version: MariaDB 10.2, PHP 7.2
Operating System and version: Windows 10

### PR DESCRIPTION
**Pull request by TechEsperto**
## **Description**

step(i):  go to contacts module and click on create contact,
step(ii): click on **Add Email Address**
step(iii): As soon as we have more than one email fields, 
step(iv): Here by default the primary email is uncheck,
  

## **Motivation and Context**
By default it keeps first email as the primary email of the contact, which saves the record of the contact with full details.

## How To Test This
step(i): Once the changes are applied in the appropriate file, go to contacts module and click on create contact,
step(ii): click on **Add Email Address**
step(iii): Now as soon as we have more than one email address input filed, now by default the first one is selected as the primary address.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 268
- Added 396
           

Complexity increasing per file
==============================
- tests/unit/phpunit/include/GoogleSync/GoogleSyncMock.php  3
- tests/unit/phpunit/lib/SuiteCRM/Search/AbstractDocumentifierTest.php  1
- lib/Log/SugarLoggerHandler.php  8
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchInstallTest.php  5
- tests/unit/phpunit/modules/Users/GoogleApiKeySaverEntryPointTest.php  2
- tests/unit/phpunit/modules/Users/GoogleApiKeySaverEntryPointMock.php  1
- tests/unit/phpunit/lib/Search/UI/SearchResultsControllerTest.php  3
- modules/Administration/Search/View.php  1
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchEngineTest.php  1
- modules/Administration/Search/ElasticSearch/scripts.js  2
- lib/Search/SearchWrapper.php  7
- include/GoogleSync/GoogleSync.php  7
- modules/Home/Search.php  1
- tests/unit/phpunit/lib/SuiteCRM/Search/SearchTestAbstract.php  1
- lib/Search/Index/Documentify/JsonSerializerDocumentifier.php  1
- lib/Utility/ArrayMapper.php  7
- modules/Administration/Search/Controller.php  2
- lib/Search/ElasticSearch/ElasticSearchEngine.php  2
- tests/unit/phpunit/lib/SuiteCRM/Search/TestCustomEngines/MockSearch.php  1
- lib/Log/CliLoggerHandler.php  1
- modules/Users/GoogleApiKeySaverEntryPoint.php  5
- include/Smarty/plugins/function.search_controller.php  1
- lib/Search/Index/Documentify/SearchDefsDocumentifier.php  9
- lib/Search/UI/MVC/Controller.php  2
- modules/Administration/Search/ajaxSubmit.js  2
- lib/Search/SqlSearch/SimpleSqlSearchEngine.php  4
- modules/Administration/Search/scripts.js  1
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchIntegrationTest.php  2
- lib/Search/UI/SearchResultsView.php  1
- lib/Search/ElasticSearch/ElasticSearchClientBuilder.php  7
- tests/unit/phpunit/modules/Administration/BaseHandlerTest.php  1
- lib/Search/SearchConfigurator.php  5
         

Complexity decreasing per file
==============================
+ include/SugarEmailAddress/SugarEmailAddress.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4898719&bid=16221343)

**Comment by TechEsperto** [comment]
Hi @samus-aran,  **Codacy/PR Quality Review** showing issues for the files which I haven't touched or modified during this fix. It will be really helpful if you suggest a way-out.
Thank you.
Screenshot from 2020-01-29 12-14-15

**Comment by Mac-Rae** [comment]
Hi @TechEsperto,

Please **rebase** this pull request onto hotfix-7.10.x as it appears to have been made on master and then aimed at hotfix-7.10.x

If you would like assistance, please ensure you select "Allow edits from maintainers" checkbox and leave us a message @tagging me! 

Thanks :+1:

**Comment by samus-aran** [comment]
Closing this, as #8510 superseeds this.

**Pull request closed without merging**
