### PR TITLE
allowed_preview is defined twice in the array

### PR DESCRIPTION
**Pull request by QuickCRM**
allowed_preview is defined twice in the array

## Description

removed one of the entries

## Motivation and Context

There is no problem with that, but the second entry is useless
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hi @QuickCRM ,
thanks for your contribution,

Could you please update your commit message to follow the formatting Fix #num - message. The number added in this case would be the number of the PR (9849).

You can see more information on raising bugs/ PR's here: 
https://docs.suitecrm.com/community/contributing-code/bugs/

Thanks in advance, 
Serhii

**Comment by QuickCRM** [comment]
There is no bug.
It's just not nice php.

**Review by jack7anderson7 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Review by johnM2401 — APPROVED** [review]
LGTM

**Pull request merged**
