### PR TITLE
Fix icons not rendering properly in Alerts.

### LINKED ISSUE #6264: The image is broken --> See screenshot
#### Context
This is a bug core on SuiteCRM version 10.4, It related to module Alerts, Please check again.

#### Your Environment

* SuiteCRM Version used: 10.4
 This is a image bug of core --> See screenshot
screenshot_1
- The image is broken --> See screenshot
screenshot_2

* Browser Chrome
* Environment name and version (e.g. MySQL, PHP 7.1):

### PR DESCRIPTION
**Pull request by connorshea**
## Description
Previously, any modules that were plural (most of them) were getting an `s` appended to their names in order to load the image for that module, leading to the CRM trying to load images like `Leadss.gif`, which does not exist. This only applies the `s` when the module name isn't already plural (this is done by just checking if the module name ends with an `s`, which isn't perfect but better than before). This also changes the icons from `.gif` files to html tags that render the icon font, since most other static image icons have been replaced already by #5273 and #5457.

Fixes #6264 (which should not be closed)

Before:

image

Now it looks like this:

Screen Shot 2019-07-30 at 10 54 14 AM

## Motivation and Context
Icons weren't loading.

~~Ideally, this would be fixed by replacing the gif with a `span` using the new icon font, as I mentioned in my comment on #6264, but I'd prefer to just fix this quickly for now and do that at a later time.~~ This now replaces the gif icons with the `span` tag icon font icons. :) 

## How To Test This
1. Log in as someone with notifications, or generate notifications for your own user account somehow.
2. Open the notifications dropdown.
3. See that the icon next to the notification text is visible and loads. Leads and Calls are both good example notifications.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
It seems like this may not work with Calls :/ I need to figure out how to get a bunch of different notification types for my account to test this change.

**Comment by connorshea** [comment]
Err, I think `imageName=Calls.gif` causes it to load an SVG, which isn't valid as the source of an img tag? I guess the CRM is just trying to load whatever it can find regardless of file extension. 😕

**Comment by gunnicom** [comment]
https://github.com/salesagility/SuiteCRM/pull/7245

**Comment by connorshea** [comment]
@gunnicom sorry, I didn't see that PR when searching around about this issue 🙇 

I've now fixed my PR for more cases by replacing the `.gif` with the icon font that was introduced in 7.10 and adding an `s` if there isn't already one at the end of the module name (this isn't ideal, but it does fix the issue for all cases I've been able to create).

**Comment by connorshea** [comment]
This should be ready for review now 👍

**Pull request merged**
