### PR TITLE
Fix:  EmailTemplates changes (issue #2266) enables old-style WYSIWYG editor for Email templates

### PR DESCRIPTION
**Pull request by gody01**
EmailTemplates changes  (issue #22669)

Allow selection of old style Edit or new mozaik based RWD edit of Email template.

## Description
New mozaik based Email Template editor breaks formatting of existing templates and does not allow inserting html code made in external template editor.

Added few changes to enable old style WYSIWYG editing, but to also select new "RWD" editing if so desired.

## Motivation and Context
After upgrade users couldn't do their jobs in usual way and old work (duplicate) was practicaly unusable. We had to come to some quick solution and hack something tu patch up.

## How To Test This
Select EmailTemplate
In detail view there is now Edit and RWD Edit button.
Edit button and Duplicate buttons open old-style template editor.
RWD edit button opens new mozaik based editor.

## Types of changes
 Changes to be committed:
	modified:   DetailView.html
	modified:   DetailView.php
	modified:   EditView.html
	modified:   EditView.php
	modified:   EditViewMain.html
	modified:   EmailTemplate.js

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [ ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@gody01 can you please edit this PR title?

**Comment by gody01** [comment]
What is should be ?
And hint how to do it would be nice, I'm neww to github ...

**Comment by horus68** [comment]
Just a more descriptive title on the issue you are solving

**Comment by pgorod** [comment]
Issue number should be #2266, you have an extra `9` in there...

**Comment by gody01** [comment]
We found some additional problems with solution (don't work in MArketingWizard, ...).
My programers are looking into this now, to find proper solution.

**Pull request closed without merging**
