### PR TITLE
Hotfix 7.8.x # Improvement in parameters for dashlet reports

### PR DESCRIPTION
**Pull request by LionelBino**
## Description
In some situations `getConditionsAsParameters()` in file `modules/AOR_Reports/aor_utils.php` line 161, return a array `$conditions=>field`  that contain a input tag like this:

```html
<input type="text" name="parameter_value[5]" id="parameter_value[5]" size="30" maxlength="255" value="3" title="" tabindex="1">
```
For this reason, the input form values are like this:

```html
<div id="">
    <input type="hidden" name="parameter_id[]" value="7d0d3274-b3f7-6467-6a0b-57e2ae3f07c5">
    <input type="hidden" name="parameter_operator[]" value="Equal_To">
    <input type="hidden" name="parameter_type[]" value="Value">
    Account - <em>ID Seller</em> - Like to 
    <input type="text" name="parameter_value[5]" id="parameter_value[5]" size="30" maxlength="255" value="3" title="" tabindex="1">
</div>
```
For this reason the value in input can't be catched and the report cannot obtain this parameter

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by gunnicom** [comment]
Maybe this is related to https://github.com/salesagility/SuiteCRM/pull/1710 ?

**Comment by LionelBino** [comment]
Yes it's related exact to this, but that it's a better fix that #1710

**Comment by gunnicom** [comment]
Maybe you can have a look how i fixed it, and see if that would work for you, as mine was less change, and does look cleaner to me.

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
