### PR TITLE
Fixed #2240 - Detail View for User profile

### LINKED ISSUE #2240: SuiteP - Tabs on User detailview have old design
#### Issue

The Tabs on user profile detailview have not changed.

tabs
#### Steps to Reproduce

1. Home page
2. Go to User Name
3. Choose Profile menu title
#### Your Environment

- SuiteCRM Version used: 7.7.4
- Browser name and version 53.x m 32 bit
- Environment name and version (e.g. MySQL, PHP 7): 5.6 PHP MySQL
- Operating System and version: Hosting - Linux

### PR DESCRIPTION
**Pull request by daniel-samson**
## Description

In relation to issue #2240, this change modifies the user profile detail view so that it is in keeping with SuiteP while being in keeping with the older themes.
- added the advanced and access tab back into suite. 
- added the reset user profile features back into suite.
- added a generic modal dialog to suite (bootstrap).
- refactored the detailview
- refactored related javascript.
- moves the all the view code into detailview.tpl
- changed detail view defs
- moved roles subpanel to the subpanels instead of in the access tab.
- made employee info panel collapsed 

user-profile-detail-view

It also fixes issue #2540.

## Motivation and Context

Adds missing features back into suite.
## How To Test This

Access the users detail view.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
I am working on the edit view.

**Comment by daniel-samson** [comment]
I need [Gyulas](https://github.com/salesagility/SuiteCRM/pull/2469) change to be merged before I can finish the SuiteP edit view for the uses profile. This is so I can accommodate his changes into mine.

**Comment by edilex** [comment]
Still an issue when ACtion menu item to the complete left
capture d ecran 2016-11-03 a 09 39 55

**Comment by daniel-samson** [comment]
Hi @edilex. Thanks for testing it :+1:. I have updated my pull request so that the menu now correctly displays when there is only one tab.

only-child fix

**Comment by daniel-samson** [comment]
Closing. See #2958.

**Pull request closed without merging**
