### PR TITLE
fix a php Strict Standards

### PR DESCRIPTION
**Pull request by gymad**
## Description

fix a php Strict Standards log message
ref: https://github.com/salesagility/SuiteCRM/issues/942#issuecomment-315302108

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
@Dillon-Brown Can you please assess?

**Comment by pgorod** [comment]
@Dillon-Brown I just saw a case of this problem in the forums today.

Why is this labelled `Wrong branch`?

**Comment by Dillon-Brown** [comment]
@pgorod Issue is also present in 7.8.x so the correct branch would be hotfix-7.8.x.

**Comment by horus68** [comment]
> Issue is also present in 7.8.x so the correct branch would be hotfix-7.8.x.

This is a strange use of branches and the workflow must be clear stated or revised. 
Example: I don't test things in 7.8 versions so I will not create a PR for older versions. I think users of 7.9 version are also not looking into solutions proposed to 7.8 versions 
A project must have a clear Hotfix branch for the latest version and solutions. If an issue is also present in any other version, then the project devs should also replicate that solution for other versions.

**Comment by Dillon-Brown** [comment]
@horus68 I agree that we should make it clearer what the appropriate branch is when submitting PR's. As it currently stands all features/enhancements should be made to the "develop" branch while all other PR's should be made to the "hotfix-7.8.x" branch unless they are 7.9.x specific. This allows us to merge PR's first into hotfix-7.8.x and then into hotfix.

**Comment by Dillon-Brown** [comment]
Original issue has been fixed / merged.

**Pull request closed without merging**
