### PR TITLE
FIXED #3560 - Now we log queries in one, and only one, log line

### LINKED ISSUE #3560: Queries logged in multiple lines.
#### Issue

SuiteCRM records one system action in more than one log line.
	

#### Expected Behavior
Each log line should represent one (and only one) system action.
A log line with a query should be recorded this way:

     Tue May 16 09:58:11 2017 [30922][1][INFO] Query: SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0     AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0     AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND jt2.deleted=0     AND jt2.deleted=0 where (alerts.assigned_user_id = '1' AND is_read != '1') AND alerts.deleted=0

#### Actual Behavior
The previous log line is recorded in more than one line:

     Tue May 16 09:58:11 2017 [30922][1][INFO] Query: SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0

     AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0

     AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND jt2.deleted=0

     AND jt2.deleted=0 where (alerts.assigned_user_id = '1' AND is_read != '1') AND alerts.deleted=0

#### Possible Fix
Remove the breaks lines from the queries before they are executed and registered in the log

#### Steps to Reproduce
Just run SuiteCRM and watch the log ;-)

#### Context

When you are debuging it is **VERY annoying** that the queries (and other system actions) are recorded in the log in several lines.
That's not a style thing it's a productive one... with queries in several lines using unix tools (cat, grep, awk, sort, wc, etc, etc) is a headache

#### Your Environment

* SuiteCRM Version used: Any
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Any
* Environment name and version (e.g. MySQL, PHP 7): Any
* Operating System and version (e.g Ubuntu 16.04): Any

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

This pull request fixes #3560
Now each log line represents one (and only one) system action.
Now a log line with a query is recorded this way:

     Tue May 16 09:58:11 2017 [30922][1][INFO] Query: SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0     AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0     AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND jt2.deleted=0     AND jt2.deleted=0 where (alerts.assigned_user_id = '1' AND is_read != '1') AND alerts.deleted=0

## Motivation and Context

When you are debuging it is **VERY annoying** that the queries (and other system actions) are recorded in the log in several lines.
That's not a style thing it's a productive one... with queries in several lines using unix tools (cat, grep, awk, sort, wc, etc, etc) is a headache

## How To Test This
Run SuiteCRM and watch the log.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
-  [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
My only concern here is that it is affecting the query itself - perhaps we need to go prior to this point to actually remove \r and \n in the first place rather than a general sweep.  Would there be any use cases where the query would need \r or \n in the query itself?  Reports and Module searching all ok? :)

**Comment by Abuelodelanada** [comment]
@samus-aran As far as I know \r and \n characters are ignored in SQL.
We have this patch in production for 2 years and all works fine. 
Module searching works ok, and reports (ZuckerReports) works ok too.
This little patch makes our life better in debugging times ;-)

**Comment by gunnicom** [comment]
Maybe if \r or \n are escaped in a query like:
`INSERT INTO table (testme) VALUES ('her comes a line\r\nbreak')`

**Comment by Abuelodelanada** [comment]
We could execute this line:

$sql = trim(str_replace(array("\r", "\n"), " ", $sql));

After executing the query:

$result = $suppress?@mysqli_query($this->database,$sql):mysqli_query($this->database,$sql);

And before loggin

$GLOBALS['log']->info('Query Execution Time:'.$this->query_time);

**Comment by pgorod** [comment]
@Abuelodelanada go for it, you can add a commit to this PR with that improved version. I agree with @samus-aran it's better (much less risky), it would make this an easy PR to test and merge if it only affects logging, and nothing else.

**Comment by chris001** [comment]
Best refactor it.  Make a function in the base class `DBManager` 
`function removeLineBreaks($sql) { 
   return trim(str_replace(array("\r", "\n"), " ", $sql)); }` 
And call it from all 5 DB types:
`$GLOBALS['log']->info ('Query: ' . removeLineBreaks($sql));`.

**Comment by Abuelodelanada** [comment]
@chris001 @pgorod @samus-aran @gunnicom This PR is closed. 
Please follow PR #3601 It's an improved one.

**Pull request closed without merging**
