### PR TITLE
Respect the subpanel `flat` flag

### PR DESCRIPTION
**Pull request by JimMackin**
## Description

The `flat` flag on subpanels detailed here: https://docs.suitecrm.com/admin/advanced-configuration-options/#_sub_panels_replacing_the_drop_down_menu_with_buttons doesn't seem to work. The option seems to not be passed through. This fix makes sure the flat flag is passed to the action menu.

## Motivation and Context

Allows selectively collapsing the action menu for subpanels.
## How To Test This

- Add a flat flag as in the link above
- Do a QR&R, check the appropriate subpanel - in the old version there will be no change. In the new version it will be a flat menu.

Note: The compose button is duplicated when this option is selected but this is unrelated to this ticket - turning on the flat action menus in the settings also exposes this. A separate PR should be made to fix this. I will do this if I get a chance.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Related discussions: 
#6927
#6533 (includes interesting suggestion to extend this to the row-level action buttons on the right (Edit, Remove, etc) and a discussion about making this setting more granular.

**Review by jack7anderson7 — APPROVED** [review]

**Comment by pgorod** [comment]
About @JimMackin 's note on the double Compose button: there is a PR here #9559

**Comment by clemente-raposo** [comment]
@jack7anderson7 commit needs issue number

**Review by jack7anderson7 — DISMISSED** [review]

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Review by jack7anderson7 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]

**Pull request merged**
