### PR TITLE
fix-conversions

### PR DESCRIPTION
**Pull request by jgramp**
## Description
Automatically convert custom fields to non-custom fields during the lead conversion process, if the names match, except the custom fields will have '_c' on the end.

1. Create a new custom field called website (website_c) for Leads.
2. Add to the Leads Edit Layout.
3. When converting a Lead with a website, the website does not copy across, because it does not exactly match, because the custom website field has a '_c' appended to the name.

No issue raised, but the issue is described on the community forums here: https://community.suitecrm.com/t/mapping-a-target-website-c-field-to-the-lead-website-field-when-converting-a-target-to-a-lead/70179

## Motivation and Context
The change allows for Lead custom fields to be converted into core fields, if a core field of the same name does not already exist.

## How To Test This
1. Create a new custom field called website (website_c) for Leads.
2. Add to the Leads Edit Layout.
3. When converting a Lead with a website, the website now copies across, because it will match,  with the custom website field that has a '_c' appended to the name.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jgramp** [comment]
This two commits named Update controller.php, fixed indentation issues in the code.

**Comment by samus-aran** [comment]
Thanks for your contribution @jgramp We'll have a chance to look over it and check back.

**Comment by serhiisamko091184** [comment]
Hello @jgramp 

thanks for your contribution one more time,

would you be so kind to sign the CLA for further assessment:

image

Many thanks in advance.

Regards,
Serhii

**Comment by serhiisamko091184** [comment]
Hello @jgramp 

one more time thank you for the PR and your time,
we’d like to continue working on this contribution and hope you can reopen it and update it when it’s appropriate for you.    

Thank you very much!

**Pull request closed without merging**
