### PR TITLE
Fix #9261 - Use decimal symbol configured in system and user

### LINKED ISSUE #9261: User-configured decimal symbol separator is not used in Templates
#### Issue
The user-configured decimal symbol separator is not used by the Email template parser and the PDF template parser.

#### Expected Behavior
The CRM uses the decimal symbol separator configured in the user

#### Actual Behavior
CRM does not use user-configured decimal symbol separator

#### Possible Fix
Add the necessary code for fields of type Decimal in:
- the function **parse_template_bean()** of the file _modules / AOS_PDF_Templates / templateParser.php_
- the function getValueFromBean() of the file modules/EmailTemplates/EmailTemplateParser.php (Line 199)

#### Steps to Reproduce
1. Set a symbol to separate decimals.
2. Create a person-based email template that contains a decimal field.
3. Create a campaign and use the decimal field.
4. Send a test email and / or a Scheduled email
5. Check that in the sent email, the decimal value is not being parsed with the configured symbol

6. Create a PDF template based on People and include the decimal field
7. Generate a PDF file of a person that has a value in the decimal field
check that the decimal symbol is not applied in the generated PDF template

#### Your Environment

*  SuiteCRM Version used: Version 7.11.19 - Sugar Version 6.5.25 (Build 344)
*  Browser name and version: Chrome Versión 92.0.4515.131 (Build oficial) (64 bits)
*  Environment name and version: MySQL, PHP 7
*  Operating System and version: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by SinergiaCRM**
## Description

This PR fixes the decimal separator symbol for a decimal or float value obtained from a database not being parsed correctly when incorporated into an email template or PDF template.

To do this, a generic function is created in the PR with a parameter where you can indicate which configuration to use: the system configuration (configured by default) or the user configuration. This function will be used in the operation of parsing the PDF template or the email template.

Our proposal is to use the system configuration for sending emails and the user configuration for using the PDF template.

## Motivation and Context
- #9261
- We have found that this also happens when sending an email from a workflow. Here is a video with the three use cases of incorrect behavior.

DecimalSymbolParser

## How To Test This
1. Create a decimal and a float fields in a contact module
2. Set a symbol to separate decimals in user profile and system configuration.
3. Create a contact-based email template that contains the decimal and float fields.
4. Create a campaign and use the previous template.
5. Send a email and check that in the sent email, the decimal and float values is being parsed with the configured system decimal symbol

6. Create a workflow based on Contacts and edit a Contact that has a value in the decimal and float fields for the workflow to send the email with the previous template
7. Check that in the sent email, the decimal and float value is being parsed with the configured system decimal symbol

8. Create a PDF template based on Contact and include the decimal and float fields
9. Generate a PDF file of a contact that has a value in the decimal field and
check that the decimal symbol is applied in the generated PDF template

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by SinergiaCRM** [comment]
Hello @serhiisamko091184, comments deleted :+1: 

Regards!!

**Comment by serhiisamko091184** [comment]
@SinergiaCRM, many thanks for the quick reply and the changes made! 

Regards,
Serhii

**Comment by SinergiaCRM** [comment]
Hi, we have detected that it also occurs with float type fields so we have added the appropriate changes in the PR

**Review by jack7anderson7 — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
LGTM, 
Now using System-set values on Emails and User-set values on PDFs.

I have noticed that this issue is also present for currency-type fields, 
see this email:
image

For the above, I have set: 
System Thousand: "X" + System Decimal: "Z"
User Thousand: "." + User Decimal: ","

And the custom Currency->Amount Field is using the user's settings.

However, as this PR resolves the issue for both Decimal and Float, I'm happy to merge as-is.

Thank you again!

**Pull request merged**
