### PR TITLE
Fix #3048 - Append and display messages by type

### LINKED ISSUE #3048: Implement a function to send messages to the user
#### Expected Behavior
Sometimes is usefull to send messages to the user when something happens.
Drupal has a function called drupal_set_message() for this:

https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_set_message/7.x

We have implemented this functionality in a SugarCRM CE instance, and use it to warn the user, or to show the user an error happend, or just to send information.

Here are an example showing the 5 types of messages we have implemented
suite_set_message

This feature is manly used in controller.php and views. Here are a real life example:

sugar_set_message_function

### PR DESCRIPTION
**Pull request by marin-h**
Feature of setting and displaying different types of color-coded messages for the user. 

suitecrm_msgs

## Description

We had implemented this feature in SugarCRM 6.5 a while ago and now adapted the code for the current version of SuiteCRM.
Basically it allows to set messages by using static method SugarApplication::appendMessage, which is meant to be called from controller.php or any other place in the application. We also added the messages rendering to the header in SugarView.php and in the Smarty templates for each theme available, also setting up the code for the different CSS implementations currently used, in order to show color-coded errors with different styling classes.
As a second approach we also found useful to have a JS implementation for this functionality, so we have added that in sugar_3.js, using the functions displayMessage for the header area and displayMessagesAfterSelector for any other area you wish to show the messages on.
Also, this feature offers the possibility for implementing any new type of color-coded message you need. Now to accomplish that you only have to ensure that the corresponding CSS classes for your custom type exist and are available. For example:

```css
.myCustomType {
background-color: #700614;
color: #CCCCCC;
}
```

https://github.com/salesagility/SuiteCRM/issues/3048

## Motivation and Context

Please refer to issue: https://github.com/salesagility/SuiteCRM/issues/3048

## How To Test This
You need to clean application cache. Also remember to repair compiled CSS stylesheets and minifyied JS cache files. Then run SugarApplicationTest.php with PHPUnit and/or call displayMessage function from JS console into to the browser. The type parameter currently has the following allowed values: info, error, alert, okay, working. When you use these remember to quote them as their expected data-type is string.  See some examples below.

In javascript:
```javascript
// Insert this directly into the browser console
displayMessage('working', 'working class hero');
```
In PHP:
```php
// Put this in controller.php or any other PHP file in the view
SugarApplication::appendMessage('some info', 'info');
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Can the alerts words (alert, info, working) be translated?

**Comment by marin-h** [comment]
@horus68 the methods for appending and displaying messages accept two parameters:
- The **type** (which is named after the corresponding CSS class, for that the values currently available are: info, error, alert, okay, working, you can add your own customized classes if you want to display other types of messages)
- The **message's text** itself, meaning the literal string you want to display as text into the message's div. For this parameter you can use Suite's translate method, in case you have set different languages in your implementation.

In the screenshot above, I put random text in the messages just for showing the different classes of color-coded messages available.

**Comment by samus-aran** [comment]
[Implement a function to send messages to the user](https://trello.com/c/Rcjss5a6/33-implement-a-function-to-send-messages-to-the-user)

**Comment by samus-aran** [comment]
[Implement a function to send messages to the user](https://trello.com/c/Rcjss5a6/33-implement-a-function-to-send-messages-to-the-user)

**Comment by Abuelodelanada** [comment]
Hello @Dillon-Brown this is a simple feature we send on Feb that let's developers to send messages to the user if something happends. It is very userful!
We also have a issue in Trello: https://trello.com/c/Rcjss5a6/33-implement-a-function-to-send-messages-to-the-user

Can you give it a look?

**Comment by Dillon-Brown** [comment]
Hi @Abuelodelanada, I'll take a look. Although new features tend to involve a lengthier process / discussion than simple bug fixes to get merged.

**Comment by samus-aran** [comment]
Hey @Abuelodelanada & @marin-h.
Circulating within the team just now. Preferably it would still be to the develop branch so it would be from 7.11+
Just a quick note, could we consider to add anything [for accessible](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role) for the html div itself e.g like using role=alertdialog?

**Comment by Abuelodelanada** [comment]
Hi @samus-aran 

> Circulating within the team just now. Preferably it would still be to the develop branch so it would be from 7.11+
> Just a quick note, could we consider to add anything [for accessible](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role) for the html div itself e.g like using role=alertdialog?

Yes, I think it is a good idea. We will be working in this, and send an new PR.

**Comment by Abuelodelanada** [comment]
Hi @samus-aran 

There is a new PR #6602  that replace this one.

**Comment by Dillon-Brown** [comment]
Closing in favour of #6602

**Pull request closed without merging**
