### PR TITLE
fixed - #1424 Remove unused LBL_MODIFIED_USER_NAME_MOD label?

### PR DESCRIPTION
**Pull request by shogunpol**
Remove unused LBL_MODIFIED_USER_NAME_MOD label?
## Description

Remove unused LBL_MODIFIED_USER_NAME_MOD label?
References issue #1424

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
Also requested to be removed here:
Unused language strings (Cases) · Issue #2534 - https://github.com/salesagility/SuiteCRM/issues/2534

**Comment by shogunpol** [comment]
@horus68 , 'LBL_MODIFIED_USER_NAME_MOD' has been removed from #2534,

about other labels: if you see any unused Labels, please if you create issue, they will be handled quick as possible.

**Comment by horus68** [comment]
@shogunpol you can consider #1424 and #2534 as duplicated issues/PR and close one down.
The real problem here is that the PR is not yet merged and as so its just a PR to "remove" code not a "removed" code.
Until those language related issues on #2444 are not merged its too difficult to test the language strings.
I know this means time and detail but this is a major PR (as the SuiteP feature PM).
Those PR will create a new version!

**Comment by shogunpol** [comment]
@horus68 , i closed original issue(which i usually dint do), so now is consistent.

**Comment by Dillon-Brown** [comment]
Superseded by combined language file update #3349

**Pull request closed without merging**
