### PR TITLE
Abort delete in before_delete logic hook

### PR DESCRIPTION
**Pull request by ildarius**
## Description
Allow aborting of the delete operation via abort_mark_deleted flag that can be set inside before_delete logic hook method. Quick explanation https://youtu.be/p9xeikuZs3E

## Motivation and Context

Currently there's no other way to stop the delete procedure inside the before_delete hook tried the alternative of using the $bean->mark_undeleted($id), but unfortunately it does not restore previously created relationships and even if it did it could cause the firing of additional logics hooks which may result in unexpected behaviour.

## How To Test This

By setting $bean->abort_mark_deleted = 1; inside the logic hook method we prevent the deletion and destruction of relationships performed by mark_delete method.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 222
- Added 391
           

Complexity increasing per file
==============================
- lib/Search/SearchWrapper.php  7
- modules/Administration/Search/View.php  1
- tests/unit/phpunit/lib/SuiteCRM/Search/SearchTestAbstract.php  1
- lib/Search/SearchConfigurator.php  5
- lib/Log/CliLoggerHandler.php  1
- lib/Log/SugarLoggerHandler.php  8
- lib/Search/SqlSearch/SimpleSqlSearchEngine.php  4
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchEngineTest.php  1
- modules/Administration/Search/ajaxSubmit.js  2
- modules/Administration/Search/ElasticSearch/scripts.js  2
- lib/Search/UI/MVC/Controller.php  2
- include/Smarty/plugins/function.search_controller.php  1
- modules/Administration/Search/scripts.js  1
- lib/Search/Index/Documentify/JsonSerializerDocumentifier.php  1
- lib/Search/Index/Documentify/SearchDefsDocumentifier.php  9
- lib/Utility/ArrayMapper.php  7
- modules/Home/Search.php  1
- lib/Search/ElasticSearch/ElasticSearchEngine.php  2
- lib/Search/ElasticSearch/ElasticSearchClientBuilder.php  7
- lib/Search/UI/SearchResultsView.php  1
- tests/unit/phpunit/lib/SuiteCRM/Search/TestCustomEngines/MockSearch.php  1
- modules/Administration/Search/Controller.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4793279&bid=15957030)

**Comment by ildarius** [comment]
Hi Ashley

That's a good point, it does affect a lot of other components.

I'll keep it in mind for the future.

Thank you

**Comment by Mac-Rae** [comment]
Hi @ildarius,

Take a look at what SuiteBot said please.

Could you resolve the conflicts on this pull request bringing it up to date with the related branch?
For more information please take a look at our [contribution guidelines](https://docs.suitecrm.com/community/contributing-code/).

If you would like assistance please ensure you select "Allow edits from maintainers" checkbox and leave us a message @tagging me! 

Thanks :+1:

**Comment by pgorod** [comment]
@ildarius that Codecov comment, despite being signed by samus-aran, is really just a bot working from her account. 

But I don't think report really applies to what you made - the real problem is with the branch you're using, it's bringing in a LOT of other commits, that's why the report says you're changing a lot of stuff affecting tests coverage. But if it was just looking at your simple commit, it would have almost nothing to complain about.

An easy way to start a PR from the right branch, and with an up-to-date branch, is this (everything from GitHub web site, which is very convenient, but only for very simple PR's that touch only a file or two):

1. On GitHub, click **"Code" tab** and Navigate to the **correct branch** (`hotfix-7.10.x`). You can find the branch navigator on the left, above the file list:
image

2. Now navigate the directories to **get to the file** you want to change.

3. Click the **edit button** (with a pencil icon). GitHub will fork the repo to your own area, if it's not forked already; and it will start a new branch from a completely up-to-date `hotfix-7.10.x` branch, which is what we want.

4. **Make your changes** in the editor. When you **save**, it creates a commit in the new branch (called `patch-1` for example) in your forked repo.

5. It will then offer to **start a PR** from there into SalesAgility/SuiteCRM.

6. The best thing is that, if you later need to change something, all you need to do is **add more commits** or edit more files **in your repo, in that patch branch**, and the PR will be updated automatically to include all that.

I hope this helps.

**Comment by ildarius** [comment]
Hi Pedro

Thank you so much for the detailed explanation! Will do that.

Have a great day

**Comment by ildarius** [comment]
moving pull to hotfix-7.10.x

**Pull request closed without merging**
