### PR TITLE
 	If validation type is callback you dont want required check

### PR DESCRIPTION
**Pull request by gunnicom**
If you use the validation type "callback" you want to do your validation in a custom javascript function, so you dont want sugar to check the required.
Use case for me:
Check if field is empty, but an other field has some value.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Hi @gunnicom, are you able to update this and change the branch to hotfix-7.8.x? Thanks.

**Comment by gunnicom** [comment]
Are you kidding me? This is two years old. 
I wont put work in it now, and then it lies another two years.

**Comment by Dillon-Brown** [comment]
@gunnicom I understand your frustration. I'm only asking as I will be going through and assessing all of the old PR's that haven't been merged. If you are still interested in updating your open PR's it would be much appreciated but if not, please close them or tick the box allowing us to update them for you. Thanks.

**Comment by Dillon-Brown** [comment]
I see you already allow maintainers to push to your branches. I've gone ahead and updated all of your PR's that I was able to assess. Thanks for the contribution!

**Comment by gunnicom** [comment]
@Dillon-Brown If you tell me for sure which PRs are going into the next 7.8.x release i may be willing to look into them, but if i don't know, and i may edit some of them and then they lie another two years, i won't do that.

**Comment by Dillon-Brown** [comment]
@gunnicom I can't guarantee which PR's will go into the next release as that will depend on how much time is available for code reviews and assessments. However, they will definitely all get looked at.

From your current open PR's I believe #718 and #1710 are the only ones that I was unable to assess. The rest are now waiting for code review before they get the "Ready to Merge" label.

**Comment by gunnicom** [comment]
Ok, maybe i look into them. And #1708 is really only a suggestion for getting rid of code duplication, so that PR is not really important and i dont care about that one.

**Comment by gunnicom** [comment]
For #718 the one commit is only a bugfix and should be easy mergable: https://github.com/salesagility/SuiteCRM/pull/718/commits/68d891955a247b14070c03cf1a7d8b19bb58de49

**Comment by Dillon-Brown** [comment]
It might help to split the bug fix from the enhancement in #718 so you can make it to the hotfix-7.8.x branch. That way it will be able to get merged much faster.

**Comment by daniel-samson** [comment]
We need to resolve the conflicts here. Before we can review this pull request.

**Comment by gunnicom** [comment]
I do not know if i did the resolving correct, so maybe you just do a quick look.

**Pull request merged**
