### PR TITLE
decimal numbers calculations fix

### PR DESCRIPTION
**Pull request by tiefwasserreede**
## Description

When using calculated field and using decimal values (e.g. 10,50 + 12,00) to calculate a decimal field, the result will not be correct (e.g. it will display 999,99 instead of 22,50).  The proposed change fixes this fault and renders the correct value. The issue only occured when one of the decimals is not equal to 0, fyi if you´re trying to reproduce it.

## Motivation and Context

The change is required, because calculated fields should calculate correctly...

## How To Test This

create three decimal fields; value A, value B and result C; 
Set one of the values to (e.g.) 12.50 and the other one to 10.00
Set up a workflow and calculate value A + value B by using  {add({P0};{P1})} or any other formula you wish
That´s it - the result will indicate 999,99

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jack7anderson7** [comment]
Hi @tiefwasserreede,

Can you point your Pull request to the `hotfix` branch instead of `master`.

Thanks,
Jack

**Comment by tiefwasserreede** [comment]
> Hi @tiefwasserreede,
> 
> Can you point your Pull request to the `hotfix` branch instead of `master`.
> 
> Thanks, Jack

Sorry, I haven´t contributed too much so far - not sure, if it´s enough to change the branch to "hotfix"? 

Thanks, Richard

**Comment by jack7anderson7** [comment]
> > Hi @tiefwasserreede,
> > Can you point your Pull request to the `hotfix` branch instead of `master`.
> > Thanks, Jack
> 
> Sorry, I haven´t contributed too much so far - not sure, if it´s enough to change the branch to "hotfix"?
> 
> Thanks, Richard

Hi @tiefwasserreede,

No need to apologise, it is enough to just change it to hotfix.

Thanks,
Jack

**Review by pgorod — DISMISSED** [review]

**Review by jack7anderson7 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Comment by clemente-raposo** [comment]
Hi @tiefwasserreede, thank you for your PR

**Review by johnM2401 — APPROVED** [review]
LGTM, Calculations are accurate when using either "," or "." as the decimal value.

**Pull request merged**
