### PR TITLE
Fix/events calendar labels

### PR DESCRIPTION
**Pull request by e-reeley**
## Description

This fix is to label the fields within the events pop up from the calendar dashlet.

## Motivation and Context

This specific popup had a number of missing labels causing the values to seem ambiguous.

## How To Test This

1) Create an event within the events module
2) Navigate to the home page
3) Ensure that the calendar dashlet is visible
4) Hover over the newly created event
5) The fields should now have appropriate labels in the popup box
6) Also, click the body of the event within the dashlet
7) View the larger popup and ensure that the appropriate labels are visible, e.g. all buttons, fields and title

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
@e-reeley  Is there a need for ending spaces in labels?
```
    'LBL_LOCATION' => 'Location: ',
    'LBL_STATUS' => 'Status: ',
```

See general issue https://github.com/salesagility/SuiteCRM/issues/5652

**Comment by e-reeley** [comment]
@horus68 

My thinking with this one is that when it displays on the pop up it will read a bit more clear? This is an opinion though, e.g.

Location:Meeting Room or
Location: Meeting Room.

The space breaks up the display in my opinion?

Im happy to take on board the case for no space though!

**Comment by horus68** [comment]
True, its a consistency issue. Unfortunately there is no standard here.
Asking @Dillon-Brown for support

**Comment by e-reeley** [comment]
Excellent, please keep me up to date! Once we have agreed on which way we will use as standard then I will update accordingly :+1: 

Thank you for mentioning this.

**Comment by horus68** [comment]
@e-reeley can this be merged?

**Comment by Dillon-Brown** [comment]
Assessed

**Pull request merged**
