### PR TITLE
Allow database character set configuration

### PR DESCRIPTION
**Pull request by dominicchinkh**
Allow database character set configuration

## Description
On install UI, add "Advanced Database Configuration" session under "More options". Under "Advanced Database Configuration", add "Collation" and "Character Set" combo box. The collations list and character set list can be configured with install/suite_install/collations.php file.

SuiteCRM administrator can configure "dbconfigoption" as below in config_override.php file so that the MySQL database support storing four bytes per character.

$sugar_config['dbconfigoption']['collation'] = 'utf8mb4_unicode_ci';
$sugar_config['dbconfigoption']['charset'] = 'utf8mb4';

This pull request merge the changes of 2 related pull requests:
https://github.com/salesagility/SuiteCRM/pull/6461
https://github.com/salesagility/SuiteCRM/pull/6475

## Motivation and Context
MySQL's encoding called "utf8" (alias of "utf8mb3") only stores a maximum of three bytes per code point. SuiteCRM users often copy and paste text which may include emoji or unicode characters into SuiteCRM text field. This change supports storing supplemental characters in MySQL database.

## How To Test This
(1) Delete the config.php file. Reinstall the MySQL database
(2) Add a new relationship in Studio

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by horus68** [comment]
there are too many file changes. Maybe wrong branch or outdated local?

**Comment by pgorod** [comment]
If you're having trouble with rebasing in `git`, this might help you:

https://pgorod.github.io/Git-rebase-atomic/

**Comment by dominicchinkh** [comment]
Sorry. This is a mistake. Can this be undo or ignored?

**Comment by dominicchinkh** [comment]
Wrong base

**Pull request closed without merging**
