### PR TITLE
Fix for issue #2786 - Panels showing wrong in SuiteP

### PR DESCRIPTION
**Pull request by Szellszi**
## Description

Issue #2786 
Added tabid for panels and show/hide them when their tab is shown/hidden.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by LuminisIndia** [comment]
Dear Szellszi,

Thanks for the solution.

RK

**Comment by apoonawa** [comment]
Hi, these changes do not work in version 7.9.2.
Could anyone help with figuring out an updated fix for this version?

**Comment by pgorod** [comment]
@apoonawa [this](https://github.com/salesagility/SuiteCRM/commit/d5ab9b5181ff0099ae104de68cf4b589d9d73d4b#diff-2b88949d33b4bcf68eceed7680dbdf67) is the commit that's causing the conflicts (by the same author as the current PR...)

Have you tried applying both changes manually? But possibly the cause for this not working can be somewhere else...

**Comment by apoonawa** [comment]
@pgorod 
Thanks for the help. That commit is safe and does not break affect anything.

**Comment by apoonawa** [comment]
I figured out a fix to the issue for Ver 7.9.2. I'm sorry I couldnt figure out how to create a fix on github (if someone can help me figure that out, i would be happy to create fix and pull request)
Problem was that the file themes/SuiteP/include/DetailView/DetailView.tpl was changed in version 7.9.2 so the fix doesn't work as intended. 
Ignore the above fix for the file and make the following changes to themes/SuiteP/include/DetailView/DetailView.tpl :

1) Ensure that the all occurrences of '<div class="panel panel-default">'
are replaced with :
'{{if $useTabs}}
{{if $tabCount == 0}}
<div class="panel panel-default tab-panel-{{$tabCount}}" style="display: block;">
{{else}}
<div class="panel panel-default tab-panel-{{$tabCount}}" style="display: none;">
{{/if}}
{{else}}
<div class="panel panel-default">
{{/if}}'

2) Replace 
'var selectTabDetailView = function(tab) {
                        $('#content div.tab-content div.tab-pane-NOBOOTSTRAPTOGGLER').hide();
                        $('#content div.tab-content div.tab-pane-NOBOOTSTRAPTOGGLER').eq(tab).show().addClass('active').addClass('in');
                    };'

with
'var selectTabDetailView = function(tab) {
                        $('#content div.tab-content div.tab-pane-NOBOOTSTRAPTOGGLER').hide();
                        $('#content div.tab-content div.tab-pane-NOBOOTSTRAPTOGGLER').eq(tab).show().addClass('active').addClass('in');
                        $('#content div.panel-content div.panel').hide();
                        $('#content div.panel-content div.panel.tab-panel-' + tab).show();
                    };'

3) Replace
'<div class="panel-content">
<div>&nbsp;</div>
{{counter name="panelCount" start=-1 print=false assign="panelCount"}}'

with
'<div class="panel-content">
<div>&nbsp;</div>
{{counter name="tabCount" start=-1 print=false assign="tabCount"}}
{{counter name="panelCount" start=-1 print=false assign="panelCount"}}'

4) Replace 
'{* if tab *}
(isset($tabDefs[$label_upper].newTab) && $tabDefs[$label_upper].newTab == true && $useTabs)}}
{*if tab skip*}'

with
'{* if tab *}
(isset($tabDefs[$label_upper].newTab) && $tabDefs[$label_upper].newTab == true && $useTabs)}}
{{counter name="tabCount" print=false}}
{*if tab skip*}'

**Comment by apoonawa** [comment]
Please see fix for issue for Ver 7.9.2
https://github.com/salesagility/SuiteCRM/pull/3888

**Comment by LuminisIndia** [comment]
I just upadated to SuiteCRM 7.9.4 and then made both changes #3888 and #3889  manually.  Both worked correctly.

With thanks,

RK

**Comment by pgorod** [comment]
What does this mean for the current PR? Can it be closed without merging, because the fixes are already made in other places?

**Comment by LuminisIndia** [comment]
@pgorod , The proposed fixes #3888 and #3889 are not actually merged in the current version 7.9.4.  They have to merge these in future release.  It is still pending!

With thanks,

RK

**Comment by pgorod** [comment]
Yes, I understand that, but then the current PR should be closed. The other two PR's are left open, waiting to be merged, and the original Issue #2786 is left open to track this.

Just give me a thumbs up on this and then @Dillon-Brown or @Szellszi can come here and close! Thanks

**Pull request closed without merging**
