### PR TITLE
Error handling for old code

### PR DESCRIPTION
**Pull request by daniel-samson**
## Description

This change makes it easier to provide better tests for old or legacy code. It provides a new error handler which uses the exceptions to provide a detailed stack trace.

Added exceptions:
* UndefinedBehaviour
* UnusableValue
* InvalidType
* ErrorLevel

Error Collection and assertion:
* ErrorCollection

Also i have added the [robo](http://robo.li/) for parallel acceptance testing.

## Motivation and Context

* Provides a means to soft throw exceptions without breaking legacy customisations.

## Example

OldFeature.php
```

/**
 * Class OldFeature
 * Challenge add error handling without throwing exceptions
 */
class OldFeature
{
    /**
     * Typical code
     * @param $a
     * @return array()
     */
    function old_function($a)
    {
        $arr = array();

        if (is_null($a)) {
            // bad error message
            $GLOBALS['log']->fatal('cannot find old feature...');
            // added when after I created tests
            ErrorCollection::throwAndLog(new UnusableValue('$a is null expected boolean'));
        }

        // 100 lines of code

        if (gettype($a) !== 'boolean') {
            // Even worse error message
            $GLOBALS['log']->fatal('Unknown $a');
            // added when after I created tests
            ErrorCollection::throwAndLog(new InvalidType('Actual: '.gettype($a). ' expected: boolean'));
        } else {
            if ($a === true) {
                $arr['ID'] = '1';
                $arr['NAME'] = 'Daniel';
                $arr['DELETED'] = '1';
            } else {
                $arr['ID'] = '';
                $arr['NAME'] = '';
                $arr['DELETED'] = '';
            }
        }

        return $arr;
    }
}

```
OldFeatureTest.php
```

<?php

// this is just because i don't want to change bootstrap.php
require_once 'include/Exceptions/exceptions.php';

class OldFeatureTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var OldFeature $class
     */
    protected static $class;

    /**
     * Set up dependencies
     */
    protected function setUp()
    {
        global $current_user;
        get_Suite_config_defaults();
        $current_user = new User();
        self::$class = new OldFeature();
    }

    /**
     * test old feature
     */
    public function test_old_function_valid_cases()
    {
        $expected = array(
            'ID' => '1',
            'NAME' => 'Daniel',
            'DELETED' => '1'
        );
        $actual = self::$class->old_function(true);
        $this->assertFalse(
            ErrorCollection::hasErrors(),
            ErrorCollection::getStackTraceMessage()
        );
        $this->assertSame($expected, $actual);
        ErrorCollection::clearErrors();

        $expected = array(
            'ID' => '',
            'NAME' => '',
            'DELETED' => ''
        );
        $actual = self::$class->old_function(false);
        $this->assertFalse(
            ErrorCollection::hasErrors(),
            ErrorCollection::getStackTraceMessage()
        );
        $this->assertSame($expected, $actual);
        ErrorCollection::clearErrors();
    }

    public function test_old_function_invalid_cases()
    {
        self::$class->old_function(1);
        $this->assertTrue(
            ErrorCollection::hasThrownError(new InvalidType()),
            ErrorCollection::getStackTraceMessage()
        );
        ErrorCollection::clearErrors();

        self::$class->old_function('true');
        $this->assertTrue(
            ErrorCollection::hasThrownError(new InvalidType()),
            ErrorCollection::getStackTraceMessage()
        );
        ErrorCollection::clearErrors();


        self::$class->old_function('false');
        $this->assertTrue(
            SuiteErrorHandler::hasThrownError(new InvalidType()),
            SuiteErrorHandler::getStackTraceMessage()
        );
        SuiteErrorHandler::clearErrors();

        self::$class->old_function(self::class);
        $this->assertTrue(
            ErrorCollection::hasThrownError(new InvalidType()),
            ErrorCollection::getStackTraceMessage()
        );
        ErrorCollection::clearErrors();

        self::$class->old_function(null);
        $this->assertTrue(
            ErrorCollection::hasThrownError(new UnusableValue()),
            ErrorCollection::getStackTraceMessage()
        );
        ErrorCollection::clearErrors();
    }
    // test other methods
}
```

## How To Test This

See Example

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by chris001** [comment]
Good idea to make old code testable! 💯 

The best part is, Travis is running Codeception and phpunit on this branch and it's reporting back many errors it found lurking in there for ages.
* tons of errors in the silent installer, 
* fatal error while attempting to access a missing database table, 
* the SQL query builder builds invalid queries, 
* many an invalid array index, and 
* failed unit test on the `Scheduler` bean class method `deriveDBDateTimes()`!

**Comment by daniel-samson** [comment]
@chris001 :- the current unit tests are not complete. I noticed that the tests seems to be dependent on the execution order.  We need to add the dependencies in each test class. Before we can really get into that, we need to ensure that we have the required tools to write more complete tests. I am looking into mocking the data in each test.

I think if we can at least cover the SugarObjects which govern the templates used by each module, we can drastically increase the code coverage of each module. Especially when we can run automated acceptance tests for the common actions in template.

We also need to look into the database manager, so that we can test different database engines.

**Comment by chris001** [comment]
@daniel-samson  
1. First, it's essential to remove the `-f` option from the `codecep` command, so that all of the tests run, and it doesn't stop on the first failure.
2. Obviously, the missing requirements must be installed with `apt`, as I've previously discovered and reported
3. The test which failed (see above) - `testderiveDBDateTimes()` - doesn't depend on previous test execution order having created data and left it laying around, or missing mocked data.  It's a failure of the code to fail to generate scheduled task dates and times as expected.
4. Most of the very many database bugs will be cleared up quickly by work in progress on adding new very well tested DB manager which connects to all database types from a single class - MySQL, MS SQL, Postgres, Oracle, IBM, about 20 types. and the reliable query builder which comes with it.
5. For testing against different db's, `dbunit` should be added to codeception as soon as possible.

**Comment by daniel-samson** [comment]
@chris001 -   I will take a further look into those points you have made. 

When I was testing this without the '-f', it would sometimes show up as passed even when there were failures. I added '-f' option because it guarantees that codeception returns an error code, causing the travis ci build to fail.

I think point six could be solved with the acceptance tests.  

I am also thinking about adding a bot to analyse the logs. So that if a fatal error was found it could cause the travis builld to fail. These are just some of my ideas. Thank you for your input.

**Comment by chris001** [comment]
@daniel-samson
* Can you share the exact steps to reproduce when you were testing without `-f` sometimes showing up as passed even when there were failures, and please file a new issue at https://github.com/Codeception/Codeception/issues

**Comment by chris001** [comment]
@daniel-samson  Is it possible for you to push the `codeception` feature to `hotfix`, `master` and `develop` so that the tests will not only run on PRs to the `feature` branch, but also run on PRs to these other branches where it's very important that the tests run and notify failed tests right on the PR and hopefully prevent anyone from merging bugged PRs and prevent buggy releases as much as possible.

**Comment by daniel-samson** [comment]
Hi @chris001, the short answer is no. This is a feature branch. The feature is not yet ready. We still need to add extra tooling, updating the tests, and add more tests.  When the feature is ready we it will merged it into develop.

I have already raised the issues with the current testing framework. When reviewing pull requests, we are making an extra effort to avoid critical issues. For example checking the output from travis regardless of its status, and placing more emphasis for the testing.

If you are concerned with this feature branch being out to date. I can assure you that I will be keeping this branch up to date with hotfix and develop respectively. I will also be reporting any issues I find internally and on the reviews of each pull request.

We are focusing on the next patch release(s) at the moment. However, We are reviewing our quality and testing processes. we have scheduled time to work on this feature as a priority for 7.10. Due to scheduling, this feature won't make into 7.9, as the emphasis in the next release(s) are for bug fixing.

See https://suitecrm.com/forum/suggestion-box/13923-tackling-github for updates on this.

**Comment by chris001** [comment]
@daniel-samson Thanks for your reply.  
My 2 pence:

1. Is automated tests really a product feature?  For developers, sure.  A product feature is something the end user sees and interacts with inside the app.  So these automated tests are not really a product feature, they're part of the continuous integration / quality check / code analysis / build process.  The end user, during their daily use of the app, unless they're a developer, will never need to look into the tests folder, and will probably never be required to know that automated tests were used to build the software.

2. Are additional tests, extra tooling, and updated tests, absolutely necessary before using the existing 1202 fully running and working tests?  Unless there's something we're missing here, each of these unit tests stands on its own and is ready to test `develop`, `master`, and `hotfix` PRs right now.  The entire set of existing unit tests can be added to these 3 branches right now via this Codeception Feature #3600 .  I realize 20 or so unit tests are marked `Skip` and `Incomplete`, and that's just fine for now, these few non-running unit tests can be fixed and enabled one by one going forward.  Other tooling - `php-cs-fixer`, `phpcs`, and `Scrutinizer-CI` - can be flipped on practically by adding a line or two in `.travis.yml` - they just run by themselves with a few parameters, print out a report, and can be fined tuned going forward..

**Comment by daniel-samson** [comment]
@chris001 
1. It's a feature, so we need a feature branch.
2. The tools are small changes. The code coverage really needs to be improved. So we need time to work on this further. The current tests need to be updated to support the new changes we have made. There is little value in merging codeception into hotfix/develop/master, as the current test are not any different from the existing test suite. We need to automate some of the user acceptance tests.
 
I ran a test to find out the code coverage it took a day to finish.
https://travis-ci.org/daniel-samson/SuiteCRM/jobs/241715957#L2786

Keep in mind that SuiteCRM is a huge project, and I am working on a strategy to drastically increase the code coverage.

**Comment by chris001** [comment]
* Thanks @daniel-samson   The `codeception` test report currently running only on `feature` is far more informative, human friendly and actionable, it shows you each `phpunit` test file name and the test function, with the test result, execution time, color coded, easy on the eyes.  The old, plain test report currently running on `master` `hotfix` and `develop` is far less useful, let's be honest here, it's useless, devoid of information, it only shows a dot `.` when a test passes, or a `I` for complete, `S` for skipped, `F` for fail, no name of the test file, no test function name, no execution time.  So the non-developer users observing PRs in `master`, `develop` and `hotfix` are facing a huge barrier and for all practical purposes unable to determine the area of the app which failed a test!  We're currently just seeing a meaningless dot `.` on a line with test number next to it: `183/1202`.  What on earth does that correlate to??  The average non-developer cannot know, yet, they should be provided clear information, and would get this, if `codeception` were running the tests.  The area of the app which failed the test is obscured and that's wrong.

* 👍 for your work to increase test coverage drastically with the `--coverage` and nondisruptive soft error catcher logger.  Now let's enable `PHPCS` (PHP code sniffer), `php-cs-fixer` (coding standards checker) and `Scrutinizer-CI` help achieve this better faster and stronger, without writing additional code.

**Comment by chris001** [comment]
@daniel-samson 
Following up on this from 2 weeks ago.
Daniel,. do you realize, none of the sample data is even being installed for the Travis phpunit/codeception tests ?
This lack of sample data would explain why **some, not all** failing tests, are failing - they have no sample data to run their tests upon...
(facepalm)

**Comment by daniel-samson** [comment]
@chris001 I am aware of these issues but thank you for raising them. I have been reviewing the issues with our current testing framework. That is why we are going to work on the automated testing for 7.10 which will be a priority task. There are many things we need to improve such as code quality, data mocking, schema verification, code coverage, dependency injection, PHP Doc, and automated security analysis. Just to name a few.

The sample data is for demonstrating the capability of SuiteCRM to those who have never used the product. Though we do use it to manually test functionality, it is not suitable for automated testing. We need to provide a means to allow us to test units in isolation and also as part of a sub system. We need to also cover automated user acceptance testing as well. This is where better data mocking needs to play its role here.

The current test framework is mostly functional tests with some unit tests. It is clear that we need to update the tests to better reflect the new functionality. We need to assess the quality of the tests and how we can improve them. I don't simply want to implement a new test framework because it looks good. I want to improve the quality of SuiteCRM by improving the manual and automated processes. I also want to create better quality tests which are accurate, economical, traceable, repeatable and reusable.

As described in previous comments, this feature is finished yet. Since we are still working on 7.9.x this feature has not yet been started. These pull requests in which you have seen are a preamble to the actual task. 

I acknowledge your feedback and I appreciate your input.

**Comment by chris001** [comment]
@daniel-samson 
The testing you're talking about, a "new feature", planned for 7.10, I'm aware of the magnitude of this and applaud it. Finally to see modern development methods used in this project and get up to par with the ways of the major PHP software which have been doing things this way for many years, brings hope.
The "legacy 6.5 tests" have been in existence since the year 2011 however:
https://developer.sugarcrm.com/2011/06/23/unit-tests-can-create-a-false-sense-of-security/
The legacy 6.5 tests of #3600 require no new code, they're runnable with `codeception` now with #3600 .  They're not perfect, nothing is.  Yet they provide more tests than not having them active in the Travis build process.  Something about how `phpunit` is running them is giving false good builds and need to replace that with the codeception way.
Most importantly, getting the 6.5 tests active and out there and visible, starts to get contributors in the mindset of starting to write tests for their contributions. They can have a look at the test code and see how easy it is to write unit tests for their contributions

Since tests were requested for years now, by some prominent contributors @adamjakab #461 @gunnicom #641 #3237 @gagarine who left when their golden contributions were ignored by @salesagility .

Let's add the legacy Sugar 6.5 tests from 2012 that's five years ago, why not add them now.  It's quick and easy.   Why on earth wait until 7.10 which looks like it's scheduled for July?  That's unjustified.   The sugar 6.5 tests are not new development. They're already in the product and have existed in the world since over 5 years. They just need to be called thru codeception in Travis.

Benefits: 
1. Bang.  Detailed reports in every new PR.  When a tests fails, the build will fail with a big red X.
2. A feeling of catching up to modern development standards used by competing github projects.
3. Massively greater protection of against bugs getting in thru PRs and out into releases.
4. Some of the prominent contributors who have left after they lost trust in you guys, you might earn them back.  Wait too long, they might never be back.

It's a competitive world and merging 3600 now is how you keep up.

My 2 pence.

**Pull request closed without merging**
