### PR TITLE
Fix #2890 - Workflow Condition on custom field error

### LINKED ISSUE #2890: Workflow Condition on custom field error
#### Issue
If using a workflow condition on a custom field, the resulting query generates an error. For example, I've added the custom field "division_c" in the users module and if added as a workflow condition, a log error is generated

Tue Jan 10 16:39:00 2017 [6916][1][FATAL]  Get One Failed:
SELECT aos_quotes.id AS id
FROM aos_quotes
LEFT JOIN users assigned_user_link ON aos_quotes.assigned_user_id=assigned_user_link.id AND assigned_user_link.deleted=0
LEFT JOIN users_cstm assigned_user_link_cstm ON users.id = assigned_user_link_cstm.id_c
WHERE assigned_user_link_cstm.division_c = 'x' AND aos_quotes.id = 'x': MySQL error 1054: Unknown column 'users.id' in 'on clause'

By looking at at query, the 2nd left join should be assigned_user_link.id = assigned_user_link_cstm.id_c and not users.id = assigned_user_link_cstm.id_c

#### Your Environment
SuiteCRM v7.7.8 & v7.7.9
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 55 on Windows 10 (same behavior with other browsers)

### PR DESCRIPTION
**Pull request by sanchezfauste**
## Description

See issue #2890 

If using a workflow condition on a custom field, the resulting query generates an error. For example, I've added the custom field `division_c` in the users module and if added as a workflow condition, a log error is generated
```
Tue Jan 10 16:39:00 2017 [6916][1][FATAL] Get One Failed:
SELECT aos_quotes.id AS id
FROM aos_quotes
LEFT JOIN users assigned_user_link ON aos_quotes.assigned_user_id=assigned_user_link.id AND assigned_user_link.deleted=0
LEFT JOIN users_cstm assigned_user_link_cstm ON users.id = assigned_user_link_cstm.id_c
WHERE assigned_user_link_cstm.division_c = 'x' AND aos_quotes.id = 'x': MySQL error 1054: Unknown column 'users.id' in 'on clause'
```
By looking at at query, the 2nd left join should be `assigned_user_link.id = assigned_user_link_cstm.id_c` and not `users.id = assigned_user_link_cstm.id_c`.

## Motivation and Context

If you create a scheduler workflow with a condition using a custom field of a related module, you get the error described on the previous section.

I have rewritten the generation of the JOIN to be correct.

## How To Test This

Create a scheduler workflow an add a condition using a custom field of related module.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
Hi @sanchezfauste 

I noticed that you branch doesn't have the newer testing suite. Can you please update this pull request to match the latest hotfix-7.8.x?

**Comment by sanchezfauste** [comment]
Now it's updated.

**Comment by daniel-samson** [comment]
Hi @sanchezfauste,

I have just tested your branch, I am having trouble adding the an action in AOW Workflow. When I add an action in aow and click the actions do not appear to be saved. When I tried to do the same on the hotfix branch. I was able to add an action and save the workflow. 

Can you please look at this?

**Comment by sanchezfauste** [comment]
Hi @daniel-samson,

I will try to replicate and correct the error.

**Comment by sanchezfauste** [comment]
You are right! When you save a workflow you get the following error on `error.log`:

```
[Mon Jul 30 19:53:38.950065 2018] [fcgid:warn] [pid 11451] [client localhost:35782] mod_fcgid: stderr: PHP Notice:  Undefined index: aow_conditions_id in modules/AOW_Conditions/AOW_Condition.php on line 119, referer: https://crm.example.com/index.php?action=ajaxui
```

But... if you switch to `hotfix-7.8.x` branch you get the same error. This makes me wonder that the error is really not introduced in this PR, since I have not modified `modules/AOW_Conditions/AOW_Condition.php` file.

I'll try to do more tests to see if I find what is causing this error.

**Comment by sanchezfauste** [comment]
Hi @daniel-samson, 

I have found and fixed the error. Now the workflow is saved properly.

PD: Copy-paste is bad sometimes... https://github.com/salesagility/SuiteCRM/commit/2cb5971f20b1c414552998c8d19b276b8635e334#diff-35ac2a2c22276a4e6dbb6d0f685bccedL91

**Comment by daniel-samson** [comment]
Assessed

**Pull request merged**
