### PR TITLE
Update tab_panel_content.tpl

### LINKED ISSUE #3763: EditView and QuickCreate tab order ignored - tabindex setting not set
#### Issue
I've set tab order numbers for all contact fields in the QuickCreate layout for Contacts.  Yet when the page is rendered, all the tabindex's show -1 or no value at all.
image

#### Expected Behavior
The set tab order should be followed, so the user can easily move through forms in the intended field sequence.

#### Actual Behavior
Original/nonsensical tab order is used, or basically none.  Tabbing through fields skips by and ignores most of them.  Repair/Rebuild after changing the tab ordering in Studio has no effect.

#### Possible Fix
Unknown where these changes are not being carried from Studio into the actual rendered site.  Server cache issue?

#### Steps to Reproduce - can be done on SuiteCRM Demo too.
1.  In Studio> Contacts> Layouts> QuickCreate, adjust the tab ordering so First Name is one, Last Name is two.
2.  Go into an Account.  In the Contacts subpanel, click Create.
3.  Click into into the first name field.  Enter text.
4.  Hit the tab key on the keyboard, expecting perhaps to move into the Last Name field as the tab order is set.  You move across into the Account/Relate field instead.

#### Context
This causes large amounts of user frustration for those who are entering Contacts all day, as well as in other areas where tab order is ignored.  Accounts>EditView is also affected, at least.

#### Your Environment
* SuiteCRM Version used:  7.9.0 and 7.9.1
* Browser name and version (e.g. Chrome Version 58.0.3029.110 (64-bit)):
* Environment name and version (MySQL 5.7.11, PHP 7.0.3):
* Operating System and version (Windows 10):

### PR DESCRIPTION
**Pull request by javitoron**
Fixed #3763.
Set tabindex in EditView fields as specified by users in Studio

## Description
I have replaced the $tabindex var by the $var.tabindex.
$var is $subfields the first time and $colData.field next three times

## Motivation and Context
EditViews where not usable if you couldn't move with your tab key, point every field with your mouse before start typing all the time is a real pain.

## How To Test This
You can set tabindex for several fields for an EditView in any module in Layouts studio and then navigate to that form. And move with your tab key to see each field selected.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by daniel-samson** [comment]
@Dillon-Brown can you please assess?

**Comment by javitoron** [comment]
sorry! do I have to do something? perhaps I'm lost in translation... what does it means "assess" here?

I feel so stupid... :-(

**Comment by Dillon-Brown** [comment]
@javitoron The assess is just a message for me to check that the pull request is working so that it can be assigned the "Ready to Merge" label.

**Comment by javitoron** [comment]
Sorry, and this means that you want me to confirm that it works on my own system, where I have tested it?

**Comment by Dillon-Brown** [comment]
@javitoron No more testing is needed. PR is ready to be merged into hotfix. Thanks for the contribution!

**Comment by javitoron** [comment]
So I say everything is ok and close?

**Comment by daniel-samson** [comment]
We assume that you have tested it. However, before we can merge your changes, we need to verify your fix. 

When a contributor makes a pull request, one community member will code review the changes to ensure that it meets our coding standards and to ensure that the quality seems of a reasonable standard. That member will raise any issues and request any changes need. Once a pull request has passed a review. A second community member must test it. If the pull request passes testing, then a third member will make a final review and merge the changes into the project.

Please do not close your pull request. You don't need to close the pull request, as github will automatically close the pull request after it has been merged. If you close the pull request we cannot accept the change.

**Comment by daniel-samson** [comment]
@javitoron 

Also can you please tick the checkbox "My code follows the code style of this project found" ?

**Comment by javitoron** [comment]
Yes, of course I tested it!

OK! ticked!

So I have to make nothing more, right?

**Comment by samus-aran** [comment]
Hi @javitoron 

One thing that was missed in the code review is that your PR is pointing to the 'master' branch rather than the 'hotfix' branch.

Have a read of our 'How to Contribute' section which detailed the correct branch to use.

https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM

We have also added the LTS label as an indication that we need to include this into the 7.8.x branch. You don't need to do anything for this, we'll merge it manually.

Thanks for your contribution!

**Pull request merged**
