### PR TITLE
Fix 3275 - Remove extra delimiter at the end of the exported line

### PR DESCRIPTION
**Pull request by atellier2**
## Description
Fix the issue https://github.com/salesagility/SuiteCRM/issues/3275 

## Motivation and Context
At the end of each csv export there is an extra delimiter. For example you have
Field1,Field2,Field3,
Instead of 
Field1,Field2,Field3

## How To Test This
- export any report into CSV

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by atellier2** [comment]
@shogunpol  Done ;-)

**Comment by chris001** [comment]
This bug is probably in every module that offers Export?  Not just `AOR_Reports`?  If possible, would be best to find the source of the problem and fix it there for all modules, possibly one level below, in `include/export_utils.php`, no?

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by samus-aran** [comment]
Code looks good :+1:

**Pull request merged**
