### PR TITLE
 Indentation fixed

### PR DESCRIPTION
**Pull request by asha15**
Indentation spaces in language values - 'Install' language file

## Description
@horus68  @pgorod  Fixed issue no. #6286 
Taking so many spaces by the strings

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by asha15** [comment]
@horus68 I don't get how to re-base the pull request into another branch? could you please help me? 
Screenshot from 2019-10-11 17-06-49

**Comment by pgorod** [comment]
You can only change white-space in strings that are going to be output as HTML, and then only white-space that is ignored by the browser and thus irrelevant to the output. An example would be `REQUIRED_SYS_CHK_MSG` which is used directly as HTML [here](https://github.com/salesagility/SuiteCRM/blob/83ba237a4eb48255b1e9e6eb62e37c2a046a4406/install/ready.php#L353).

I didn't go and check each one, but I wouldn't touch the other labels adding line breaks just to make the file look tidier. You'd have to be sure these line-breaks aren't going to end up displayed to the user in places you don't even suspect.

**Comment by horus68** [comment]
I don't see the point to create additional hard line breaks in the language file involving strings with HTML formatted values".
The initial issue states the need to remove the extra spaces for text indentation (inside a string)

**Comment by asha15** [comment]
@horus68  Sorry for the mistake. I thought it will be clean if i removed it. 
Anyway i'll make those changes

**Comment by Mac-Rae** [comment]
Hi @asha15,

Could you sign this ClaHub to allow us to review?

**Comment by serhiisamko091184** [comment]
Hello, @asha15 

The PR has been marked as stale because there has been no recent activity. It will be closed if no further activity occurs.
Thanks for your contributions.

Regards,
Serhii

**Comment by horus68** [comment]
This PR should never be accepted as it breaks a single sentence text line in more than one text line. That would break the translation flow

**Pull request closed without merging**
