### PR TITLE
Fixed #7315 - Adding parameter date field in Reports module causes error in Browser console

### LINKED ISSUE #7315: Adding parameter date field in Reports module causes error in Browser console
#### Issue
Reports module date parameter doesn't work. In technical terms entered date parameter is not posted to index.php because of Javascript error.

#### Expected Behavior
When parameter condition is added to report its value should be set and passed to SuiteCRM backend resulting in adequate report.

#### Actual Behavior
Browser throws Javascript fatal error when running the report:

conditionLines.js:318 Uncaught ReferenceError: setModuleFieldsPendingFinishedCallback is not defined
    at testModuleFieldsPendingFinished (conditionLines.js:318)
    at Object.success (conditionLines.js:364)
    at Object.handleTransactionResponse (sugar_grp1_yui.js?v=vFv2IT2lNHOn27RtYpjcvw:109)
    at sugar_grp1_yui.js?v=vFv2IT2lNHOn27RtYpjcvw:109

#### Steps to Reproduce
1. Create a report
2. Add Date Created condition  mark it as parameter
3. Try to view the resulting report, open browser console and check for errors

#### Context
This seems like a high priority error because date parameters aren't working.

#### Your Environment
* SuiteCRM ondemand demo environment
* Version: Version 7.11.4
Sugar Version 6.5.25 (Build 344)

### PR DESCRIPTION
**Pull request by 604media**
Fixed #7315 - Adding parameter date field in Reports module causes error in Browser console

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Unable to properly test until #7641 is resolved.

**Comment by connorshea** [comment]
That PR was merged, so now this can probably be rebased and tested.

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by samus-aran** [comment]
Hey @604media  :wave: 

Apologies on the delay but we would like to ask if you are able to provide us your shipping details so we can thank you for your hard work and time you’ve dedicated to contributing to SuiteCRM during the 2019 HacktoberFest period! :jack_o_lantern: :ghost: 

[HacktoberFest x SuiteCRM 2019 submission form](https://suitecrm.com/merchandise-data-collection/)

We will be closing the submission in 2 weeks time (Friday 7th February 2020) so we can immediately process your goodies.

If you have any concerns or feedback please reach out to us by emailing [community@suitecrm.com](mailto:community@suitecrm.com).

Would like to thank you again for participating with us on improving the SuiteCRM codebase and we look forward to future contributions from yourself :tada:

**Pull request merged**
