### PR TITLE
Browser search bar support for SuiteCRM

### PR DESCRIPTION
**Pull request by gunnicom**
Superseeds https://github.com/salesagility/SuiteCRM/pull/3677

Firefox allows new search plugins with opensearch ( http://www.opensearch.org/Home ).
This small patch allows sugar as search plugin for browser search bars.

### CODE REVIEW

**Comment by samus-aran** [comment]
Restarted Travis since it was failing. Anyone willing to test :+1:

**Comment by pgorod** [comment]
Hi @gunnicom I was testing this just now on a 7.8 instance, and I got a few problems related to URL formation.

I can add the engine properly (and it looks nice with the correct favicon and the system name).

But then when I search I get

`http://my.own.org//index.php?action=UnifiedSearch&module=Home&search_form=false&advanced=false&query_string=Pedro`

1. A double slash between host name and the rest

2. A missing port number (it should be `my.own.org:201`)

My settings in `config.php` are as follows:

```php
  'host_name' => 'my.own.org:201',
  'site_url' => 'http://my.own.org:201',
```

**Comment by gunnicom** [comment]
@pgorod Yes that may be the case as i concat the search URL in a maybe not good way:
`$searchuri="{$_SERVER['REQUEST_SCHEME']}://{$_SERVER['SERVER_NAME']}" . dirname($_SERVER['REQUEST_URI']). "/index.php?action=UnifiedSearch&amp;module=Home&amp;search_form=false&amp;advanced=false&amp;query_string={searchTerms}";`
I think i did it this way, as in my first try i just did not include any of the sugar framework. As i now include it anyways, i am sure i can do it a better way.
Mabye i just should use the config vars for that.

**Comment by gunnicom** [comment]
@pgorod Can you try my new code?

**Comment by pgorod** [comment]
I just tried it and it seems to work fine!

The problem with the double-slashes is no longer happening, and the port number is now properly included.

Thanks @gunnicom!

**Comment by Mac-Rae** [comment]
Please rebase this pull request to the hotfix-7.10.x branch as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Comment by gunnicom** [comment]
No, wont do.

**Pull request closed without merging**
