### PR TITLE
Avoid Notices when importing

### PR DESCRIPTION
**Pull request by gunnicom**
"NOTICE: [8] Undefined property: Account::$SecurityGroups on line 286 in file"

See also: https://suitecrm.com/suitecrm/forum/installation-upgrade-help/19831-error-code-when-importing-data

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Travis failing is unrelated to this PR. Looks good!

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by Dillon-Brown** [comment]
Hi @gunnicom, thanks for the contribution, however this would now need to be rebased to hotfix-7.10.x to be merged.

**Comment by gunnicom** [comment]
Ok, then i close here, as i wont rebase it.

**Pull request closed without merging**
