### PR TITLE
Securitysuite 3.1.16 updates

### PR DESCRIPTION
**Pull request by eggsurplus**
This brings SecuritySuite up to 3.1.16 on all bug fixes.

## Description

Includes fixes for the blank rows in the My Activity Stream, changing over to static functions as appropriate, and group selector on new record creation.

## Motivation and Context

Long overdue and also due to this issue: https://github.com/salesagility/SuiteCRM/issues/1491

## How To Test This

Do groups still work?
Is the blank row problem solved?

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by eggsurplus** [comment]
Both of these build check failures (Codacy/Travis) seem to be due to just general SuiteCRM core workings. If there are any build issues specific to the changes I made please let me know.

**Comment by pgorod** [comment]
Thanks!

This needs to be directed at `hotfix-7.10.x` (which then will go into the other `hotfix` bramches, see workflow [here](https://docs.suitecrm.com/community/contributing-code/bugs/))

To avoid seeing all these commits form other people on your PR, you would need to 

1. first bring `eggsurplus\hotfix-7.10.x` up to date with `salesagility\hotfix-7.10.x` (if this sounds complicated, use [this procedure](https://pgorod.github.io/Git-rebase-atomic/))

2. Now start a branch for this patch from under your `hotfix-7.10.x`, and make the commit with the code changes (you can cherry-pick to grab it from another branch).

3. Now start a PR (or edit this one) to pull the changes into `salesagility` repo

Tell me if you need further help. Thank you.

**Comment by eggsurplus** [comment]
Sure, I can do that. This doc needs to be updated then: https://docs.suitecrm.com/community/contributing-code/features/

**Comment by pgorod** [comment]
That page is supposed to be for new features (which go into `develop` branch), while the `hotfix` branches are for bug fixes. Your PR falls somewhere in between, but I guess `hotfix` is better because it gets into the product sooner.

Is this branch issue what you meant when you said the docs needs updating? Or is it something else?

**Comment by eggsurplus** [comment]
Kind of. As a casual contributor I can't remember processes for this project and there isn't an easy way to find any info on the desired process. It would be great if there was a link in the project README to processes for both new features and bug fixes. I can only find the contributor agreement and some non-related links in it.

**Comment by pgorod** [comment]
Thanks for that feedback, updating the README with this info is a good idea, I will take care of this next week. 👍

**Comment by pgorod** [comment]
README update: #7406

**Comment by samus-aran** [comment]
Hey @eggsurplus Thanks for this :+1: So yeah, Pedro already helped out with the process. Would it be easier if you are able to checkout the hotfix-7.10.x and cherry pick your last commit?

Our next release would be end of June, would you be able to adjust this PR by then? (or create a new one as it could be easier). If not then just holler and we can see what we can do on our side to allocate resources.

**Comment by eggsurplus** [comment]
@samus-aran I can do whatever is preferred. I will do hotfix-7.10.x unless you want it somewhere else.

**Comment by eggsurplus** [comment]
Changed over to 7.10.x: https://github.com/salesagility/SuiteCRM/pull/7474

**Pull request closed without merging**
