### PR TITLE
Fix is_admin_for_user warning

### PR DESCRIPTION
**Pull request by eggsurplus**
Warning: Use of undefined constant is_admin_for_user

### CODE REVIEW

**Comment by samus-aran** [comment]
Good Morning Jason,

Saw alot of PRs I'm assuming they are all the same. 
Just a note we don't merge anything directly into master but use hotfix, develop and hotfix-7.8.x or hotfix-7.9.x. If you know the issue exists in all supported versions (7.8.x +) then make the fix into hotfix-7.8.x as when we release we merge upwards hotfix7.8.x into hotfix 7.9.x etc etc

Hope that makes sense.

**Comment by samus-aran** [comment]
Ahh, apologies, they are not all the same.
I would then recommend combining them all together in a single PR. If a commit can be grouped contextually then we can merge it rather than having a single PR for each commit.

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by Dillon-Brown** [comment]
Code review in duplicate #5388.

**Pull request merged**
